### ISSUE TITLE
Save button mis-aligned in Firefox Quantum

### ISSUE THREAD

**Issue by lukeyouell** [solspace/craft3-freeform#1]
<img width="369" alt="image" src="https://user-images.githubusercontent.com/24975058/35354828-396c3af6-0143-11e8-8732-05a3e61661b0.png">

**Comment by lukeyouell** [comment]
This problem seems to be limited to Freeform Lite, I installed Pro which doesn't seem to have this issue.

**Comment by kjmartens** [comment]
I too have noticed this issue happening intermittently. Thanks for reporting. :)

**Comment by kjmartens** [comment]
This should be resolved now in Freeform 2.0.0-beta.2 :)
Please updates and let me know if the issue persists.
