### ISSUE TITLE
Missing GraphQL fields/interface for (page) submit buttons?

### ISSUE THREAD

**Issue by FreekVR** [solspace/craft3-freeform#1004]
After upgrading to Freeform v5, there doesn't seem to be any way to get the configuration for the (page) submit button, specifically the label and layout configs:

![image](https://github.com/solspace/craft-freeform/assets/417416/1ceb1f63-0d0d-4655-a4b1-057d3379c515)

**Steps to reproduce**

1. Create an (empty) form with the default submit in place
2. Attempt to fetch all the information via GraphQL ("full schema") graphiql

**Expected behavior**
There should be a field, or metadata in the page field, to get the information shown in the screenshot above. There doesn't appear to be any type definition or field for this?

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 4.7.1
- Freeform Version:  5.0.5
- Freeform Edition: Pro
- Fresh Install or Upgrade: Upgrade (Freeform 3 -> 4 -> 5)

**Additional context**

**Comment by kjmartens** [comment]
This should be resolved in Freeform 5.0.7 now. 🙂
