### ISSUE TITLE
Freeform v5 defines GraphQL field names with hypens, which is not supported in gql

### ISSUE THREAD

**Issue by FreekVR** [solspace/craft3-freeform#1005]
**Describe the bug or issue you're experiencing**
I get errors like these after upgrading an old Craft 3 freeform install and running GraphQL mutations or trying to access the schema definition (introspection)
```
{
  "errors": [
    "Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but \"course-id\" does not.",
    "Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but \"course-id\" does not.",
    "Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but \"course-id\" does not.",
    "Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but \"course-id\" does not.",
    "Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but \"course-id\" does not.",
    "Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but \"course-id\" does not.",
    "Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but \"course-id\" does not.",
    "Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but \"course-id\" does not.",
    "Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but \"save_safe-6-essentialsCOM_Submission\" does not.",
    "Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but \"save_safe-6-essentialsFR_Submission\" does not.",
    "Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but \"save_safe-6-essentialsNL_Submission\" does not.",
    "Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but \"save_safe-6-essentialsIN_Submission\" does not.",
    "Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but \"save_safe-6-essentialsDE_Submission\" does not.",
    "Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but \"Course-id\" does not.",
    "Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but \"course-id\" does not.",
    "Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but \"course-id\" does not.",
    "Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but \"course-id\" does not.",
    "Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but \"course-id\" does not.",
    "Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but \"course-id\" does not.",
    "Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but \"course-id\" does not.",
    "Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but \"course-id\" does not.",
    "Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but \"course-id\" does not.",
    "Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but \"course-id\" does not.",
    "Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but \"safe-6-essentialsCOM_Submission\" does not.",
    "Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but \"safe-6-essentialsFR_Submission\" does not.",
    "Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but \"safe-6-essentialsNL_Submission\" does not.",
    "Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but \"safe-6-essentialsIN_Submission\" does not.",
    "Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but \"safe-6-essentialsDE_Submission\" does not.",
    "Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but \"Course-id\" does not.",
    "Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but \"course-id\" does not."
  ]
```

**Steps to reproduce**

1. Define fields with hypens in the field handle
2. AND/OR
3. Define forms with hypens in the form handle

**Expected behavior**
Freeform does not allow hyphens in the input, or converts them to underscores/camel case for use in GQL, or converts them during the upgrade process for all usages.

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 4.x
- Freeform Version: 5.0.5
- Freeform Edition: Pro
- Fresh Install or Upgrade: Upgrade

**Additional context**

**Comment by kjmartens** [comment]
This should be resolved in Freeform 5.0.7 now. 🙂

**Comment by valboivin** [comment]
@kjmartens , would it be possible to still support hyphens in handle, but just convert them for use in GQL?

The problem I have, is that our website has multiple forms and they are all bound to different form instances in Salesforce (and other platforms). Those endpoints are expecting hyphenated handles/input names. We can't change those in Salesforce has there are too many implications (analytics, sales partner, etc.) and our development team doesn't even have access to this Salesforce account.

**Comment by kjmartens** [comment]
@valboivin In the Salesforce integration, you map the Freeform fields to the Salesforce fields, so it shouldn't matter what their handles or names are. 🙂  Or is there a different use case you're referring to?

**Comment by valboivin** [comment]
@kjmartens our client is not really using the CRM integration, but I'm not sure why. They also told us that there are third parties involved between our website and their Salesforce account.

**Comment by kjmartens** [comment]
Ok fair enough. I will make note of this and we will consider adding a setting that will let sites allow the user of dashes. 🙂

**Comment by valboivin** [comment]
@kjmartens, any update regarding this?

**Comment by kjmartens** [comment]
@valboivin, yes, we added an **Allow Dashes in Field Handles** setting for this under _General Settings_. 🙂

**Comment by valboivin** [comment]
@kjmartens oh great! Thank you, much appreciated 😃
