### ISSUE TITLE
GraphQL caches not reset after editing field handle(s)

### ISSUE THREAD

**Issue by FreekVR** [solspace/craft3-freeform#1007]
**Describe the bug or issue you're experiencing**
After updating a form with a new field handle this change is not immediately reflected in graphql queries fetching the form.

**Steps to reproduce**

1. Make sure caching incl. graphql query caching is enabled on the environment
2. Open an existing freeform form
3. Change the field handle, in my case, I was trying to workaround #1005 by changing a field handle from 'course-id' to 'courseId'
4. Run a `form(id: x)` query to fetch the field handles `pages { rows { fields { handle } } }`

**Expected behavior**
The updated field handle is returned

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 4.x
- Freeform Version: 5..0.5
- Freeform Edition: Pro
- Fresh Install or Upgrade: Upgrade

**Additional context**
Manually emptying the graphql cache via "utilities" fixed the issue.

**Comment by kjmartens** [comment]
This should be resolved in Freeform 5.0.7 now. 🙂
