### ISSUE TITLE
GraphQL field value (defaultValue) not availalble/empty

### ISSUE THREAD

**Issue by FreekVR** [solspace/craft3-freeform#1008]
**Describe the bug or issue you're experiencing**
The "default value" for a field does not appear to be available to GraphQL:
`field { value }` returns `null`
`field { defaultValue }` is not available as a GraphQL field

**Steps to reproduce**

1. Create a field with a default value
2. Attempt to fetch it from GraphQL, for example:
```
query MyQuery {
  freeform {
    form(id: 7) {
      fields {
        ... on FreeformField_Text {
          value
          type
          rules
          required
          placeholder
          pageIndex
          label
          instructions
          id
          attributes {
            container {
              value
              attribute
            }
            error {
              attribute
              value
            }
            input {
              attribute
              value
            }
            instructions {
              attribute
              value
            }
            label {
              attribute
              value
            }
          }
          handle
        }
      }
    }
  }
}
```

**Expected behavior**
The "default value" filled in the UI field config should be available somewhere in GraphQL, but it's not.

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 4.x
- Freeform Version: 5.0.5
- Freeform Edition: Pro
- Fresh Install or Upgrade: Upgrade

**Additional context**

**Comment by seandelaney** [comment]
This was fixed in Freeform 5.0.6 (https://github.com/solspace/craft-freeform/pull/1006)

**Comment by FreekVR** [comment]
Thanks! It does seem to be fixed. Unfortunately a new issue popped up now
where it throws an error about "values not being iterable" when attempting
to get the (default) value for an email field. May be a type bug as I can
only query values (plural) not "value" like on text fields.

**Comment by seandelaney** [comment]
This will be fixed in https://github.com/solspace/craft-freeform/pull/1017
