### ISSUE TITLE
Attempting to query "maxLength" for a field via GraphQL always results in an error

### ISSUE THREAD

**Issue by FreekVR** [solspace/craft3-freeform#1009]
**Describe the bug or issue you're experiencing**

**Steps to reproduce**

1. Run the following GraphQL query
```
query MyQuery {
  freeform {
    form(id: 7) {
      fields {
        ... on FreeformField_Text {
          maxLength
        }
      }
    }
  }
}
```
2. Error shown: 
```"
debugMessage": "Can't get a way to read the property \"maxLength\" in class \"Solspace\\Freeform\\Fields\\Implementations\\TextField\".",
      "message": "Internal server error",
```

**Expected behavior**
It should return the configured maximum length, or not be available to the GQL interface if unsupported.

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 4
- Freeform Version: 5.0.5
- Freeform Edition: Pro
- Fresh Install or Upgrade: Upgrade

**Additional context**

**Comment by kjmartens** [comment]
This should be resolved in Freeform 5.0.7 now. 🙂
