### ISSUE TITLE
Guzzle 7.2.0 - Purge Submissions Failiure

### ISSUE THREAD

**Issue by kiwidood** [solspace/craft3-freeform#101]
**Describe the bug or issue you're experiencing**

This happens on freeform submissions with some null fields.

After updating to Guzzle 7.2.0 this issue starts happening (updated as part of Craft update, notably the dependency change happened at version 3.6.0). This worked fine on Guzzle 6.5.5 and version 3.8.4 of Freeform.

Automatic submission purge is failing. Error seen under Utilities -> Queue Manager, named "Purge Submissions".

Argument 1 passed to GuzzleHttp\json_decode() must be of the type string, null given, called in /container/application/releases/20210204231757/vendor/solspace/craft-freeform/packages/plugin/src/Services/SubmissionsService.php on line 483

It appears Guzzle's json_decode's behaviour has changed.

**Steps to reproduce**
1. Create form with field that's not required, submit entry (make sure a row with field_* value is set to null in freeform_submissions database)
2. Modify database entry's dateCreated in (freeform_submissions) to be on a date after the Freeform -> Settings -> "Days After Submission Date to Purge" period
3. Make sure Freeform -> Settings -> Automatically Purge Submission Data is enabled
4. Delete freeform-purge-cache-key from freeform_lock if it exists
5. Load backend
6. See error in Queue Manager

**Craft & Plugin Info (please complete the following information):**
 - Craft Version: Craft Pro 3.6.3
 - Freeform Version: 3.10.6
 - Freeform Edition: Pro
 - Fresh Install or Upgrade: Upgrade

**Comment by gustavs-gutmanis** [comment]
Thanks for reporting this @kiwidood, I'm on it.

**Comment by gustavs-gutmanis** [comment]
This will be fixed in the upcoming release.
