### ISSUE TITLE
Captcha Integrations no longer saved in project config

### ISSUE THREAD

**Issue by DowleyDeveloped** [solspace/craft3-freeform#1010]
The Captcha Integrations seem to be saved to the DB and not to the project yml file anymore.

This means if we make any changes locally, we'd have to do a database merge, which isn't something I'd like to do, especially with a live site.

Previously this was saved to the config file which was much better.

The captcha intergrations are also hidden when not in dev mode, so there's no way of actually adding these to a live site without changing the file on the server and then changing it back. Which also presents risk. 

Is there any way we can have it saved within the config again?

- Craft Version: 4.7.1 
- Freeform Version: 5.0.5
- Freeform Edition: Pro
- Fresh Install or Upgrade: Upgrade

**Comment by kjmartens** [comment]
Sorry for the trouble @DowleyDeveloped,

Freeform 5.0.6.1 is now available and includes a fix for this. 🙂
