### ISSUE TITLE
Conditional Rules not working

### ISSUE THREAD

**Issue by phrichards** [solspace/craft3-freeform#1011]
**Describe the bug or issue you're experiencing**

Conditional fields that are set to show/hide based on the value of another field are not showing/hiding

**Steps to reproduce**

1. Create a Country dropdown field
2. Create a State dropdown field
3. Create a rule that the State field should only be visible if the country field is equal to "United States"

**Expected behavior**

The State field is visible when a user selects United States as their country

**Craft & Plugin Info (please complete the following information):**

- Craft Version: Craft Pro 4.7.1
- Freeform Version: 5.0.5
- Freeform Edition: Pro
- Fresh Install or Upgrade: Upgrade

**Additional context**

Hi, we're testing an upgrade to Freefom 5 on an existing site that is running version 4. The form has a country field with a number of options, and a state field that should only be visible if the country is set to United States. This worked on v4, but does not on v5. I've tried "is equal to", "starts with" and "contains" as the trigger in the rule but none work. If I try the negative condition (is not equal to, does not contain) the state field is visible on page load but it doesn't disappear if I select United States, which is what I would expect.

I've tried multiple combinations of how and where to load the Freeform scripts with no luck, and I can confirm that the scripts are loaded on the page.

I should also note that selecting any of "is empty", "is not empty", "is one of" or "is not one of" as the rule trigger causes an UnhandledMatchError template error, as it seems that these conditions are not defined in ConditionValidator.php: 

![Screen Shot 2024-01-31 at 2 50 27 PM](https://github.com/solspace/craft-freeform/assets/8181255/81736b24-e0a9-4a23-a2c4-bc58a7c3ef9f)

**Comment by chadcrowell** [comment]
+1 as reported via support form

**Comment by kjmartens** [comment]
Hi @phrichards and @chadcrowell,

I'm very sorry for the trouble. I can confirm this issue and we'll get it resolved very soon. 🙂

**Comment by kjmartens** [comment]
Freeform 5.0.8 is now available, which includes fixes for Conditional Rules. You may need to hard refresh the browser though. 🙂
