### ISSUE TITLE
Dynamic Notification fails - Expects a RecipientCollection type when a string/array is passed in

### ISSUE THREAD

**Issue by CAIDcreative** [solspace/craft3-freeform#1012]
**Describe the bug or issue you're experiencing**
When using the dynamicNotification parameter in your template in the template to pass in an email string/array of emails it will not submit and cause an error stating that it needs to be of type `RecipientCollection`.

However this seems to be a simple bug can be fixed by going to line `71` of `vendor/solspace/craft-freeform/packages/plugin/src/Bundles/Notifications/SendListeners/DynamicTemplateRecipients.php` and changing `$recipients` to `$recipientCollection` (the `$recipientCollection` is created and recipients are passed into it from `$recipients`, but it passes in `$recipients` and `$recipientCollection` is never used)

**Craft & Plugin Info (please complete the following information):**

- Craft Version: Craft Pro 4.7.1
- Freeform Version: 5.0.6
- Freeform Edition: Pro
- Fresh Install or Upgrade: Upgrade

**Comment by gustavs-gutmanis** [comment]
Thanks for finding this @CAIDcreative 

We'll add this fix to the next version!

**Comment by kjmartens** [comment]
Freeform 5.0.6.1 is now available and includes a fix for this. 🙂
