### ISSUE TITLE
Integrations page not available in environments with admin changes disallowed

### ISSUE THREAD

**Issue by FreekVR** [solspace/craft3-freeform#1013]
**Describe the bug or issue you're experiencing**
The integrations page is not shown in the freeform menu, nor is it reachable by URL, on environment where the project config is readonly.

**Steps to reproduce**

1. Set `allowAdminChanges' => false` in config/general.php
2. Navigate to https://cms.staging.gladwellacademy.com/admin/freeform/settings

**Expected behavior**
The integrations overview link is shown & available, I should be able to add CRM integrations through the admin panel as they are not stored in project config

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 4
- Freeform Version: 5.0.5
- Freeform Edition: Pro
- Fresh Install or Upgrade: Upgrade

**Additional context**
Integrations can be added and edited via direct deeplinks like
admin/freeform/settings/integrations/crm/2?site=en
admin/freeform/settings/integrations/crm

**Comment by jbrew30** [comment]
I submitted a support ticket regarding this issue. I was forced to switch my production site to dev mode to configure my Recaptcha and avoid the waves of spam emails. I'm so glad I'm not the only one seeing this issue.

**Comment by kjmartens** [comment]
Sorry about this @FreekVR and @jbrew30. This was technically still working if you accessed the pages directly, but the navigation menu was incorrectly hiding the links to them.

Anyway, Freeform 5.0.6.1 is now available and includes a fix for this. 🙂
