### ISSUE TITLE
v5 Unable to create user registration form - Chain icon/Element connections missing

### ISSUE THREAD

**Issue by satcreative** [solspace/craft3-freeform#1015]
I am upgrading from v4 to v5. I have a form that handles user registration which uses the 'Element connection' panel to map the form field to the user fields.

However, the element connection panel seems to no longer exist in v5. I have consulted the Freeform v5 docs and it references the old interface and says to click on the 'chain icon' to set up the connection - https://docs.solspace.com/craft/freeform/v5/guides/user-registration-forms/#step2

Am I missing something here are is this a bug?

**Steps to reproduce**

1. Create a user registration form in Freeform v5

**Expected behavior**

Element connection panel to be accessible on an individual form to allow user registration setup

**Craft & Plugin Info (please complete the following information):**

- Craft Version: Craft Pro 4.7.1
- Freeform Version:5.0.6
- Freeform Edition: Pro
- Fresh Install or Upgrade: Upgrade

**Additional context**

Reference doc - https://docs.solspace.com/craft/freeform/v5/guides/user-registration-forms/#step2

**Comment by satcreative** [comment]
Having looked through the changelogs, I can see that there is now an 'Elements' panel in the freeform main settings. This is where the element connections need creating, which can then be applied to the individual form in the 'Integrations' tab.

The freeform v5 docs need updating to reflect this new process.

**Comment by kjmartens** [comment]
Sorry for the inconvenience, @satcreative. There are definitely some areas in the docs that need to be adjusted. I will update this guide shortly. 🙂 

Please let us know if you encounter any other issues.
