### ISSUE TITLE
Notifications with tables in the html not sending

### ISSUE THREAD

**Issue by MariskaMB** [solspace/craft3-freeform#1018]
**Describe the bug or issue you're experiencing**

When using a notification template with table elements in de html, the notification does not get sent. No error is logged either, so tables may not be the only problem. I managed to get the notification to be sent only by removing all tables in the template, however.

**Steps to reproduce**

1. Go the the notifications tab to edit a notification template.
2. In the body of the e-mail, add a `<table>` element.
3. Go to a form and add a notification using the template with the table in it.
4. Fill out the form on the website like a normal visitor and submit, triggering the notifications to be sent.

**Expected behavior**

Notifications being sent with all the usual html elements, or alternatively an error being logged.

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 4.7.1
- Freeform Version: 5.0.6.1
- Freeform Edition: Pro
- Fresh Install or Upgrade: Upgrade

**Comment by kjmartens** [comment]
Hi @MariskaMB,

I have played around with this on my end and I cannot duplicate this issue. Are you 100% sure there weren't any errors in the template code? Can you try re-adding a table in the notification template and see if it fails? And if so, can you copy and paste the template code here? 🙂
