### ISSUE TITLE
Inclusion of Checkboxes field in export profile causing error: Cannot use object of type ...OptionCollection as array

### ISSUE THREAD

**Issue by satcreative** [solspace/craft3-freeform#1027]
I'm using a checkboxes field within a form. When I attempt to export the submission with that field included I receive the following error:

`Cannot use object of type Solspace\Freeform\Attributes\Property\Implementations\Options\OptionCollection as array`

When I disable the field from being included in the export profile then the export completes successfully.

**Steps to reproduce**

1. Create a form with a 'Checkboxes' field
2. Make some submissions to the form
3. Create an export profile with the checkboxes field included
4. Run the export. It should fail
5. Disable the checkboxes field from being included in the export profile
6. Run the export again. It should succeed

**Craft & Plugin Info (please complete the following information):**

- Craft Version: Craft Pro 4.7.1
- Freeform Version: 5.0.7
- Freeform Edition: Pro
- Fresh Install or Upgrade: Upgrade

**Error output**

`Error: Cannot use object of type Solspace\Freeform\Attributes\Property\Implementations\Options\OptionCollection as array in /var/www/html/vendor/solspace/craft-freeform/packages/plugin/src/Library/Export/AbstractExport.php:139
Stack trace:
#0 /var/www/html/vendor/solspace/craft-freeform/packages/plugin/src/Library/Export/AbstractExport.php(40): Solspace\Freeform\Library\Export\AbstractExport->parseSubmissionDataIntoRows(Array)
#1 /var/www/html/vendor/solspace/craft-freeform/packages/plugin/src/controllers/SubmissionsController.php(132): Solspace\Freeform\Library\Export\AbstractExport->__construct(Object(Solspace\Freeform\Form\Types\Regular), Array, Object(Solspace\Freeform\Library\DataObjects\ExportSettings))
#2 [internal function]: Solspace\Freeform\controllers\SubmissionsController->actionExport()
#3 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#4 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#5 /var/www/html/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('export', Array)
#6 /var/www/html/vendor/craftcms/cms/src/web/Application.php(305): yii\base\Module->runAction('freeform/submis...', Array)
#7 /var/www/html/vendor/craftcms/cms/src/web/Application.php(606): craft\web\Application->runAction('freeform/submis...', Array)
#8 /var/www/html/vendor/craftcms/cms/src/web/Application.php(284): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#9 /var/www/html/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest(Object(craft\web\Request))
#10 /var/www/html/web/index.php(12): yii\base\Application->run()
#11 {main}`

**Comment by kjmartens** [comment]
Hi @satcreative,

In my testing, it is working correctly. Can you tell me more about this field? What kind of values does it have configured for it? 🙂

**Comment by kjmartens** [comment]
Nevermind... I was able to duplicate this on another install. We'll get it resolved shortly. 🙂

**Comment by kjmartens** [comment]
This is now resolved in Freeform 5.0.10+. 🙂
