### ISSUE TITLE
[5.x] Migration error on install due to missing tables when using prefixes

### ISSUE THREAD

**Issue by jrrdnx** [solspace/craft3-freeform#1054]
**Describe the bug or issue you're experiencing**

Fresh install of 5.x fails due to a migration error. In the `afterInstall()` method, calls to `addForeignKey()` are referencing new table names but without the `{{%...}}` syntax so installs are failing on projects with a table prefix set.

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 4.7.2.1
- Freeform Version: 5.0.10
- Fresh Install or Upgrade: Fresh install

**Additional context**

Pull request incoming...

**Comment by kjmartens** [comment]
Hi @jrrdnx,

Sorry for the trouble, and thank you for reporting this.

This should be resolved in Freeform 5.0.11 now. 🙂
