### ISSUE TITLE
Field with handle name "parent" makes the display of submissions to crash.

### ISSUE THREAD

**Issue by thomas-soemoen** [solspace/craft3-freeform#1060]
If one creates a field with the name "parent" the display of a submission fails. I quess the reason is that "parent" is an reserved word in Craft. The line 

`value: submission[field.handle].value,` in the field templates fails since accessing parent tries to access a parent object, and not a field named "parent."

**Steps to reproduce**

1. Make a field with handle name "parent"
2. Make a submission
3. Try to display the submission in CP

**Expected behavior**
To get a error message in CP when create a field with a a handle name that is reserved in Craft.

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 4.7.3
- Freeform Version: 5.0.11
- Freeform Edition: Pro
- Fresh Install or Upgrade: Upgrade

**Additional context**

**Comment by kjmartens** [comment]
Sorry for the trouble @thomas-soemoen.

I can duplicate this as well. We'll get it resolved shortly. Thanks for reporting it. 🙂

**Comment by kjmartens** [comment]
This is fixed now in Freeform 5.0.13+. We've added a reserved words validator that is based on the Craft reserved fields validator. 🙂
