### ISSUE TITLE
Multi-page conditional skipping not working

### ISSUE THREAD

**Issue by Coysh** [solspace/craft3-freeform#1063]
**Describe the bug or issue you're experiencing**
Can't skip a page dependent on dropdown.

**Steps to reproduce**

1. Create dropdown
2. Create rule
3. If any values except 2 values are selected, the page should be skipped
![CleanShot 2024-02-19 at 15 37 14](https://github.com/solspace/craft-freeform/assets/5764356/0ba300f9-7a50-424f-9ad3-993d2ba16f9b)
![CleanShot 2024-02-19 at 15 37 53](https://github.com/solspace/craft-freeform/assets/5764356/3538ea41-da5b-4a2d-9d76-5e6323e00cba)

Sorry for some redacted information in screenshots

**Expected behavior**
Page **before** "Criteria for membership" should be skipped

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 4.6.0 Pro
- Freeform Version: 5.0.10
- Freeform Edition: Pro
- Fresh Install or Upgrade: Upgrade

**Additional context**
This was working in Freeform 4

**Comment by kjmartens** [comment]
Sorry for the trouble you're experiencing @Coysh.

I can duplicate this as well. We'll get it resolved shortly. 🙂

**Comment by kjmartens** [comment]
We've made a fix for this in Freeform 5.0.13. However, there is one other issue that may come up when final-submitting the form. We'll have another fix for that available very soon. 🙂
