### ISSUE TITLE
Entry integrations are always enabled

### ISSUE THREAD

**Issue by Rommert** [solspace/craft3-freeform#1065]
**Describe the bug or issue you're experiencing**

**Steps to reproduce**

Form submissions mapped as entries (via integrations) are always enabled.

I have tried various approaches with an invisible field set to 0, mapping it to the enabled field.

Settings such as enabled = false, enabled = 0, etc. Can this be fixed?

**Craft & Plugin Info (please complete the following information):**

- Craft Version:  4.7.1
- Freeform Version: 5.0.11
- Freeform Edition: PRO
- Fresh Install or Upgrade:

**Comment by kjmartens** [comment]
Sorry for the trouble, @Rommert.

I can't duplicate this in my testing. Curious, how many other integrations do you have configured in the list (in the Integrations tab of the form builder)?

And what is happening? Is it that it shows as enabled, but when you disable it, save the form, and then refresh the page, it's still showing enabled? Can you also send a screenshot of it? 🙂

**Comment by Rommert** [comment]
Thanks @kjmartens for your reply. It seems like my story is not entirely clear. A screenshot says more :)

![Scherm­afbeelding 2024-02-20 om 09 16 21](https://github.com/solspace/craft-freeform/assets/2290530/b140ce70-f582-499e-a7cb-998a23c322b6)

**Comment by kjmartens** [comment]
Hi @Rommert,

This will be fixed in Freeform 5.1.5 early next week. It will check for `n`, `no`, and `false` values to set the entry to Disabled. 🙂
