### ISSUE TITLE
Setting the value of a field with Template Overrides does not work according to documentation

### ISSUE THREAD

**Issue by andersaloof** [solspace/craft3-freeform#1067]
**Describe the bug or issue you're experiencing**

Prefilling the values of fields using template overrides does not work according to the documentation at https://docs.solspace.com/craft/freeform/v5/templates/formatting/#template-overrides. It states that one should use an `#` symbol followed by the field handle. This does not work, it only works without the `#` symbol.

**Steps to reproduce**

1. Create a form with two fields, with handles firstName and lastName.
2. Render the form with the following code
```twig
{% set form = craft.freeform.form('testTemplateOverrides', {
    fields: {
        '#firstName': { value: 'John' },
        lastName: { value: 'Doe' }
    }
}) %}
{{ form.render() }}
```
3. Observe that only the lastName has field has the value correctly prefilled.   
![image](https://github.com/solspace/craft-freeform/assets/1235821/eadaddd7-4809-435f-8d4e-4d823bde8ae8)

**Expected behavior**

According to the documentation, if should be opposite, firstName should be filled with 'John' since it's using the `#` symbol.

**Craft & Plugin Info (please complete the following information):**

- Craft Version:
- Freeform Version:
- Freeform Edition:
- Fresh Install or Upgrade:

**Additional context**

**Expected behavior**

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 4.7.1
- Freeform Version: 5.0.12
- Freeform Edition: PRO
- Fresh Install or Upgrade: Upgraded Freeform from 4.1.13

**Additional context**

**Comment by kjmartens** [comment]
Sorry about this @andersaloof.

The documentation is showing an older approach to it during the alpha. That changed along the way and we must have missed it. I'll update the documentation shortly. 🙂
