### ISSUE TITLE
Unable to create a form with a name using international characters

### ISSUE THREAD

**Issue by andersaloof** [solspace/craft3-freeform#1068]
**Describe the bug or issue you're experiencing**

Creating a new form, I'm unable to create it if the form name contains international characters.

**Steps to reproduce**

1. Press "Add new form" to open the modal
2. Open developer tools with the network tab open
3. Enter a name containing international characters, eg. `Test på skjema`, and press "Save"
4. Observe that the form is not created and the network request failing with error "Value is not a valid handle"

**Expected behavior**

The form should be created correctly and the created handle should be "testPaSkjema", in the same way a slug would be created on an entry with the same title.

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 4.7.1
- Freeform Version: 5.0.12
- Freeform Edition: PRO
- Fresh Install or Upgrade: Upgraded from 4.1.13

**Additional context**

**Comment by kjmartens** [comment]
Thanks for reporting this, @andersaloof.

I can duplicate this issue as well, and we'll get it fixed shortly. 🙂
