### ISSUE TITLE
Unable to view the submitted value of a hidden field with the handle "url"

### ISSUE THREAD

**Issue by andersaloof** [solspace/craft3-freeform#1069]
**Describe the bug or issue you're experiencing**

I have a hidden field on an existing form which is prefilled with the URL of the page the user is submitting the form on. This field is called URL, and the handle is `url`. However, the submitted value is not visible when viewing submissions. If I rename the field handle to `url2` the submitted value is visible.

**Steps to reproduce**

1. Create a new form with a field called URL and handle `url`.
2. Render the form on a page, enter some info in the field an submit it.
3. View the submission 
4. Observe that the value of the field is not visible when viewing the submission.   
![image](https://github.com/solspace/craft-freeform/assets/1235821/a7f2faaa-ada5-4735-9e92-e3df77c889a9)
5. Change the handle of the field to `url2`
6. Reopen the same submission and observe that the value of the field is visible.  
![image](https://github.com/solspace/craft-freeform/assets/1235821/97c5949b-04b3-46e6-912b-41a56f8b9f0c)

**Expected behavior**

The value of the submission should be visible no matter the name of the handle of the field.

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 4.7.1
- Freeform Version: 5.0.12
- Freeform Edition: PRO
- Fresh Install or Upgrade: Upgrade from 4.1.13

**Additional context**

When viewing the list of submissions, the value if the field URL is shown correctly no matter the name of the handle.

![image](https://github.com/solspace/craft-freeform/assets/1235821/21896d5e-88e2-48b5-a101-57f764874043)

**Comment by kjmartens** [comment]
Thanks for reporting this @andersaloof.

It's very likely that `url` should be a reserved keyword. We'll investigate the issue and make an appropriate change in an upcoming version. 🙂
