### ISSUE TITLE
Migration to 5 has migrated values to the wrong field

### ISSUE THREAD

**Issue by Coysh** [solspace/craft3-freeform#1072]
**Describe the bug or issue you're experiencing**
We've noticed that old submissions that were entered in Freeform 4 have migrated into different columns/fields in 5.
New submissions are mapping absolutely fine

![CleanShot 2024-02-20 at 19 24 19](https://github.com/solspace/craft-freeform/assets/5764356/2b0ebe04-152e-44d1-8e51-de30e715de2f)

**Steps to reproduce**

1.
2.

**Expected behavior**

**Craft & Plugin Info (please complete the following information):**

- Craft Version:
- Freeform Version:
- Freeform Edition:
- Fresh Install or Upgrade:

**Additional context**

**Comment by kjmartens** [comment]
Hi @Coysh,

Sorry for the trouble you are experiencing. Can I ask which version you upgraded to from v4? Was it the latest (`5.0.11` or `5.0.12`)? Or something before `5.0.11`? If it was before 5.0.11, there were issues we addressed in regards to this and we recommend you revert back to your FF4 backup and try the migration again on 5.0.12+.

**Comment by Coysh** [comment]
It was actually 5.0.10! I'll attempt that and let you know.
