### ISSUE TITLE
Expiry date mapping won't work

### ISSUE THREAD

**Issue by Rommert** [solspace/craft3-freeform#1081]
**Describe the bug or issue you're experiencing**

**Steps to reproduce**

I have migrated a Freeform form from version 4 to 5. There is currently an issue with the mapping of submissions to entries. Within the form, there is a datepicker (expiry date), and this field should be mapped as the 'expiration date' of the entry and a field named 'expiry date.' When this is done, the form returns a 500 error (in plugins.js). Can this be resolved?"

- Craft Version:
- Freeform Version:  5.0.12
- Freeform Edition: Pro
- Fresh Install or Upgrade: Upgrade

<img width="1052" alt="Scherm­afbeelding 2024-02-21 om 17 16 17" src="https://github.com/solspace/craft-freeform/assets/2290530/47a6df47-5a21-4215-817c-88553956582f">

**Comment by kjmartens** [comment]
Sorry for the trouble @Rommert.

I can duplicate this issue in my testing as well (including mapping to the Post Date as well). We'll get this fixed shortly. 🙂

**Comment by kjmartens** [comment]
This is resolved now in Freeform 5.0.14. 🙂
