### ISSUE TITLE
[5] Dropdown or Radio without default value causes fatal error

### ISSUE THREAD

**Issue by Coysh** [solspace/craft3-freeform#1086]
**Describe the bug or issue you're experiencing**
If I add a Dropdown or Radio field without selected a default value, I get a fatal error.
This is on my own template, as well as the default demo templates.
<img width="1312" alt="CleanShot 2024-02-22 at 12 14 43@2x" src="https://github.com/solspace/craft-freeform/assets/5764356/d15608f1-3ee6-4203-8a86-a0384a30087c">

**Steps to reproduce**

1. Create a dropdown field
2. Enter values, but don't select a default
3. Form rendered with fatal error `Cannot assign array to property Solspace\Freeform\Fields\Implementations\DropdownField::$defaultValue of type string`

**Expected behavior**

**Craft & Plugin Info (please complete the following information):**

- Craft Version:
- Freeform Version:
- Freeform Edition:
- Fresh Install or Upgrade:

**Additional context**

**Comment by kjmartens** [comment]
Hi @Coysh,

I am not able to duplicate this in my testing. Can you confirm which exact version of Freeform you're experiencing this on? And can you send a screenshot of what your field and its settings look like inside the form builder?

Thanks! 🙂

**Comment by davebeeldr** [comment]
Hi @kjmartens, 

I have almost the same problem only with the elements.
When we select the Elements from a dropdown and want to add a default value using a label. This is not shown on the website. It automatically grabs the first element. And not the 'placeholder' without a value.

![label issue freeform 5](https://github.com/solspace/craft-freeform/assets/78590032/49e00df9-0fb7-49da-b053-302cdc029bb4)

Freeform: 5.0.14.1
Craft CMS PRO: 4.7.4

**Comment by Coysh** [comment]
Hi @kjmartens - I'm struggling to reproduce this myself now, so happy for this to be closed. Though looks like @davebeeldr is having a similar issue

**Comment by kjmartens** [comment]
Thanks @Coysh 🙂 

@davebeeldr,

> I have almost the same problem only with the elements. When we select the Elements from a dropdown and want to add a default value using a label. This is not shown on the website. It automatically grabs the first element. And not the 'placeholder' without a value.

Unfortunately this is currently a limitation right now. However, we have plans to add support for an "Empty Option Label" for this kind of situation. 🙂
