### ISSUE TITLE
On the backend it is not possible to search for submissions using the content other than the title 

### ISSUE THREAD

**Issue by ggallo909** [solspace/craft3-freeform#109]
Problem: no submissions returned when searching for content in the "submissions" backend page other than the title.

Expected result: if there is a form with a text field called "message" and a submission contains the text "hello" written in the field "message", searching for the keyword "hello" in the "submissions" page (on the backend) should return the related submission entry. This worked correctly in Freeform for Craft 2.

**Craft & Plugin Info:**
 - Craft Version: 3.5.13.2
 - Freeform Version: 3.10.8
 - Freeform Edition: pro
 - Fresh Install or Upgrade: fresh install

**Comment by kjmartens** [comment]
This is currently a limitation of Freeform, unfortunately. Freeform's usage of its own fields makes the field searching incompatible in the current Submissions index page, and only Title searching will work at this time.

We will revisit this again now though, and see what our options are. We may be able to address this in the near future, but if not, definitely for Freeform 4.  :)

**Comment by moorebrett0** [comment]
@kjmartens - same issue here, would be REALLY nice if this feature could be worked in for several of our bigger free form using sites.

**Comment by klmiller308** [comment]
I have a lot of clients that use Freeform on Craft 2 with the search functioning correctly. Our Craft 3 clients are having a lot of trouble managing their submissions without the search. And we can't update our Craft 2 clients to Craft 3 until this is resolved. We would really appreciate a fix to this! Thank you!

**Comment by kjmartens** [comment]
Thanks for your feedback @moorebrett0 and @klmiller308. We're working on a solution for this now. :)

**Comment by kjmartens** [comment]
@ggallo909 @moorebrett0 @klmiller308 We've added support for this in the latest Freeform 3.11 beta. If you'd like to get access to this feature right now, you can check out the 3.11 beta. :)
https://docs.solspace.com/craft/freeform/v3/setup/betas.html

Otherwise, we'll likely have this available in the main release within the next week or two.
