### ISSUE TITLE
[5] Form not submitting (AJAX, Multipage)

### ISSUE THREAD

**Issue by Coysh** [solspace/craft3-freeform#1095]
**Describe the bug or issue you're experiencing**
A form is not submitting, AJAX request is being sent but no error or success message being shown.

**Steps to reproduce**

1. Create multi-page form
2. Complete form and press submit
3. AJAX response:
```
{
    "success": true,
    "finished": false,
    "onSuccess": "reload",
    "id": null,
    "hash": "NlDK9eK7O-a9pMRZM7g-5qhE7srxYXTPt7OMXVPYA8J93jmhFN1u3q44q77E",
    "values": {
        [REDACTED]
    },
    "errors": [],
    "formErrors": [],
    "returnUrl": "[Current URL]?success",
    "submissionId": null,
    "submissionToken": "5u7P4k2kNkdaQ6SHDPvt118iuaJPrMi6oorNxmIaCnGnxdcHIUVjVbYRYf9kleQybvQ0USTA0s4k4iO2IeUQJzMuxXnmPXvPRkwh",
    "html": "[REDACTED]"
}
```

**Expected behavior**
Form submits succesfully

**Craft & Plugin Info (please complete the following information):**

- Craft Version: Pro 4.7.4
- Freeform Version: Pro 5.0.13
- Freeform Edition:
- Fresh Install or Upgrade:

**Additional context**
The page has multi-page conditional rules

**Comment by kjmartens** [comment]
Hi @Coysh,

Sorry about this. This was an issue we fixed in 5.0.14, so an update will resolve the issue. 🙂
