### ISSUE TITLE
Change "Form Type" to "Surveys & Polls" has no effect

### ISSUE THREAD

**Issue by HigumaSan4050** [solspace/craft3-freeform#1103]
Change Form Type makes nothing.

1. Create new Form
2. got to Settings > General
3. Change "Form Type" to "Surveys & Polls"
4. Save

After save the Form Type of the form is still Solspace\Freeform\Form\Types\Regular in the Database.
It schould be Solspace\Freeform\Bundles\Form\Types\Surveys\Survey

- Craft Version: 4.8.0 Pro
- Freeform Version: 5.1.0 (Trial)
- Freeform Edition: Pro
- Fresh Install or Upgrade: Fressh

**Comment by kjmartens** [comment]
Sorry for the trouble @HigumaSan4050.

I can duplicate this issue as well. We'll get it resolved shortly. 🙂

**Comment by kjmartens** [comment]
This has been resolved in Freeform 5.1.2 now. 🙂
