### ISSUE TITLE
Cannot use the cc field in a notification template

### ISSUE THREAD

**Issue by wsteidl** [solspace/craft3-freeform#1104]
Hi there, 

What I try to achieve is to send out CC-emails with my email template, so I can pass email addresses from my form to this template. I want my client to be able to enter email-addresses in craft when adding a form to a page and then I add those emails to a hidden formfield and send this back to freeform. So the first step is just trying to use the CC field in the email notification template like this, with a hardcoded email:

{# cc: email@example.com #}

I am testing locally with ddev & mailpit, In my mailpit I do *not* get the cc email, only the main email, but the cc-email is there  in the CC:

<img width="262" alt="Screenshot 2024-03-04 at 10 00 10" src="https://github.com/solspace/craft-freeform/assets/104757329/7c983ecf-e90a-405a-b15d-28772b1aabe5">

I also tried it on a webserver that actually sends out emails, to a valid cc-email address, but no luck. But then again I do see that cc email in my mail client....

- Craft Version: 4.8.0
- Freeform Version: 5.1.0
- Freeform Edition: Pro
- Fresh Install or Upgrade: upgrade, but not from freeform 4, I started with freeform 5 on this project

**Comment by kjmartens** [comment]
Sorry for the delay, @wsteidl.

I can see this happening this way too, but I am wondering if it is just the mail service behaving this way. As in, when using with a built-in mail service or something like [Mailtrap](https://mailtrap.io/), it handles it this way, but in the real world it works fine.

I haven't heard anyone else report this issue. From what I can see, it seems to be behaving correctly. Have you had a chance to see if this appears to work correctly in production? And if not, can you try using a CC email address that is on a completely different server? 🙂
