### ISSUE TITLE
No ability to customize reCAPTCHA container template

### ISSUE THREAD

**Issue by timnolte** [solspace/craft3-freeform#1105]
**Describe the bug or issue you're experiencing**

The Google reCAPTCHA is now an automatically added field and so there doesn't seem to be a way to customize the container. There are ways to do this for the Submit buttons using the for `buttons` attribute configuration but there doesn't seem to be a way to do this anymore for reCAPTCHA.

**Expected behavior**

Should be able to set reCAPTCHA container classes.

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 4.8
- Freeform Version: 5.0.16
- Freeform Edition: Pro
- Fresh Install or Upgrade: Upgrade

**Additional context**

**Comment by kjmartens** [comment]
Thanks for your feedback @timnolte.

I have noted this and we'll likely implement something similar to how the Submit buttons are. Watch for an update sometime next week. 🙂

**Comment by kjmartens** [comment]
We've now added the ability to set classes and other attributes to the Captcha container `<div>` in Freeform 5.1.4:
https://docs.solspace.com/craft/freeform/v5/templates/formatting/#on-captcha-wrapper

``` twig
{{ form.render({
    captchas: {
        class: ["custom-class", "another-class"],
        "data-test": true,
    }
}) }}
```
