### ISSUE TITLE
Double Opt-In with ActiveCampaign

### ISSUE THREAD

**Issue by alexanderloewe** [solspace/craft3-freeform#111]
**Describe the bug or issue you're experiencing**
The Option for a Double Opt-In is missing in the mailing list option. 
When I create forms in ActiveCampaign I have to set the option for a  Double Opt-In in the form. In the Freeform UI I can't find an option for that. It this one missing?

**Comment by kjmartens** [comment]
This is a part of the integration is not currently supported. However, we'll add support for it this week. :)

**Comment by alexanderloewe** [comment]
Vers good. Thank you a lot.

**Comment by gustavs-gutmanis** [comment]
Hi, @alexanderloewe 

It seems like AC's API doesn't provide the means to handle double opt-in functionality.  
I've come across a forum post, which says that one should `pass the form ID to the contact api`, which I tried in several different ways, but nothing worked.  

There is [this article about automations](https://help.activecampaign.com/hc/en-us/articles/360016659919-Add-a-double-opt-in-automation-to-your-ActiveCampaign-account) which you might find useful, which might help you achieve what you're trying to do.

**Comment by alexanderloewe** [comment]
Hello,

okay thank you. I think we will contact ActiveCampaign and ask if they can add a way to do that directly via the API.
