### ISSUE TITLE
Table already exists error during migration

### ISSUE THREAD

**Issue by watchwood** [solspace/craft3-freeform#1111]
I'm trying to migrate our site from Craft 3 to Craft 4, and when I run the database migrations I get the following error:

Database Exception: SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'freeform_submissions_farm_renting_form_4' already exists
The SQL being executed was: CREATE TABLE freeform_submissions_farm_renting_form_4 (
id int(11) NOT NULL,
contactname_1 text,
email_3 text,
phonenumber_6 text,
type_of_farming_youre_interested_in_15 text,
housing_requirements_20 text,
amount_of_land_required_16 text,
outbuildings_required_19 text,
field_of_study_25 text,
select_valueasa_tenant_14 text
) ENGINE = InnoDb DEFAULT CHARACTER SET = utf8

Migration: Solspace\Freeform\migrations\m220330_111857_SplitSubmissionsTable

Output:

> create table {{%freeform_submissions_farm_renting_form_4}} ...Exception: SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'freeform_submissions_farm_renting_form_4' already exists
The SQL being executed was: CREATE TABLE freeform_submissions_farm_renting_form_4 (
id int(11) NOT NULL,
contactname_1 text,
email_3 text,
phonenumber_6 text,
type_of_farming_youre_interested_in_15 text,
housing_requirements_20 text,
amount_of_land_required_16 text,
outbuildings_required_19 text,
field_of_study_25 text,
select_valueasa_tenant_14 text
) ENGINE = InnoDb DEFAULT CHARACTER SET = utf8 (/home/vagrant/code/vendor/yiisoft/yii2/db/Schema.php:676)
#0 /home/vagrant/code/vendor/yiisoft/yii2/db/Command.php(1307): yii\db\Schema->convertException()
#1 /home/vagrant/code/vendor/yiisoft/yii2/db/Command.php(1102): yii\db\Command->internalExecute()
#2 /home/vagrant/code/vendor/yiisoft/yii2/db/Migration.php(322): yii\db\Command->execute()
#3 /home/vagrant/code/vendor/solspace/craft-freeform/packages/plugin/src/migrations/m220330_111857_SplitSubmissionsTable.php(118): yii\db\Migration->createTable()
#4 /home/vagrant/code/vendor/solspace/craft-freeform/packages/plugin/src/migrations/m220330_111857_SplitSubmissionsTable.php(85): Solspace\Freeform\migrations\m220330_111857_SplitSubmissionsTable->createFormTable()
#5 /home/vagrant/code/vendor/craftcms/cms/src/db/Migration.php(49): Solspace\Freeform\migrations\m220330_111857_SplitSubmissionsTable->safeUp()
#6 /home/vagrant/code/vendor/craftcms/cms/src/db/MigrationManager.php(233): craft\db\Migration->up()
#7 /home/vagrant/code/vendor/craftcms/cms/src/db/MigrationManager.php(149): craft\db\MigrationManager->migrateUp()
#8 /home/vagrant/code/vendor/craftcms/cms/src/services/Updates.php(252): craft\db\MigrationManager->up()
#9 /home/vagrant/code/vendor/craftcms/cms/src/controllers/BaseUpdaterController.php(493): craft\services\Updates->runMigrations()
#10 /home/vagrant/code/vendor/craftcms/cms/src/controllers/UpdaterController.php(203): craft\controllers\BaseUpdaterController->runMigrations()
#11 [internal function]: craft\controllers\UpdaterController->actionMigrate()
#12 /home/vagrant/code/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#13 /home/vagrant/code/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams()
#14 /home/vagrant/code/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction()
#15 /home/vagrant/code/vendor/craftcms/cms/src/web/Application.php(341): yii\base\Module->runAction()
#16 /home/vagrant/code/vendor/craftcms/cms/src/web/Application.php(729): craft\web\Application->runAction()
#17 /home/vagrant/code/vendor/craftcms/cms/src/web/Application.php(246): craft\web\Application->_processUpdateLogic()
#18 /home/vagrant/code/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest()
#19 /home/vagrant/code/public/index.php(23): yii\base\Application->run()
#20 {main}

This is with CraftCMS 4.8.0 and Freeform 5.1.0

**Comment by kjmartens** [comment]
Sorry for the trouble @watchwood,

Can you confirm which exact version of Freeform you started out with? If it wasn't the latest version of Freeform 3, could you try that first, then update to Craft 4 and Freeform 4.x. See if that works, then try updating to Freeform 5.x 🙂

**Comment by watchwood** [comment]
@kjmartens The prod site is currently on Freeform 3.13.32.  I have tried updating everything to the lasted Craft 3 compatible versions before migrating to Craft 4 versions.

**Comment by kjmartens** [comment]
Sorry for the delay @watchwood,

To confirm, if you attempt to update from Freeform 3 (fresh reset database, not using a potentially corrupted one from previous upgrade attempt) to Freeform 4, does the migration work?

I'm curious if what might have happened was that the FF4 migration worked out alright, and then the FF5 migration failed somewhere. However, instead of starting fresh with the original FF3 database, the database is already corrupt, so attempting to run the migration again fails because they've already partially run.

Is it possible this is the case? 🙂

**Comment by kjmartens** [comment]
Hi @watchwood,

We were able to replicate this issue and get it fixed now in Freeform 5.1.7. 🙂 

Sorry again for the trouble.
