### ISSUE TITLE
dynmaicNotifications hard limit on recipients?

### ISSUE THREAD

**Issue by StuartMcD** [solspace/craft3-freeform#1114]
So, I have a form to send updates to recipients to. It uses the `dynamicNotification` function and **works** well when I send it to say 3x email addresses in an array. When I send it the same behaviour but with 11 emails in array - it fails with the entire array followed by `... does not comply with addr-spec of RFC 2822`

I realise hard limits and am careful not to send to 100, be great if there was a BCC version but one thing at a time.

Cannot test exact number bc it's live data and use a dev group to test notifications thats limited to 3-4 addresses. Confirmed emails are all valid, no duplicates.
 

**Expected behavior**
It worked at some stage between V5.0 and now

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 4.74
- Freeform Version: 5.1.0
- Freeform Edition: Pro
- Fresh Install or Upgrade: Upgrade

**Comment by gustavs-gutmanis** [comment]
Hi @StuartMcD, based on the error message you're seeing, it seems like one or more of the email addresses is not a valid email address.

There are no limitations on how many addresses you could use.
The idea about allowing specifying `BCC` addresses makes a lot of sense, we will consider adding that functionality.

**Comment by StuartMcD** [comment]
I hear what you say but I can categorically deny any email address in the array is invalid. I use every email address listed to deliver an assortment of emails 1:1 and elsewhere without issue.

I use push to add emails to the array, as in

```
{% set emails = [] %}
{% for player in playerList %}
{% set emails = emails|push(player.c_email) %}
{% endfor %}
```

Then 

```
{% set emailsAsString = emails|unique|join(',') %}
{% set form = freeform.form("kennelNotifications", {
	attributes:{
		id: "form",
		class: "flex flex-col gap-4",
	},
	disable: ["submitButtons"],
	dynamicNotification: { 
	    recipients: [emailsAsString], 
	    template: "kennel_notification.twig" 
	},
}) 
%}
```
Tried removing the square brackets on the recipients tag to no avail.

In the log file in CP, the email addresses listed are wrapped in quotes '"' as though one long string which I'd imagine is a reporting format more so then a long string because if I target another group, it works just fine.

**Comment by gustavs-gutmanis** [comment]
Have you tried passing `recipients` as an array, that isn't a joined as a string?

```
  recipients: (emails|unique),
```

**Comment by StuartMcD** [comment]
It's late but I have a working version (no idea why it once did work but now doesnt).
