### ISSUE TITLE
v5 Elements Integrations lost multiple User Groups selection

### ISSUE THREAD

**Issue by vonscriptor** [solspace/craft3-freeform#1119]
In v4, Element Connections of Type Users (e.g. user registration) would allow you to select multiple User Groups to be applied. In v5 you can only select one.

**Steps to reproduce**

1. Create a User Integration
2. Can only select 1 User Group

**Expected behavior**
Be able to select multiple User Groups to associate the user with.

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 4.8.1
- Freeform Version: 5.1.1
- Freeform Edition: Pro
- Fresh Install or Upgrade: Upgrade

**Comment by kjmartens** [comment]
Sorry about this @vonscriptor,

We'll get this fixed shortly. 🙂

**Comment by kjmartens** [comment]
This will be addressed in Freeform 5.1.5. Stay tuned for that early next week. 🙂
