### ISSUE TITLE
SEO metric in Lighthouse: "Links are not crawlable"

### ISSUE THREAD

**Issue by jrrdnx** [solspace/craft3-freeform#112]
Running Lighthouse in Google Chrome includes the following check in the SEO metric:

> Links are not crawlable
> Search engines may use `href` attributes on links to crawl websites. Ensure that the `href` attribute of anchor elements links to an appropriate destination, so more pages of the site can be discovered.

```
Uncrawlable Link
--
a#cd1980-form-5KM0OK02p_0dc8_7433494e10dfe85f665504738b65ec744cffd9fc6048c0039baa4
```

Which is a link included in the form via `{{ craft.freeform.form(form.handle).render }}`.

I'm not sure of the purpose of this anchor tag, but since there's no `href` attribute I presume this is used as a link target somewhere. Could this be updated to be a `div` element instead? If it needs to remain an `a` element could `href` and `title` attributes be added? (Once the `href` is added to avoid the "not crawlable" issue, it's then replaced with an accessibility issue for not having descriptive text so would need a `title` attribute as well.)

 - Craft Version: 3.6.8
 - Freeform Version: 3.10.8

**Comment by gustavs-gutmanis** [comment]
@jrrdnx thanks for reporting this, it will be fixed in the upcoming release.
