### ISSUE TITLE
v5 "Send activation email?" option missing

### ISSUE THREAD

**Issue by vonscriptor** [solspace/craft3-freeform#1120]
In v4, Element Connections of Type Users (e.g. user registration) would allow you toggle "Send activation email?". In v5 the documentation references the same field when creating an Integration and when adding the form's integration, yet it doesn't appear.

**Steps to reproduce**

1. Create a User Integration
2. Any reference to "Send activation email?" is missing

**Expected behavior**
Be able to enable/disable activation emails for user integrations.

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 4.8.1
- Freeform Version: 5.1.1
- Freeform Edition: Pro
- Fresh Install or Upgrade: Upgrade

**Comment by vonscriptor** [comment]
It doesn't show up when creating/editing an Elements > Integrations, even if Active is toggled off. However, "Send activation email?" does show up when editing a form's Integrations when Active is toggled off. Might be a non-issue then.

**Comment by kjmartens** [comment]
Hi @vonscriptor,

This is working as expected. This is because an email activation cannot be sent if the user is automatically enabled. I will clarify the labeling of the "Activate Users" setting though... that part could be clearer. 🙂
