### ISSUE TITLE
Page tabs become inaccessible when the number of tabs exceeds the width of the browser window.

### ISSUE THREAD

**Issue by bwiggs42** [solspace/craft3-freeform#1122]
**Describe the bug or issue you're experiencing**
Page tabs become inaccessible when the number of tabs exceeds the width of the browser window. Specifically, the tabs begin to overflow out of the container and become hidden.

A quick solution is to add `overflow: scroll;` to the tab container.

![freeform-page-tabs](https://github.com/solspace/craft-freeform/assets/111062531/2a5fce6b-d181-4f7b-ae93-f09cd6b74a2b)

**Steps to reproduce**

1. Create a new form.
2. Add pages until the number of tabs exceeds the width of your browser window.

**Expected behavior**
Page tabs should remain accessible regardless of the number of tabs or the width of the browser window.

**Craft & Plugin Info:**

- Craft Version: 4.8.1
- Freeform Version: 5.1.2
- Freeform Edition: Pro
- Fresh Install or Upgrade: Fresh Install

**Comment by kjmartens** [comment]
Sorry about this @bwiggs42,

We'll get it resolved shortly. 🙂
