### ISSUE TITLE
[5.x] The form could not be submitted from with required "file drag & drop" fields

### ISSUE THREAD

**Issue by Romanavr** [solspace/craft3-freeform#1127]
**Describe the bug or issue you're experiencing**
If you add the “drag & drop file” field and make it **Required**, then it is impossible to submit the form, because it swears that the file is empty (or just fails the validation).
![изображение](https://github.com/solspace/craft-freeform/assets/3519951/c3f76e2e-eb46-4c8e-87af-991b4f92f5c8)
![изображение](https://github.com/solspace/craft-freeform/assets/3519951/2d0c0aa4-c663-44b9-90c6-1a0f9544d96b)

**Steps to reproduce**
1.Create a form with a "Drag & Drop" field
2.Drop any file (1 or more)
3. An error occurs

**Expected behavior**
1. There should be no error when submitting the form if the file added

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 4.8.0
- Freeform Version: 5.1.2
- Freeform Edition: **Pro**
- Fresh Install or Upgrade: **Upgrade**

**Additional context**

**Comment by kjmartens** [comment]
Sorry for the trouble @Romanavr.

I can't duplicate this issue in my testing, but I wonder if it's related to this issue? https://github.com/solspace/craft-freeform/issues/1126
