### ISSUE TITLE
[5.x] Conditional rules are migrated incorrectly (Argument #2 ($field) must be of type FieldInterface, null given)

### ISSUE THREAD

**Issue by Romanavr** [solspace/craft3-freeform#1128]
**Describe the bug or issue you're experiencing**
After upgrading to FreeForm 5.x, some of our forms broke + some conditions were not transferred/or were transferred incorrectly (for example, previously there was a value of “Not empty”, it was set to “Not equal to”)

The main error was the one below:
`Solspace\Freeform\Library\Rules\Condition::__construct(): Argument #2 ($field) must be of type Solspace\Freeform\Fields\FieldInterface, null given, called in /site.com/vendor/craft-freeform/packages/plugin/src/Bundles/Rules/RuleProvider.php on line 175`
As far as I understand, the error is that the form is trying to find a field that does not have one.
I solved this problem by deleting the rule from `freeform_rules_fields` table.
Perhaps someone will encounter the same problem and then you will have food for thought.

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 4.8.0
- Freeform Version: 5.1.2
- Freeform Edition: **Pro**
- Fresh Install or Upgrade: **Upgrade**

**Comment by kjmartens** [comment]
Thanks for reporting this @Romanavr. I will note this for further review by a developer 🙂
