### ISSUE TITLE
[5.x] Can't add conditional rules for Submit button?

### ISSUE THREAD

**Issue by Romanavr** [solspace/craft3-freeform#1129]
**Describe the bug or issue you're experiencing**
Before this, it was possible to add conditional rules for the "Submit" button, because it was made as a separate element.
Now it is always included in the form by default and I don’t quite understand how to prevent it from being displayed by default directly from the form settings?
I had a condition for displaying the Submit button when certain fields were filled out.
I didn't find anything about this in the migration guide, only this https://docs.solspace.com/craft/freeform/v5/templates/formatting/#submit-button-customization.
Do I understand correctly that this functionality has been removed?

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 4.8.0
- Freeform Version: 5.1.2
- Freeform Edition: **Pro**
- Fresh Install or Upgrade: **Upgrade**

**Comment by kjmartens** [comment]
Thanks for your feedback about this, @Romanavr.

The new automatic insertion of Submit buttons definitely complicates this. I will check with a developer and see if we can find a solution. 🙂

**Comment by kjmartens** [comment]
This is now possible in Freeform 5.1.16+. 🙂 

Thanks for your patience, @Romanavr.
