### ISSUE TITLE
Conditional fields are difficult to set when a form has two or more fields with same name

### ISSUE THREAD

**Issue by vasuhooda** [solspace/craft3-freeform#113]
**Describe the bug or issue you're experiencing**

Some fields have same `name`. But the `handle` is different. For example 
<img width="1213" alt="Screenshot 2021-03-10 at 14 55 22" src="https://user-images.githubusercontent.com/8009769/110640352-06e81680-81b1-11eb-955e-e45ed632b8f1.png">

In conditional fields, only field `name` is visible, `handle` is not visible - 
<img width="967" alt="Screenshot 2021-03-10 at 14 55 39" src="https://user-images.githubusercontent.com/8009769/110640387-11a2ab80-81b1-11eb-9343-e3bc35dbff07.png">

Without `handle` there is no way to know if you have selected correct field while setting condition. This makes it very difficult for the end user to set conditions.

**Expected behavior**
`handle` should be visible in a bracket along with `name` for setting conditional fields

**Craft & Plugin Info (please complete the following information):**
 - Craft Version: 3.2.10
 - Freeform Version: 3
 - Freeform Edition: 3.5.9

**Comment by gustavs-gutmanis** [comment]
@vasuhooda thanks for reporting this.

A checkbox toggle has been added to let you enable the displaying of field handles next to the labels as well.

![image](https://user-images.githubusercontent.com/709181/110752833-74965000-824e-11eb-95df-11b3d046a8d1.png)

It will be added in the next release.
