### ISSUE TITLE
Option for "Not like" in export report options

### ISSUE THREAD

**Issue by clarknelson** [solspace/craft3-freeform#1131]
**Describe the bug or issue you're experiencing**

My client was curious if there is a reason the "Not like" filter option is not available in this settings menu. They might be able to use it filter out expected results.

![image](https://github.com/solspace/craft-freeform/assets/4106671/6131538e-23eb-46f2-a593-84e9d36ab1d7)

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 4.8
- Freeform Version: 5.1
- Freeform Edition: Pro
- Fresh Install or Upgrade: Upgrade

**Comment by kjmartens** [comment]
Thanks for your feedback @clarknelson,

I'll check and see if this is a quick thing for us to add support for. 🙂

**Comment by kjmartens** [comment]
This has now been added in Freeform 5.1.6. 🙂
