### ISSUE TITLE
Google reCAPTCHA v3 marks all submissions as spam

### ISSUE THREAD

**Issue by br-designer** [solspace/craft3-freeform#1135]
**Describe the bug or issue you're experiencing**
Following an upgrade from Freeforms v4 to v5, all new form submissions are being incorrectly flagged as spam by Google reCAPTCHA v3. Despite using the same reCAPTCHA keys as the previous version where they functioned correctly, and even setting the score threshold to 1.0 to ensure submissions are recognized as human, the issue persists. This problem is challenging to troubleshoot due to the automatic injection of reCAPTCHA into forms.

**Expected behavior**
Expecting legitimate submissions to not be marked as spam.

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 4.8.1
- Freeform Version: 5.1.2
- Freeform Edition: Pro
- Fresh Install or Upgrade: Upgrade

**Additional context**
reCAPTCHA settings within CMS
<img width="1250" alt="Screenshot 2024-03-12 at 11 11 38 AM" src="https://github.com/solspace/craft-freeform/assets/5600724/64177afd-9245-476a-9f79-37ed5f4f3cfd">

Template code for reference:
```twig
{%- set form = form ?? {} -%}
{%- set label = label ?? true -%}
{%- set gridClass = gridClass ?? "" -%}
{%- set placeholder = placeholder ?? false -%}

{{ form.renderTag({
    class: "form",
    labelClass: "uk-form-label",
    submitClass: "button-primary transition-bg transition-750",
    buttons: {
        attributes: {
            submit: { class: "button-primary transition-bg transition-750" },
            back: { class: "button-secondary transition-bg transition-750" },
            save: { class: "button-primary transition-bg transition-750" },
        },
        submitLabel: "Send",
        backLabel: "Previous",
        saveLabel: "Save",
    },
}) }}
{% if form.submittedSuccessfully %}
    <div class="p-4 mb-6 text-green-success bg-green-success-bg">
        {{ form.successMessage }}
    </div>
{% endif %}
{% if form.hasErrors %}
    <div class="p-4 mb-6 text-red-700 bg-red-100 freeform-form-has-errors">
        <p class="font-bold">
            {{ "There was an error submitting this form"|t }}
        </p>
        {% if form.errors|length %}
            <ul>
                {% for error in form.errors %}
                    <li>{{ error }}</li>
                {% endfor %}
            </ul>
        {% endif %}
    </div>
{% endif %}

{% if craft.app.request.getQueryParam('success') == 1 %}
    <div class="p-4 mb-6 text-green-success bg-green-success-bg">
        Your message has been sent. A team member will contact you shortly.
    </div>
{% endif %}

<div class="flex flex-wrap md:-mx-8 {{ gridClass }}" uk-grid>
    {% for row in form %}
        {% for field in row %}
            <div class="w-full md:w-1/{{ row|length }} md:px-8">
                {{ field.render }}
            </div>
    {% endfor %}
{% endfor %}
</div>

{{ form.renderClosingTag }}

```

**Comment by kjmartens** [comment]
Sorry for the trouble you're experiencing @br-designer.

To rule some things out, is it possible for you to try the form in the demo templates? Or create a brand new template somewhere with the template code like this:

``` twig
<html>
<head></head>
<body>

{{ freeform.form("yourFormHandle", {
    formattingTemplate: 'basic-light/index.twig'
}).render() }}

</body>
</html>
```

If that doesn't work, can you take a screenshot of your Diagnostics page in the Freeform control panel? 🙂

**Comment by br-designer** [comment]
I tried using the template code above and received the same spam error. I've attached a screenshot of the diagnostics page as requested. Thanks!

<img width="1089" alt="Screenshot 2024-03-18 at 2 59 00 PM" src="https://github.com/solspace/craft-freeform/assets/5600724/fd88f1f2-df55-4601-a5c3-0fc2de7f5291">

**Comment by kjmartens** [comment]
Sorry for the delay @br-designer,

Are you seeing any JS errors in the browser? And if so, what does it say?

Also curious if changing the _Freeform Script Insert Type_ setting from **As Static URLs** to **As Files** makes any difference for you? 🙂

**Comment by br-designer** [comment]
Hey @kjmartens, Sorry for not closing out this issue. We created new reCAPTCHA keys yesterday and the forms worked as expected. Just terrible timing for the keys to have an issue. Really appreciate your help with this.

**Comment by kjmartens** [comment]
Thank you for letting us know @br-designer. Glad you were able to figure this one out. 🙂
