### ISSUE TITLE
Updating Recipients does not always work

### ISSUE THREAD

**Issue by fvwanja** [solspace/craft3-freeform#1136]
**Describe the bug or issue you're experiencing**

**Steps to reproduce**

1. Go to forms notifications
2. Admin notification
3. Update the value
4. Hit „Save”
5. Navigate to another section
6. Go back
7. See the old value

![Screenshot 2024-03-12 at 18 15 09](https://github.com/solspace/craft-freeform/assets/90781427/63ea8c20-b2c9-4a4f-92b3-90bd7ce9ef2a)

I recorded a video of this, so you can see for yourselves:

https://github.com/solspace/craft-freeform/assets/90781427/3a09d0ed-ba3f-466d-a7e3-fb11df7ab415

**Expected behavior**

After saving we should see the new value. 

It does work, when I reload the page after saving.

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 4.8.1
- Freeform Version: 5.1.2
- Freeform Edition: Pro
- Fresh Install or Upgrade: Upgrade from 4

**Comment by kjmartens** [comment]
Thanks for reporting this @fvwanja,

I can duplicate this behavior as well. We'll get it resolved shortly. 🙂

**Comment by kjmartens** [comment]
This is now resolved in Freeform 5.1.5. 🙂

**Comment by fvwanja** [comment]
Thank you 👍
