### ISSUE TITLE
[5.x] GraphQL documentation has old field names 

### ISSUE THREAD

**Issue by Stalex89** [solspace/craft3-freeform#1158]
Some fields in documentation for the version 5.x have old names:

[Form Interface](https://docs.solspace.com/craft/freeform/v5/headless/graphql/#form-interface)

1. showSpinner (should be showProcessingSpinner)
2. showLoadingText (should be showProcessingText)
3. loadingText (should be processingText)

**Comment by kjmartens** [comment]
Sorry about this @Stalex89. We'll get the docs updated shortly. 🙂
