### ISSUE TITLE
[5.x] Cannot set maximum length of chars for Text and Textarea fields, GraphQL field also disappeared

### ISSUE THREAD

**Issue by Stalex89** [solspace/craft3-freeform#1159]
**Describe the bug or issue you're experiencing**

After upgrading Freeform plugin from v4.x to v5.x, I cannot set the maximum length of chars for Text and Textarea fields anymore, also this field is available no more in GraphQL query.

However, the field is still present in [Standard settings](https://docs.solspace.com/craft/freeform/v5/forms/fields/#standard-settings)

**Craft & Plugin Info (please complete the following information):**

- Craft Version: Craft Pro 4.8.4
- Freeform Version: 5.1.6
- Freeform Edition: Pro
- Fresh Install or Upgrade: Upgrade from 4.1.13

**Comment by kjmartens** [comment]
Sorry for the trouble @Stalex89. We'll get this one addressed shortly. 🙂

**Comment by kjmartens** [comment]
This should be resolved in Freeform 5.1.9 now. 🙂
