### ISSUE TITLE
Cacheable forms CSRF token error

### ISSUE THREAD

**Issue by alexanderloewe** [solspace/craft3-freeform#116]
**Describe the bug or issue you're experiencing**
I cache my the page wirn Bliz now i want so load the CSRF via ajax like in your Doc:
https://docs.solspace.com/craft/freeform/v3/templating/caching.html#twig-template-caching

My setup

Folder: `ajax/form.twig`
This folder is not cached by bliz, i have other files in this folder, they work fine.

Inside the file is this.
```
{{ {
    hash: craft.freeform.form(craft.app.request.get('footerSlimForm')).hash,
    honeypot: craft.freeform.honeypot( craft.freeform.form(craft.app.request.get('footerSlimForm')) ),
    csrf: {
        name: craft.app.config.general.csrfTokenName,
        value: craft.app.request.csrfToken,
    }
} | json_encode | raw }}
```

I try this as well:
```
{% set form = craft.freeform.form(craft.app.request.get('footerSlimForm')) %}
{{ {
    hash: form.hash,
    csrf: {
        name: craft.app.config.general.csrfTokenName,
        value: craft.app.request.csrfToken,
    }
} | json_encode | raw }}
```

When I try to access the file via URL I then this error:
```
Argument 1 passed to Solspace\Freeform\Services\FormsService::getFormByHandle() must be of the type string, null given, called in /home/www/florianilgen/v1/vendor/solspace/craft-freeform/packages/plugin/src/Services/FormsService.php on line 203
```
With:
`https://domain.com/ajax/form?form=footerSlimForm` or
`https://domain.com/ajax/form`

The form with the handle footerSlimForm exists. I also have tried it with an other form, same error.

**Craft & Plugin Info (please complete the following information):**
 - Craft Version: 3.6.10
 - Freeform Version: 3.10.9
 - Freeform Edition: Pro
 - Fresh Install or Upgrade: Fresh

**Comment by gustavs-gutmanis** [comment]
Hi @alexanderloewe, you're asking for an URL query variable of the name `footerSlimForm` which would contain the handle.  
What you need is to just pass the form handle as string:

```twig
{% set form = craft.freeform.form('footerSlimForm') %}
{{ {
    hash: form.hash,
    csrf: {
        name: craft.app.config.general.csrfTokenName,
        value: craft.app.request.csrfToken,
    }
} | json_encode | raw }}
```
