### ISSUE TITLE
Multipage Forms Rules broken?

### ISSUE THREAD

**Issue by ghost** [solspace/craft3-freeform#1161]
Skipping pages works from the first page, but not from the following pages.

**Steps to reproduce**

1. Create a new freeform form with four pages.
2. Place a radio button with two options on the 1st page.
3. Create a text field on page 2.
4. Create a text field on page 3.
5. Create a rule on page 2 that it is only displayed if option 1 is selected.
6. Create a rule on page 3 that it will only be displayed if option 2 is selected.
7. Create a rule for page 4 that is to be displayed if content has been entered in the respective text field on page 2 OR on page 3.
8. Call up the form in the frontend and select option 1 and submit to get to page 2.
9. Enter text in the text field on page 2 and submit.
10. you arrive on page 3, although the conditions for page 4 are fulfilled and those for page 3 are not

**Expected behavior**
I would have expected to be able to skip the third page, but this doesn't seem to work. 
It still worked in  Craft Pro 4.7.2.1; Freeform Pro 4.1.13 though

**Craft & Plugin Info:**
- Craft Version: Pro 4.8.1
- Freeform Version: 5.1.3
- Freeform Edition: Pro
- Fresh Install or Upgrade: Upgrade

**Comment by kjmartens** [comment]
Hi @BlueElefant,

It is currently expected that conditional rules do not apply across all pages (only their current page). However, we have queued up adding this as a new feature - hoping to have it available within the next week ish. 🙂 

After rereading your list a couple of times, I think it's possible this is not the issue exactly, but we'll try to ensure this flow works as well. 🙂

**Comment by BasBeeldr** [comment]
Hi @kjmartens,

I'm experiencing the same problem. Now I see that you indicated about 3 weeks ago that you would hopefully have a solution within 1 week, but this does not seem to have been successful yet. Is there any prospect of when there will be a solution to this?

**Comment by kjmartens** [comment]
Sorry @BlueElefant and @BasBeeldr,

We are currently working on a large update to Conditional Rules that includes support for this. We should likely have an update available next week. 🙂

**Comment by kjmartens** [comment]
This is now possible in Freeform 5.1.16+. 🙂 

Thanks for your patience, @BlueElefant and @BasBeeldr

**Comment by samuel-clara** [comment]
This seems still to not work. I have version 5.5.5 installed.

I have 6 pages, and I've set a rule on page 2,3,4,5 so that only one of these should be shown based on the value of a field on page 1. When clicking on submit it correctly skips the first pages but when for example the first submit sends to page 3, by the next submit also 4 is shown and then also 5 (both excluded by specific rules).

**Comment by kjmartens** [comment]
Hi @samuel-clara,

This is behaving as expected. A page that skips to another, cannot know to ignore other pages beyond that one. For example, if you're skipping from page 1 to page 3, Freeform cannot know that page 3 is also the "last page", unless you add additional logic to page 3 to tell it to submit the form if Field X contains whatever. So it might still be doable then. 🙂
