### ISSUE TITLE
Form with Stripe Payment and Recaptcha incorrectly validating

### ISSUE THREAD

**Issue by icreatestuff** [solspace/craft3-freeform#1165]
When I have a form that has both the Stripe and Recaptcha v2 checkbox integrations enabled, leaving the Recaptcha field unticked still processes submits the form successfully and charges the customer.

![Screenshot 2024-03-26 at 15 08 12](https://github.com/solspace/craft-freeform/assets/1300714/5e1e34e1-8750-4fb3-8017-d5fe783690c6)

**Expected behavior**
The form should fail to validate until the Recaptcha checkbox is ticked.

**Craft & Plugin Info (please complete the following information):**

- Craft Version: Pro 4.8.5
- Freeform Version: 5.1.7
- Freeform Edition: Pro
- Fresh Install or Upgrade: Upgrade

**Comment by icreatestuff** [comment]
In case it's useful here's the diagnostics info
![Screenshot 2024-03-26 at 15 25 03](https://github.com/solspace/craft-freeform/assets/1300714/38c10deb-76c7-4a64-967a-8e18cf40acac)

**Comment by kjmartens** [comment]
Sorry for the trouble @icreatestuff. We'll get this fixed shortly. 🙂

**Comment by kjmartens** [comment]
This should be resolved in Freeform 5.1.9 now. 🙂
