### ISSUE TITLE
Undefined constant EVENT_UPDATE_PAYMENT_INTENT_DATA

### ISSUE THREAD

**Issue by icreatestuff** [solspace/craft3-freeform#1166]
**Describe the bug or issue you're experiencing**
I'm looking for a way to add custom metadata to a payment in Stripe.

I found [this documentation](https://docs.solspace.com/craft/freeform/v5/developer/events/stripe-payments/#when-updating-payment-intent-data), however, copying that code block into my site's custom module class threw up some issues.

Initially I was warned that the `Solspace\Freeform\Integrations\PaymentGateways\Stripe` class didn't exist but was able to find the following class `Solspace\Freeform\Integrations\PaymentGateways\Stripe\Stripe`.

However this then produced the following error:
`Undefined constant Solspace\Freeform\Integrations\PaymentGateways\Stripe\Stripe::EVENT_UPDATE_PAYMENT_INTENT_DATA`

**Expected behavior**
No error is thrown and the custom data is added to the payment and viewable within the Stripe dashboard.

**Craft & Plugin Info:**

- Craft Version: Pro 4.8.5
- Freeform Version: 5.1.7
- Freeform Edition: Pro
- Fresh Install or Upgrade: Upgrade

**Additional context**
![Screenshot 2024-03-26 at 15 25 03](https://github.com/solspace/craft-freeform/assets/1300714/ee4d6623-36f4-4ec2-aba1-c6cbb912e926)

**Comment by kjmartens** [comment]
Sorry for the trouble @icreatestuff. This will be different in Freeform 5. I'll have @gustavs-gutmanis check into this and get more details shortly. 🙂

**Comment by kjmartens** [comment]
The updated event for Stripe in Freeform 5 (available in upcoming 5.1.9 release) will now be:

``` php
use Solspace\Freeform\Integrations\PaymentGateways\Stripe;
use Solspace\Freeform\Integrations\PaymentGateways\Events\UpdateMetadataEvent;

Event::on(
  Stripe::class,
  Stripe::EVENT_UPDATE_PAYMENT_METADATA,
  function (UpdateMetadataEvent $event) {
    $event->addData('description', 'My custom payment intent description');
    $event->addData('custom metadata entry', 'Some more data to be persisted in metadata');
  }
)
```

Once we release 5.1.9 and you update to it, try the above event. Please let me know if you have any issues using it. 🙂

**Comment by icreatestuff** [comment]
Thanks @kjmartens this is working great for including static (unchanging) text. Is there a way to access the submission data within this event to pass along as metadata with the Stripe payment making it more dynamic? For example, if we used a form to collect donations and had a 'reason for your donation' textarea field, we'd like to be able to pass that content along to Stripe too.

**Comment by gustavs-gutmanis** [comment]
Hi @icreatestuff,

Due to the new approach Stripe is taking, we are creating the payment before the submission is finalized. Only after stripe has been successful is the submission then created.

What you could do, is listen to the [after submit event](https://docs.solspace.com/craft/freeform/v5/developer/events/submission/#after-a-submission-is-submitted) and get the submission details you want to update the stripe payment with, then fetch the Stripe integration for the current form and perform an update for the payment intent (payment intent ID is stored in the payment field value for the current submission).

This would get pretty complicated pretty fast, I think we can offer another event which would streamline this process for you, but it will take a bit of time for us to implement it. Would that work for you?

**Comment by icreatestuff** [comment]
Thanks for the extra context @gustavs-gutmanis that's really helpful. I'll look into the 'after submit' approach but it might be that we wait on any new event(s) you can provide in future to keep it streamlined.

**Comment by LoriWJ** [comment]
Hi @gustavs-gutmanis, I also need to pass data from the form fields to Stripe. Can you explain how I can do this with the after submit event? How do you deal with the field mapping for the address fields? I want field mapping with some fields mapped to the metadata area in Stripe. We had this set up in Freeform 4 but it no longer works.

**Comment by gustavs-gutmanis** [comment]
Hi @LoriWJ 
Sorry for the late reply.

You should be able to access all of your form fields within the event.
Here's an example:

```php
use Solspace\Freeform\Integrations\PaymentGateways\Stripe;
use Solspace\Freeform\Integrations\PaymentGateways\Events\UpdateMetadataEvent;

Event::on(
  Stripe::class,
  Stripe::EVENT_UPDATE_PAYMENT_METADATA,
  function (UpdateMetadataEvent $event) {
    $form = $event->getForm();

    $fields = $form->getLayout()->getFields()->getStorableFields();
    foreach ($fields as $field) {
        $event->addData($field->getHandle(), $field->getValueAsString());
    }
  }
)
```

Let me know if you need further assistance.

**Comment by icreatestuff** [comment]
@gustavs-gutmanis Am I right in thinking the implementation example you gave above still wouldn't work for dynamic content within the form? It still looks like this event is only run when the Payment Intent is initially created, not when the form is submitted, which means that it could only work for static file data e.g. from a hidden field.

Has there been any progress on creating an event that would allow updating the Payment intent or charge metadata after the submission is created? Thanks

**Comment by gustavs-gutmanis** [comment]
You are correct, the submission element is not available during this event.
We can create an event which triggers when the submission data is being attached to the stripe payment after the whole process is done - that will allow you to do what you're looking for.
I'm adding the task to our backlog and we'll get to it as soon we have spare time.
Sorry for the inconvenience.

**Comment by icreatestuff** [comment]
Thanks for confirming @gustavs-gutmanis, I'll keep my eyes peeled for that new event in future.

**Comment by gustavs-gutmanis** [comment]
But, if you don't need a submission's ID, the submitted data should be available for you, even the dynamic values posted, you just need to access them via the form object.

```php
$form->get('myFieldHandle')->getValue();
```

**Comment by icreatestuff** [comment]
I don't need the submission ID at the moment, here's what I have:

```php
Event::on(
    Stripe::class,    
    Stripe::EVENT_UPDATE_PAYMENT_METADATA,
    function (UpdateMetadataEvent $event) {
        $form = $event->getForm();
        $fields = $form->getLayout()->getFields()->getStorableFields();
                
        foreach ($fields as $field) {
            // Gift Aid
            if ($field->getHandle() === 'giftAid') {
                $event->addData('Gift Aid', $field->getValueAsString() == '1' ? 'Yes' : 'No');
            }
        }
    }
);
```

Gift Aid is added as a metadata key, but the value it is set to is always 'No' because the checkbox isn't ticket by default.

Worth noting that we ask for the 'amount' before the Gift Aid field so I assume the Payment Intent and therefore this code, is run using all the default values for the fields, and that the payment intent isn't updated when any other fields other than the amount field are changed.

To be totally accurate my guess is we'd need an event that triggers at a similar time to `EVENT_AFTER_SUBMIT` that handles updating the metadata and does the heavy lifting of processing that on the relevant payment intent for the relevant Stripe Integration.

Or another way to look at it might be to have a way to trigger an update to the payment intent which in turn uses this existing event `EVENT_UPDATE_PAYMENT_METADATA` when other fields in the form are changed.

**Comment by LoriWJ** [comment]
@icreatestuff, I'm also trying to query the Gift Aid checkbox. I found a workaround: split the form into pages and have the payment fields on the last page. It's not ideal, but at least I've got the form working again (for now) after the upgrade to Freeform 5.

**Comment by kjmartens** [comment]
In Freeform 5.6.3, we've added a new Stripe `EVENT_AFTER_UPDATE_PAYMENT_METADATA` event that allows additional metadata to be attached to a payment intent when a submission is created. 🙂

**Comment by icreatestuff** [comment]
Amazing thank you @kjmartens and team. Is this documented anywhere, or would it be a drop-in replacement to the `EVENT_UPDATE_PAYMENT_METADATA` event we've tried before?

**Comment by gustavs-gutmanis** [comment]
@icreatestuff it is the same event but fired with a different trigger, so that you can handle both cases. 

We will add documentation for it in a little bit, but you should be able to do what you did before, only this time the submission object will be persisted and present.

**Comment by icreatestuff** [comment]
👍 thanks @gustavs-gutmanis

**Comment by icreatestuff** [comment]
Hey @gustavs-gutmanis @kjmartens are you able to confirm if this is still working? I'm not seeing any custom metadata saved against the Stripe transaction/Payment Intent. 

```php
use Solspace\Freeform\Integrations\PaymentGateways\Stripe\Stripe;
use Solspace\Freeform\Integrations\PaymentGateways\Events\UpdateMetadataEvent;

Event::on(
    Stripe::class,
    Stripe::EVENT_AFTER_UPDATE_PAYMENT_METADATA,
    function (UpdateMetadataEvent $event) {
        $event->addData('TEST', 'Hello World');
    }
);
```

I do see the 'submission' saved in the metadata which I believe is being set in the `StripeCallbackService` class and where the `UpdateMetadataEvent` event is triggered, but it's like it isn't combining my custom metadata with the `$submissionMetadata` array defined in that class.

We're currently on Freeform 5.8.0 and Craft 4.13.5
