### ISSUE TITLE
Freeform 5 - Salesforce integration

### ISSUE THREAD

**Issue by kate-stretton** [solspace/craft3-freeform#1168]
**Describe the bug or issue you're experiencing**

**Steps to reproduce**

After upgrading to Freeform 5, I set up the Salesforce integration again following the instructions here - https://docs.solspace.com/craft/freeform/v5/integrations/salesforce/ . The integration is correctly showing as 'Authorized'. I've mapped the form fields to the leads endpoint. 

When I attempt to submit a form which uses the integration I get an error. The response is 
 **`400 Bad Request` response: [{"message":"Cannot deserialize instance of boolean from VALUE_STRING value 0 or request may be missing a required field (truncated...)**

There are two checkbox fields on the form. The values for these fields are being sent through as strings with 'yes' or 'no' rather than as booleans. Is this likely to be the issue? 

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 4.8.1
- Freeform Version: 5.1.7
- Freeform Edition: Freeform Pro
- Fresh Install or Upgrade: Upgrade

**Comment by kjmartens** [comment]
Sorry for the trouble you're experiencing @kate-stretton,

I can duplicate this happening to me, too. We'll get it fixed shortly. 🙂

**Comment by kjmartens** [comment]
This should be resolved in Freeform 5.1.9 now. 🙂

**Comment by kate-stretton** [comment]
Thank you so much :)
