### ISSUE TITLE
Problem with POST Forwarding when upgrading to version 5

### ISSUE THREAD

**Issue by JamesNock** [solspace/craft3-freeform#1169]
**Describe the bug or issue you're experiencing**

We're currently trying to upgrade to version 5 of Freeform from version 4 but we've hit a problem in that the PayloadForwarding code seems to have been removed in version 5.

**Steps to reproduce**

1. Add the code as per the official documentation here: https://docs.solspace.com/craft/freeform/v5/developer/events/post-forwarding/
2. Run `php craft migrate/all`

**Expected behavior**

I'd expect the migration to run but instead I get this error:
`Exception 'Error' with message 'Class "Solspace\Freeform\Bundles\Form\PayloadForwarding\PayloadForwarding" not found'`

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 4.7.4
- Freeform Version: 5.1.7
- Freeform Edition: Pro
- Fresh Install or Upgrade: Upgrade

**Additional context**

**Comment by kjmartens** [comment]
Sorry for the trouble, @JamesNock.

I'll have a developer check into this shortly. We'll get back to you with instructions and/or a fix soon. 🙂

**Comment by JamesNock** [comment]
Thank you @kjmartens I appreciate it 😀

**Comment by kjmartens** [comment]
Ok @JamesNock, this changed in Freeform 5. The new approach works something like this instead (we'll update the docs):

``` php
use Solspace\Freeform\Events\PostForwarding\PostForwardingEvent;
use Solspace\Freeform\Integrations\Single\PostForwarding\PostForwarding;

Event::on(
    PostForwarding::class,
    PostForwarding::EVENT_POST_FORWARDING,
    function (PostForwardingEvent $event) {
        // ...
    }
);
```

Hope this helps 🙂

**Comment by JamesNock** [comment]
Thank you, we've tested this working. 😀
