### ISSUE TITLE
Required Fields not Preventing Submission

### ISSUE THREAD

**Issue by kevinamezaga** [solspace/craft3-freeform#117]
Required fields are not preventing the saving of forms.

**Steps to reproduce**
1. Do not enter required fields
2. Submit form

**Expected behavior**
1. Do not enter required fields
2. Receive errors notifying you of missing fields

**Craft & Plugin Info (please complete the following information):**
 - Craft Version: Craft 3.6.9
 - Freeform Version: 3.11.0-beta.2
 - Freeform Edition: Pro
 - Fresh Install or Upgrade: Upgrade

**Comment by kjmartens** [comment]
Hi @kevinamezaga, I tried testing this on my end and can't duplicate the issue in any way. Perhaps the issue has to do with something very specific to your setup. Would you be able to provide us with more information about what you're doing?

Some ideas:

1. Can you try updating to Beta 3 and see if that makes any difference?
2. Just to confirm, are you setting the fields to be required in the form builder per form?
3. Does this happen when you have a very simple form (e.g. name, email, message - with at least one of the fields set to required inside the form builder)?
4. Does this issue occur in the Demo Templates area that you can install?
5. Are you doing anything special like connecting to another element via Element Connections?
6. Perhaps a screenshot of the form and setup. :)

**Comment by kevinamezaga** [comment]
I’m trying to insert a value into a date field, which I’ve gotten working now with

 

{% set dateFixed = now | date('Y-m-d\\TH:i') %}

{{ craft.freeform.form("scooterFixes", {

                                overrideValues: {

                                    scooterReportID: reportID,

                                    currentUserID: currentUser.id,

                                    currentDate: dateFixed

                                },

                                submitClass: "btn btn-block"

                            }).render({

                                elementId: reportObject.id,

                            }) }}

 

However, the date is about four hours off for some reason, regardless of the timezone inputted to the date() filter.

 

Thanks,

 

👨🏻‍💻 Kevin Amézaga
Content Producer
––––––––––––––––––––––––––––––––––––
A: 2103 Coral Way FL 2 Miami, FL 33145
E: ***@***.***
w: mostlikelykevin.com t: (786)361-8202

 

From: Kelsey Martens ***@***.***>
Reply-To: solspace/craft3-freeform ***@***.***>
Date: Wednesday, March 17, 2021 at 14:20
To: solspace/craft3-freeform ***@***.***>
Cc: Kevin Amézaga ***@***.***>, Mention ***@***.***>
Subject: Re: [solspace/craft3-freeform] Required Fields not Preventing Submission (#117)

 

Hi @kevinamezaga, I tried testing this on my end and can't duplicate the issue in any way. Perhaps the issue has to do with something very specific to your setup. Would you be able to provide us with more information about what you're doing?

Some ideas:
Can you try updating to Beta 3 and see if that makes any difference?
Just to confirm, are you setting the fields to be required in the form builder per form?
Does this happen when you have a very simple form (e.g. name, email, message - with at least one of the fields set to required inside the form builder)?
Does this issue occur in the Demo Templates area that you can install?
Are you doing anything special like connecting to another element via Element Connections?
Perhaps a screenshot of the form and setup. :)

**Comment by kevinamezaga** [comment]
I realized I responded to this with another issue by accident.

I upgraded to Beta 3 and am still having the same problem. On a simpler form, the issue doesn't happen, but on the first form I am using an element connection.

<img width="367" alt="Screen Shot 2021-03-18 at 10 49 31" src="https://user-images.githubusercontent.com/25387497/111645983-a0c64980-87d7-11eb-93d8-fe00401e7724.png">


<img width="671" alt="Screen Shot 2021-03-18 at 10 42 56" src="https://user-images.githubusercontent.com/25387497/111644977-b6873f00-87d6-11eb-8313-8aecebadb2c5.png">

https://user-images.githubusercontent.com/25387497/111645253-e6364700-87d6-11eb-805b-01b110a6d325.mov

**Comment by kevinamezaga** [comment]
I am able to confirm this is an issue with the entries connection. When the connection is disabled, the entry is not saved. For some reason Freeform is attempting to save an entry with no fields which obviously can't be done.

**Comment by kjmartens** [comment]
Thanks @kevinamezaga... I was able to confirm there was an issue with using Element Connections in the beta, but wasn't sure if that was the exact issue you were up against too. We're working on a fix for it. :)

**Comment by kevinamezaga** [comment]
Thanks @kjmartens. Hoping to use FreeForm on a production site for the first time soon. Really amazing tool you guys are building.

Hope to see a fix soon.

**Comment by kjmartens** [comment]
We'll likely have a fix today or tomorrow :)

**Comment by kjmartens** [comment]
@kevinamezaga You can try out **v3.11.0-beta.4** now :)

**Comment by kevinamezaga** [comment]
It works now! Thank you @kjmartens and @gustavs-gutmanis. You're the best!
