### ISSUE TITLE
Website Field - domain extension length is too short

### ISSUE THREAD

**Issue by vonscriptor** [solspace/craft3-freeform#1176]
Users with domain extensions like .digital and .engineering result in an error.

**Steps to reproduce**

1. Add a form with a Website field
2. Enter a value like https://example.engineering

**Expected behavior**
Those URLs are valid and should be accepted. Consider increasing the domain extensions length to at least 12.

**Craft & Plugin Info (please complete the following information):**

- Craft Version: Pro 4.8.6
- Freeform Version: 5.1.8
- Freeform Edition: Pro
- Fresh Install or Upgrade: Fresh

**Comment by kjmartens** [comment]
Thanks for letting us know @vonscriptor. We've updated it from 6 characters to `15` for the next version. 🙂
