### ISSUE TITLE
Unable to install Craft 5.0.1 due to symfony/property-access version

### ISSUE THREAD

**Issue by WHITE-developer** [solspace/craft3-freeform#1187]
Craft [added](https://github.com/craftcms/cms/commit/1fd0eaf0f129a6a12e92242bcd931550b9d85ca4) `symfony/property-access` 7.0 as dependency which  makes it unable to install cause freeform [doesn't accept](https://github.com/solspace/craft-freeform/blob/v5/composer.json#L17) that version

**Comment by kjmartens** [comment]
Thanks for letting us know @WHITE-developer. We'll update this shortly.

**Comment by kjmartens** [comment]
We've released Freeform 5.1.10 now, which resolves this issue. 🙂
