### ISSUE TITLE
Submission marked as spam still processes charge in Stripe

### ISSUE THREAD

**Issue by icreatestuff** [solspace/craft3-freeform#1188]
**Describe the bug or issue you're experiencing**

When a submission has been marked as spam for the 'Honeypot check failed' reason, the charge is still processed through Stripe successfully.

![Screenshot 2024-04-04 at 15 55 42](https://github.com/solspace/craft-freeform/assets/1300714/796aab05-877f-476e-9bbc-73e1bf4bfec5)

**Steps to reproduce**
1. Create a form that uses the Stripe integration and stripe payment field.
2. Enable the honeypot integration for the form
3. Complete the form from a frontend template and fill in the hidden honeypot field.

**Expected behavior**
The charge be halted if the submission is marked as spam.

**Craft & Plugin Info (please complete the following information):**

- Craft Version: Pro 4.8.7
- Freeform Version: 5.1.9
- Freeform Edition: Pro
- Fresh Install or Upgrade: Upgrade

![Screenshot 2024-04-04 at 15 56 47](https://github.com/solspace/craft-freeform/assets/1300714/025799c6-df0e-48b5-ac25-bd5791126e72)

**Comment by kjmartens** [comment]
Sorry for the delay @icreatestuff. We'll get this resolved shortly.

**Comment by kjmartens** [comment]
This has been resolved now in Freeform 5.1.15. 🙂
