### ISSUE TITLE
During update to craft 5: don't install solspace/craft-freeform 5.1.10 (conflict analysis result)

### ISSUE THREAD

**Issue by atelierbim** [solspace/craft3-freeform#1189]
**Describe the bug or issue you're experiencing**
When running the "composer update or install" command to update Craft 4 to Craft 5 it throws a conflict error:
` Conclusion: don't install solspace/craft-freeform 5.1.10 (conflict analysis result)
    - craftcms/commerce-stripe 5.0.0 requires stripe/stripe-php ^13.0 -> satisfiable by stripe/stripe-php[v13.0.0, ..., v13.18.0-beta.1].
    - You can only install one version of a package, so only one of these can be installed: stripe/stripe-php[v7.0.0, ..., v7.128.0, v8.0.0, ..., v8.125.0-beta.4, v9.0.0, ..., v9.9.0, v10.0.0, ..., v10.22.0-beta.1, v13.0.0, ..., v13.18.0-beta.1].
    - solspace/craft-freeform 5.1.10 requires stripe/stripe-php ^7.0|^8.0|^9.0|^10.0 -> satisfiable by stripe/stripe-php[v7.0.0, ..., v7.128.0, v8.0.0, ..., v8.125.0-beta.4, v9.0.0, ..., v9.9.0, v10.0.0, ..., v10.22.0-beta.1].
    - Conclusion: don't install stripe/stripe-php v10.21.0 (conflict analysis result)
    - Root composer.json requires solspace/craft-freeform 5.1.10 -> satisfiable by solspace/craft-freeform[5.1.10].
    - Root composer.json requires craftcms/commerce-stripe ^5.0 -> satisfiable by craftcms/commerce-stripe[5.0.0].`

**Craft & Plugin Info (please complete the following information):**

        "craftcms/ckeditor": "^4.0",
        "craftcms/cloud": "^2.0",
        "craftcms/cms": "^5.0.0",
        "craftcms/commerce": "^5.0.0-beta.2",
        "craftcms/commerce-paypal-checkout": "^3.0",
        "craftcms/commerce-stripe": "^5.0",
        "craftcms/mailgun": "^3.1",
        "doublesecretagency/craft-siteswitcher": "^3.0",
        "mmikkel/retcon": "^3.0",
        "nystudio107/craft-seomatic": "^3.3",
        "nystudio107/craft-typogrify": "^5.0@beta",
        "putyourlightson/craft-campaign": "^3.0@beta",
        "putyourlightson/craft-sprig": "^3.0@beta",
        "solspace/craft-freeform": "5.1.10",
        "spacecatninja/imager-x": "^5.0@beta",
        "vlucas/phpdotenv": "^5.5"

**Comment by kjmartens** [comment]
Thanks for reporting this @atelierbim,

We'll update the dependency shortly. 🙂

**Comment by kjmartens** [comment]
We'll release an update for this in Freeform 5.1.11 within the next day or two. If you need access to that change right now, you can set your Freeform version in `composer.json` to:

``` json
"solspace/craft-freeform": "v5.x-dev",
```

And then run `composer update`. 🙂
