### ISSUE TITLE
Rich text disappears after upgrading to Freeform 5

### ISSUE THREAD

**Issue by jonathanpardon** [solspace/craft3-freeform#1193]
After upgrading to Freeform 5, the value of rich text fields disappear.
We are using custom templates for the form.
I followed the upgrade instructions, changing the rich_text to rich-text.

**Steps to reproduce**

1. Create a custom form render
2. Check the type = rich-text
3. Output the field.value raw html

<img width="454" alt="Screenshot 2024-04-10 at 10 29 25" src="https://github.com/solspace/craft-freeform/assets/1384905/6571ccf6-6062-4e0a-8c7a-9956819e8904">

**Expected behavior**
Should ouput richt text value, but outputs nothing.

Before upgrade:
![Screenshot 2024-04-10 at 10 34 31](https://github.com/solspace/craft-freeform/assets/1384905/5711cc11-c92f-4fef-b908-b2b33dd82f22)

After upgrade:
<img width="292" alt="Screenshot 2024-04-10 at 10 35 03" src="https://github.com/solspace/craft-freeform/assets/1384905/7b58635e-42a4-44c6-ab95-50b38999c115">
![Screenshot 2024-04-10 at 10 34 42](https://github.com/solspace/craft-freeform/assets/1384905/3abedb95-7f03-4f05-a738-37876c7cffb7)

**Craft & Plugin Info (please complete the following information):**

- Craft Version: Craft Pro 4.8.3
- Freeform Version: 5.1.8
- Freeform Edition: Pro
- Fresh Install or Upgrade: Upgrade

**Comment by kjmartens** [comment]
Sorry for the trouble @jonathanpardon,

Curious... what happens if you assign a sample Freeform formatting template instead? Does it load correctly?

I'm also curious what your complete formatting template code looks like. Would you be able to share that for our review? 🙂

**Comment by jonathanpardon** [comment]
Hi,

We used the Grid formatting template, but did some custom rendering in the twig file.
When I switch it to the default form.render(), the text appears again.

The full code for the template:

``` twig
 {% set form = craft.freeform.form(passedForm) %}
  {{ form.renderTag(renderValues) }}
    {% for row in form %}
        <div class="form__row">
            {% for field in row %}
                {% if field.type == 'submit' %}
                    <button
                            type="submit"
                            class="btn btn--primary has-icon"
                            name="form_page_submit"
                            data-freeform-action="submit"
                    >
                        {{ type is defined and type == 'ebook' ? 'Download e-book'|t : type is defined and type == 'webinar' ? 'Register now'|t : 'Submit'|t }}

                        <svg class="icon icon--arrow-right" aria-hidden="true" role="presentation">
                            <use xlink:href="#arrow-right"></use>
                        </svg>
                    </button>

                {% elseif field.type == 'rich-text' %}
                    <div class="form__row__field">
                        {{ field.value|raw }}
                    </div>

                {% elseif field.type == 'checkbox' %}
                    <div class="form__row__field{{ field.handle == 'acceptance' ? ' form__row__field--acceptance' : '' }}{{ field.required ? ' form__row__field--required' : '' }}">
                        {{ field.renderSingleInput({
                            class: 'form__row__field__input form__row__field__input--' ~ field.type,
                        }) }}

                        <label for="{{ field.idAttribute }}">
                            {{ field.label|t|raw }}
                        </label>
                    </div>

                {% elseif field.type == 'select' %}
                    <div class="form__row__field">
                        <label for="{{ field.idAttribute }}" class="form-field__label">
                            {{ field.label|t }}
                        </label>

                        <select id="{{ field.idAttribute }}" name="{{ field.handle }}"
                                class="form__row__field__input form__row__field__input--{{ field.type }}">
                            {% for option in field.options %}
                                <option value="{{ option.value }}">
                                    {{ option.label|t }}
                                </option>
                            {% endfor %}
                        </select>
                    </div>

                {% else %}
                    <div class="form__row__field{{ field.required ? ' form__row__field--required' : '' }}">
                        <label for="{{ field.idAttribute }}" class="form-field__label">
                            {{ field.label|t }}
                        </label>

                        {{ field.renderInput({
                            class: 'form__row__field__input form__row__field__input--' ~ field.type,
                        }) }}

                        {% if field.instructions %}
                            <p class="form-field-instructions">
                                {{ field.instructions|t }}
                            </p>
                        {% endif %}
                    </div>
                {% endif %}
            {% endfor %}
        </div>
    {% endfor %}

    {{ form.renderClosingTag }}
```

**Comment by kjmartens** [comment]
Sorry for the delay @jonathanpardon,

Can you try updating that part of the code to this and see if that makes any difference: 🙂 

``` twig
                {% elseif field.type == 'rich-text' %}
                    <div class="form__row__field">
                        {{ field.render }}
                    </div>
```

**Comment by jonathanpardon** [comment]
Hi @kjmartens ,
this does make the text appear again.  
Is this the only way? Because it adds an extra container, which makes my css fail, but that's fixable (if needed).

before:
![Screenshot 2024-04-22 at 14 18 29](https://github.com/solspace/craft-freeform/assets/1384905/9b674a52-9d44-4347-abd4-a5202e833918)

after:
![Screenshot 2024-04-22 at 14 20 22](https://github.com/solspace/craft-freeform/assets/1384905/0ea3d6c7-a044-43f1-abfc-6dfc317e2791)

**Comment by kjmartens** [comment]
Hi @jonathanpardon,

Does using `{{ field.renderInput }}` work better? 🙂

**Comment by jonathanpardon** [comment]
@kjmartens That fixes this problem. Maybe this should be mentioned somewhere in the upgrade guide?

**Comment by kjmartens** [comment]
Thanks for confirming @jonathanpardon.

I'll update the upgrade guide. Sorry about that!
