### ISSUE TITLE
Unable to view submissions after Craft 5 upgrade

### ISSUE THREAD

**Issue by ameliagroen** [solspace/craft3-freeform#1196]
**Describe the bug or issue you're experiencing**
We recently upgraded a project from Craft 4 to Craft 5. The project is using Freeforms v5, but since upgrading we are no longer able to access the submissions at all. I've attached an image of the stack trace, please let me know if additional info is needed.

**Steps to reproduce**

1. Upgrade project using Craft 4 and Solspace 5 to Craft 5
2. Try to access the submissions via the menu item in the sidebar or via the Freeform dashboard

**Expected behavior**
See the submissions screen

**Craft & Plugin Info (please complete the following information):**

- Craft Version: Craft Pro 5.0.0
- Freeform Version: 5.1.10
- Freeform Edition: Pro
- Fresh Install or Upgrade: Upgrade

**Stack trace:**
yii\base\UnknownPropertyException: Getting unknown property: craft\web\Application::sections in /var/www/html/vendor/yiisoft/yii2/base/Component.php:154
Stack trace:
#0 /var/www/html/vendor/yiisoft/yii2/di/ServiceLocator.php(77): yii\base\Component->__get('sections')
#1 /var/www/html/vendor/solspace/craft-freeform/packages/plugin/src/Fields/Properties/Options/Elements/Types/Entries/SectionsOptionsGenerator.php(15): yii\di\ServiceLocator->__get('sections')
#2 /var/www/html/vendor/solspace/craft-freeform/packages/plugin/src/Bundles/Attributes/Property/PropertyProvider.php(199): Solspace\Freeform\Fields\Properties\Options\Elements\Types\Entries\SectionsOptionsGenerator->fetchOptions(Object(Solspace\Freeform\Attributes\Property\Input\Select))
#3 /var/www/html/vendor/solspace/craft-freeform/packages/plugin/src/Bundles/Attributes/Property/PropertyProvider.php(115): Solspace\Freeform\Bundles\Attributes\Property\PropertyProvider->processOptions(Object(Solspace\Freeform\Attributes\Property\Input\Select))
#4 /var/www/html/vendor/solspace/craft-freeform/packages/plugin/src/Bundles/Attributes/Property/PropertyProvider.php(50): Solspace\Freeform\Bundles\Attributes\Property\PropertyProvider->getEditableProperties(Object(Solspace\Freeform\Fields\Properties\Options\Elements\Types\Entries\Entries))
#5 /var/www/html/vendor/solspace/craft-freeform/packages/plugin/src/Fields/Properties/Options/OptionsConfiguration.php(24): Solspace\Freeform\Bundles\Attributes\Property\PropertyProvider->setObjectProperties(Object(Solspace\Freeform\Fields\Properties\Options\Elements\Types\Entries\Entries), Array)
#6 /var/www/html/vendor/solspace/craft-freeform/packages/plugin/src/Attributes/Property/Implementations/Options/OptionsTransformer.php(21): Solspace\Freeform\Fields\Properties\Options\OptionsConfiguration->__construct(Array, Object(Solspace\Freeform\Bundles\Attributes\Property\PropertyProvider))
#7 /var/www/html/vendor/solspace/craft-freeform/packages/plugin/src/Bundles/Attributes/Property/PropertyProvider.php(55): Solspace\Freeform\Attributes\Property\Implementations\Options\OptionsTransformer->transform(Array)
#8 /var/www/html/vendor/solspace/craft-freeform/packages/plugin/src/Services/Form/FieldsService.php(123): Solspace\Freeform\Bundles\Attributes\Property\PropertyProvider->setObjectProperties(Object(Solspace\Freeform\Fields\Implementations\DropdownField), Array)
#9 /var/www/html/vendor/solspace/craft-freeform/packages/plugin/src/Services/Form/FieldsService.php(88): Solspace\Freeform\Services\Form\FieldsService->createField(Object(Solspace\Freeform\Records\Form\FormFieldRecord), Object(Solspace\Freeform\Form\Types\Regular))
#10 /var/www/html/vendor/solspace/craft-freeform/packages/plugin/src/Services/Form/LayoutsService.php(147): Solspace\Freeform\Services\Form\FieldsService->getFields(Object(Solspace\Freeform\Form\Types\Regular))
#11 /var/www/html/vendor/solspace/craft-freeform/packages/plugin/src/Services/Form/LayoutsService.php(44): Solspace\Freeform\Services\Form\LayoutsService->getFields(Object(Solspace\Freeform\Form\Types\Regular))
#12 /var/www/html/vendor/solspace/craft-freeform/packages/plugin/src/Form/Form.php(316): Solspace\Freeform\Services\Form\LayoutsService->getLayout(Object(Solspace\Freeform\Form\Types\Regular))
#13 /var/www/html/vendor/solspace/craft-freeform/packages/plugin/src/Bundles/Submissions/CustomSourceFields.php(39): Solspace\Freeform\Form\Form->getLayout()
#14 [internal function]: Solspace\Freeform\Bundles\Submissions\CustomSourceFields->handleCustomTableAttributes(Object(craft\events\DefineSourceTableAttributesEvent))
#15 /var/www/html/vendor/yiisoft/yii2/base/Event.php(312): call_user_func(Array, Object(craft\events\DefineSourceTableAttributesEvent))
#16 /var/www/html/vendor/yiisoft/yii2/base/Component.php(642): yii\base\Event::trigger('craft\\services\\...', 'defineSourceTab...', Object(craft\events\DefineSourceTableAttributesEvent))
#17 /var/www/html/vendor/craftcms/cms/src/services/ElementSources.php(353): yii\base\Component->trigger('defineSourceTab...', Object(craft\events\DefineSourceTableAttributesEvent))
#18 /var/www/html/vendor/twig/twig/src/Extension/CoreExtension.php(1635): craft\services\ElementSources->getSourceTableAttributes('Solspace\\Freefo...', 'form:2')
#19 /var/www/html/vendor/craftcms/cms/src/helpers/Template.php(129): twig_get_attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(craft\services\ElementSources), 'getSourceTableA...', Array, 'method', false, false)
#20 /var/www/html/storage/runtime/compiled_templates/ca/ca85f3c21ade223dae034dbcfbaa2952.php(217): craft\helpers\Template::attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(craft\services\ElementSources), 'getSourceTableA...', Array, 'method')
#21 /var/www/html/vendor/twig/twig/src/Extension/CoreExtension.php(1224): __TwigTemplate_5b008b88d72cd9e3de6eb0851f43e41a->macro_sourceLink('form:2', Array, true, 'Solspace\\Freefo...', Array, Array, NULL)
#22 /var/www/html/storage/runtime/compiled_templates/ca/ca85f3c21ade223dae034dbcfbaa2952.php(128): twig_call_macro(Object(__TwigTemplate_5b008b88d72cd9e3de6eb0851f43e41a), 'macro_sourceLin...', Array, 111, Array, Object(Twig\Source))
#23 /var/www/html/vendor/twig/twig/src/Template.php(394): __TwigTemplate_5b008b88d72cd9e3de6eb0851f43e41a->doDisplay(Array, Array)
#24 /var/www/html/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling(Array, Array)
#25 /var/www/html/storage/runtime/compiled_templates/46/46d0015e2cd820664f39eb1414d21620.php(131): Twig\Template->display(Array)
#26 /var/www/html/vendor/twig/twig/src/Template.php(171): __TwigTemplate_20ffbd7f0c5bbf9693d381c70a14e48b->block_sidebar(Array, Array)
#27 /var/www/html/vendor/twig/twig/src/Template.php(243): Twig\Template->displayBlock('sidebar', Array, Array, true)
#28 /var/www/html/storage/runtime/compiled_templates/aa/aa5954f1ea6990d12f775ef82732d7d0.php(94): Twig\Template->renderBlock('sidebar', Array, Array)
#29 /var/www/html/vendor/twig/twig/src/Template.php(394): __TwigTemplate_591a9628ca3e8a38fb13e77714513608->doDisplay(Array, Array)
#30 /var/www/html/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling(Array, Array)
#31 /var/www/html/storage/runtime/compiled_templates/46/46d0015e2cd820664f39eb1414d21620.php(105): Twig\Template->display(Array, Array)
#32 /var/www/html/vendor/twig/twig/src/Template.php(394): __TwigTemplate_20ffbd7f0c5bbf9693d381c70a14e48b->doDisplay(Array, Array)
#33 /var/www/html/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling(Array, Array)
#34 /var/www/html/storage/runtime/compiled_templates/6d/6dfc36bf424a5145ffc4b46729509315.php(69): Twig\Template->display(Array, Array)
#35 /var/www/html/vendor/twig/twig/src/Template.php(394): __TwigTemplate_9e66e9999ce6a0cfc96d23ed07292c80->doDisplay(Array, Array)
#36 /var/www/html/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling(Array, Array)
#37 /var/www/html/storage/runtime/compiled_templates/d8/d8ee6fc53d69eb151c1df8db204ccf04.php(88): Twig\Template->display(Array, Array)
#38 /var/www/html/vendor/twig/twig/src/Template.php(394): __TwigTemplate_cb9bc03459498130f7be58a95afea625->doDisplay(Array, Array)
#39 /var/www/html/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling(Array, Array)
#40 /var/www/html/vendor/twig/twig/src/Template.php(379): Twig\Template->display(Array)
#41 /var/www/html/vendor/twig/twig/src/TemplateWrapper.php(38): Twig\Template->render(Array)
#42 /var/www/html/vendor/twig/twig/src/Environment.php(280): Twig\TemplateWrapper->render(Array)
#43 /var/www/html/vendor/craftcms/cms/src/web/View.php(482): Twig\Environment->render('freeform/submis...', Array)
#44 /var/www/html/vendor/craftcms/cms/src/web/View.php(535): craft\web\View->renderTemplate('freeform/submis...', Array)
#45 /var/www/html/vendor/craftcms/cms/src/web/TemplateResponseFormatter.php(57): craft\web\View->renderPageTemplate('freeform/submis...', Array, 'cp')
#46 /var/www/html/vendor/yiisoft/yii2/web/Response.php(1100): craft\web\TemplateResponseFormatter->format(Object(craft\web\Response))
#47 /var/www/html/vendor/craftcms/cms/src/web/Response.php(337): yii\web\Response->prepare()
#48 /var/www/html/vendor/yiisoft/yii2/web/Response.php(340): craft\web\Response->prepare()
#49 /var/www/html/vendor/yiisoft/yii2/base/Application.php(390): yii\web\Response->send()
#50 /var/www/html/public/index.php(12): yii\base\Application->run()
#51 {main}

**Comment by kjmartens** [comment]
Very sorry for the trouble @ameliagroen,

Would you be able to update to Freeform 5.1.12 and after running the migration, see if that resolves the issue? 🙂

**Comment by ameliagroen** [comment]
Hey @kjmartens thank you, just upgraded and I can access the submissions again. Thanks for the fix!
