### ISSUE TITLE
Unable to see Forms page after Craft 5 upgrade

### ISSUE THREAD

**Issue by iamtompickering** [solspace/craft3-freeform#1202]
**Describe the bug or issue you're experiencing**
Since upgrading to Craft 5, I can no longer see the Forms page within Freeform. All other pages appear to be working, just this one. In dev tools I can see a couple of console errors: 

![CleanShot 2024-04-12 at 08 19 54](https://github.com/solspace/craft-freeform/assets/6592882/1ca07fa7-3839-42fa-994a-300233c21be8)

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 5.0.4
- Freeform Version: 5.1.11
- Freeform Edition: Lite
- Fresh Install or Upgrade: Upgrade

**Comment by kjmartens** [comment]
Sorry for the trouble @iamtompickering,

Can you try updating to Freeform 5.1.12, and then if the errors persist, can you check what the Network Response says in the browser? You can find it by following these instructions (but look for a line with red text - won't be `options` like in this example):

![troubleshooting-forms-network-response](https://github.com/solspace/craft-freeform/assets/1821674/471d0d47-efe8-453e-b3e4-a46c9192d2ee)

**Comment by iamtompickering** [comment]
@kjmartens all fixed after updating to 5.1.12, thanks!
