### ISSUE TITLE
HTML validation not working in form

### ISSUE THREAD

**Issue by thom-moresoda** [solspace/craft3-freeform#1203]
"craftcms/cms": "4.5.6.1",
"solspace/craft-freeform": "4.1.9"

I have a site with multiple freeform forms set up - on some of the forms the html email validation works, but on others it doesn't. The forms have identical settings in the control panel & are rendered in the same way in the templates

Hoping someone can point me in the right direction!

**Comment by kjmartens** [comment]
Hi @thom-moresoda,

Can you share with us what your template(s) look like? It might be a matter of one including a parameter or attribute and the other is not. This is cleaned up nicely in Freeform 5, but in Freeform 4, there's a handful of ways this might be done: 🙂 

```twig
useRequiredAttribute: true
```

```twig
formAttributes: {
    "novalidate": true,
    "data-form-id": "test"
}
```

```twig
inputAttributes: {
   "readonly": true,
   "data-field-id": "test"
}
```

Additionally, inside the form builder for the form or each field using the "Attributes" table.
