### ISSUE TITLE
Spam still being sent as contact to Active Campaign

### ISSUE THREAD

**Issue by DowleyDeveloped** [solspace/craft3-freeform#1223]
When a email gets marked as spam, we're finding it's still creating a contact within Active Campaign. Ideally it shouldn't come through to active campaign at all.

- Craft Version:
- Freeform Version:4.8.5 
- Freeform Edition: 5.1.7

**Comment by kjmartens** [comment]
Thanks for bringing this to our attention, @DowleyDeveloped.

I can duplicate this in my testing as well. We'll work on a fix for this shortly. 🙂

**Comment by kjmartens** [comment]
This is now corrected in Freeform 5.1.16+. 🙂
