### ISSUE TITLE
[5.1] In `FormsService` use `$view->renderFile()` instead of `$view->renderString()` for better debug output

### ISSUE THREAD

**Issue by rob-c-baker** [solspace/craft3-freeform#1224]
When an exception is thrown or an error occurs in a custom form rendering template, in `devMode`, exceptions that are displayed on the front-end are hard to debug because the original Twig template file is unknown to the view layer and therefore it cannot show the template code where the exception occurred. This is because the template is loaded as a sting instead of a file.

A fix to this would be to change this call for `view->renderFile()` (dropping the `file_get_contents()` wrapper around `$templatePath` of course):

https://github.com/solspace/craft-freeform/blob/502ee66353cee36fe3363e31482eae15384ad2ff/packages/plugin/src/Services/FormsService.php#L346-L352

This seems to work well here.

**Steps to reproduce**

1. Custom form rendering template containing an error (i.e. reference an undefined variable or something)
2. Have `devMode` switched on so "friendly" errors with traces are shown
3. Try to render the form
4. An exception trace is shown but with template names like `__TwigTemplate_e733123153b2c97d929a8fefb509ae2a` instead of the Twig source from the file.

**Expected behavior**

In the exception front-end view, show the line and Twig context.

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 4.8.9
- Freeform Version: 5.1.x
- Freeform Edition: Pro
- Fresh Install or Upgrade: N/A

**Comment by gustavs-gutmanis** [comment]
Hi @rob-baker-ar, 

We will update this part, and we'll see if there are other places which can be adjusted as well, great suggestion! Thank you.

**Comment by rob-c-baker** [comment]
I should add that I have just been trying this out while working on my form template. I am getting issues with different contexts using `renderFile()`, but there are other options of course like `renderTemplate()` which would work but will require a template path relative to a template root rather than an absolute file path as is the case now.

**Comment by kjmartens** [comment]
This is available now in Freeform 5.1.17+. 🙂
