### ISSUE TITLE
[5.1] Not able to select the assets source for checkboxes, dropdowns, multi-select and radios

### ISSUE THREAD

**Issue by WHITE-developer** [solspace/craft3-freeform#1235]
We want to fill our checkboxes with assets. The documentation states that assets are an available source. But if we want to change the source type, there is no assets option.
![image](https://github.com/solspace/craft-freeform/assets/22771556/2e68b3bd-84c9-45ad-9cb7-8b30e0aa7b90)

**Steps to reproduce**
1. Updated from 3.13.28 to 5.1.14
2. Changing the source of checkboxes

**Expected behavior**
- Able to select the assets source.

**Craft & Plugin Info:**
- Craft Version: 4.8.10
- Freeform Version: 5.1.14
- Freeform Edition: Pro
- Fresh Install or Upgrade: Upgrade

**Comment by kjmartens** [comment]
Sorry about this @WHITE-developer.

Seems this fell through the cracks. We'll add support for this shortly. 🙂

**Comment by kjmartens** [comment]
This is available now in Freeform 5.1.17+. 🙂
