### ISSUE TITLE
Loads unnecessary javascripts.

### ISSUE THREAD

**Issue by amici-infotech** [solspace/craft3-freeform#124]
**Describe the bug or issue you're experiencing**
So when I load 1 form in the site, It ads up few Javascripts that I really dont need to. Like:
1. freeform.js?v=1616675011
2. api.js?render=explicit (recaptcha I guess)
3. flatpickr.min.js
4. imask.min.js
5. signature_pad.min.js

I just needed freeform.js file only but it loads up all these files that adds around 300-400kb. 
One more thing I notice is, I cant add script manually without a form object. Is there any way I can add only freeform js file and I can add it manually without having any form? The purpose it, I have 4 forms and I have seen that it loads all these scripts 4 times in footer. I tried to manually add script but I have to get form and add it for single form. (its not necessary that I will always have 4 forms, I can have 1 or 10..)

lastly, I would really appriciate if I can just add freeform.js without any other javascripts or maybe a function or variable where I can pass which js files I need for given form..

Thanks in advance

**Comment by gustavs-gutmanis** [comment]
Thanks for reporting this @amici-infotech

I'll look into it.  
The additional scripts won't be loaded in Freeform v3.11, which is in [beta right now](https://docs.solspace.com/craft/freeform/v3/setup/betas.html#beta-testing).

**Comment by croxton** [comment]
One thing I'd add to this - currently the script is generated on first request, and saved to the file system. This can be a problem if you have deployed multiple instances of craft with ephemeral file systems behind a load balancer, and in conjunction with static caching (or edge/cdn caching): the script may not exist on the particular instance serving the next user, but they may receive a static html which references it. In a previous version of freeform the script was inlined which worked fine with such a configuration, although was rather bulky.

I'm not sure if this is relevant to the way the new beta works, but I thought I'd flag it just in case.

**Comment by gustavs-gutmanis** [comment]
Thanks @croxton, I'm addressing all of these issues together in one.  
A version should be available soon in v3.11-beta

**Comment by amici-infotech** [comment]
Perfect. I am so looking forward to it.

**Comment by gustavs-gutmanis** [comment]
@amici-infotech, @croxton 

The latest changes are in the `v3.11-beta.6` release.  
This update changes the way scripts are loaded. A static link has been added that contains the current scripts and it is passing cache headers, so browsers are able to cache the script. It also uses a cache-busting hash, so if there are any changes added to the script, the users will get the updated scripts immediately.

Now you no longer have to specify the form to load the scripts.  
If you wish to add your own attributes to the script and style tags, please use the new twig function
```twig
{{ craft.freeform.loadFreeformPlugin(
   'custom="script attribute" id="custom-id"',
   'data-style-tag="attribute"'
) }}
```
For backwards compatibility, the old `loadFreeformScripts` is still present, but no longer takes in consideration the passed `Form` object.
