### ISSUE TITLE
[5.1.15] Issues when using fields with rules

### ISSUE THREAD

**Issue by yawuar** [solspace/craft3-freeform#1241]
**Describe the bug or issue you're experiencing**
Hey there,

There are two forms, each with a radio field that displays or hides specific fields based on the selected value. The problem arises when I change the 'Adresgegevens' field in the second form to 'Ik woon niet in België'; it also changes the fields in the first form. It seems like the scope isn't properly defined. When I adjust the field handle, to a unique value, the form functions as intended. I'm wondering if this was intentional or if it's an error on your end?

https://github.com/solspace/craft-freeform/assets/9060850/b88b3cb5-05c2-482b-b353-926b86196969

<img width="1233" alt="Screenshot 2024-04-26 at 10 52 29" src="https://github.com/solspace/craft-freeform/assets/9060850/c1c440bf-2517-4cce-83ae-f8e9f1890d35">

**Steps to reproduce**
1. Set up two separate forms.
2. Include a radio button field in each form, offering two options to choose from.
3. Add a field of your choice to both forms, ensuring they share the same handle.
4. Establish a rule that controls whether the shared field is displayed or hidden based on the selected option in the radio button field.
5. Verify whether the fields in both forms have been modified.

**Expected behavior**
The fields should change based on the selected value within their respective forms, not in others.

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 4.8.10
- Freeform Version: 5.1.15
- Freeform Edition: Pro
- Fresh Install or Upgrade: Upgrade

**Comment by kjmartens** [comment]
Hi @yawuar,

I wonder if this would be resolved by using the `fieldIdPrefix: 'myform-'` parameter on each form. Can you try that? 🙂

**Comment by yawuar** [comment]
@kjmartens

I tried adding `fieldIdPrefix: 'myform-' `to all the forms, but it didn't do the trick. :/

**Comment by kjmartens** [comment]
Sorry for the delay @yawuar.

I can confirm this in my testing as well. I've noted it and we'll see if there's a way around this. 🙂

**Comment by kjmartens** [comment]
This should be resolved now in Freeform 5.4. 🙂
