### ISSUE TITLE
Updating to Freeform 5.1.16 causes Database Exception - table freeform_rules_buttons doesn't exist

### ISSUE THREAD

**Issue by CAIDcreative** [solspace/craft3-freeform#1245]
**Describe the bug or issue you're experiencing**

**Steps to reproduce**

1. Update to freeform 5.1.16 via utilities

Going to any page with a freeform rendered on it causes an error as freeform_rules_buttons table does not exist. Also you cannot edit any tables because freeform_rules_submit_form does exist.

I was able to simply create these missing tables via sql and it seemed to fix it. I was able to generate this sql because my local version did have the tables.

```
CREATE TABLE `freeform_rules_buttons` (
  `id` int NOT NULL,
  `pageId` int NOT NULL,
  `button` varchar(10) NOT NULL,
  `display` varchar(10) NOT NULL,
  `dateCreated` datetime NOT NULL,
  `dateUpdated` datetime NOT NULL,
  `uid` char(36) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `fk_okztkuspykscvidmheakvfhqkazsvfgovwpy` (`pageId`),
  CONSTRAINT `fk_lklmabvvvssbjklqxawbtkwnvrvzbdjnajcy` FOREIGN KEY (`id`) REFERENCES `freeform_rules` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_okztkuspykscvidmheakvfhqkazsvfgovwpy` FOREIGN KEY (`pageId`) REFERENCES `freeform_forms_pages` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

CREATE TABLE `freeform_rules_submit_form` (
  `id` int NOT NULL,
  `formId` int NOT NULL,
  `dateCreated` datetime NOT NULL,
  `dateUpdated` datetime NOT NULL,
  `uid` char(36) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `fk_ujooictsfctxijfzaokhvtdxzojzbfvjxwfz` (`formId`),
  CONSTRAINT `fk_pfjcexpcjmhknsvasajdzonskckgethqgjat` FOREIGN KEY (`id`) REFERENCES `freeform_rules` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_ujooictsfctxijfzaokhvtdxzojzbfvjxwfz` FOREIGN KEY (`formId`) REFERENCES `freeform_forms` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
```

**Craft & Plugin Info (please complete the following information):**

- Craft Version: Craft Pro 4.8.10
- Freeform Version: 5.1.16
- Freeform Edition: Pro 
- Fresh Install or Upgrade: Upgrade

**Comment by gustavs-gutmanis** [comment]
Hi @CAIDcreative 

Thanks for reporting this. Please tell me, how did you update freeform on your local version?
The migrations should have run, both the `Install` and non-install migrations are in place...
Did you run into any issues during the update?

**Comment by kjmartens** [comment]
Sorry about this issue you're experiencing @CAIDcreative.

It's due to the migration not automatically triggering in 5.1.16. You can run the `./craft migrate/all` command to do that or you can just update to Freeform 5.1.16.1 which we've just released now. 🙂
