### ISSUE TITLE
Freeform 5 isn't properly translatable (Or I'm doing something wrong)

### ISSUE THREAD

**Issue by FrDH** [solspace/craft3-freeform#1246]
**Describe the bug or issue you're experiencing**
Parts of Freeform 5 are not translated into Dutch. When I compare the "translations/nl/freeform.php" file from a v4 install with a v5 install, there are hardly any differences. 

**Craft & Plugin Info:**

- Craft Version: 4.7
- Freeform Version: 5
- Freeform Edition: PRO
- Fresh Install or Upgrade:

**Additional context**
Some words are translated in some places, but aren't in others. For example "Submissions" should translate to "Inzendingen". So I'm guessing the `|t` isn't used everywhere.

![Scherm­afbeelding 2024-04-29 om 16 25 34](https://github.com/solspace/craft-freeform/assets/1387163/23d2c86d-1ff6-4c4b-9ea8-70511f227bef)
![Scherm­afbeelding 2024-04-29 om 16 25 12](https://github.com/solspace/craft-freeform/assets/1387163/76713e6f-9341-443f-aeb4-6eb959b2086c)

**Comment by kjmartens** [comment]
I'm sorry about this @FrDH. We're going to comb through Freeform 5 this week and ensure everything is translated correctly. 🙂

**Comment by FrDH** [comment]
Thanks!

**Comment by kjmartens** [comment]
Just wanted to let you know that we will be releasing Freeform 5.4 in the next day or two, and it will include a full translation for Dutch (`nl`). 🙂
