### ISSUE TITLE
The field type "Freeform Form" only returns the form title in GraphQL queries

### ISSUE THREAD

**Issue by okolvik-avento** [solspace/craft3-freeform#127]
**Describe the bug or issue you're experiencing**
The field type "Freeform Form" only returns the form title in GraphQL queries.

**Steps to reproduce**
1. Create a field with type "Freeform Form"
2. Add it to a section
3. Select a form
4. Save
5. Do a graphql query on the page
6. Only the title of the form is returned

**Expected behavior**
Either inline fragment support or handle that can be used to query for the form

**Craft & Plugin Info (please complete the following information):**
 - Craft Version:  3.6.11.2
 - Freeform Version: 3.10.11
 - Freeform Edition: Pro Trial
 - Fresh Install or Upgrade: Fresh

**Additional context**
The title of a form cannot be used to get the form details in another query

**Comment by gustavs-gutmanis** [comment]
Thanks for reporting this but it has been addressed in the 3.11 beta already.

**Comment by okolvik-avento** [comment]
Ok, nice! I'll check it out.
