### ISSUE TITLE
[5.1.x] Prevent Freeform from hooking in to submit event

### ISSUE THREAD

**Issue by rob-c-baker** [solspace/craft3-freeform#1270]
While upgrading a site of ours from Freeform v4 to v5 we have some pretty complex validation rules implemented in JavaScript, it also does things like show / hide fields and other content as well as invoke modals (all sorts of things) based on rules determined dynamically from the state of other fields. One of the ways this is triggered is by our code hooking into the submit event to prevent submission, if necessary, however because the Freeform JS plugin is loaded and hooked into the same event, it seems to submit the form anyway, regardless of us trying to prevent the submission.

We also need to use Google ReCAPTCHA - but in v5, this is no longer a "field" on the form - it's now an "integration" meaning it gets included automatically as part of the form rendering. Crucially, this will only happen if the Freeform JS plugin is loaded on the front-end. 

This is a problem for us as in v4 we specifically did not load the JS plugin for this form so it did not interfere with our validation - especially our hooking into the submit event. The ReCAPTCHA was still fine as Freeform rendering understood that when the field was included on the form it would emit the needed script tags (and importantly not the script(s) that hoked into the submit event).

**Expected behavior**

Some way to prevent the Freeform JS plugin from hooking into the submit event, while still being loaded on the front-end and allowing things like ReCAPTCHA, or a way to prevent said plugin from letting other scripts take control of form submission.

**Craft & Plugin Info:**

- Craft Version: 4.8.9
- Freeform Version: 5.1.18.1
- Freeform Edition: Pro
- Fresh Install or Upgrade: Upgrade

**Comment by gustavs-gutmanis** [comment]
Hi @rob-baker-ar 

If I'm understanding correctly, you would like to perform some of your own logic and prevent the form from submitting while that is happening and then determine if it should or should not submit?

As for reCAPTCHA, you could roll your own setup by creating your own frontend and backend solution, listening to [Form Validatation events](https://docs.solspace.com/craft/freeform/v5/developer/events/form/#on-validating-the-form) to perform your own recaptcha validation.

You can take a look at how [reCAPTCHA is validated in Freeform](https://github.com/solspace/craft-freeform/blob/v5/packages/plugin/src/Integrations/Captchas/ReCaptcha/ReCaptchaBundle.php#L32) and roll your own solution.
Unfortunately we cannot refactor the reCAPTCHA implementation to suit your needs.

As for the JS Submit event - there is a new method of adding [async callbacks](https://docs.solspace.com/craft/freeform/v5/developer/js-plugin/#on-submit-freeform-on-submit) to the submit thread which will block the submit from finishing until your callbacks have finished working. 

```ts
// Priorities of the callbacks are 0 by default, and are optional.
// The bigger the priority, the faster the callback will be executed.
// The smaller the priority, the slower the callback will be executed.
// Negative numbers are allowed.

const myForm = document.getElementById('my-form');
myForm.addEventListener('freeform-on-submit', function(event) {
  // Add priority 100 to make sure this callback is executed before others
  event.addCallback(async () => {
    const json = await fetch('/some/long/api/call').then((response) =>
      response.json()
    );

    if (json.errors.length) {
      alert('There was an error');
      return false;
    }
  }, 100);

  // Add priority -100 to make sure this callback is executed after others
  event.addCallback(async () => {
    // execute some blocking code here
  }, -100);
});
```

With this approach you would be able to perform whatever additional validation you need and either return `false` if it should not finish submitting, or return `void` or `true` for it to finish. You can also use Promises and either resolve or reject them accordingly.

Hope this helps.
If I misunderstood, please let me know and perhaps supply an example of what it is you wish to achieve, I might be able to help.

**Comment by rob-c-baker** [comment]
> you would like to perform some of your own logic and prevent the form from submitting while that is happening and then determine if it should or should not submit?

Yes, this is essentially it.

Many thanks for your other comments - especially the ReCAPTCHA validation hook - that may allow me to not include the Freeform JS - closer to how things were before, otherwise I need to have a  play with the 'freeform-on-submit' event and see how I can modify our existing code to have that as an entrypoint.

I'll update / close the issue when I have done this - which should be tomorrow.

**Comment by gustavs-gutmanis** [comment]
Glad this helped, if you need any help or if you run into problems, let me know, I'll help within my capabilities.

**Comment by rob-c-baker** [comment]
This:

> ```ts
> // Priorities of the callbacks are 0 by default, and are optional.
> // The bigger the priority, the faster the callback will be executed.
> // The smaller the priority, the slower the callback will be executed.
> // Negative numbers are allowed.
> 
> const myForm = document.getElementById('my-form');
> myForm.addEventListener('freeform-on-submit', function(event) {
>   // Add priority 100 to make sure this callback is executed before others
>   event.addCallback(async () => {
>     const json = await fetch('/some/long/api/call').then((response) =>
>       response.json()
>     );
> 
>     if (json.errors.length) {
>       alert('There was an error');
>       return false;
>     }
>   }, 100);
> 
>   // Add priority -100 to make sure this callback is executed after others
>   event.addCallback(async () => {
>     // execute some blocking code here
>   }, -100);
> });
> ```

From above works.

Closing, thank you.
