### ISSUE TITLE
Freeform classes not rendering properly

### ISSUE THREAD

**Issue by HAWilliams01** [solspace/craft3-freeform#1274]
The freeform-row class has an extra set of quotes on it. It is being rendered on the front end as `class=""freeform-row""` instead of `class="freeform-row"`.

I'm using version Freeform 5.1.19.1 and {{ form.render }} to render the form in the template. Craft version 4.9.2

I have a different site using Freeform 5.1.16.1 and this is not an issue. Craft version 4.9.0

**Comment by kjmartens** [comment]
Hi @HAWilliams01,

Freeform 5.1.18.1 was released to address this issue, specifically with sample formatting templates. That said, if you have any custom formatting templates, you'll need to add the `|raw` Twig filter to any instance of `form.attributes.row`, `form.attributes.success` and `form.attributes.errors`:

E.g.:
``` diff
- form.attributes.row
+ form.attributes.row|raw
```

We're not sure why this started happening very recently (with no changes on our end), but we suspect that something might have changed in a recent version of Craft or Twig, etc.
