### ISSUE TITLE
Can't map fields to ActiveCampaign tags

### ISSUE THREAD

**Issue by geertvansoest** [solspace/craft3-freeform#1285]
### What happened?

We can't map values from fields to tags in ActiveCampaign. In the Contact Mapping list in the CMS we don't longer see the "Tags" field.

Also, in the database table `freeform_crm_fields` we don't see a field having the `tags` handle. We only see the custom fields (having a numeric id) and "reserved" fields for List, First Name, Last Name, Email and Phone:
![image](https://github.com/solspace/craft-freeform/assets/6870951/84e187f9-8408-45fe-a645-47e8d0c3ec72)

Those fields are added at these lines of code and we don't see Tags there:
https://github.com/solspace/craft-freeform/blob/v5/packages/plugin/src/Integrations/CRM/ActiveCampaign/BaseActiveCampaignIntegration.php#L243-L247

Are we missing something? Or is it true that tags is missing since Freeform 5?

### Freeform Edition

Pro

### Freeform Version

5.1.16

### Craft Version

4.9.2

**Comment by kjmartens** [comment]
Hi @geertvansoest,

I'm sorry for the delay...

The **Contact Tags** feature is only available for the Email Marketing version of the ActiveCampaign integration. If you just want to map to **Contacts** and **Contact Tags**, you could switch the approach from CRM to Email Marketing, and it should serve your needs.

If you need **Deals**, unfortunately the Contact Tags feature is not available with the CRM portion of the integration. Something you could potentially try is setting up both the CRM and Email Marketing versions of the integration and see if that allows it to work (it might cause other issues though).

Aside from that, I have noted this as a feature request for future consideration. 🙂
