### ISSUE TITLE
Error undefined constants and classes

### ISSUE THREAD

**Issue by JulieVelghe** [solspace/craft3-freeform#1309]
### What happened?

I have a custom module where I adjust an entry on the event after submit. 
I have upgraded to Freeform 5.3.1 from the latest 4 release. Now I'm getting an error: 
Undefined constant Solspace\Freeform\Services\FormsService::EVENT_AFTER_SUBMIT

The code I have:

```
Event::on(
    FormsService::class,
    FormsService::EVENT_AFTER_SUBMIT,
    function (AfterSubmitEvent $event) {
        $submission = $event->getSubmission();
        $form = $event->getForm();
        if ($form->getHandle() != 'registerOpenDay') {
 ...
```
When I change the code to what the documentation says:
 `
Form::class,
  Form::EVENT_AFTER_SUBMIT,
`
I'm getting the following error: Class "Solspace\Freeform\Library\Composer\Components\Form" not found

### How can we reproduce this?

1. use freeform 4
2. make a module that does something after the submit, using the formsservice event
3. upgrade to freeform 5

### Freeform Edition

Pro

### Freeform Version

5.3.1

### Craft Version

4.9.5

**Comment by kjmartens** [comment]
Sorry for the delay @JulieVelghe,

Is this issue still happening for you? And if so, can you elaborate on what it is you're trying to do specifically and what your current module code looks like? 🙂

**Comment by JulieVelghe** [comment]
Hi @kjmartens ,
what I was trying to to with my module, was when a certain form for an event (let's say a workshop) was submitted, the seatcounter field on that event gets adjusted.
The problem seemed to have been with the following use-code from the documentation:
`use Solspace\Freeform\Library\Composer\Components\Form;`
When I changed that to the following:
`use Solspace\Freeform\Form\Form;`
the adjusted code worked again.
So all is good again :)

**Comment by kjmartens** [comment]
Thank you for letting us know @JulieVelghe. Glad it's sorted for you now. 🙂
