### ISSUE TITLE
Not able to save and continue

### ISSUE THREAD

**Issue by BasBeeldr** [solspace/craft3-freeform#1311]
### What happened?

Some time ago I updated Freeform to 5.1.16, but this week I discovered that the interim save button gives an error message. I have now discovered that updating to the latest version does not solve the problem, but a downgrade to 5.1.14 does. So it appears to be wrong from 5.1.15 onwards. Unfortunately I couldn't find anything in the logs or console/network as a specific error.

### How can we reproduce this?

1.  Use freeform 5 version 5.1.15 or higher
2. Use craft version 4.8.10

### Freeform Edition

Pro

### Freeform Version

5.1.15

### Craft Version

4.8.10

### When did this issue start?

After upgrading from older Freeform version, Unsure

### Previous Freeform Version

5.1.15

**Comment by kjmartens** [comment]
I'm very sorry about this issue and the delay @BasBeeldr.

I can duplicate this in my testing and we'll work on a fix for it shortly. 🙂

**Comment by kjmartens** [comment]
This should be resolved now in Freeform 5.4. 🙂
