### ISSUE TITLE
Freeform giving conditional errors

### ISSUE THREAD

**Issue by JulieVelghe** [solspace/craft3-freeform#1318]
### What happened?

I've upgrade to the latest freeform version for a site, but I'm getting errors about conditional fields:

Conditional Rule | error | 30 mei 2024 17:38:28 | Form field was not an instance of FieldInterface {"field":null} []

The problem is I'm having multiple forms with conditional rules, where can I find out which form is giving the problems? When saving the forms, nothing gave problems.

### How can we reproduce this?

1. have multiple forms with conditional rules
2. upgrade from freeform 4 to 5
3. look at the generated errors

### Freeform Edition

Pro

### Freeform Version

5.3.1

### Craft Version

4.9.5

**Comment by rellafella** [comment]
@JulieVelghe I see you closed this as completed. Are you able to post your solution? I am experiencing the same error but struggling to find a nice way to debug.

**Comment by svondervoort** [comment]
Same here, curious what the issue was. Would be nice to share :)
