### ISSUE TITLE
[5.3.2] Stripe payment errors do not scroll to top of form

### ISSUE THREAD

**Issue by croxton** [solspace/craft3-freeform#1329]
### What happened?

If a payment is declined or otherwise fails, an error message is displayed at the top of the form. But unlike other standard form field errors handled by the Freeform JS plugin, the page does not automatically scroll to the top of the form - meaning that on longer forms, where the error message is above the fold, the user may not see the error at all.

It would be great for UX if error responses could be handled consistently. My current solution is to make the error message `position: sticky` so it is always visible in the viewport, but that is a somewhat unusual pattern; it would be better if the form scrolled to top.

### How can we reproduce this?

1. Setup a form with a Stripe payment field (Stripe in test mode)
2. Enter a Stripe test card number to simulate a declined payment (e.g. 4000000000000002)
3. Form does not scroll to the top.

### Freeform Edition

Pro

### Freeform Version

5.3.2

### Craft Version

5.1.7

### When did this issue start?

Unsure

**Comment by kjmartens** [comment]
Sorry for the trouble and the delay @croxton.

I can duplicate this in my testing and we'll work on a fix for it. 🙂

**Comment by kjmartens** [comment]
This should be resolved now in Freeform 5.4. 🙂

**Comment by croxton** [comment]
Fantastic, thank you!
