### ISSUE TITLE
Date & Time input type "datetime" is obsolete

### ISSUE THREAD

**Issue by vonscriptor** [solspace/craft3-freeform#1332]
### What happened?

The `Date & Time` input without using the "built-in datepicker" uses an obsolete type of `datetime` and does not render (tested in Chrome).

Valid types:
1. `date`
2. `datetime-local`
3. `time`

### How can we reproduce this?

1. Create a form with a Date & Time field that does not use the built-in datepicker.
2. Render the form.
3. Notice that the native date UI is not shown/functional (tested in Chrome)

### Freeform Edition

Pro

### Freeform Version

5.3.2

### Craft Version

Craft Pro 4.9.6

### When did this issue start?

Unsure

**Comment by kjmartens** [comment]
Sorry about this @vonscriptor,

You're right about it not setting correctly. We'll update this shortly. 🙂

**Comment by vonscriptor** [comment]
Thank you! It would be great if the Date & Time field had those 3 types as selectable options so that we can pick the format (`date`, `datetime-local`, or `time`).

**Comment by kjmartens** [comment]
This should be resolved now in Freeform 5.4. 🙂 

When the Flatpickr JS is not enabled, it will correctly set the `type` attribute to `date`, `time`, or `datetime-local` - whichever is applicable. 🙂
