### ISSUE TITLE
Unable to create new forms or duplicate existing ones.

### ISSUE THREAD

**Issue by aaronbest4** [solspace/craft3-freeform#1334]
### What happened?

At some point in the past few updates I have lost the ability to create new forms or duplicate existing forms in my local instance.

I am currently running Craft 5.1.9 and Freeform 5.3.3.1. I have attempted different configurations of rolling back each or both to no avail. I have also confirmed that the file permissions on my Ubuntu development server are correct.

On the "Forms" screen of Freeform there is no "New Form" button, only the cards of existing forms. When I attempt to duplicate an existing form, the card bounces but does not load or provide a toast notification. A 403 Forbidden error does appear in the console for the "clone" callback.

The account I am using is the initial Craft account, and is an full administrator. 

If I attempt to visit the "new" URL directly I am presented with the new form screen, but it does not create the form's first page and thus does not allow me to add fields to the form.

I am able to edit an existing form without any issues.

### Errors and Stack Trace (if available)

```shell
yii\web\ForbiddenHttpException: User is not permitted to perform this action in /var/www/html/vendor/solspace/craft-freeform/packages/plugin/src/controllers/api/FormsController.php:39
Stack trace:
#0 [internal function]: Solspace\Freeform\controllers\api\FormsController->actionClone(1)
#1 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#2 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#3 /var/www/html/vendor/solspace/craft-freeform/packages/plugin/src/controllers/BaseApiController.php(15): yii\base\Controller->runAction('clone', Array)
#4 /var/www/html/vendor/yiisoft/yii2/base/Module.php(552): Solspace\Freeform\controllers\BaseApiController->runAction('clone', Array)
#5 /var/www/html/vendor/craftcms/cms/src/web/Application.php(349): yii\base\Module->runAction('freeform/api/fo...', Array)
#6 /var/www/html/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('freeform/api/fo...', Array)
#7 /var/www/html/vendor/craftcms/cms/src/web/Application.php(317): yii\web\Application->handleRequest(Object(craft\web\Request))
#8 /var/www/html/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest(Object(craft\web\Request))
#9 /var/www/html/web/index.php(12): yii\base\Application->run()
#10 {main}
```

### How can we reproduce this?

1. Forms Screen
2a. (Missing New Form Button) 
2b. (Above stack trace error when attempting to clone existing form)

### Freeform Edition

Pro

### Freeform Version

5.3.3.1

### Craft Version

5.1.9

### When did this issue start?

Unsure

### Previous Freeform Version

5.3.2

**Comment by kjmartens** [comment]
Sorry for the delay @aaronbest4,

What ended up being the issue? Was the edition set as `Express` or something? 🙂
