### ISSUE TITLE
Project Config Scheme Version

### ISSUE THREAD

**Issue by hugo-costa** [solspace/craft3-freeform#134]
project-config/sync has been renamed to project-config/apply. Running that instead...
Your project config files were created for different versions of Craft and/or plugins than what’s currently installed.

Forms is installed with schema version of 3.3.1 while 3.3.0 was expected.

Try running `composer install` from your terminal to resolve.

**Steps to reproduce**

php ./craft project-config/sync

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 3.6.13
- Freeform Version: 3.11.3
- Freeform Edition: pro
- Fresh Install or Upgrade: upgrade

**Additional context**
`rm -rf vendor/ && rm composer.lock && composer clear-cache && composer update` but the issues still persists.

**Comment by gustavs-gutmanis** [comment]
Hi @hugo-costa,  
For some reason, your DB is newer than your project config file. Are you doing this on your local dev machine? What was the flow of your update?

**Comment by mikewink** [comment]
I am getting the same error here: 

```
Your project config files were created for different versions of Craft and/or plugins than what’s currently installed.

Forms is installed with schema version of 5.8.0 while 5.14.0 was expected.
```

I did `composer install` on production, then run `php craft up` and after installing the migrations, I got this message. This has happened to me multiple times in the past.

Where would I find this 5.8.0 value inside Craft CMS? There is the plugin.yaml and the plugin table inside the DB. But both show 5.14.0 as the current version.

**Comment by kjmartens** [comment]
The schema value also appears inside the `/config/project/config.yaml`:

```yaml
  freeform:
    edition: pro
    enabled: true
    licenseKey: XXXXXXXXXXXXXXXXXXXXXX
    schemaVersion: 5.14.1
```

**Comment by mikewink** [comment]
> The schema value also appears inside the `/config/project/config.yaml`:
> 
>   freeform:
>     edition: pro
>     enabled: true
>     licenseKey: XXXXXXXXXXXXXXXXXXXXXX
>     schemaVersion: 5.14.1

There I looked and found 5.14.0. That is why I am confused about where this 5.8.0 comes from. The plugins table in the DB also says 5.14.0.
