### ISSUE TITLE
v5.4.0 - "One of Freeform’s migrations failed."

### ISSUE THREAD

**Issue by vonscriptor** [solspace/craft3-freeform#1354]
### What happened?

During the update process via the CP it failed due to a migration issue. I was updating Craft CMS to v4.10.2 at the same time.

### Errors and Stack Trace (if available)

```shell
One of Freeform’s migrations failed.
yii\base\ErrorException: Attempt to read property "name" on null
```

### How can we reproduce this?

1. Upgrade to v5.4.0
2. 
3. 

### Freeform Edition

Pro

### Freeform Version

5.4.0

### Craft Version

Craft Pro 4.10.2

### When did this issue start?

After upgrading from older Freeform version, After upgrading from older Craft version

### Previous Freeform Version

5.3.5

**Comment by kjmartens** [comment]
Sorry for the trouble @vonscriptor,

Are you seeing any other information about the error, which migration failed, a stack trace, etc? 🙂

**Comment by vonscriptor** [comment]
That's all it said. Is there a place I should be able to see additional details?

**Comment by kjmartens** [comment]
Can you check your Craft logs? (`/storage/logs`) You can check out a number of logs, depending on where you are with this:

- phperrors.log
- web-2024-06-19.log
- console-2024-06-19.log

Or if you temporarily enable `devMode`, you'll get the error directly on the CP page. 🙂

**Comment by vonscriptor** [comment]
For my situation I tried running the craft-typogrify plugin update, Craft CMS update, then Freeform update all after each other this time and that worked fine. Checked the web log and it said the migration was successful.

**Comment by kjmartens** [comment]
Thanks for the update! Glad you got it solved 🙂
