### ISSUE TITLE
Date & Time field - Not respecting Date order in playload value

### ISSUE THREAD

**Issue by vonscriptor** [solspace/craft3-freeform#1356]
### What happened?

I have a `Date & Time` field with a `Date Order` of: `Month, Day, Year`. The placeholder text is displayed correctly (`MM-DD-YYYY`), as well as the `data-datepicker-format="m-d-Y"`. However, my custom validation throws an error about the format not conforming. The Network tab's payload shows a value that is formatted: YYYY-MM-DD.

### How can we reproduce this?

1. Create a `Date & Time` field
2. Type: `Date`
3. Disable: `Use the built-in datepicker`
4. Enable: `Use date format as placeholder`
5. Date order: `Month, Day, Year`
6. Enable: `Four digit year`
7. Enable: `Leading zero on date`
8. Date separator `-`
9. Select a date using the native HTML UI.
10. Submit the form and check the field's payload value having a format of `YYYY-MM-DD` instead of `MM-DD-YYYY`

### Freeform Edition

Pro

### Freeform Version

5.4.0

### Craft Version

Craft Pro 4.10.2

### When did this issue start?

Unsure

**Comment by kjmartens** [comment]
This should now be fixed in Freeform 5.5.0. 🙂
