### ISSUE TITLE
Form editor in control panel not loading in Craft 5.x after upgrade 

### ISSUE THREAD

**Issue by bliswebagency** [solspace/craft3-freeform#1357]
### What happened?

After upgrading from 5.3.5 to 5.4.0 Lite the forms can no longer be edited in control panel. It appears that form editor starts to load and appears for a brief moment then disappears with client.js error reported in the browser console.

It appears at some point the value of "n.types" changes to something else other than an array, and the call to map() function fails. The screenshot shows n.types with a valid value, but at some point during load it will encounter a field group or field that causes this to become invalid.

We've since rolled back to Freeform 5.3.5 to temporarily resolve the problem.

Please see attached screenshot:

![Screenshot 2024-06-19 at 5 04 43 PM](https://github.com/solspace/craft-freeform/assets/158676/c48b57d6-b86f-4ba1-b844-0fc9b3610444)

![Screenshot 2024-06-19 at 5 04 32 PM](https://github.com/solspace/craft-freeform/assets/158676/d67504e5-32b9-449c-8ab9-ec56c5d1ebdd)

### Errors and Stack Trace (if available)

```shell
Please see attachment
```

### How can we reproduce this?

1. Upgrade from Freeform 5.3.5 to 5.4.0 with existing forms
2. Try to edit form in backend
3. It starts to load then disappears with error message reported in console

### Freeform Edition

Lite

### Freeform Version

5.4.0

### Craft Version

5.2.2

### When did this issue start?

After upgrading from older Freeform version

### Previous Freeform Version

5.3.5

**Comment by kjmartens** [comment]
Sorry about this @bliswebagency,

We'll get it fixed right away!

**Comment by kjmartens** [comment]
This is resolved now in Freeform 5.4.1. Sorry again for the trouble. 🙂

**Comment by bliswebagency** [comment]
@kjmartens thank you for the quick response!
