### ISSUE TITLE
Webhook errors should fail gracefully

### ISSUE THREAD

**Issue by mofman** [solspace/craft3-freeform#1358]
### What happened?

At the moment, if the webhook fails for whatever reason, Craft returns a 500. I believe this should fail gracefully so that the user still proceeds to the success page. 

Additionally it doesnt appear that webhook integrations are included in the new job queue changes that were made in 5.4.0?

### How can we reproduce this?

Process a submission to a broken webhook.

### Freeform Edition

Pro

### Freeform Version

5.4.1

### Craft Version

4.10.2

**Comment by kjmartens** [comment]
Sorry about this @mofman,

We'll release a fix for this shortly. 🙂

**Comment by kjmartens** [comment]
This should now be fixed in Freeform 5.5.0. 🙂
