### ISSUE TITLE
Create and Duplicate Forms

### ISSUE THREAD

**Issue by DianyelaMaldonado** [solspace/craft3-freeform#1363]
### What happened?

I have a form created called: "Contact", but I want to add other forms but I cannot create a new form or duplicate my existing form, in craft 5 version.  Could someone please tell me why it happens?

### How can we reproduce this?

1. 
2. 
3. 

### Freeform Edition

Lite

### Freeform Version

5.4.2

### Craft Version

5

**Comment by kjmartens** [comment]
Hi @DianyelaMaldonado,

Is there a chance you're accidentally using the Express edition of Freeform? That free edition is limited to 1 form. If this is the case, can you follow the instructions to switch the edition here? 🙂 

https://docs.solspace.com/craft/freeform/v5/setup/installing-updating/#changing-editions

**Comment by DianyelaMaldonado** [comment]
@kjmartens Thank you very much, it already worked for me. 🥳
