### ISSUE TITLE
Stripe: Mapping from user

### ISSUE THREAD

**Issue by Coysh** [solspace/craft3-freeform#1377]
### What happened?

![CleanShot 2024-06-26 at 17 47 57](https://github.com/solspace/craft-freeform/assets/5764356/5eb39023-bfbc-43b8-ad32-223d1764de55)

We're exploring whether Freeform Pro with Stripe is a good solution.
We will have some of the mapped fields (Full name) available in the page, likely collected from the User element, rather than an input on the form itself.

Would this be possible?

### How can we reproduce this?

1. Map user field to Stripe

### Freeform Edition

Pro

### Freeform Version

5.5.0

### Craft Version

latest

**Comment by gustavs-gutmanis** [comment]
Hi @Coysh,

The twig that is used for field mappings is isolated from the rest of the Craft environment, so you would not be able to directly map to `{{ craft.user.name }}`, but, you would be able to create an `invisible` field, and in your formatting template force its value to that of the current user name, and map the invisible field directly in the field mapping.

Would this work for you?

The template code would look something like this:

```twig
{{ freeform.form('my-form').render({
  fields: {
    myInvisibleFieldHandle: {
      value: craft.user.fullname,
    }
  }
})
```

**Comment by Coysh** [comment]
> Hi @Coysh,
> 
> The twig that is used for field mappings is isolated from the rest of the Craft environment, so you would not be able to directly map to `{{ craft.user.name }}`, but, you would be able to create an `invisible` field, and in your formatting template force its value to that of the current user name, and map the invisible field directly in the field mapping.
> 
> Would this work for you?
> 
> The template code would look something like this:
> 
> ```
> {{ freeform.form('my-form').render({
>   fields: {
>     myInvisibleFieldHandle: {
>       value: craft.user.fullname,
>     }
>   }
> })
> ```

Great - thanks. I think that would work for my user case!
