### ISSUE TITLE
Spam Integrations Not Visible While allowAdminChanges = false

### ISSUE THREAD

**Issue by mofman** [solspace/craft3-freeform#1379]
### What happened?

5.5.0 Brought some welcome changes, meaning that admin could add spam words / email without writing to config. 

However the link is not visible while `allowAdminChanges` is set to `false`, it is however accessible with the correct URL eg /admin/freeform/settings/integrations/spam-blocking?site=default

### Errors and Stack Trace (if available)

```shell
5.5
```

### How can we reproduce this?

Add Spam Integrations in devMode, attempt to find them while in production..

### Freeform Edition

Pro

### Freeform Version

5.5.0

### Craft Version

4.10.2

### When did this issue start?

After upgrading from older Freeform version

### Previous Freeform Version

5.4.0

**Comment by kjmartens** [comment]
Sorry about this @mofman 

We'll release a fix shortly 🙂

**Comment by kjmartens** [comment]
This is now resolved in Freeform 5.5.1. 🙂
