### ISSUE TITLE
 Integration errors should fail gracefully 

### ISSUE THREAD

**Issue by mofman** [solspace/craft3-freeform#1380]
### What happened?

At the moment, if an integration fails for whatever reason, Craft returns a 500. I believe this should fail gracefully so that the user still proceeds to the success page. 

As it stands any errors with integration eg. Salesforce will stop user from getting to success page or email notifiations being sent.

### How can we reproduce this?

Process a submission to a integration .eg. Salesforce.

### Freeform Edition

Pro

### Freeform Version

5.5.0

### Craft Version

4.10.2

**Comment by kjmartens** [comment]
Sorry about this @mofman.

We'll improve/fix this issue shortly. 🙂

**Comment by kjmartens** [comment]
This has now been updated and resolved in Freeform 5.5.3. 🙂
