### ISSUE TITLE
Drag and drop not positioning fields correctly

### ISSUE THREAD

**Issue by Coysh** [solspace/craft3-freeform#1384]
### What happened?

Trying to move fields around in the form builder on a multi-page form and having quite a few issues!

See below:

https://github.com/solspace/craft-freeform/assets/5764356/477ebe4c-073a-41ce-8aec-79b579e419ca

### How can we reproduce this?

1.  Open multi-page form
2.  Try to move field in form builder
3. 

### Freeform Edition

Pro

### Freeform Version

5.5.0

### Craft Version

Latest

**Comment by kjmartens** [comment]
Sorry for the delay @Coysh,

I am noticing a similar issue from time to time as well. We'll look further into it. 🙂

**Comment by kjmartens** [comment]
This should be resolved now in Freeform 5.5.5. 🙂
