### ISSUE TITLE
Multiple freeform.js files loading due to AJAX page loading, causes multiple sends

### ISSUE THREAD

**Issue by vonscriptor** [solspace/craft3-freeform#1386]
### What happened?

The site I'm building uses AJAX page loading (not to be confused with Freeform's AJAX submissions, e.g. [Taxi.js](https://taxi.js.org/)) for most pages, but not all.

My current Freeform config is…
Script Insert Location: Inside Form
Script Insert Type: Asset Bundles
Captchas -> reCAPTCHA (v3): Only load Captcha scripts once the user interacts with the form: Enabled

(I've tried other config options, but still have the issue or the forms fail to send, or get marked as spam.)

If I go from one page that has a Freeform form on it, then load a new page via AJAX that also has a Freeform form on it the freeform.js file is loaded again (or: from a page with a Freeform form, AJAX page load to another, then back). Once you submit a Freeform form there will be multiple sends, one for each freeform.js that was loaded.

I'm not sure how to properly handle this. Is there a way for me or Freeform itself to destroy previous freeform.js instances? I'd prefer if Freeform was able to handle this internally.

### How can we reproduce this?

1. Load webpages via AJAX
2. Navigate to a page that has a Freeform form
3. Navigate to another page and back to the previous, or to another page that has a Freeform form
4. Notice how multiple freeform.js files are loaded.
5. Submit the Freeform form and notice how many submissions are made matching up with the number of freeform.js files that were loaded.

### Freeform Edition

Pro

### Freeform Version

5.5.1

### Craft Version

Craft Pro 4.10.3

### When did this issue start?

Unsure

**Comment by gustavs-gutmanis** [comment]
Hi @vonscriptor 

I would suggest you try disabling the insertion of Freeform scripts and load them manually only once, on your initial page load.

[Here's documentation](https://docs.solspace.com/craft/freeform/v5/developer/js-plugin/#loading-freeform-js-manually) on how to load the scripts manually.

Hope this helps.

**Comment by vonscriptor** [comment]
Hi @gustavs-gutmanis I've tried that, but I also have reCAPTCH (v3) on some forms (including this particular one that is trying to send an email) and it keeps sending my submissions to spam.

I have Script Insert Location: None (add manually) and put `{{ freeform.loadFreeformPlugin() }}` at the bottom of the body which is loaded once when the website is initially.

Then I have `<script type="text/javascript" src="https://www.google.com/recaptcha/api.js?render=explicit" data-taxi-reload></script>` after this particular Freeform render.

Each of the scripts are loading, but like I mentioned messages are always marked as spam:
- reCAPTCHA - The response parameter is invalid or malformed.
- Please verify that you are not a robot.

**Comment by gustavs-gutmanis** [comment]
It looks like you're loading your own reCAPTCHA script. It would not work unless you wrote your own module for validating it in Freeform. 
I am looking at how reCAPTCHA scripts are attached to the forms and I see that it would not work with `.loadFreeformPlugin` since that loads just the plugin and the other scripts are attached when rendering the closing tag of a form. I will have to figure out a way to collect the scripts added that way and include them when calling the `loadFreeformPlugin`.

To try to have this work right now, without waiting on a fix, would it be possible for you to include this file from the freeform directory?

`[craft-root]/vendor/solspace/craft-freeform/packages/plugin/src/Resources/js/scripts/front-end/captchas/recaptcha/v3.js`

Maybe copy the file and add that to a publicly accessible folder and load it from there?
Sorry for the inconvenience...

**Comment by vonscriptor** [comment]
Hi @gustavs-gutmanis, I appreciate the quick info! That does appear to be working as a temporary solution—thank you! Even with `Only load Captcha scripts once the user interacts with the form`: **Enabled**, which is good.

**Comment by kjmartens** [comment]
This feature has now been added to Freeform 5.5.3. 🙂 

We've added `freeform.loadFormSpecificScripts(form)`, which will load form-specific scripts such as **reCAPTCHA** and the **JS Test** scripts, where applicable. Be sure to pass the form handle to this function. If `form` is already defined, you can use that.

Your code might look something like this:

```twig{4-5}
<body>
    {# your template code #}

    {{ freeform.loadFreeformPlugin }}
    {{ freeform.loadFormSpecificScripts(form) }}
</body>
```

**Comment by vonscriptor** [comment]
Hello, I guess I'm not totally clear on how to implement the solution for my needs—AJAX page loading on a website that has multiple forms.

`{{ freeform.loadFreeformPlugin }}` Seems to only be needed to run once.
`{{ freeform.loadFormSpecificScripts(form) }}` Seems to need to be run for each individual form? How should that work with AJAX page loading and multiple forms?

**Comment by kjmartens** [comment]
Sorry about this @vonscriptor.

We're going to create another function to handle this. We should have an update available within the next day or two. 🙂

**Comment by kjmartens** [comment]
@vonscriptor,

We've added a `loadScripts` function in Freeform 5.5.4. It is capable of generating any of Freeform's scripts when you specify them.

Options are:

- `freeform`
- `freeform.js-test`
- `recaptcha.v2-invisible`
- `recaptcha.v2-checkbox`
- `recaptcha.v3`
- `hcaptcha.invisible`
- `hcaptcha.checkbox`
- `stripe`

Your template might look something like this:

``` twig
{{ freeform.loadScripts([
    "freeform",
    "freeform.js-test",
    "stripe",
    "recaptcha.v3"
]) }}
```
