### ISSUE TITLE
Forms can't be saved

### ISSUE THREAD

**Issue by alexanderloewe** [solspace/craft3-freeform#141]
**Describe the bug or issue you're experiencing**
I can not save the form. The System returns a `500()` flash message and in the log i can find this message: `No form ID specified in`

**Expected behavior**

**Craft & Plugin Info (please complete the following information):**

- Craft Version: Craft CMS 3.6.14
- Freeform Version: 3.11.4.1
- Freeform Edition: po
- Fresh Install or Upgrade: Update

**Additional context**
2021-05-14 02:23:01 [-][4][-][error][Solspace\Freeform\Library\Exceptions\FreeformException] Solspace\Freeform\Library\Exceptions\FreeformException: No form ID specified in /home/www/web/v1/vendor/solspace/craft-freeform/packages/plugin/src/Controllers/FormsController.php:160
Stack trace:
#0 [internal function]: Solspace\Freeform\Controllers\FormsController->actionSave()
#1 /home/www/web/v1/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#2 /home/www/web/v1/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams(Array)
#3 /home/www/web/v1/vendor/craftcms/cms/src/web/Controller.php(190): yii\base\Controller->runAction('save', Array)
#4 /home/www/web/v1/vendor/yiisoft/yii2/base/Module.php(534): craft\web\Controller->runAction('save', Array)
#5 /home/www/web/v1/vendor/craftcms/cms/src/web/Application.php(274): yii\base\Module->runAction('freeform/forms/...', Array)
#6 /home/www/web/v1/vendor/yiisoft/yii2/web/Application.php(104): craft\web\Application->runAction('freeform/forms/...', Array)
#7 /home/www/web/v1/vendor/craftcms/cms/src/web/Application.php(259): yii\web\Application->handleRequest(Object(craft\web\Request))
#8 /home/www/web/v1/vendor/yiisoft/yii2/base/Application.php(392): craft\web\Application->handleRequest(Object(craft\web\Request))
#9 /home/www/web/v1/web/index.php(21): yii\base\Application->run()
#10 {main}
2021-05-14 02:23:01 [-][4][-][info][application] $_GET = [
    'p' => 'admin/freeform/forms/save/'
]

**Comment by kjmartens** [comment]
Can you try checking out this common issue? 🙂
https://docs.solspace.com/craft/freeform/v3/setup/common-issues.html#_500-error-no-form-id-specified-or-the-request-response-is-empty

**Comment by alexanderloewe** [comment]
perfect, that did the job!

Thank you.
