### ISSUE TITLE
"Survey Results" link is broken

### ISSUE THREAD

**Issue by jcdarwin** [solspace/craft3-freeform#1425]
### What happened?

We've created a form of type "Surveys & Polls", and can see a card for the survey in the control panel at `/freeform/forms`:

<img width="1178" alt="image" src="https://github.com/user-attachments/assets/b192f247-ab13-45bc-875e-44edca4c6f08">

We notice that there's a "Survey Results" link (created by [this code](https://github.com/solspace/craft-freeform/blob/v5/packages/plugin/src/Bundles/Form/Types/Surveys/EventListeners/AttachFormLinks.php#L27)) which as of 5.5.0 links to `'/surveys/'.$form->getHandle()`.

In our case, there's nothing at this link, and we end up with a 404, as it links to `/surveys/chinaCapableMasterclassAlumni` (i.e. frontend), but should actually instead link to `/[cpTrigger]/freeform/surveys/chinaCapableMasterclassAlumni` (where `[cpTrigger]` is normally `admin`, though in our case we override the default value of `cpTrigger`).

This was working in version 5.4.2, but broke in 5.5.0

### How can we reproduce this?

1.  Create a form of type "Surveys & Polls"
2.  Got to the dashboard in the control panel (e.g. `admin//freeform/forms`)
3. See the "Survey Results" link on the card for the new survey
4. Click it and experience a 404

### Freeform Edition

Pro

### Freeform Version

5.5.2

### Craft Version

4.10.4

### When did this issue start?

It was working in 5.4.2, but broke in 5.5.0

### Previous Freeform Version

5.5.2

**Comment by kjmartens** [comment]
Sorry about this @jcdarwin,

We'll get it fixed shortly. 🙂

**Comment by kjmartens** [comment]
This will be resolved in Freeform 5.5.5 🙂
