### ISSUE TITLE
[Zoho Lead integration] Unable to re-authenticate after client changed his password

### ISSUE THREAD

**Issue by mdominguez** [solspace/craft3-freeform#144]
**Describe the bug or issue you're experiencing**
A couple of months ago we've successfully setup the Zoho Lead CRM integration for a client of ours, which was working fine until recently the client changed his Zoho account password. So now we're trying to re-authenticating with the new login credentials he has sent us but unfortunately everytime we follow the correct steps as described in [the docs](https://docs.solspace.com/craft/freeform/v3/api-integrations/crm/zoho-lead.html), the indicator of the CRM page in Craft turns red and says it can't authorize (in the console we get a {response: false} object as a response)... While on the Zoho side everything went as usual... Any ideas on what could be the issue here?

We've also tried creating a fresh CRM integration instead of re-authenticating the current one but unfortunately we keep getting the same issue. We even created a new application in Zoho API Console, followed the exact same steps described in the docs with a new Zoho Lead CRM Integration in Craft but again; same issue pops up time after time...

So now after a couple of hours of trying we're down to not knowing whatever the heck could be wrong... Thanks a million for any tips or help! You can hit me up on the Craft's Discord Channel if you would need any quick and further information (@mdominguez)

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 3.6.14
- Freeform Version: 3.11.4.1
- Freeform Edition: Pro
- Fresh Install or Upgrade: Upgrade

**Comment by gustavs-gutmanis** [comment]
Hi @mdominguez 

Is it possible that the client has enabled a 2-factor-authentication?  
I remember trying everything to get my account with 2fa enabled to work with anything other than zoho's web tools to no avail.

**Comment by mdominguez** [comment]
Hmm nope I don't see any 2FA authentication enabled, I probably would've failed to login myself when trying to?

**Comment by gustavs-gutmanis** [comment]
Is it possible for you to debug the code, see what happens when Freeform is trying to fetch [Zoho's access token](https://github.com/solspace/craft3-freeform/blob/master/packages/plugin/src/Integrations/CRM/Zoho/AbstractZohoIntegration.php#L168)?

**Comment by mdominguez** [comment]
The code's not getting into that 'catch'. I successfully get a $json object with the access and refresh token [view screenshot](https://share.getcloudapp.com/nOuoGdG2)

**Comment by gustavs-gutmanis** [comment]
Try the [`::checkConnection()`](https://github.com/solspace/craft3-freeform/blob/master/packages/plugin/src/Integrations/CRM/Zoho/AbstractZohoIntegration.php#L203) endpoint.

**Comment by mdominguez** [comment]
this is the print_r($client->get($endpoint));

```
GuzzleHttp\Psr7\Response Object
(
    [reasonPhrase:GuzzleHttp\Psr7\Response:private] => No Content
    [statusCode:GuzzleHttp\Psr7\Response:private] => 204
    [headers:GuzzleHttp\Psr7\Response:private] => Array
        (
            [Server] => Array
                (
                    [0] => ZGS
                )

            [Date] => Array
                (
                    [0] => Tue, 18 May 2021 13:34:04 GMT
                )

            [Content-Type] => Array
                (
                    [0] => application/json;charset=utf-8
                )

            [Connection] => Array
                (
                    [0] => keep-alive
                )

            [Set-Cookie] => Array
                (
                    [0] => 1a99390653=097d1e8a5f4f275774525e2143b1676b; Path=/
                    [1] => crmcsr=2f68c473-c7d6-45cc-a241-42273d2fbc86;path=/;SameSite=None;Secure;priority=high
                    [2] => _zcsr_tmp=2f68c473-c7d6-45cc-a241-42273d2fbc86;path=/;SameSite=Strict;Secure;priority=high
                    [3] => JSESSIONID=C94CBA3C596F8615BE10B3D92D45BBF6; Path=/; Secure
                )

            [Referrer-Policy] => Array
                (
                    [0] => strict-origin
                )

            [X-Content-Type-Options] => Array
                (
                    [0] => nosniff
                )

            [X-XSS-Protection] => Array
                (
                    [0] => 1; mode=block
                )

            [Pragma] => Array
                (
                    [0] => no-cache
                )

            [Cache-Control] => Array
                (
                    [0] => no-store, no-cache, must-revalidate, private
                )

            [Expires] => Array
                (
                    [0] => Thu, 01 Jan 1970 00:00:00 GMT
                )

            [X-Frame-Options] => Array
                (
                    [0] => SAMEORIGIN
                )

            [X-ACCESSTOKEN-RESET] => Array
                (
                    [0] => 2021-05-18T16:32:40+02:00
                )

            [clientVersion] => Array
                (
                    [0] => 4040544
                )

            [clientsubVersion] => Array
                (
                    [0] => 3306d77ab3a5ffaa8409608b12a6b343
                )

            [Content-Disposition] => Array
                (
                    [0] => attachment; filename=response.json
                )

            [X-Download-Options] => Array
                (
                    [0] => noopen
                )

            [Content-Language] => Array
                (
                    [0] => en-US
                )

            [Strict-Transport-Security] => Array
                (
                    [0] => max-age=63072000
                )

        )

    [headerNames:GuzzleHttp\Psr7\Response:private] => Array
        (
            [server] => Server
            [date] => Date
            [content-type] => Content-Type
            [connection] => Connection
            [set-cookie] => Set-Cookie
            [referrer-policy] => Referrer-Policy
            [x-content-type-options] => X-Content-Type-Options
            [x-xss-protection] => X-XSS-Protection
            [pragma] => Pragma
            [cache-control] => Cache-Control
            [expires] => Expires
            [x-frame-options] => X-Frame-Options
            [x-accesstoken-reset] => X-ACCESSTOKEN-RESET
            [clientversion] => clientVersion
            [clientsubversion] => clientsubVersion
            [content-disposition] => Content-Disposition
            [x-download-options] => X-Download-Options
            [content-language] => Content-Language
            [strict-transport-security] => Strict-Transport-Security
        )

    [protocol:GuzzleHttp\Psr7\Response:private] => 1.1
    [stream:GuzzleHttp\Psr7\Response:private] => GuzzleHttp\Psr7\Stream Object
        (
            [stream:GuzzleHttp\Psr7\Stream:private] => Resource id #124
            [size:GuzzleHttp\Psr7\Stream:private] => 
            [seekable:GuzzleHttp\Psr7\Stream:private] => 1
            [readable:GuzzleHttp\Psr7\Stream:private] => 1
            [writable:GuzzleHttp\Psr7\Stream:private] => 1
            [uri:GuzzleHttp\Psr7\Stream:private] => php://temp
            [customMetadata:GuzzleHttp\Psr7\Stream:private] => Array
                (
                )

        )

)
```

**Comment by kjmartens** [comment]
@mdominguez I just tried testing this again now, and everything seemed to connect fine for me. Can you document all the exact steps you're taking (which things you're clicking in Zoho, etc)? Perhaps there's some sort of misstep along the way. The only other issue I could think of would be if it was in any way related to a region, as I am testing in the "USA"/North America vs you presumably testing in EU?

**Comment by mdominguez** [comment]
Hi @kjmartens, thanks for looking into this!

Steps are:

1. Going to /admin/freeform/settings/crm/1
2. Clicking the authorize link and getting redirected to Zoho
3. [step 3](https://share.getcloudapp.com/6qu86Lxe)
4. [step 4](https://share.getcloudapp.com/7KuPDybW)
5. [step 5](https://share.getcloudapp.com/p9ubW58p)
6. [Zoho API Console](https://share.getcloudapp.com/P8u5LYNg)

**Comment by kjmartens** [comment]
Thanks for that. I'm wondering if you can create a brand new one and show me the steps instead (rather than attempting to reauthorize an existing one). Would you be able to do that for me? :)

**Comment by mdominguez** [comment]
No problem: I've tried it again with a new CRM integration and took screenshots of every step:

1. [screenshot 1](https://share.getcloudapp.com/OAuPY4Pm)
2. [screenshot 2](https://share.getcloudapp.com/WnuYoqYk)
3. [screenshot 3](https://share.getcloudapp.com/yAuDdkDm)
4. [screenshot 4](https://share.getcloudapp.com/9ZuxbDdx)
5. [screenshot 5](https://share.getcloudapp.com/jkuLxmPz)
6. [screenshot 6](https://share.getcloudapp.com/bLuAWxq5)
7. [screenshot 7](https://share.getcloudapp.com/nOuoG95w)

**Comment by kjmartens** [comment]
Thanks for this @mdominguez. Out of curiousity, what is / how did you get to #5 (https://share.getcloudapp.com/jkuLxmPz)? Did you click SAVE on the Freeform CP page immediately after copying the Client ID and Secret? Or did you do some other step to get #5? :)

**Comment by mdominguez** [comment]
I pasted in the Client ID and Secret in Craft, then click save and get redirected to https://share.getcloudapp.com/jkuLxmPz which I click the first radio button > click Accept > be redirected to the Redirect URI as expected, but then still get the red dot that it couldn't get authorized...

**Comment by gustavs-gutmanis** [comment]
This has been resolved.
