### ISSUE TITLE
Form Builder allows for duplicated fields using drag and drop

### ISSUE THREAD

**Issue by david-olson** [solspace/craft3-freeform#145]
**Describe the bug or issue you're experiencing**
When editing or creating a form, using a drag and drop method to place a field on the form from the list on the far left allows users to create multiple fields on the form with the same handle without causing an error message. If a user attempts to remove one of these fields, the entire form builder page disappears.

**Steps to reproduce**

1. Create a new form
2. Drag fields from the 'Fields' column on the left and drop them into the body of the form
3. Repeat with the same field
4. Attempt to remove one of the fields

**Expected behavior**
After a field has been added to the body of the form by the Drag and Drop method it will no longer appear in the list of fields on the left.

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 3.6.12.1
- Freeform Version: 3.11.3
- Freeform Edition: Pro
- Fresh Install or Upgrade: Upgrade

**Screenshots**
![image](https://user-images.githubusercontent.com/22801189/118889535-3b700100-b8cb-11eb-8c93-2ea410471bec.png)
![image](https://user-images.githubusercontent.com/22801189/118889554-40cd4b80-b8cb-11eb-803e-0d4da5d0d305.png)

**Comment by gustavs-gutmanis** [comment]
Thanks for reporting this @david-olson,

We'll address this in the next version

**Comment by krizzzly** [comment]
i have installed the latest version of freeform 3.11.4.1, and we have the same issue. i cannot delete the dublicate field, it will lead to an empty page.

**Comment by kjmartens** [comment]
@krizzzly This has just been fixed for the unreleased version. We'll likely release that today/shortly. :)
