### ISSUE TITLE
Url Site Parameter - Undefined

### ISSUE THREAD

**Issue by DowleyDeveloped** [solspace/craft3-freeform#1464]
### What happened?

When within Freeform all other links within the side have the site parameter as `site=undefined` 

This is breaking other plugins and Craft.

### Errors and Stack Trace (if available)

```shell
"admin/entries?site=undefined"
```

### How can we reproduce this?

1. Go the forms dashboard, look at url for Entries

### Freeform Edition

Pro

### Freeform Version

5.5.5

### Craft Version

5.3.1

### When did this issue start?

After upgrading from older Freeform version

### Previous Freeform Version

5.5.4

**Comment by kjmartens** [comment]
Sorry about this @DowleyDeveloped,

We'll look into it and see what we can do. It seems to stem from the React app that handles the form builder.

**Comment by kjmartens** [comment]
This should now be resolved in Freeform 5.5.7.

Please note that for this to work correctly, you must enable the _Site Filtering for Forms and Submissions_ setting.
