### ISSUE TITLE
Element Connections Cannot Be Edited After Importing Database

### ISSUE THREAD

**Issue by kevinamezaga** [solspace/craft3-freeform#148]
**Describe the bug or issue you're experiencing**
I can't edit my forms' element connections after importing the forms from another install of freeform.

**Steps to reproduce**

1. Import Freeform Data from other site with element connections
2. Attempt to edit connections

**Expected behavior**
See the connection & edit

**Craft & Plugin Info (please complete the following information):**

- Craft Version: Craft Pro 3.6.15
- Freeform Version: 3.11.0-beta.6
- Freeform Edition: Pro
- Fresh Install or Upgrade: Fresh install + database tables import

**Additional Context**
I can't edit the imported forms' element connections, but if I create a new form I can. When clicking the element connections tab, I get the following JS errors in console, but on a new form I don't get it.
<img width="100%" alt="Screen Shot 2021-05-23 at 14 31 37" src="https://user-images.githubusercontent.com/25387497/119272611-ce16e580-bbd4-11eb-9027-e9fc8d47c630.png">
<img width="100%" alt="Screen Shot 2021-05-23 at 14 36 15" src="https://user-images.githubusercontent.com/25387497/119272612-d1aa6c80-bbd4-11eb-8fa3-cc0c4000ffc0.png">

**Comment by kevinamezaga** [comment]
###Update
I discovered this error occurs because Freeform saves element connections in the database in the layoutJson column with the form. This connection is saved using the section and entry type's IDs and not their handles. Because of this, when transferring to a new site, these are not able to transfer over.

If anyone else runs into this issue, I'd suggest turning off connections before migrating. Extra step but saves the headache of having to go edit the JSON in the database when moving from dev to production.

<img width="100%" alt="Screen Shot 2021-05-23 at 14 56 51" src="https://user-images.githubusercontent.com/25387497/119273057-1cc57f00-bbd7-11eb-9656-742e8c73ab54.png">

**Comment by gustavs-gutmanis** [comment]
Hi @kevinamezaga,

There's really no way around this without employing project config, and we can't really support project config, because there are too many clients who want the forms editable on their production sites, which wouldn't work with `allowAdminChanges` disabled.
