### ISSUE TITLE
File Upload marked unfinalized in Control Panel. Gets deleted after 3 hours.

### ISSUE THREAD

**Issue by urbantrout** [solspace/craft3-freeform#1487]
### What happened?

When editing the submission in the control panel and replacing the file with a new one, the new one is marked as unfinalized and gets deleted after 3 hours.

### How can we reproduce this?

1. Submit form with a file upload
2. Edit the submission in control panel
3. Replace uploaded file with new one
4. Check table `freeform_unfinalized_files` for new rows
5. Upload gets deleted after ~3hrs

### Freeform Edition

Pro

### Freeform Version

5.5.7

### Craft Version

5.3.0

**Comment by kjmartens** [comment]
Sorry about this @urbantrout.

I can duplicate this as well. We'll get it fixed shortly. 🙂

**Comment by urbantrout** [comment]
Thanks!

This also happens in Version 3 (and probably Version 4). Any chance this fix is going to be backported?

**Comment by kjmartens** [comment]
@urbantrout noted. We'll look into v3 and v4 as well.

**Comment by kjmartens** [comment]
This is now resolved in Freeform 5.5.9 (with fixes on the way for Freeform 3.x and 4.x soon). 🙂

**Comment by urbantrout** [comment]
Thanks for the fix!

I see that this was fixed in [5.5.9](https://github.com/solspace/craft-freeform/releases/tag/v5.5.9) and [4.1.22](https://github.com/solspace/craft-freeform/releases/tag/v4.1.22). Can you give me an ETA for v3?

**Comment by urbantrout** [comment]
Sorry for bothering you again @kjmartens.

Can you tell when this fix is going to be released for Freeform 3?

**Comment by kjmartens** [comment]
@urbantrout Sorry for the delay. The fix is now available in Freeform 3.13.38 as well. 🙂

**Comment by urbantrout** [comment]
Awesome! Thanks a lot!
