### ISSUE TITLE
Relational form field only returns first created form via GraphQL

### ISSUE THREAD

**Issue by Tam** [solspace/craft3-freeform#149]
**Describe the bug or issue you're experiencing**

**Steps to reproduce**

1. Create multiple forms
2. Select a form that isn't the first form you created in an entries Form field
3. Enable access to the forms in the schema
4. Try querying the form via GraphQL

**Expected behavior**
The form that's returned should be the one that was selected.

**Craft & Plugin Info (please complete the following information):**

- Craft Version: Craft Pro 3.6.15
- Freeform Version: 3.11.4.1
- Freeform Edition: Lite
- Fresh Install or Upgrade: Fresh

**Additional context**

**Comment by gustavs-gutmanis** [comment]
Hi @Tam,

Thanks for reporting this issue. The fix for it will be released in the upcoming release.

**Comment by kjmartens** [comment]
HI @Tam,

If you'd like to try out this fix now, you can set your main Craft `composer.json` file to `dev-master` for Freeform version and run `composer update`:

```
"solspace/craft-freeform": "dev-master"
```

🙂

**Comment by shpfive** [comment]
hi @kjmartens,
i'm on version 3.11.6 and still experience the same issue as described above.
Do i still need to use dev/master ?

**Comment by riekusdn** [comment]
I'm experiencing the same problem described in the opening post, using the field within a Matrix block. The graphql API always returns the form with the lowest id, not the form I've selected in the Matrix block. 



Craft edition & version | Craft Pro 3.6.17
Plugins:


Amazon S3 1.2.11
Bugsnag 2.1.2
Freeform 3.11.7
Redactor 2.8.7
Redactor custom styles 3.0.4
SEOmatic 3.3.43
Super table 2.6.8
Trigger 0.3.3

**Comment by riekusdn** [comment]
In addition: I looked up the fix to this issue, which checks whether the source is an instance of craft\elements\Entry. My guess is this is not the case when using Neo / Matrix blocks

**Comment by kjmartens** [comment]
Sorry, the latest changes won't affect this scenario, but we'll get that working shortly too. :)

**Comment by gustavs-gutmanis** [comment]
@shpfive @riekusdn the GQL should now resolve the correct forms as expected.  
This fix will be released in the upcoming release.
