### ISSUE TITLE
EE Freeform PRO - Accessing file uploads in Submissions data - files no longer hyperlinked

### ISSUE THREAD

**Issue by melbazany** [solspace/craft3-freeform#150]
**Describe the bug or issue you're experiencing**
I've previously been able to click directly on any File field submissions when viewing Form Submissions. However, the File field don't seem to be hyperlinked anymore as they were in Freeform Pro 1.x, etc.

**Steps to reproduce**

1. Navigate to the ExpressionEngine Freeform Pro add-on (/cp/addons/settings/freeform_next/forms)
2. Navigate to any created form's submissions.
3. Find a column for a File data field: This used to be hyperlinked so that the field's file could be downloaded, but it's no longer an option.

**Expected behavior**

This used to be hyperlinked so that the field's file could be downloaded, but it's no longer an option.

- ExpressionEngine Version: 6.0.3
- Freeform Version: 2.0.0-b3

**Comment by kjmartens** [comment]
Issue is for EE Freeform - posted in Craft Freeform GitHub repo... closing now. I will respond to your private support ticket with an update. :)
