### ISSUE TITLE
ReCAPTCHA rendering after FF V5 upgrade - no `recaptchaEnabled` conditional

### ISSUE THREAD

**Issue by thisisjamessmith** [solspace/craft3-freeform#1500]
### What happened?

I have always eschewed Solspace's front end JS and HTML auto-rendering in favour of my own. In Craft 4, for lazy-rendering of ReCAPTCHA, I was able to do something like this in my form template:

```
{% if form.recaptchaEnabled %}
	<div class="js-lazyloadScriptsWhenFieldFocussed">
		<input type="hidden" name="g-recaptcha-response">
		<script data-src="https://www.google.com/recaptcha/api.js?render={{ getenv('RECAPTCHA_V3_SITE_KEY') }}"></script>
	</div>
{% endif %}
```

It seems like you've made the captcha rendering entirely automatic in V5. Is it possible to make this example work so that I can carry on avoiding Solspace's JS? (At the moment I get an error message because `recaptchaEnabled` is not a valid thing anymore). I've tried dumping out my `form` object but can't see anything useful there.

### How can we reproduce this?

Have a manually rendered form something like

```{{ form.renderTag({...}) }}...{{ form.renderClosingTag }}```

Then try to output the ReCAPTCHA field manually.

### Freeform Edition

Pro

### Freeform Version

5.5.8

### Craft Version

4.11.5

### When did this issue start?

After upgrading from older Freeform version

### Previous Freeform Version

4.x

**Comment by kjmartens** [comment]
Sorry for the delay @thisisjamessmith,

I will look into this and see how soon we can get a conditional like that working again. In the meantime, doesn't the **Only load Captcha scripts once the user interacts with the form** setting do the same thing? 🙂

**Comment by thisisjamessmith** [comment]
It does, but as I mentioned, I don't use any of Solspace's JS because (in v4 at least), it was 90KB of almost entirely unused cruft which was destroying my page speed scores. For me at least, it feels a lot more Craft-like and less Wordpressy for plugins to never be allowed to output any of their own JS or CSS to the front end.

**Comment by thisisjamessmith** [comment]
A better option, perhaps, would be to have an option to make all forms have a recaptcha by default, which cannot be switched on/off by the client. After all, it's really not something clients should have to consider, and especially not on a form-by-form basis.

**Comment by thisisjamessmith** [comment]
A further requirement for this would be the need to only load captchas if the appropriate consents have been granted - all the more reason to use our own JS.

**Comment by gustavs-gutmanis** [comment]
@thisisjamessmith 
Captchas require setup, client ID, client Secret, as well as some more customization.
You can enable recaptcha on all forms by default when you set it up, that would solve the issue of managing them form-by-form.

**Comment by kjmartens** [comment]
@thisisjamessmith,

We have queued up adding a conditional for this. I suspect we'll have it available within the next few days. 🙂

**Comment by kjmartens** [comment]
This is now doable in Freeform 5.6+. 🙂 

Use the integration handle for the check: `{% if form.isIntegrationEnabled("integrationHandle") %}`
