### ISSUE TITLE
Pardot v4 integration missing the "pardot_api" scope

### ISSUE THREAD

**Issue by tylerfowle** [solspace/craft3-freeform#1502]
### What happened?

When trying to authorize a Pardot v4 Integration you will get an Error Code 184: access_token is invalid, unknown, or malformed.

Please add the `pardot_api` scope

```$event->add('scope', 'refresh_token api pardot_api');```

https://github.com/solspace/craft-freeform/blob/0d1db22c9171d3b777126e31bffa81224739d7bd/packages/plugin/src/Integrations/CRM/Pardot/EventListeners/PardotTokenListener.php#L47

### How can we reproduce this?

1. try authorizing a Pardot v4 CRM integration
2. 
3. 

### Freeform Edition

Pro

### Freeform Version

5.5.8

### Craft Version

4.9.7

**Comment by tylerfowle** [comment]
@kjmartens after making this change locally I was able to get the authorization to complete.

**Comment by kjmartens** [comment]
Thanks very much for this @tylerfowle. We'll get this fixed in the next release of Freeform (v5.5.9, available today). 🙂
