### ISSUE TITLE
Tailwind Formatting Template duplicating classes

### ISSUE THREAD

**Issue by svondervoort** [solspace/craft3-freeform#1506]
### What happened?

I've set up a form using the default Tailwind formatting template and whenever I inspect the wrapper within a row has duplicate classes.

This is the class attribute for a Text input:
```
lg:w-1/2 md:w-1/3 lg:w-1/3 xl:w-1/3 w-full px-2 w-full px-2 w-full px-2
```

This also happens on other levels.

I'm not extending the formatting in any way, I'm just loading and rendering the form using `{{ form.render() }}`

### How can we reproduce this?

1. Create a form with some basic fields
2. Set the `Formatting Template` to `Tailwind 3`
3. Check the rendered HTML

### Freeform Edition

Pro

### Freeform Version

5.5.7

### Craft Version

4.11.4

### When did this issue start?

Unsure

**Comment by kjmartens** [comment]
Hi @svondervoort,

I'm very sorry for the long delay...

Are you still experiencing this issue? If so, are you able to provide the full template code where you're rendering the form? I'm curious if you're setting any overrides or loading other forms, etc. 🙂

**Comment by svondervoort** [comment]
Hi @kjmartens, thanks for checking in, I think I figured it out.
At least, I'm not sure how I fixed it (it's been a while) but I don't see any "bloat" classes anymore.
