### ISSUE TITLE
Recaptcha V2 Checkbox can't be placed manually within form builder

### ISSUE THREAD

**Issue by icreatestuff** [solspace/craft3-freeform#1510]
### What happened?

In Freeform V4 we could specifically place where this type of Recaptcha appeared within the form.

In V5 this appears to always be automatically rendered right before the closing form tag `{{ form.renderClosingTag }}` or `</form>`. 

The overview section of the [docs here](https://docs.solspace.com/craft/freeform/v5/integrations/recaptcha/) states that it would be rendered before the submit button, but if I'm using some custom implementation of the submit button to render it elsewhere in the form other that it's default position before the closing form tag, then the reCAPTCHA checkbox doesn't render above it, but instead still above the closing </form> tag.

```twig
 {{ form.renderTag({
    disable: ["submitButtons"]
}) }}
    {% set page = form.pages.current %}

     <div>
        <div>
            {# Custom placement of submit button #}
            {{ page.buttons.renderSubmit() }}
        </div>
    </div>
    
    {# reCAPTCHA V2 Checkbox still rendered here #}
{{ form.renderClosingTag }}
```

![Screenshot 2024-09-05 at 19 04 31](https://github.com/user-attachments/assets/ee1db385-a2bb-4fbd-a9d6-faf48503d016)

Either, the automated placement of the reCAPTCHA needs to stick above the submit button, wherever it is placed, manually as above or with its automatic placement at the very end of the form, **or** there needs to be a way to manually place the checkbox elsewhere which could be:

- With a similar render tag as the submit button now has or;
- By drag and drop within the form builder layout

If I'm missing another option that already exists to place it I'm all ears.

Looking forward to hearing your thoughts.

### How can we reproduce this?

1. Create a form with the reCAPTCHA V2 checkbox integration enabled
2. Manually move the submit button using the submitRender() tag in Twig
3. Notice how the recpatcha checkbox doesn't appear above the submit button anymore

### Freeform Edition

Pro

### Freeform Version

5.5.9

### Craft Version

4.12.0

**Comment by icreatestuff** [comment]
Is there anything that can be done to customise the placement of the reCAPTCHA?

**Comment by gustavs-gutmanis** [comment]
Hi @icreatestuff 

Sorry, but currently it isn't possible to alter the position of captchas. We will, however, think of a solution that would let you change their positions.

**Comment by icreatestuff** [comment]
Thanks for the reply @gustavs-gutmanis, appreciate you adding it to the list to explore a solution.
