### ISSUE TITLE
Conditional rules on a group type doesn't work with flexbox

### ISSUE THREAD

**Issue by jeffreyschmitz87** [solspace/craft3-freeform#1512]
### What happened?

I've created a form with 2 fields:
- Checkbox
- Group with 2 fields (Text and Email)

Inside the 'Rules' tab I've added a rule that the group field should be visible when the checkbox has been checked. In the 'Settings' tab I've set the template to 'Flexbox'.

When I render the form from the Twig template the group field is visible by default. Checking and unchecking the checkbox doesn't change the visibility of the group. I'm using the code below:
```
{{ freeform.form(contentField.form.handle).render() }}
```

When I switch the template to Basic Light the group field is not visible by default and when I check the checkbox the visibility is being toggled. This is what should happen with the Flexbox template as well.

### How can we reproduce this?

Described in the 'What happened?' section.

### Freeform Edition

Pro

### Freeform Version

5.5.8

### Craft Version

4.11.5

**Comment by mazaalai** [comment]
I am experiencing the same issue: Group with Rules are not functioning correctly when using Flexbox for Template Formatting.

**Comment by kjmartens** [comment]
Sorry for the trouble with this. I can duplicate this as well, and we'll get a fix for it shortly. 🙂
