### ISSUE TITLE
RegexField default error is gone after upgrading from 4 to 5

### ISSUE THREAD

**Issue by svondervoort** [solspace/craft3-freeform#1529]
### What happened?

This might be intended so I'm just checking to be sure, but after upgrading FreeForm from v4 to v5 there is no default error message present for an a RegexField.

In v4 you can even see the default error message in the error field as a placeholder but in v5 this is also gone.

Also in v4 the error field was a text field now it seems to be a textarea, might be part of the reason or issue?

### How can we reproduce this?

Create a form with a regex field in FreeForm v4 and FreeForm v5 without setting a custom Error message for both variants.
Don't fill in the field in the frontend form to trigger the error message.

### Freeform Edition

Pro

### Freeform Version

5.6.1

### Craft Version

4.12.3

### When did this issue start?

After upgrading from older Freeform version

### Previous Freeform Version

4.1.15

**Comment by kjmartens** [comment]
Hi @svondervoort,

I have now added a default error message when creating new Regex fields. I'll check into the migration process. 🙂

**Comment by kjmartens** [comment]
This is now resolved in Freeform 5.6.4+ 🙂
