### ISSUE TITLE
Hidden text field character limit is fixed to 250

### ISSUE THREAD

**Issue by johnwbaxter** [solspace/craft3-freeform#153]
We are using a plain text field and it's set to be "hidden". Then using some js, we are putting a value in that field that gets carried into the saved submission data.

However, we're not sure when, it feels like in some update, the field length for a hidden text field has been limited to 250 chars, and that has started tripping us up as the data we save in that field can be long.

It doesn't seem possible to change the char length of a plain text field and if I convert it to a textarea field, then I can't make that field "hidden" in the form composer.

Ideally, I want a plain text field to be configurable to have a variable char length like craft does.

**Craft & Plugin Info (please complete the following information):**

- Craft Version:3.6.9
- Freeform Version: 3.10.9
- Freeform Edition: Freeform Pro
- Fresh Install or Upgrade: Fresh Install

**Comment by gustavs-gutmanis** [comment]
Noted, we're considering adding an option to choose the column type, or just using `TEXT` for all field types.

You can, however, set the column type manually in your database to remedy this problem right now, before we come up with a suitable solution.

**Comment by johnwbaxter** [comment]
@gustavs-gutmanis You seem to have the field length hard coded in your plugin and it is causing the validation to field.

**Comment by gustavs-gutmanis** [comment]
@johnwbaxter while the constant is there, it is never used, so that should not affect anything.  
I'll remove it.

**Comment by johnwbaxter** [comment]
@gustavs-gutmanis Ah ok cool. So, what table holds the freeform fields in? Where can I modify the field length?

**Comment by gustavs-gutmanis** [comment]
It's the `freeform_submissions` table. Check the database to see what your field `ID` is and then modify the corresponding `field_[ID]` column in the `freeform_submissions` table.

**Comment by johnwbaxter** [comment]
Ah ok, cool, that makes sense! Cheers!

**Comment by johnwbaxter** [comment]
@gustavs-gutmanis I've changed the column in the DB to be "text", but still getting the same error:

"The allowed maximum length is 250 characters. Current size is 58 characters too long"

Is there anything else I need to do?

**Comment by kjmartens** [comment]
@johnwbaxter If you're getting an error like that, it's likely from what is configured for the field in the property editor of the form builder. Can you check and see if you have any limit value set there?
<img width="548" alt="Screen Shot 2021-06-03 at 8 50 39 AM" src="https://user-images.githubusercontent.com/1821674/120656006-d7137c80-c448-11eb-85c0-0fed09b0bcde.png">

**Comment by johnwbaxter** [comment]
@kjmartens I only have these options:

![image](https://user-images.githubusercontent.com/338729/120656259-6043a700-c47b-11eb-997e-657b008aa0ce.png)

**Comment by kjmartens** [comment]
Oh right, hidden field type. Okay, my guess then is that since Hidden field types are set to VARCHAR(255) in the database, to help prevent customers from getting nasty database errors, we added the built-in limit, as you appear to have identified earlier. As Gustavs mentioned, we do have plans to greatly improve this area of Freeform in the near future. Until then, we'll look at removing this built-in limit shortly so you can get on with your project. :)

**Comment by johnwbaxter** [comment]
Hey @kjmartens ok cool, umm, how shortly is shortly? :)

**Comment by kjmartens** [comment]
How many characters do you likely need? :D We can change it now.

**Comment by johnwbaxter** [comment]
Well, we're using it to capture url's of people that come on the site, so the url's can be hella long with adword url params on them! A text field length would be adequate tbh :)

**Comment by kjmartens** [comment]
@johnwbaxter I've just set it to 5000 for now. You'll need to update to `dev-master` for Freeform version to try this out (our next release might be a few days away). Let me know if that resolves the issue for you. :)

**Comment by johnwbaxter** [comment]
@kjmartens Ok great thanks so much! I'll try that out :)

**Comment by johnwbaxter** [comment]
@kjmartens That has worked beautifully, thank you so much!!!

**Comment by kjmartens** [comment]
Perfect!
