### ISSUE TITLE
Migrating from 4x - 5x: Dynamic Recipient field doesn't have config / source carried over.

### ISSUE THREAD

**Issue by alexmillman23** [solspace/craft3-freeform#1532]
### What happened?

We have a dynamic_recipients field that is pointed toward an Entries source. When performing the migration from 4.1.x to 5.1.0, that config/source is not migrated over and the Dropdown field that it turns into has no options.

This also affects existing submissions since the previously filled out field no longer has values. So they're gone.

### How can we reproduce this?

1. On version 4.1.x, create a dynamic_recipients field type and assign to a form.
2. Set the source to an entries or similar
3. Update to 5.1.x and review the newly created Dropdown version of it not have its settings carried over

### Freeform Edition

Pro

### Freeform Version

5.1.3

### Craft Version

4.1.8

### When did this issue start?

After upgrading from older Freeform version

### Previous Freeform Version

4.1

**Comment by kjmartens** [comment]
Sorry for the delay and the trouble you experienced @alexmillman23.

I will have a developer check into this shortly. 🙂
