### ISSUE TITLE
Javascript Plugin Options: scrollToAnchor not disabling when false

### ISSUE THREAD

**Issue by EKBenI** [solspace/craft3-freeform#1535]
### What happened?

The scrollToAnchor value is set to false in the "freeform-ready" event's options object, but the viewport still scrolls to the top of the form.

![image](https://github.com/user-attachments/assets/15251d19-09ff-45da-9cdb-26c86313880f)

![image](https://github.com/user-attachments/assets/2bb65e1a-c6d4-4eed-91ad-5e8073800288)

https://www.loom.com/share/d5eddb67fcff4ca9bff9ec5fd0d117e6

### How can we reproduce this?

1. Add "freeform-ready" event listener per documentation.
2. Add scrollToAnchor property to options object.
3. Submit form

### Freeform Edition

Pro

### Freeform Version

5.5.10

### Craft Version

5.4.4

### When did this issue start?

Fresh install of Freeform

**Comment by kjmartens** [comment]
Hi @EKBenI,

If you include `event.options.autoScroll = false;`, does that give you the behavior you're looking for? 🙂

**Comment by EKBenI** [comment]
Hi @kjmartens, thanks - that appears to be working. It looks like the documentation just needs to be updated: https://docs.solspace.com/craft/freeform/v5/developer/js-plugin/#plugin-options

![image](https://github.com/user-attachments/assets/c04c2843-5359-40ba-820c-4fb85b0e45c9)

**Comment by kjmartens** [comment]
Docs will be updated shortly. 🙂
