### ISSUE TITLE
After updating to 3.11.x CSS & JS 404ing

### ISSUE THREAD

**Issue by alexjcollins** [solspace/craft3-freeform#154]
**Describe the bug or issue you're experiencing**
After updating to 3.11.x the CSS and JS started 404ing on the frontend.

We're loading our forms in via the form field on the entry with the following twig:

```
{{ craft.freeform.form(block.form.handle, {
    labelClass: "form-label",
    inputClass: "form-control",
    instructionsBelowField: true,
}).render() }}
```
(The name of our field in a matrix block is `form`)

We're currently mitigating the issue by rolling back to 3.10.11

**Steps to reproduce**

1. Select a form in an entry, via a freeform custom field
2. Load the form on the frontend 

**Expected behaviour**

The CSS and JS should load as per 3.10.x

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 3.6.16
- Freeform Version: 3.11.5
- Freeform Edition: PRO

**Comment by gustavs-gutmanis** [comment]
You probably have a server rule which serves all static files directly.  
With freeform 3.11.x we introduced a new way of serving scripts, which, unfortunately, doesn't work when the server is set to serve the files directly.  
To make this work for your setup, please open Freeform Settings, and under the `General` set the `Freeform script insert type` to `As files` and click save.

Sorry for the inconvenience.

**Comment by alexjcollins** [comment]
@gustavs-gutmanis Thanks for that. Not sure how I missed those settings, definitely looked through General to see if there was anything I was doing wrong. 🤷‍♂️

**Comment by icreatestuff** [comment]
Thanks @gustavs-gutmanis for pointing out that new setting. While I am now getting the CSS and JS resources from the `cpresources` folder as real files I'm still seeing in devtools that the `freeform/plugins.js` and `freeform/plugin.css` is still trying to be loaded and 404ing. I guess these are surplus to requirement now that the real files are loaded?

**Comment by gustavs-gutmanis** [comment]
That should not be happening, I'll try and reproduce it on my end. Thanks for reporting it.

**Comment by icreatestuff** [comment]
Just to further add to this, if I choose to load the `{{ craft.freeform.loadFreeformPlugin() }}` tag and have the 'Freeform script insert type' set to 'As Files', this isn't respected. The tag always seems to output files to the /freeform/plugin.js and /freeform/plugin.css endpoints rather than the files in /cpresources.

Is his a bug or the expected behaviour? Thanks
