### ISSUE TITLE
Dynamic recipient field issue - same email address in multiple options can cause multiple emails being sent.

### ISSUE THREAD

**Issue by wei2go** [solspace/craft3-freeform#155]
**Describe the bug or issue you're experiencing**
When using the "Dynamic recipients" field, if the same email address is set to multiple options, for example, ['General' => 'info@test.com', 'Change request' => 'request@test.com', 'Other' => 'info@test.com'] (also see in the screenshot here: https://drive.google.com/file/d/13OdFLybUeoMfi_PiSFf50vI7N4WA8H4d/view?usp=sharing), it will cause the following issues:
1. Freeform will send out multiple emails. In this example, it will send out two emails to info@test.com.
2. The email notification show the value of this field as all the options with the same email. In this example, it will show "General, Other".
3. If you try to choose one of the options as default, it chooses all with the same email. As shown in the screenshot.

**Steps to reproduce**

1. Create a dynamic recipient field.
2. Set multiple options, assign two of them the same email address as value.
3. Submit the form on the front end by choosing an option with this issue (e.g. "General" in the example mentioned above), and it will produce the issues.

**Expected behavior**
It is not uncommon that some organisations would want one email address to receive multiple topics of enquiries. It would be great if you can fix this issue, so:
1. The form only sends off one email, regardless of this email is set in multiple options or not.
2. The email notification should only show the user selected option, not all the options with the same email.
3. We should be able to choose only one option as default in CP.

**Craft & Plugin Info (please complete the following information):**

- Craft Version: Craft Pro 3.6.15
- Freeform Version: 3.11.4.1
- Freeform Edition: Pro
- Fresh Install or Upgrade: ? It was a fresh install in Craft 3 and yes we have been updating it.

**Additional context**

**Comment by gustavs-gutmanis** [comment]
Hi @wei2go,

Unfortunately this is a known issue. The emails are used as array values, so when you set the same email to the same value as another option, they're effectively the same option.  
What we can do, however, is make sure it gets sent out only once. We'll add this to our todo list for the upcoming release.

**Comment by wei2go** [comment]
Hi @gustavs-gutmanis , thanks for the prompt response.

It would be awesome if you can get it to send out only once.

Can issue 2 (the email notification template issue) also be tackled somehow?

**Comment by gustavs-gutmanis** [comment]
I'm sorry, what issue 2? Could you please elaborate?

Can your email server do the `+tag` notation? If you would set the emails to be `info+general@test.com` and the other to `info+other@test.com` would that work?  
I know several email servers support this.

**Comment by wei2go** [comment]
Hi @gustavs-gutmanis ,

Sorry for the confusion.

I meant the issue 2 I listed above:

"The email notification show the value of this field as all the options with the same email."

See the example of a submission below (the "Reason for Contacting Us" is the dynamic recipient field):
---
First Name: TEST
Last Name: TEST
Phone:
Email: test@test.com
Reason for Contacting Us: General, Other
Message: TEST, Please ignore

**Comment by gustavs-gutmanis** [comment]
Unfortunately, this drawback in the current implementation cannot be fixed without refactoring the way dynamic recipients work. We do have plans to address this soon, but I doubt you will want to wait that long.  
Meanwhile, would it be possible for you to try the `info+general@test.com` suggestion?

**Comment by wei2go** [comment]
> Unfortunately, this drawback in the current implementation cannot be fixed without refactoring the way dynamic recipients work. We do have plans to address this soon, but I doubt you will want to wait that long.
> Meanwhile, would it be possible for you to try the `info+general@test.com` suggestion?

Thanks for the suggestion. I think that may work. We will check with the email admins whether that's a valid email format on their end.
