### ISSUE TITLE
Stripe payment sets `receipt_email` to customer email, even if option is disabled in control panel.

### ISSUE THREAD

**Issue by croxton** [solspace/craft3-freeform#1550]
### What happened?

I have a Stripe payment form with the fields mapped as per screenshot below. I do not want Stripe to send a receipt to the customer and the 'Send success email from Stripe..' lightswitch is disabled in the integration settings. In the Stripe control panel itself email receipts are also disabled. Nonetheless, the `receipt_email` is always set and in LIVE mode triggers an email from Stripe to the customer (no email is sent in TEST mode).

<img width="1072" alt="Screenshot 2024-10-03 at 16 49 03" src="https://github.com/user-attachments/assets/6c9663b3-3fb7-40fd-8d9d-737e930ad798">

### How can we reproduce this?

1. Create a payment form using the Stripe integration, authorized with live keys.
2. Map fields as per screenshot above. 
3. Submit form.

### Freeform Edition

Pro

### Freeform Version

5.6.3

### Craft Version

5.4.6

### When did this issue start?

Unsure

**Comment by kjmartens** [comment]
Sorry about this @croxton. We'll check into this shortly. 🙂

**Comment by kjmartens** [comment]
This should now be resolved in Freeform 5.6.5+ 🙂
