### ISSUE TITLE
Form template attributes removed after submission and validation errors

### ISSUE THREAD

**Issue by alexmillman23** [solspace/craft3-freeform#1557]
### What happened?

If I'm rendering a form like:

```
{{ theFormToRender.render({
   attributes:{
      id: 'theid',
   }
}) }}
```

on the initial load I will get `<form id="theid">`

After the form is submitted (non-ajax) and returns back, the id (and all attributes) are stripped.

### How can we reproduce this?

1. Render a form with required fields
2. Set the attributes and add an ID or any attribute
3. Submit form without filling out required fields and inspect form for missing attributes

### Freeform Edition

Pro

### Freeform Version

5.6.3

### Craft Version

4.10

**Comment by seandelaney** [comment]
Hello @alexmillman23 

Are you using caching, and refreshing the hash, payload and CSRF token using some JS?

Also are you calling `form.registerContext` anywhere in your template?

**Comment by seandelaney** [comment]
@alexmillman23

I can see your full template, including any form related JS ?
