### ISSUE TITLE
"Network failed" download error when using Quick Export with CSV

### ISSUE THREAD

**Issue by martinhellwagner** [solspace/craft3-freeform#156]
**Describe the bug or issue you're experiencing**

We have a lot of forms on one of our Freeform Pro installs. All of them can be exported just fine in any format – except the one that has the most submissions and also the most spams. Strangely, the quick export only fails on our Live system, not on our Stage system – even though the two system are basically identical. Also, the quick export of this particular form as an Excel or TXT file is always successful – CSV or JSON fail, on the other hand.

**Steps to reproduce**

1. Try to quick export the form with the largest number of submissions / spams as CSV or JSON

**Expected behavior**

Quick Export of form should be successful, not produce a network error

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 3.5.19.1
- Freeform Version: 3.10.6
- Freeform Edition: Pro

**Additional context**

The download actually starts correctly, but then fails towards the end:

![Export 1](https://user-images.githubusercontent.com/19146752/120984406-ec571680-c77a-11eb-9e7b-c1e49793d874.png)

![Export 2](https://user-images.githubusercontent.com/19146752/120984423-ee20da00-c77a-11eb-8568-d4b06c8d6fbc.png)

**Comment by gustavs-gutmanis** [comment]
Hi @martinhellwagner,

Is the data being exported identical in both environments?  
Maybe production has some sort of timeout or limit set?

**Comment by martinhellwagner** [comment]
Yes, the exported data is exactly the same. Also, all PHP timeouts / limits are the same in both environments. The size of the CSV is around 5 MB (whereas the Excel and TXT files are smaller) – maybe that's the problem? Although 5 MB isn't that much, to be honest.

**Comment by gustavs-gutmanis** [comment]
You get to 3.9mb, which is maybe some kind of tipping point and a chunk of the file doesn't get sent? Seems very strange though.

**Comment by martinhellwagner** [comment]
I think the download actually even goes higher than 4 MB, but 3.9 MB was the last chance I had for a screenshot. But there's no pattern or explanation why or at which point the download fails. However, it fails both in Chrome and in Firefox.

**Comment by gustavs-gutmanis** [comment]
Well, it sounds a lot like a server problem, because it throws a network error...
Have you tried having a different person try it from a different network?

**Comment by martinhellwagner** [comment]
Yes, a client of ours reported the problem from their network, and I'm able to exactly reproduce it.
Is there anything regarding PHP or NGINX settings that I might be missing?

**Comment by gustavs-gutmanis** [comment]
I wouldn't know, this seems strange.

I found something that might point to this issue:  
https://stackoverflow.com/questions/1733306/nginx-errors-readv-and-recv-failed

**Comment by martinhellwagner** [comment]
Unfortunately, none of the solutions are applicable to us. We didn't enable to parameter `fastcgi_keep_conn`, and our requests & timeouts are set to rather high values. Also, the download sometimes fails after a second or two, so I don't think it'll ever run in a timeout.

**Comment by gustavs-gutmanis** [comment]
This is a very edge-case scenario, and I'm afraid we won't be of much help. This seems like a server issue, especially since you cannot reproduce this on other environments.

**Comment by martinhellwagner** [comment]
I'm guessing it is. I'll investigate some more. Thanks for the help though!
