### ISSUE TITLE
Notification template uses wrong language for translations when using the queue

### ISSUE THREAD

**Issue by WHITE-developer** [solspace/craft3-freeform#1572]
### What happened?

When sending the form notifications via the queue, translations in the notification template don't get the site language from where the submission is send parsed in, ending up with an untranslated/wrong translated email notification.

We use a separate queue runner to handle the queue. I also tested without that, then it seemed to use the language of the logged in user.

### How can we reproduce this?

1. Have a site in an other language than EN, in our case NL
2. Enable the setting "Use Queue for Email Notifications"
3. Use a notification template for a form with a translation string, eg. `{{ "blog_confirmation_thank_you_for_your_message"|t }}`
4. Make sure it is translated in NL but not in EN
5. Submit the form from the NL site
6. See the string not getting translated
![image](https://github.com/user-attachments/assets/aa55d98a-4587-45ca-b0e9-1be2413440fb)

### Freeform Edition

Pro

### Freeform Version

5.6.5

### Craft Version

4.12.6.1

### When did this issue start?

Unsure

### Previous Freeform Version

4.1.13

**Comment by gustavs-gutmanis** [comment]
Could you please elaborate on the "separate queue runner" please? It might be a key ingredient in solving this issue for you.

**Comment by WHITE-developer** [comment]
We use a docker container that runs `php craft queue/listen -v` in combination with the general config `->runQueueAutomatically(false)`

**Comment by gustavs-gutmanis** [comment]
Thanks for reporting this @WHITE-developer, it has been addressed and will be fixed in the upcoming version.

**Comment by kjmartens** [comment]
This is resolved in Freeform 5.6.6+ now. 🙂
