### ISSUE TITLE
Unknown attributes use behavior syntax

### ISSUE THREAD

**Issue by jannisborgers** [solspace/craft3-freeform#1575]
### What happened?

I thought I had the same issue as #1558 at first, so I’ll add this note here, maybe it’s useful for others, and maybe it should be fixed? 

The [behavior syntax](https://docs.solspace.com/craft/freeform/v5/templates/formatting/#behavior-syntax) also applies to _unknown_ attributes. What an unknown attribute is is not clearly stated in the docs. But this: 

```twig
{{ form.render({
  attributes: {
    "x-data": "form"
  }
}) }}
```

…when used with multiple instances of the same form, will result in:

```html
<!-- First instance -->
<form x-data="form" …>

<!-- Second instance -->
<form x-data="form form" …>
```

The **correct** way is this:

```twig
{{ form.render({
  attributes: {
    "=x-data": "form"
  }
}) }}
```

Beware the `=` in front of the attribute name 🫠

### How can we reproduce this?

See above

### Freeform Edition

Lite

### Freeform Version

5.6.5

### Craft Version

5.4.8

### When did this issue start?

Fresh install of Freeform

### Previous Freeform Version

5.6.4

**Comment by gustavs-gutmanis** [comment]
Hi @jannisborgers

Sorry if the docs aren't clear enough, we will update them to be more clear. This behavior syntax applies to any an all attributes that you pass in the form or field attributes.
