### ISSUE TITLE
Mailchimp contact tags don't get added to contact

### ISSUE THREAD

**Issue by curtishenson** [solspace/craft3-freeform#1576]
### What happened?

Having an issue where Mailchimp tags aren't being added to contacts using the integration.

Seems anything I try to put under "Contact Tags" doesn't get pushed to the contact. The basic setup would be a hidden input with a value(Website-Sign-Up) and synced under "Contact Tags". I've also tried just putting the value directly in Contact Tags.

The error log seems like it's trying to create a tag instead of adding the tag to the contact? This tag does exist already and is added to several other contacts. This started happening after updating to Freeform v5 and setting everything back up, it was working with the old v4 Mailchimp integration.

More info:
- The integration is authorized and working otherwise.
- I've tried with and without double opt-in
- Tried with "Append Tags on Update Instead of Overwriting" on and off

_Unrelated_: It looks like the [support form](https://docs.solspace.com/craft/freeform/support/) on the website isn't submitting.

### Errors and Stack Trace (if available)

```shell
Mailchimp: {"type":"https://mailchimp.com/developer/marketing/docs/errors/","title":"Bad Request","status":400,"detail":"Sorry, that tag already exists.","instance":"xxxxx"} {"integration":{"id":3,"handle":"mailchimp"}} []
```

### How can we reproduce this?

1. Setup Mailchimp integration
2. Add a hidden input with a value to a form
3. Map Contact Tags to the hidden field
4. On submission the mailchimp contact will not be tagged with the hidden input's value

### Freeform Edition

Pro

### Freeform Version

5.6.4

### Craft Version

4.12.5

### When did this issue start?

After upgrading from older Freeform version

### Previous Freeform Version

v4

**Comment by kjmartens** [comment]
Sorry for the delay and the trouble you're experiencing @curtishenson,

I have tried to duplicate this several ways and it always works correctly. Is this issue still happening? Are you able to provide more context such as an example of a tag name, and what happens if you create a new random one like `test`? 🙂

**Comment by curtishenson** [comment]
Yes the issue is still happening.

Tag name is `Website-Sign-up` and then also tested `test-website-sign-up`.

I tried a new tag and the first submission does work and gets tagged, adding a second email throws the error.

So my reproduction is probably missing a step where the mailchimp tag already needs to have been added to an email.

Also just tried creating an all new form and got the same behavior. Also updated to the 5.6.7

**Comment by kjmartens** [comment]
Sorry for the delay @curtishenson,

Is this issue still happening for you? I have tried testing this a number of ways and even used your tag names, etc. It always seems to work for me.

Is it possible to include a screenshot of what your Mailchimp configuration (in the form builder) looks like? And how are you setting the tag... in a hidden field, dropdown options, etc? 🙂

**Comment by curtishenson** [comment]
Yeah still happening. I've also tried just putting the tag right in the integration settings instead of a hidden field. Hope I'm just doing something wrong! Google only has 2 results for that error so...yeah.

Here's some screenshots:

<img width="1415" alt="Screenshot 2024-11-14 at 9 43 03 AM" src="https://github.com/user-attachments/assets/c988af95-9b9e-4311-abf3-480dca05d4e0">
<img width="1411" alt="Screenshot 2024-11-14 at 9 43 18 AM" src="https://github.com/user-attachments/assets/9bf9f644-9c18-473d-b71d-e6a49da55b5d">

**Comment by kjmartens** [comment]
Thanks for the additional information, @curtishenson.

I have played around with this in a wide variety of ways, using what appears to be the same setup as you. And each time, I cannot get it to fail. 🫤 

I'm curious about a couple things:

- Are you testing with the same email address over and over?
- Do you have anything configured inside of Mailchimp such as special rules or whatever, that might be causing this behavior? Perhaps something in the `Audience fields and *|MERGE|* tags` area or `Automations`?

If still no luck tracking this down, is it possible for you to send us a copy of your database (support@solspace.com) and reference this GH issue? We can have a developer review and see if they can troubleshoot the issue. 🙂

**Comment by curtishenson** [comment]
- Different email addresses. It is live in production and I can see the error on everyone that has signed up.
- Audience Fields look normal. First Name has a default value and Birthday has been added but that's it.
- 1 active automation that sends a birthday email and offer, then tags them. Don't think it runs on submission and these forms don't have a birthday field option.

I'll send the database, I'm all out of ideas.

**Comment by kjmartens** [comment]
Thanks @curtishenson. It's being reviewed by a developer. 🙂

**Comment by kjmartens** [comment]
We have done a thorough investigation of this issue and believe it is caused by the configuration of your Mailchimp account. We've updated Freeform (5.7.4+) to include additional error logging around Contact Tags, so hopefully that will help identify the issue. 🙂 

Unfortunately, we would need access to the Mailchimp account to investigate anything further.
