### ISSUE TITLE
Invisible and Hidden fields are not exported 

### ISSUE THREAD

**Issue by scandella** [solspace/craft3-freeform#1582]
### What happened?

When importing a form with some invisible and hidden fields, these fields are not imported (or exported, depending on your point of view).
I haven't checked the behavior for other fields.
Also, the submit button is not in sync.

### How can we reproduce this?

1. Export a form with some hidden and invisible field
2. Import the form
3. hidden and invisible fields are not imported

### Freeform Edition

Pro

### Freeform Version

5.6.6

### Craft Version

Craft Pro 4.12.7

**Comment by kjmartens** [comment]
Sorry for the trouble @scandella,

We'll get this fixed shortly. 🙂

**Comment by kjmartens** [comment]
This should now be resolved in Freeform 5.6.7. 🙂
