### ISSUE TITLE
PurgeUnfinalizedAssetsJob runs constantly

### ISSUE THREAD

**Issue by jaspertandy** [solspace/craft3-freeform#1590]
### What happened?

My queue is constantly filling up with PurgeUnfinalizedAssetsJob because it seems to get run during init:

https://github.com/solspace/craft-freeform/blob/a0da095a587af762d7e6aecfd685b8d1c512a3ed/packages/plugin/src/Freeform.php#L621

So when I'm looking at the queue, every time the queue polls, it hits init and adds another PurgeUnfinalizedAssetsJob. Is this intended behaviour? The same is also true of every CP asset that gets loaded, every other async request to an admin URL. There must be a way to disable this? If Freeform needs housekeeping to be done, I think it should be done on a cron but I don't think there's any way to configure it like that. The options in the download are all times, so I don't think I can set false or something.

### How can we reproduce this?

1. 
2. 
3. 

### Freeform Edition

Pro

### Freeform Version

5.6.6

### Craft Version

4.12.7

### When did this issue start?

After upgrading from older Freeform version

### Previous Freeform Version

unknown when this started happening

**Comment by gustavs-gutmanis** [comment]
Thanks for reporting this @jaspertandy,

Your concerns are very valid, we will improve this functionality.

**Comment by jaspertandy** [comment]
@gustavs-gutmanis thanks very much!

**Comment by gustavs-gutmanis** [comment]
Hey @jaspertandy,

When I was checking into this issue, I noticed that we're already allowing the generation of this Job once an hour at minimum, so the issue you're experiencing should not be happening. We're using Craft's cache to store a lock entry that prevents the execution of this thing when present.

Is your flow clearing the cache before executing jobs? If it is, we will need to implement a mechanism for running these as a cronjob for people who are comfortable with running cronjobs.

**Comment by jaspertandy** [comment]
Yep weird, it looks like what was probably happening the other day was this bit was failing: https://github.com/solspace/craft-freeform/blob/a0da095a587af762d7e6aecfd685b8d1c512a3ed/packages/plugin/src/Freeform.php#L627

Maybe my cache wasn't getting set properly or something. If it happens again, I at least know where to check first. Thanks for that and sorry for wasting your time. Please close this - I didn't just want to do it in case it affects any of your workflows.

**Comment by gustavs-gutmanis** [comment]
Thanks, hopefully that was a one-time thing, but if not, be sure to let us know.
