### ISSUE TITLE
Docs are returning 403 Forbidden

### ISSUE THREAD

**Issue by croxton** [solspace/craft3-freeform#1592]
### What happened?

When I try to view the Freeform docs I see a 403 Forbidden error:
https://docs.solspace.com/craft/freeform/

I tried a few VPN locations and it looks like it's blocked for everyone, not just me.

### How can we reproduce this?

1. Visit https://docs.solspace.com/craft/freeform/

### Freeform Edition

Pro

### Freeform Version

5.x

### Craft Version

5.x

**Comment by kjmartens** [comment]
Sorry about this @croxton. Thank you for bringing it to our attention.

We have resolved the issue now. 🙂
