### ISSUE TITLE
Submission doen't get send to all receipients because template mode is switched

### ISSUE THREAD

**Issue by WHITE-developer** [solspace/craft3-freeform#1594]
### What happened?

When a admin notification has multiple recipients, and you are using a files template, only the first sends out.
Seems that the template mode is switched to early here https://github.com/solspace/craft-freeform/blob/v5/packages/plugin/src/Services/MailerService.php#L151. Moving the switch outside the foreach works.

![image](https://github.com/user-attachments/assets/bf120497-eed4-4491-bf73-d6859d52d792)

### How can we reproduce this?

See above

### Freeform Edition

Pro

### Freeform Version

5.6.7

### Craft Version

Craft Pro 4.12.8

### When did this issue start?

After upgrading from older Freeform version, After upgrading from older Craft version

### Previous Freeform Version

4.x

**Comment by kjmartens** [comment]
Hi @WHITE-developer,

I tried testing this on my end, and I can't seem to get it to fail. I wonder if there's another factor here. I'll have a developer check into it and see what they think. 🙂

**Comment by WHITE-developer** [comment]
I'm also sending via the queue, maybe that's something.

**Comment by WHITE-developer** [comment]
@kjmartens any update on this?

**Comment by kjmartens** [comment]
Sorry for the delay @WHITE-developer.

I have queued this for a developer to check into shortly. I should likely have an update for you by tomorrow (Friday). 🙂

**Comment by kjmartens** [comment]
This should be resolved now in Freeform 5.7.0 🙂
