### ISSUE TITLE
Documentation Error

### ISSUE THREAD

**Issue by CreateSean** [solspace/craft3-freeform#1631]
### What happened?

On this page https://docs.solspace.com/craft/freeform/v5/setup/updating-freeform-4/ in the submit buttons section there's a link to **submit button customization** which goes to a 404 page https://docs.solspace.com/craft/freeform/v5/setup/templates/formatting/#submit-button-customization

Also here in github issues clicking submit a private issue also goes to a 404 page.

### How can we reproduce this?

1. 
2. 
3. 

### Freeform Edition

Lite

### Freeform Version

5.7.1

### Craft Version

4.12.8

### Previous Freeform Version

highest version 4

**Comment by kjmartens** [comment]
Sorry about that @CreateSean. It should be fixed now. 🙂
