### ISSUE TITLE
Error the new Pardot V5 Oauth integration posting data 400 error

### ISSUE THREAD

**Issue by payello** [solspace/craft3-freeform#166]
**Describe the bug or issue you're experiencing**

**Steps to reproduce**

1. Trying to integrate with the new Pardot V5 integration
2. Set up the integration in the admin/freeform/settings/crm/ and authorize it.
3. Add integration to form
4. Submit form in the freeform.log I get the message - `CRM Integration.ERROR:  {"exception":"Client error: `GET https://pi.pardot.com/api/prospect/version/4/do/create/email/peter@test.com` resulted in a `400 Bad Request` response:\n<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<rsp stat=\"fail\" version=\"1.0\">\n   <err code=\"4\">Invalid prospect email address</ (truncated...)\n"} []`
5. I can see that in the PardotV5 Integration Class - `pushObject` function the get request is hardcoded which needs to be a post call - line 161 - Solspace\Freeform\Integrations\CRM\PardotV5
`try {
            $response = $client->get(
                $endpoint,
                ['query' => $keyValueList]
            );`

            `$this->getHandler()->onAfterResponse($this, $response);

            return true;`

If I change the `$client->get` to `$client->post` it will work

**Expected behavior**
Data to post to Pardot API
**Craft & Plugin Info (please complete the following information):**

- Craft Version:  Craft Pro - 3.6.17
- Freeform Version: 3.11.7
- Freeform Edition: 
- Fresh Install or Upgrade:

**Additional context**
Anyway I can piggy back off the authentication with Pardot to make my own API calls? ie change the endpoints etc.

**Comment by gustavs-gutmanis** [comment]
Thanks for reporting this @payello!
It's been fixed and will be released in the next version.

**Comment by payello** [comment]
Thanks @gustavs-gutmanis - do you know when the next release will be?

**Comment by gustavs-gutmanis** [comment]
Hi @payello, the one containing the Pardot OAuth feature is already out in `3.11.8`.  
The OAuth functionality is in a new integration called `Pardot (v5)`, you will have to make a new integration using it for it to work.
