### ISSUE TITLE
Incorrect max length validation on text areas

### ISSUE THREAD

**Issue by LeonBatch** [solspace/craft3-freeform#1675]
### What happened?

Using a text area field, if you enter in the max amount of characters as specified within the freeform "Max Length" settings it correctly restricts you to the max length (1500 for example) however upon submission i get the following error:

Value must be no more than 1500 characters

I don't think it is accounting for new lines and special characters.

<img width="972" alt="Screen Shot 2024-12-10 at 3 45 50 PM" src="https://github.com/user-attachments/assets/7dfb0549-7599-47b6-ac6a-32d19f786fc9">
<img width="842" alt="Screen Shot 2024-12-10 at 3 46 00 PM" src="https://github.com/user-attachments/assets/ff8bdc15-af52-41e5-ab4e-541780fa2262">

### How can we reproduce this?

1. Create a text area field with a max length of 1500
2. Enter in 1500 characters on the front end and submit
3. See error

### Freeform Edition

Pro

### Freeform Version

5.6.8

### Craft Version

5.5.0.1

### When did this issue start?

Unsure

**Comment by kjmartens** [comment]
Thanks @LeonBatch,

We'll check into this and see what we can do. 🙂

**Comment by seandelaney** [comment]
@LeonBatch 

Line breaks, spaces and tabs all are counted as characters in PHP validation checks. The database will also count these as character too.

The error you get is correct.
