### ISSUE TITLE
Dropdown field numbers source doesn't respect last number setting

### ISSUE THREAD

**Issue by davidmbb** [solspace/craft3-freeform#1680]
### What happened?

When creating a dropdown field and using the predefined numbers setting, it takes into account the 'first number' value, but the last number is always 20.

### How can we reproduce this?

1. Add a dropdown with the numbers source
2. Set a last number value of anything
3. The result is always 20

### Freeform Edition

Pro

### Freeform Version

5.8.1

### Craft Version

5.5.5

**Comment by kjmartens** [comment]
I'm very sorry about this issue and the delay, @davidmbb.

I've fixed the issue now and it'll be available in the next release of Freeform (5.8.4). 🙂
