### ISSUE TITLE
Update docs for upgrading to freeform 5 RE customAttributes

### ISSUE THREAD

**Issue by iamtompickering** [solspace/craft3-freeform#1681]
### What happened?

Had to dive into the plugin files to figure it out, but we had a number of variables getting custom attributes e.g. `form.customAttributes.overrideValues['heading']` and it looks like this needs to be updated to `form.getProperties.get('overrideValues').heading`. 

Might be worth adding this to your key notes for upgrading. 

### How can we reproduce this?

1. Upgrade from Craft 4 > 5

### Freeform Edition

Pro

### Freeform Version

5.8.0

### Craft Version

5.5.5

### When did this issue start?

After upgrading from older Freeform version, After upgrading from older Craft version

**Comment by kjmartens** [comment]
I'm very sorry about this @iamtompickering.

I thought it was noted in there, but apparently not. We'll update the documentation. 🙂
