### ISSUE TITLE
Cacheable Forms CSRF Code Failing HoneyPot

### ISSUE THREAD

**Issue by accarpenter** [solspace/craft3-freeform#171]
**Describe the bug or issue you're experiencing**
I am unable to get the CSRF token code to work so I can use Cloudflare to entire cache web pages.

**Steps to reproduce**

```
{# I have this code in /dynamic/index.twig #}
{% set form = craft.freeform.form(craft.app.request.get('form')) %}
{{ {
    hash: form.hash,
    honeypot: craft.freeform.honeypot(form),
    csrf: {
        name: craft.app.config.general.csrfTokenName,
        value: craft.app.request.csrfToken,
    }
}|json_encode|raw }}
```

```
{# This code at the bottom of my scripts #}
<script>
    $(function () {
        // Find the corresponding Form
        var form = document.querySelector('form');

        $.ajax({
            // Specify the form handle in the GET parameters
            // ! Make sure to change the `myFormHandle` to your specific form handle.
            url: '/dynamic?form=contactForm',
            type: 'get',
            dataType: 'json',
            success: function (response) {
                // Update the Form Hash
                form.querySelector('input[name=formHash]').value = response.hash;

                // Update the JS Honeypot (ONLY when JS Enhancement setting is ON)
                var honeypot = response.honeypot;
                var honeypotInput = form.querySelector('input[name^="freeform_form_handle"]');
                honeypotInput.setAttribute('id', honeypot.name);
                honeypotInput.setAttribute('name', honeypot.name);
                honeypotInput.value = honeypot.hash;

                // Locate and update the CSRF input
                var csrf = response.csrf;
                form.querySelector('input[name=' + csrf.name + ']').value = csrf.value;
            },
        });
    });
</script>
```

```
{#And this code to render the form#}
{% set form = craft.freeform.form("contactForm") %}
{{ form.render }}
```

The first submit works.  And if I clear the cache one or more usually work.  All others fail the honeypot check and go to spam when using the same device.  If it is a new device then it gives the error Bad Request: Unable to verify your data submission.

**Expected behavior**

To submit the form as normal.

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 3.6.15
- Freeform Version: 3.11.4.1
- Freeform Edition: Lite
- Fresh Install or Upgrade: Fresh

**Additional context**

I have needed to do this for multiple sites but haven't been able to get it to work on any.  
I am using Cache Level: Bypass for *domain.com/dynamic/*

**Comment by kjmartens** [comment]
Would you be able to try setting the rule for: `domain.com/dynamic/*` (with wildcard)? :)

I spoke with another developer with more experience with CloudFlare, and he suggests that you try running a test against those URLs to see if CF is actually bypassing the URL path indicated.

This can be run in the CLI, like Terminal on Mac:
`curl -svo /dev/null http://www.example.com/dynamic/something`

For the `CF-Cache` header, if you see `HIT` then CF is caching the dynamic URL. If you see `BYPASS`, then things are working correctly on that point.

You could also load Chrome and in the dev tools, look at the headers of a request to that dynamic URL.

**Comment by accarpenter** [comment]
I have tried every possible combination of the settings rules I can think of, including exact urls.  Both dynamic?form=contactForm ad ?form=contactForm always show as either DYNAMIC, HIT, or MISS, and never as BYPASS as needed.

I am also using a cloudflare rule to bypass domain.com/admin/* and that is working.

If I don't include header code below then it won't cache everything on the page because the Craft default seems to be no-store, no-cache, must-revalidate.  Could something in the header code be override the rule and telling it to cache all requests?  Or is there a way to add those headers to that directory?  

```
{% set expiry = now|date_modify('+30 days') %}

{% header "Cache-Control: public, max-age=" ~ expiry.timestamp %}
{% header "Pragma: cache" %}
{% header "Expires: " ~ expiry|date('D, d M Y H:i:s', 'GMT') ~ " GMT" %}
```

**Comment by kjmartens** [comment]
For anyone else with this issue, it happened to be an issue with where the 'dynamic' folder was located. The 'dynamic' folder needed to be inside the Craft `templates` folder so that the twig code would be parsed, rather than inside the webroot where it would be treated as a regular Linux folder. 🙂
