### ISSUE TITLE
freeform_lock table performance issues

### ISSUE THREAD

**Issue by piotrpog** [solspace/craft3-freeform#176]
I am aware that there was recently some kind of fix for performance with this table, but i still have these. Here's screenshot from profilin tab of debug toolbar:

![image](https://user-images.githubusercontent.com/42622545/125808849-92120330-1057-47e5-aac0-b2a7da21b4ad.png)

These lags dont pop up all the time, just once per 10 requests maybe. My freeform version is 3.11.9. System info:

PHP version | 7.4.7

Linux 4.4.254.core2.263
MySQL 5.7.28
Imagick 3.4.4 (ImageMagick 6.8.9-9)
Craft Pro 3.6.14

**Comment by gustavs-gutmanis** [comment]
This was addressed in [this commit](https://github.com/solspace/craft3-freeform/commit/cea8b2dd1d0d6f9f678e506347616e040107b211).  
It's in `v3.11.9`

**Comment by gustavs-gutmanis** [comment]
I just noticed that you said you're already on `v3.11.9`  
Very strange. Can you do an ``EXPLAIN DELETE FROM `freeform_lock` WHERE `dateCreated` = '2021-07-08 14:00:00'`` so that we know your DB has the correct keys and is using them?

**Comment by gustavs-gutmanis** [comment]
@piotrpog are you able to run the explain query, please?
