### ISSUE TITLE
[Multipage payment form] Can't go back to the previous page

### ISSUE THREAD

**Issue by umkasanki** [solspace/craft3-freeform#177]
**Describe the bug or issue you're experiencing**

Can't go back to the previous page from last step of payment form if card data is not filled.

https://user-images.githubusercontent.com/496132/126148809-9b31e29c-c891-4ebc-94fb-59f9407b3c89.mp4

**Steps to reproduce**

1. Add multipage payment form
2. Go to payment page
3. Try to return to previous page without filling payment info.

**Expected behavior**
Go to previous page

**Craft & Plugin Info (please complete the following information):**

- Craft Version: Craft Pro 3.6.16
- Freeform Version: 3.11.9
- Freeform Edition: Pro
- Fresh Install or Upgrade: Fresh

**Additional context**

**Comment by kjmartens** [comment]
This is resolved now in v3.11.10 :)
