### ISSUE TITLE
Error notifications in multipage forms

### ISSUE THREAD

**Issue by umkasanki** [solspace/craft3-freeform#179]
**Describe the bug or issue you're experiencing**
Error notifications in multi-page forms are deleted when the field is filled only on the 1st page of the form.

https://user-images.githubusercontent.com/496132/127310580-c14563ff-dc95-4e4c-8e9e-d757f04046c3.mp4

**Steps to reproduce**

1. Add multipage ajax form
2. Make some fields required
3. Try to submit empty form
4. Fill required fields

**Expected behavior**
The error notification under the field should disappear when the error is corrected

**Craft & Plugin Info (please complete the following information):**

-  Craft Version: Pro 3.7.5
-  Freeform Version: 3.11.10
-  Freeform Edition: Pro
-  Fresh Install or Upgrade: Fresh

**Additional context**

**Comment by gustavs-gutmanis** [comment]
Thanks @umkasanki for reporting this, very good catch. We'll get on it.
