### ISSUE TITLE
"Use custom values" for drop downs unexpected behavior

### ISSUE THREAD

**Issue by knynkwl** [solspace/craft3-freeform#184]
**Describe the bug or issue you're experiencing**
![Screen Recording 2021-08-02 at 9 06 05 AM](https://user-images.githubusercontent.com/4225771/127867321-bf11fc99-838d-4895-81b7-242bbdeaff10.gif)

**Steps to reproduce**
1. Add custom values in dropdown
2. click "Use custom values"

**Expected behavior**

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 3.7.5
- Freeform Version: 3.11.10
- Freeform Edition: Pro
- Fresh Install or Upgrade: Fresh

**Additional context**

**Comment by siebird** [comment]
Not sure if it's related, but one thing that has always bothered me with custom values in FreeForm is that it does not follow Craft's native camelCasing for values. For example, when using the element connections the field values need to match and going through and camelCasing values is cumbersome.

**Comment by kjmartens** [comment]
@knynkwl I am using Craft 3.7.7 now and can't duplicate this issue (where it seems like unchecking that checkbox just stays checked and resets values). I also tested in Chrome and Safari on macOS. I'm curious which browser and version you are using. :)

@siebird I've made a note about that and we'll probably adjust the behavior in an upcoming version. :)

**Comment by knynkwl** [comment]
@kjmartens I am using Brave, but it's built off chromium so should behave the same as chrome.

**Comment by kjmartens** [comment]
@knynkwl would you be able to try out Chrome and see if it makes a difference? And also try upgrading to Craft 3.7.7 as well? :)
