### ISSUE TITLE
Salesforce Lead now requires oAuth2 Token

### ISSUE THREAD

**Issue by pseudoclass** [solspace/craft3-freeform#192]
**Describe the bug or issue you're experiencing**
As of August 10th it appears Salesforce Lead now requires an oAuth token to connect integrations. As a result, the Salesforce Lead CRM integration cannot authorise with Salesforce:

![Screenshot 2021-08-23 at 21 47 32](https://user-images.githubusercontent.com/1387821/130510718-81615964-3188-4687-bfba-9b0f6eaba9b9.png)

The error logs display :

{"error":"invalid_grant","error_description":"authentication failure"} {"exception":"Client error: `POST https://login.salesforce.com/services/oauth2/token` resulted in a `400 Bad Request` response:\n{\"error\":\"invalid_grant\",\"error_description\":\"authentication failure\"}\n"} []

**Steps to reproduce**

1. Setup a Salesforce Lead CRM integration in Freeform including the Client ID, Client Secret, Username, and Password fields provided.
2. Return to the Salesforce Lead CRM integration you just created to check if it has authorized
3. "Not able to authorize" message is displayed

**Expected behavior**
1. There should be a new field for the oAuth key required by Salesforce included in the CRM integration form
2. Submitting this data should prevent the integration from failing to authorize

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 3.7.6
- Freeform Version: 3.11.10
- Freeform Edition: Pro
- Fresh Install or Upgrade: Upgrade

**Additional context**

**Comment by kjmartens** [comment]
Sorry for the trouble @pseudoclass. I am noticing an issue on my site now too. We'll look into this ASAP and see what the issue might be.

**Comment by kjmartens** [comment]
@pseudoclass Can you try adding the integration on Freeform's side again? I waited a while because sometimes it could take up to 10 minutes before the integration "app" can be used. I guess I didn't wait long enough the first time. I tried again now and it worked for me. Perhaps this is the same issue you're experiencing. :)

**Comment by pseudoclass** [comment]
Hello @kjmartens , I tried removing and adding the integration again however it will not let me save it now:

![Screenshot 2021-08-24 at 16 00 10](https://user-images.githubusercontent.com/1387821/130630367-9ad34bd2-7360-4898-a2b7-9c0a55df623f.png)
