### ISSUE TITLE
Honeypot Failure

### ISSUE THREAD

**Issue by ambidustrious** [solspace/craft3-freeform#199]
I have some forms that are completed daily by the same user. These are legitimate support requests. The honeypot is failing for many of them. I am caching the forms, but I use JS to update the honeypot fields as documented. This is working correctly.  I'm wondering if the field might be getting updated with a browser autocomplete feature. I don't see anything in the rendered code that prevents autocomplete. Any thoughts?

Thanks

**Craft & Plugin Info (please complete the following information):**

- Craft Version: Craft CMS 3.7.10
- Freeform Version: 3.11.10
- Freeform Edition: Pro
- Fresh Install or Upgrade: Fresh Install June 2021

**Comment by kjmartens** [comment]
Sorry for the trouble @ambidustrious. I'm curious to know what kind of volume you're dealing with here... how often is it happening? E.g. 10 out of every 100, etc?

Also, is there a chance that this form might also be in a different template somewhere else (e.g. a page footer) that is cached without being refreshed? If you're not 100% sure if this form is being used elsewhere (or maybe you are sure it is, but not sure if one instance is failing and others aren't), one thing you could consider trying is including a Hidden field in the layout and and using the `overrideValues` parameter to feed it the current URL:

```
overrideValues: {
  yourCurrentUrlField: url(craft.app.request.pathInfo),
}
```

**Comment by ambidustrious** [comment]
volume wise... it's about 1 out of 5. I added autocomplete="false" to the honeypot. (This should typically be "off", but there's documentation to suggest "false"  makes chrome obey). 

Since I've done this, the problem seems to have disappeared - it's yet to be determined if this will impact spam prevention site wide...  

I'll keep an eye on it and perhaps try adding the hidden field - but i'm not sure it will work as the path is the same for every user on this particular form

**Comment by kjmartens** [comment]
We're going to add `autocomplete="off"` to the honeypot field in an upcoming release of Freeform, so hopefully that will resolve the issue for you and others experiencing it. :)
