### ISSUE TITLE
Dutch translations not coming through

### ISSUE THREAD

**Issue by riasvdv** [solspace/craft3-freeform#20]
So the Dutch translation files have been added, but they're not actually being applied. 

![afbeelding](https://user-images.githubusercontent.com/3626559/36251292-fab78b9e-1240-11e8-97f9-835daa8f5d91.png)

As you can see in the screenshot, the sidebar is Dutch, but nothing from the plugin is in Dutch.

**Comment by kjmartens** [comment]
Unfortunately the Composer interface is currently not translatable. This is because it's all based heavily in JS. It'll be a lot of work, but a future version will likely have this available. :)
