### ISSUE TITLE
Loading submission index pages takes very long

### ISSUE THREAD

**Issue by nilsenpaul** [solspace/craft3-freeform#200]
**Describe the bug or issue you're experiencing**
Whenever I try to load the submission page for a form with only 80-something submissions, it takes up to 35 seconds to load. Other admin interactions (entry index pages with a lot more entries, for example) are just fine.
The only difference (we can think of) between these forms and other forms we created before, is the amount of fields in the form (35), and the fact that the form has 3 file fields.

**Steps to reproduce**

1. Create a form with 35 fields (input, dropdown and file fields, in our case)
2. Create 80 submissions
3. Load the index page

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 3.7.13
- Freeform Version: 3.11.10
- Freeform Edition: Pro

**Comment by kjmartens** [comment]
Sorry for the trouble @nilsenpaul. Can you confirm if this is only happening when viewing this 1 form set? Or is it happening when viewing any form's submissions? Anything "special" about this form (e.g. uses Conditional Rules, Stripe Payments, etc)? 🙂

**Comment by nilsenpaul** [comment]
Kelsey,

This is only happening (or seems to be worst) with two forms (of the 8 forms on the site). What sets these forms apart from the other forms on the site, is the number of form fields, and the fact that they each have 3 file fields. If it makes it easier for you to debug this issue, we could schedule a meeting so I can show you what's happening?

**Comment by kjmartens** [comment]
I've never heard of an issue like this before. I have a test form with around 50 fields and it loads no different than my other forms. I'm curious if there's anything else at play here... are you able to send a screenshot(s) of what the form layout looks like in the form builder? Perhaps there's a specific field type that plays into this more.

Another test you could try would be creating a brand new test form and assigning those 3 file upload fields to it and see if that causes any issues when loading that form (with a few submissions of course).

And finally, can you try clearing browser cache and opening up the Network table of the developer console and watch the loading of the page happen. I imagine if you have lots of image file thumbnails to load, some kind of slow down may be inevitable. 35 seconds is still very long, but if you told me there were 40 images for each submission being loaded, it could change that. And regardless of that, perhaps there are 1 or more files that somehow don't have a proper reduced thumbnail generated and the slowdown is there... the Network -> Images tab would show this clearly. :)

**Comment by nilsenpaul** [comment]
See https://www.dropbox.com/t/p19SqT9ito7k6I4U for a screen capture of the form configuration.

- A new form with 3 file fields and some submissions doesn't have the delays.
- It's the `index.php?p=admin/actions/element-indexes/get-elements` request that takes ~35s. No images are uploaded, it's all PDF's/docx/excel files:

<img width="548" alt="Schermafbeelding 2021-09-16 om 10 01 52" src="https://user-images.githubusercontent.com/6794819/133574342-d8e57ea6-82d6-400e-ac23-88825d7c643e.png">
<img width="548" alt="Schermafbeelding 2021-09-16 om 10 01 29" src="https://user-images.githubusercontent.com/6794819/133574353-7e441f5f-b652-4c19-b0c1-a87f63e49084.png">

**Comment by kjmartens** [comment]
Thanks for the additional information. I'm wondering if you can provide us with server environment specs... like PHP version, MySQL/PostgreSQL, etc. And can you confirm if this is a recent fresh install, or if it has a longer history of updates (and which the first version installed likely was)? :)

**Comment by nilsenpaul** [comment]
PHP 8.0, MariaDB 10.1.48.

This website was first built in July of 2019 and has been updated ever since.

**Comment by kjmartens** [comment]
@nilsenpaul I'm wondering if you might be able to provide a slow query log for us? That would hopefully narrow things down for us quite a bit. 🙂 

https://mariadb.com/kb/en/slow-query-log-overview/

**Comment by nilsenpaul** [comment]
Kelsey, slow query log does not log any slow queries in this case.
After diving into the source, I found that _just_ before the element query gets executed [here](https://github.com/craftcms/cms/blob/2c1ab17e7e41194b2f5b040944c93aab08fee15b/src/base/Element.php#L789), I can print the SQL in just milliseconds. No delays. Executing the sql itself in MySQL takes just milliseconds. If I, however, let Craft execute the `$elementQuery->all()` part, it takes more than 30 seconds. So my assumption would be that it's not the sql that takes this much time, it's populating the elements (things Craft does, or things the plugin does while populating). Does this information help you at all?

Again, if it helps you to take over the wheel and Zoom your way to a solution ... be my guest.

**Comment by angrybrad** [comment]
@nilsenpaul Can you enable the debug toolbar, load the element index page, open the debug toolbar, then select the dropdown for the past 10 requests. Find the POST request for the call to `get-elements`, then click the database tab and sort the queries by the execution duration descending. What's the longest query execution time there?

**Comment by nilsenpaul** [comment]
HI @angrybrad, thanks for jumping in! 

Never knew that that was possible with the debug toolbar, thanks!
Now, there are no slow queries in the query log, but using the `timeline` I get this:

<img width="1379" alt="Schermafbeelding 2021-10-07 om 19 54 49" src="https://user-images.githubusercontent.com/6794819/136438038-f1440724-3749-4039-b383-46d51fdf1946.png">

So, that's ~45 fast queries, then ~30 seconds of nothing (query-wise), than 2 more short queries. Does this help ... at all?

**Comment by kjmartens** [comment]
You can create a support ticket or email directly at support@solspace.com 🙂
