### ISSUE TITLE
Client account cannot view submissions on Freeform Lite with Craft Client License

### ISSUE THREAD

**Issue by onebrightlight** [solspace/craft3-freeform#21]
Set up a system that works perfectly for my admin account, but when I try to access submissions with the **Client** account, I get a double `An unknown error occurred.` message at the top. They have permissions to access everything in the CP as far as the settings will allow, and they can create/modify forms, just aren't able to see the results.

I’m running Craft CMS 3.0.0-RC10.1
and Freeform Lite v2.0.0-beta.9

**Comment by kjmartens** [comment]
Thanks for reporting this. I can duplicate this as well. We'll get this fixed for the next release :)

**Comment by kjmartens** [comment]
This should now be resolved in 2.0.0-beta.10
