### ISSUE TITLE
Select fields in form prevents form from saving

### ISSUE THREAD

**Issue by ishetnogferre** [solspace/craft3-freeform#210]
**Describe the bug or issue you're experiencing**

**Steps to reproduce**

1. Open a form with a select field
2. Don't know if it's something but in this case the select field gets focus immediately without user action (see screenshot), other forms require user action before a field is focused.
3. Save the form either without changing something or after changing something
4.  Error "The request response is empty"

**Expected behavior**

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 3.5.16 (pro)
- Freeform Version: 3.11.11.1
- Freeform Edition: Pro
- Fresh Install or Upgrade: Upgrade

**Additional context**
![Screenshot 2021-10-08 at 15 51 22](https://user-images.githubusercontent.com/6649706/136569277-849a0770-746f-4734-bec0-49d3591f2898.png)
![Screenshot 2021-10-08 at 15 51 39](https://user-images.githubusercontent.com/6649706/136569279-40920f4c-cd5d-4d3c-aa3e-82e5cf660e38.png)
![Screenshot 2021-10-08 at 15 51 15](https://user-images.githubusercontent.com/6649706/136569275-7682597b-a9b7-41a6-a3fd-762543d7bcc1.png)

**Comment by kjmartens** [comment]
Sorry for the trouble you're experiencing @ishetnogferre. I haven't heard of this kind of issue happening before, but I wonder if it has something to do with the values you have set for the field. Can you send us a screenshot of what those values are? And if there's anything "irregular" about them out of sight from screenshot (such as tons of options, super long values, special characters, etc), please let us know. :)

**Comment by ishetnogferre** [comment]
@kjmartens thanks for your quick reply!

I did try the steps from the Common Issue guide, but this didn't fix it. Also, **forms without Select fields can be saved**, those with Select fields can't.

**Comment by kjmartens** [comment]
Can you let me know what the Select field contains for options? And if you try adding another Select field that just contains very simple values without special characters, etc, does it save?

**Comment by ishetnogferre** [comment]
We see this behaviour in multiple forms. The Select Fields we use are those with "predefined valued" like years (2021 - 1990) or numbers (0-10).

Attached is one of those fields. When I delete the Select Field, the form can be saved. When re-added completely from scratch we get the same error again.

<img width="310" alt="Screenshot 2021-10-10 at 11 33 40" src="https://user-images.githubusercontent.com/6649706/136690449-f9415e24-2b70-4b0d-9945-0bdc902f23c1.png">

**Comment by kjmartens** [comment]
Would you be able to send us what is in the "Headers" tab of the "Network" tab? Also, do you have any idea if you have any aggressive security settings enabled on your server such as ModSecurity / SQL injection detection? The only known issue we have seen of this in the past has had to do with aggressive security settings (though it typically was triggered on HTML fields, etc).

**Comment by ishetnogferre** [comment]
@kjmartens We had a "sql injection" activated, but even when disabled, we still have the same error.
The "Headers" tab has the following data in it:
<img width="404" alt="Screenshot 2021-10-21 at 10 22 32" src="https://user-images.githubusercontent.com/6649706/138239943-2cfa5181-8c61-49bc-8681-f2e017a9ccb7.png">
<img width="1033" alt="Screenshot 2021-10-21 at 10 22 43" src="https://user-images.githubusercontent.com/6649706/138239948-1eb8ac2b-b43d-4887-822b-07dae4793ad9.png">
<img width="1035" alt="Screenshot 2021-10-21 at 10 22 51" src="https://user-images.githubusercontent.com/6649706/138239952-c182ad6f-9306-4a16-b2ef-4442a5597f2b.png">

**Comment by Stevenlitton** [comment]
@kjmartens Hi, could I ask how this was resolved? I have this exact issue and no matter how many select fields I delete and re-create, I just can't get the form to save. The plugin works great apart from not being able to use select fields, it's a very odd error.
