### ISSUE TITLE
Empty Value Returned for Checkbox Using GraphQL

### ISSUE THREAD

**Issue by sarahschuetz** [solspace/craft3-freeform#212]
When using the following query:
```
... on FreeformField_Checkbox {
    value
    checked
}
```
... the **value is empty** if the checkbox is not checked by default. If "Check by default" is true the correct value is returned.

**Expected behavior:**
The correct value is returned regardless if the checkbox is checked by default or not.

**Craft & Plugin Info (please complete the following information):**

- Craft Version: Craft CMS 3.6.11.2
- Freeform Version: 3.11.5
- Freeform Edition: Lite

**Comment by kjmartens** [comment]
Sorry for the trouble @sarahschuetz. We'll add support for this sometime next week. :)

**Comment by kjmartens** [comment]
Just wanted to see if this issue was still happening for you. We checked into it today and are unable to reproduce the issue on our end... 🙂
