### ISSUE TITLE
User not created if no User Group has been chosen

### ISSUE THREAD

**Issue by johndwells** [solspace/craft3-freeform#219]
I have a freeform form that we use for user registration. So we have fields set up and then under "Element Connections" we have set Type to "Users". Previously we've always had a user group checked, and this has worked fine. But now we're making some changes and do **not** want to assign new users to a group.

However it appears that when no user group is selected, the user is never created. The submission saves fine, but no new user is created in the backend.

**Steps to reproduce**

1. Create form with email address minimum
2. Set up an "Element Connection" mapping to a User
3. Do not select any member group
4. Set user to be activated automatically
5. Render form on front end
6. Submit form with new user info

**Expected behavior**

After a successful form submission, a new user should be created.

**Craft & Plugin Info:**

- Craft Version: 3.7.16
- Freeform Version: 3.11.11.1
- Freeform Edition: Pro
- Fresh Install or Upgrade: Fresh Install

**Comment by kjmartens** [comment]
Thanks for the thorough report, @johndwells.  I can duplicate this in my testing as well.

Sorry for the trouble! We'll get this fixed soon. :)

**Comment by kjmartens** [comment]
This is now fixed in 3.11.13 🙂
