### ISSUE TITLE
Custom select values are reset by any keystroke in the label field

### ISSUE THREAD

**Issue by ben-at-sahmri** [solspace/craft3-freeform#227]
When editing a `Select` field which uses custom values, any keystroke in the _Label_ column field causes the _Value_ field to be recreated from the label value, overwriting the existing custom value. This happens even when the keystroke is not changing the value (I discovered it while copy+pasting the labels out of the form: CMD+A, CMD+C trigger the bug).

**Steps to reproduce**

1. Create a new field of type select (doesn't need to be saved)
2. Enable 'Custom values'
3. Add a row
4. Enter some Label text, then a custom Value
5. Click back into the label text and hit CMD+A to select all, then CMD+C to copy
6. Observe that the custom value is overwritten with the label text

**Expected behavior**

* Already set custom values should not be over-written when the label is changed.
* Non-keystroke characters shouldn't trigger the value generation

**Craft & Plugin Info:**

- Craft Version: 3.7.11
- Freeform Version: 3.11.10
- Freeform Edition: Pro (Trial)
- Fresh Install or Upgrade: Fresh install

**Comment by kjmartens** [comment]
We've adjusted Freeform 3.12.3+ to no longer change the value when pressing non-alphanumeric keys keystrokes such as `⌘ + C`.  🙂
