### ISSUE TITLE
French translation

### ISSUE THREAD

**Issue by rtrudel** [solspace/craft3-freeform#23]
I would like to translate (at least) error messages for the form validation. I used the recommended way for Craft 3 to do it, by creation a folder craft/translations/fr and by adding the "plugin-handle.php" (so craft3-freeform.php) but it seems that is not working. Am I doing it wrong?

Note: I also tried to add directly in vendors/solspace/craft3-freeform/translations/fr.php", no success there either.

**Comment by kjmartens** [comment]
I can duplicate that translations don't seem to be having an effect on Freeform. We'll look into this issue.

And a side note... the `plugin-handle.php` would actually need to be `freeform.php`. :)

**Comment by rtrudel** [comment]
It worked "partially" by renaming `freemform.php`, but many messages seems missing in the translation file.
In my case, this outputs now french:
`"This field is required" => "Ce champ est requis",`

but those are not found in the file:
_"Value must be numeric"_, _"There was an error submitting this form"_, etc.

**Comment by kjmartens** [comment]
It's very likely we may have missed some language strings in the translation file, but we'll make sure we add them in for next release.

In the meantime, you can likely just add those in manually. :)

**Comment by rtrudel** [comment]
As the dutch is included along the plugin, I understand the NL package is not complete either? Once corrected, I can provide you the french translation if you want it.

**Comment by kjmartens** [comment]
Sorry for the long delay on this one. I think things should be mostly sorted out now if you want to give it another look. :)
