### ISSUE TITLE
Error editing a form with a multi-select mapped to categories

### ISSUE THREAD

**Issue by anchovy** [solspace/craft3-freeform#230]
**Describe the bug or issue you're experiencing**
When editing a entry with a multi-select field mapped to a category field in the entry we get the error:

_Object of class craft\elements\db\CategoryQuery could not be converted to int in /Users/benjaminsims/Sites/nzda-craft/vendor/solspace/craft-freeform/packages/plugin/src/Services/FieldsService.php at line 454

**Steps to reproduce**

1. Add a multi-select field to a form; source: Categories.
2. Add Element Connection to an entry.
3. Map field from step 1 above to a category field in the entry.
4. complete an initial submission.
5. check data is recorded in the enty.
6. Set the `elementId` in the form so that it loads the entry from step 4 above.
7. load the page - you'll see the error.

**Expected behavior**
The form should load and the previously selected categories should be selected, along with the other form fields.

**Craft & Plugin Info (please complete the following information):**

- Craft Version: Craft Pro 3.7.20
- Freeform Version: 3.11.12
- Freeform Edition: craft
- Fresh Install or Upgrade: general use

**Additional context**

**Comment by anchovy** [comment]
@kjmartens - this is a blocking issue, do you know when you'll be able to look at this?

p.s. Double checked and there are no issues with editing an entry that has a single select field mapped to a category.

**Comment by anchovy** [comment]
Actually - it works when the field that the select is mapped to is a plain text field, storing the category id as a text value.

**Comment by kjmartens** [comment]
Sorry for the delay. I can duplicate this in my testing as well and appears to affect any Craft relation field type that is mapped to a Freeform multi-option field type. I wonder if something in Craft changed recently. At any rate, I'll have our developer check into this shortly. 🙂

**Comment by kjmartens** [comment]
This has been fixed in Freeform 3.12 now. 🙂
