### ISSUE TITLE
AJAX form fails with "Column not found: 1054 Unknown column 'field_34' in 'field list'

### ISSUE THREAD

**Issue by ben-at-sahmri** [solspace/craft3-freeform#231]
Hi,

I'm having trouble with a form submission which has previously worked. This is a multi-page form with a Stripe credit card form on the last page. 

When submitted, the payment processing works, but the `Submission#afterSave` method fails with the error: 

```
Exception (Database Exception) 'yii\\db\\Exception' with message 'SQLSTATE[42S22]: 
Column not found: 1054 Unknown column 'field_34' in 'field list'

The SQL being executed was: INSERT INTO `freeform_submissions` (
`formId`, `statusId`, `incrementalId`, `token`, `ip`, `isSpam`, `field_37`, `field_34`, `field_35`, `field_33`, `field_25`, `field_24`, `field_26`, `field_23`, `field_20`, `field_29`, `field_30`, `field_28`, `field_21`, `field_22`, `field_27`, `field_36`, `field_31`, `field_14`, `id`, `dateCreated`, `dateUpdated`, `uid`
) 
VALUES (
3, 2, 19, ... (more)
)
```

**Steps to reproduce**

1. Create a multi-page form with Stripe integration, with the amount set in a hidden field.
2. Fill in and submit the form
3. Observe the AJAX request come back with the 500 error.

**Expected behavior**

The "form success" message should be shown on successful submission.

**Craft & Plugin Info (please complete the following information):**

- Craft Version: Craft Pro 3.7.17.2
- Freeform Version: 3.11.11.1
- Freeform Edition: Pro (Trial) 
- Fresh Install or Upgrade: Fresh

**Additional context**

Looking at the values, `field_34` looks like it refers(referred?) to a hidden field (actually the amount to be processed via Square), and the column `field_34` does not exist in the `freeform_submissions` table in the DB.

The `afterSave` method is adding the data from `$this->storedFieldValues` to the insert statement - which presumably includes the field mapping. Can you tell me where this draws its data from, and if there's anything I can do to update/refresh it?

We've done some re-work of the field structure, including renaming that field, and have also tried removing and recreating the field on the hunch there's some id/name mapping being cached somewhere, but the behaviour persists.

**Comment by anchovy** [comment]
Have you got a row in `freeform_fields` with the id 34 and/or can you view/edit the field in the cp `http://you.site.com/admin/freeform/fields/33`

I had this issue after some form changes - the row did exist in `freeform_fields` but not as a column in `freeform_submissions` - so I manually added the column to the db and it worked like a treat.

**Comment by kjmartens** [comment]
@ben-at-sahmri, as @anchovy mentions, it's possible that you might be missing the database column for field ID "34" in your `freeform_submissions` database table. Not sure how it might go missing, but if it is, you can manually re-add it to the database. Just be sure the **Field** value is set to `field_34`, **Type** is `VARCHAR`... **Length** can be something like `100`.
