### ISSUE TITLE
Issues with form submission after updating to 3.12 ("Form has expired")

### ISSUE THREAD

**Issue by akselikap** [solspace/craft3-freeform#236]
**Describe the bug or issue you're experiencing**

First submission of any form fails with "Form has expired". The 2nd submission try works.

**Steps to reproduce**

1. Fill out any form.
2. Submit it and get an error "Form has expired"
3. Submit it again and it works.

**Expected behavior**

It should work on the first try. There should be no step 3.

**Craft & Plugin Info (please complete the following information):**

- Craft Version: Craft Pro 3.6.15
- Freeform Version: 3.12.1
- Freeform Edition: Pro
- Fresh Install or Upgrade: Upgraded from 3.11 to 3.12-beta9 and then to 3.12.

**Additional context**

I tried disabling the spam protection altogether but that doesn't seem to help. I also checked the difference between the network requests of the 1st failing and the 2nd successful one and the only thing that seems to change is the WebKitFormBoundary. Also I can't access the diagnostics page of the plugin at all. It crashes with error:
```Undefined index: edition
1. in /app/vendor/solspace/craft-freeform/packages/plugin/src/Services/SummaryService.phpat line 474
2.     $plugins = [];
        foreach (\Craft::$app->projectConfig->get('plugins') as $handle => $info) {
            if (!$info['enabled']) {
                continue;
            }
 
            $dbInfo = $pluginInfo[$handle];
 
            $plugin = new PluginInfo();
            $plugin->edition = $info['edition']; // THIS LINE IS THE CAUSE OF THE CRASH
            $plugin->version = $dbInfo['version'] ?? '';
            $plugin->installDate = $dbInfo['installDate'] ? new Carbon($dbInfo['installDate'], 'UTC') : null;
            $plugin->license = $dbInfo['licenseKeyStatus'] ?? null;
 
            $plugins[$handle] = $plugin;
        }
 
        return $plugins;
    }
```

**Comment by akselikap** [comment]
I also tried updating to Craft Pro 3.7.20 but I'm running into same issues.

**Comment by gustavs-gutmanis** [comment]
Hi @akselikap,

Could you tell me which session storage mechanism your Freeform is using?
It's located here `/admin/freeform/settings/form-behavior`
Setting name: **Freeform Session Context**

**Comment by akselikap** [comment]
Hi! It seems to be set to PHP Session with 180 minute sessions and 100 active forms per user.

**Comment by gustavs-gutmanis** [comment]
I can't seem to be able to reproduce this issue.
Could you try switching to the `Encrypted Payload` or `Database table` session context and tell me if the problem still persists?

**Comment by akselikap** [comment]
I tried to change it to encrypted payload and the issue is gone. We are using Redis for storing sessions so that might affect this somehow. I guess we'll switch to using encrypted payload for now.

**Comment by gustavs-gutmanis** [comment]
Thanks for letting me know, I'll set up redis to see if that's causing this somehow.

**Comment by croxton** [comment]
Also seeing this issue after upgrading from 3.11.x - using the `PHP Sessions`. Switching to `Encrypted Payload` works for normal forms but I'm finding that Stripe payment forms do not complete - lots of Content Security Policy errors in the console (not sure if that's related to Freeform or a change at Stripe, but this was working last time I tested a few weeks ago).

**Comment by kjmartens** [comment]
Thanks for the additional info @croxton. We're currently investigating this and hope to have a solution soon.

**Comment by kjmartens** [comment]
Are either of you able to provide CP access for us to investigate this deeper and quickly see how your site is set up, etc? If you can, please send credentials to support@solspace.com 🙂

**Comment by brandondeweese** [comment]
Seeing the same thing across my sites. Using "Encrypted Payload" i get a "DateTime::__construct(): Failed to parse time string (1637159704) at position 7 (7): Unexpected character". Not sure what that means in this context.

**Comment by brandondeweese** [comment]
Switching Form Behavior > Freeform Session Context to "Using Database Table" was the only way I could get it to work.

**Comment by kjmartens** [comment]
Thanks for the additional information @brandondeweese. Are you at all able to provide CP access for us to review your setup as well? 🙂

**Comment by croxton** [comment]
@kjmartens 

> Are either of you able to provide CP access for us to investigate this deeper and quickly see how your site is set up, etc? If you can, please send credentials to [support@solspace.com](mailto:support@solspace.com) 🙂

That would be tricky on this particular project (sorry), but I will try to explain how we have Freeform setup:

First, we have a basic ajax contact form configured to allow it to be static cached - the form hash, CSRF token and honeypot are refreshed when the first required input field receives focus - very similar to the pattern described here: 
https://docs.solspace.com/craft/freeform/v3/templating/caching.html

This basic contact form generates the "Form has expired" error when using `PHP sessions`, but works as expected using `Encrypted Payload`

Second, a Stripe payment form that closely follows the instructions and example templates here. It is not static cached.
https://docs.solspace.com/craft/freeform/v3/integrations/payments/

This payment form generates Content Security Policy console errors on form submission when `Encrypted Payload` is enabled and the submission does not complete (no Freeform submission entry and no Stripe payment data is created). I did not test this form with `PHP sessions`.

**Comment by gustavs-gutmanis** [comment]
@croxton, could you please update to the latest `dev-master` and see if the issue has been solved?

**Comment by croxton** [comment]
@gustavs-gutmanis Using latest dev-master

Contact form using `PHP sessions`: Still gives the "Form has expired" error.
Contact form using `Encrypted Payload`: Works as expected

Stripe payment form using `PHP sessions`: Works as expected, but now seems to require two clicks on the submit button (first click does nothing, second click submits form).

Stripe payment form using `Encrypted Payload`: Works as expected, also requires two clicks on the submit button.

**Comment by gustavs-gutmanis** [comment]
Thanks @croxton, I'll keep investigating

**Comment by gustavs-gutmanis** [comment]
@croxton I edited in a suggestion, but you might have missed it. Please take a look.

**Comment by kjmartens** [comment]
@croxton Just curious how long you wait on the first click before clicking a second time on the Payment form? And do you have the **Disable Submit Button on Form Submit?** setting enabled and/or Loading Indicators enabled, etc? Are you seeing any browser console errors after the first click? I'm curious if you can provide more info about this Payment form as well (is it long, is it multi-page, where are the CC fields located if multipage, etc)? 🙂

**Comment by croxton** [comment]
@gustavs-gutmanis That works! I added `{% do form.registerContext %}` to the template where the form is displayed AND to the `/dynamic/form-tokens.twig` template which provides the refreshed tokens when the first input field is focussed. I then set the session type to `PHP sessions` and tried a form submission on un-cached and a cached page. All works.

**Comment by gustavs-gutmanis** [comment]
Glad to hear that. We'll keep investigating the payment forms and make sure to notify people of this issue.

**Comment by croxton** [comment]
@kjmartens Yes I have **Disable Submit Button on Form Submit?** enabled. I do not have the loading indicators enabled. There are no errors in the console on first click of the button.

I am doing some client-side validation on `freeform-ajax-before-submit` which might preventing the form submitting, so I'm going to play with that and see what's going on. It's just a bit odd that it was working with a single click previously.

**Comment by croxton** [comment]
So it looks like the issue is that the event `freeform-ajax-before-submit` is only triggered the second time the form is submitted. The first submit does nothing.

**Comment by kjmartens** [comment]
@croxton I will separate this into a different issue for us to discuss further. 🙂

**Comment by kjmartens** [comment]
@croxton Would you be able to create a new GH issue for this so we can keep that separate from this other issue? 🙂

**Comment by kjmartens** [comment]
## RECAP & SOLUTION:

The issue appears to be with cached forms using PHP Sessions. 

We recommend all sites use/switch to Encrypted Payload. We've just released an update (3.12.4+) where Encrypted Payload is the new default, so that should avoid this issue from surfacing.

If for any reason someone wishes to continue using PHP Sessions instead (and are caching forms), you will need to add `{% do form.registerContext %}` below your form when loading the form in a cached template. 🙂 

For example (only necessary when the **Freeform Session Context** setting is set to PHP Sessions or Database Table):

``` twig {2}
{% set form = craft.freeform.form("myForm") %}
{% do form.registerContext %}

{% cache for 1 day %}

   {{ form.render }}

{% endcache %}
```

**Comment by akselikap** [comment]
I forgot to mention in the start that we are also using this setup which should work despite caching: https://docs.solspace.com/craft/freeform/v3/templating/caching.html#static-page-caching-cdn-blitz If that's not going to work with PHP Sessions anymore then the docs should be edited.

**Comment by kjmartens** [comment]
@akselikap For sure! If using Blitz and PHP Sessions (or Database Tables), you would add `{% do form.registerContext %}` there as well:

``` twig {2}
{% set form = craft.freeform.form(craft.app.request.get('form')) %}
{% do form.registerContext %}
{{ {
    hash: form.hash,
    honeypot: craft.freeform.honeypot(form),
    csrf: {
        name: craft.app.config.general.csrfTokenName,
        value: craft.app.request.csrfToken,
    }
}|json_encode|raw }}
```

I'll update the docs shortly.

**Comment by sjcallender** [comment]
@kjmartens - We're seeing this issue after updating to Freeform 3.13.0. Our challenge is that we're not using Twig, we're using Vue and axios.

**Comment by kjmartens** [comment]
@sjcallender Is this an issue new to 3.13, where you were okay on 3.12 before? Or were you on an older version than 3.12 prior to upgrading to 3.13? If so, it could be that you're missing the payload now... it can be done like:

```
payload="{{ form.json.freeform_payload }}"
:form-object="{{ form | json_encode }}"
```

Or:

```
data.append('freeform_payload', '{{ form.json.freeform_payload }}');
```

**Comment by sjcallender** [comment]
@harmputman - No, we've just kept our auto-retry hack in place.

**Comment by anchovy** [comment]
Ran into the same error with using Vue and upgrading Freeform Pro 3.11.9 => 3.13.11.
```{% do form.registerContext %}``` and changing to using PHP Sessions seemed to fix the issue for us.
