### ISSUE TITLE
Queue job fails

### ISSUE THREAD

**Issue by RichardJong** [solspace/craft3-freeform#237]
Our queue is filled with failed jobs stating:
```  Calling unknown method: craft\console\Request::post() ```
```
{
    "elementType": "Solspace\\Freeform\\Elements\\Submission",
    "elementId": 2861047,
    "siteId": 1,
    "fieldHandles": [],
    "description": null
}
```
Notifications of new form submissions are not sent.

**Craft & Plugin Info**

- Craft Version: Craft Pro 3.7.20
- Freeform Version: 3.12.1
- Freeform Edition: PRO

**Comment by gustavs-gutmanis** [comment]
Hi @RichardJong 

Could you please try the `dev-master` version, to see if it's fixed?

**Comment by RichardJong** [comment]
Problem fixed, but no notifications are sent. Doing more research now what might cause this.

**Comment by gustavs-gutmanis** [comment]
Thanks @RichardJong. Notifications as in email notifications after submitting forms?

**Comment by RichardJong** [comment]
Correct

**Comment by kjmartens** [comment]
@RichardJong Just to be clear, are you saying that using Admin notifications and/or Email field (Submitter) notifications works fine? Just fails with Dynamic Recipients field type? And if so, can you elaborate on how this field is set up? (option source, options, display type, etc) 🙂

**Comment by kjmartens** [comment]
After rereading, I figured out you're likely using the `dynamicNotification` template-level parameter approach. Is that correct? I am able to duplicate an issue where that seems to not be working. We'll check into this further and get a fix asap. Sorry for the trouble.

**Comment by RichardJong** [comment]
That is correct, with the following Twig code:
```
{{
    form.render({
        returnUrl: false,
        action: false,
        dynamicNotification: {recipients: recipient, template: notificationTemplate},
        overrideValues: {
            pageUrl: craft.app.request.absoluteUrl
        }
    })
}}
```

Variable recipient being e.g. "test@example.com" and notificationTemplate being the slug of an email notification e.g. "contactform"
