### ISSUE TITLE
Invisible fields no longer work after 3.12 update

### ISSUE THREAD

**Issue by AbbeyDesign** [solspace/craft3-freeform#238]
I have multiple forms with Element Connections. These connections tie in with entries that have dynamic titles. I had these forms set up as follows and it worked until the latest upgrade. Now I get a "Title cannot be blank" error and the form does not submit. I have summarized the code below for clarity.

`{% set appId = 'A'~now|date('ymdHis') %}`

`{{ form.renderTag({
    overrideValues: {
        idField: appId,
        }
    }) }}`

 The idField is the element field that is tied to a field in the target element which uses it for the title field.

**Steps to reproduce**

1. Fill out the form. Get error.

**Expected behavior**
After upgrading to Freeform 3.12.1 forms stopped working. Upgraded to Freeform 3.12.2 and still get the error. These forms worked before the update.

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 3.7.20
- Freeform Version: 3.12.1 and 3.12.2
- Freeform Edition: Pro
- Fresh Install or Upgrade: Upgrade

**Comment by kjmartens** [comment]
@AbbeyDesign Can you confirm if `idField` is an **Invisible** field type? I played around with this for a while and could only duplicate the issue when using the Invisible field type - didn't matter if using `overrideValues` or if I specified a value for the field inside the form builder. It also seems like the field type simply just doesn't collect any values at all.

We'll get a fix out for this as quickly as possible, but can you confirm if you're using the Invisible field type? 🙂

**Comment by AbbeyDesign** [comment]
It is in fact, an invisible field.

**Comment by kjmartens** [comment]
Thank you! We should likely have a fix ready tomorrow morning.

**Comment by AbbeyDesign** [comment]
Any hotfix I can do? The site is live.

**Comment by kjmartens** [comment]
You could add a Hidden field to the layout, override its value and map the new Hidden field to the Element instead. That should work without issue and feel no different to you and the customer.

**Comment by AbbeyDesign** [comment]
Yeah, that was what I was thinking... thanks!

**Comment by gustavs-gutmanis** [comment]
@AbbeyDesign could you install the `dev-master` version, please, and test if it works as expected now?
Thanks!

**Comment by AbbeyDesign** [comment]
I was successful. Forms work with the dev-master version.



David Abbey ~ AbbeyDesign ~ (305) 924-1991 ***@***.***

**Comment by kjmartens** [comment]
Freeform 3.12.3 has now been released with the fix for this. Sorry again for the trouble!
