### ISSUE TITLE
The field.label property always outputs "Submit", regardless of what the field label is in Composer

### ISSUE THREAD

**Issue by peteheaney** [solspace/craft3-freeform#24]
If I add a submit button to a form and give it a label of, say, "Send", then use the `{{ field.label }}` tag in the template, the label tag still outputs "Submit".  For example:

```
<button type="submit">{{ field.label }}</button>
```

will render a button with the label "Submit", when it should be "Send".

Craft 3.0.0-RC12
Freeform Lite v2.0.0-beta.9

**Comment by kjmartens** [comment]
Thanks, I can duplicate this as well. :)

**Comment by kjmartens** [comment]
We've added this as an alias to the Submit / Next button (in the context of multi-page forms), but you can currently achieve this with `labelNext` in the meantime. :)

https://solspace.com/craft/freeform/docs/field/#field-submit
