### ISSUE TITLE
Cannot save as a new form

### ISSUE THREAD

**Issue by dowadidi** [solspace/craft3-freeform#240]
When trying to save an existing form as a new form, I get a 'The request response is empty' error.

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 3.7.18.2
- Freeform Version: 3.11.12

It seems [this line](https://github.com/solspace/craft3-freeform/blob/bae33c4f580057c07ee38fc8b13559e035713c6f/packages/builder/src/components/SaveButton.jsx#L92) is triggering [this error](https://github.com/solspace/craft3-freeform/blob/master/packages/plugin/src/Controllers/FormsController.php#L148).

**Comment by kjmartens** [comment]
Hi @dowadidi,

Sorry for the trouble you're experiencing. This sometimes happens to sites when they have a rewrite rule for trailing slashes to be added or removed for .htaccess or Nginx.

The easiest way around this might be to just try excluding the admin directory from the rewrite:

### .htaccess

``` apache
# Append a trailing slash
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteCond %{REQUEST_URI} !/$
# Exclude Admin directory
RewriteCond %{REQUEST_URI} !^/admin/
RewriteRule . %{REQUEST_URI}/ [R=301,L]
```

### Nginx

``` nginx
# Redirect URLs with trailing slash, exclude Admin directory
rewrite ^/(?!admin)(.*)/$ /$1 permanent;
```

Also, be sure that you don't have any aggressive security settings enabled on your server such as **ModSecurity / SQL injection detection**.

https://docs.solspace.com/craft/freeform/v3/setup/common-issues.html#_500-error-no-form-id-specified-or-the-request-response-is-empty
