### ISSUE TITLE
Bootstrap 5 template: Button position not respected

### ISSUE THREAD

**Issue by darylknight** [solspace/craft3-freeform#243]
**Describe the bug or issue you're experiencing**
If you select Bootstrap 5 as a template, the submit button always appears on the left, regardless of whether you select Left, Center or Right.

Editor:
![image](https://user-images.githubusercontent.com/1250017/142624676-290d9929-35aa-48ef-a792-a3c8a19a5135.png)

Front end:
![image](https://user-images.githubusercontent.com/1250017/142624710-635c30ac-ba5d-48e2-8dee-0025d1d45dc4.png)

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 3.7.21
- Freeform Version: 3.12.4
- Freeform Edition: Pro
- Fresh Install or Upgrade: Upgrade

**Comment by kjmartens** [comment]
This is now fixed in Freeform 3.12.5. 🙂

**Comment by darylknight** [comment]
Great, thanks!
