### ISSUE TITLE
hidden mailing list field doesn't work since update to 3.12.0 

### ISSUE THREAD

**Issue by i-just** [solspace/craft3-freeform#244]
**Describe the bug or issue you're experiencing**
After updating to Freeform Pro 3.12.0, mailing list field that's set to checked by default and hidden doesn't work. It doesn't send new subscriber details to the mailing list (Mailchimp).

**Steps to reproduce**

1. Update to Freeform Pro 3.12.0 (or any version above; tested up until 3.12.5)
2. Submit newsletter subscription form which had a hidden, checked by default mailing list integration field
3. Check Mailchimp - email address was not added to the list
4. Downgrade to Freeform Pro 3.11.13.1
5. Submit the exact same form 
6. Check Mailchimp - email address was added to the list

**Expected behavior**
Hidden, checked by default mailing list field should submit details to mailing list.

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 3.7.21
- Freeform Version: 3.12.0
- Freeform Edition: Pro
- Fresh Install or Upgrade: Upgrade

**Additional context**
Tested with Freeform Pro 3.11.13 and 3.11.13.1 - works as expected
Tested with Freeform Pro 3.12.0, 3.12.4, 3.12.5 - doesn't work as expected

**Comment by kjmartens** [comment]
Sorry for the trouble with this, @i-just. I can duplicate this issue as well. We'll get a fix for it very soon!

**Comment by kjmartens** [comment]
This is now corrected in Freeform 3.12.6 🙂
