### ISSUE TITLE
Form validation documentation issue

### ISSUE THREAD

**Issue by gavinanderegg** [solspace/craft3-freeform#246]
I was reading the following documentation and found some issues: [Form Events: On Validating the Form](https://docs.solspace.com/craft/freeform/v3/developer/form-events.html#on-validating-the-)

1. The section linked about mentioned `Forms::class` and `Forms::EVENT_FORM_VALIDATE`. It appears this should be `Form` instead of `Forms`, as in the rest of that same documentation link.
2. When trying the code snippet in this section, I got an error when trying to use the `EVENT_FORM_VALIDATE` constant. Looking through the code, I found `EVENT_BEFORE_VALIDATE` and `EVENT_AFTER_VALIDATE`. Both worked without raising an error when I used them instead. Based on the code snippet, it appears that `EVENT_AFTER_VALIDATE` is likely correct here.
3. The code on this page uses the `ValidationEvent` event type, however other pages (for example this one: [Field Events](https://docs.solspace.com/craft/freeform/v3/developer/field-events.html)) use the `ValidateEvent` event type. What's the difference between these two types? Should one be preferred?

Thanks!

**Comment by gustavs-gutmanis** [comment]
Thanks for reporting this @gavinanderegg 

We'll fix the inconsistencies for 1. and 2.
However 3. is using an event specific to field validation, but forms use an event for form validation. They differ in the properties they have, thus they are two different events.
