### ISSUE TITLE
Freeform css file (opinion-scale) always included and not minified

### ISSUE THREAD

**Issue by terryupton** [solspace/craft3-freeform#247]
**Describe the bug or issue you're experiencing**
It seems since a recent update that there is now a css file that is included by default in the templates.
freeform/plugin.css?v=ac7ec6ff2a861f36a476cabb10430036545bc25f

This file is un-minified and seems to only offer styling for the `.opinion-scale`

**Expected behaviour**

1. I expect that this css file should only be included if there is an opinion-scale field type that is part of the form.
2. Then if this is the case and the file is required should also be minified.

**Comment by terryupton** [comment]
In a more recent version, this file also extends to include CSS for the `.freeform-file-drag-and-drop` 
Again, I feel this should only exist and be included if these fields are used or even a setting to include these or not, as users might want to roll/overwrite their own CSS for these.

**Comment by kjmartens** [comment]
Hi @terryupton,

Thanks for reporting this. We'll look into adjusting the behavior of this. 🙂

**Comment by kjmartens** [comment]
This has been adjusted now in Freeform 3.12.8. 🙂
