### ISSUE TITLE
Instructions don't appear on checkbox fields in Bootstrap 5 templates

### ISSUE THREAD

**Issue by darylknight** [solspace/craft3-freeform#248]
**Describe the bug or issue you're experiencing**

Control panel:
![image](https://user-images.githubusercontent.com/1250017/144066708-791e51ee-e937-465a-b52b-3256d2ba0f00.png)

Front end:
![image](https://user-images.githubusercontent.com/1250017/144066744-5a83e00a-2392-4276-a2b8-955aa1aeebf1.png)

**Steps to reproduce**

1. Set a form to Bootstrap 5
2. Add instructions to a checkbox field

**Expected behavior**
Instructions should appear on the front end of the site

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 3.7.23
- Freeform Version: 3.12.7
- Freeform Edition: Pro

**Comment by kjmartens** [comment]
Hi @darylknight, sorry about this. I can duplicate this in my testing as well. We'll get a fix for it shortly. 🙂

**Comment by kjmartens** [comment]
This is fixed now in Freeform 3.12.8. 🙂
