### ISSUE TITLE
Multiselect / Multipicklist Pardot v5 

### ISSUE THREAD

**Issue by shpfive** [solspace/craft3-freeform#249]
**Describe the bug or issue you're experiencing**

I set up pardot v5 crm integration and i'm having issues with a multiselect field mapping to a multipicklist in salesforce
I cant' see the selected values.

**Steps to reproduce**

1. setup pardot v5 integration
2. map a multiselect field to a multipicklist in pardot and send the form

**Expected behavior**

selected values should show in pardot

**Craft & Plugin Info (please complete the following information):**

- Craft Version: Craft Pro 3.7.18.2
- Freeform Version: 3.11.12
- Freeform Edition: Pro
- Fresh Install or Upgrade: Fresh Install

**Additional context**

I don't know if it's my problem or if the values are in a wrong format. It seems like pardot is expecting value1;value2 with ';' but in mail templates the values are shown with ','.
I hope you can help me with that

Thanks,
Sascha

**Comment by kjmartens** [comment]
Hi @shpfive. Sorry for the trouble. I'll have a developer check into this and we'll likely adjust the syntax if necessary. 🙂

**Comment by kjmartens** [comment]
Hi @shpfive, would you be able to try out the latest fix in the repo? You can do this by updating the Freeform line in your site's main composer.json file to:
`"solspace/craft-freeform": "dev-feat/pardot as 3.12.8.1",`

And then run `composer update` in Terminal. :)

**Comment by kjmartens** [comment]
@shpfive We've released 3.12.9, which I believe should resolve this issue. :)

**Comment by shpfive** [comment]
Hey @kjmartens, 
no problem, i changed to checkboxes instead of multiselect so everything is working for me right now.
i will update and test multiselect in a new form. 
Thanks for fixing so fast 

have a good day
