### ISSUE TITLE
Documentation for the form object suggests that the customAttributes property is an object

### ISSUE THREAD

**Issue by peteheaney** [solspace/craft3-freeform#25]
In the [documentation for the `form` object](https://solspace.com/craft/freeform/docs/form/), the list of properties suggests that the `customAttributes` property is an object, with each of the following properties (`id`, `class`, etc) being properties of that object.  Whereas they are actually properties of the main `form` object. `customAttributes` doesn't exist as a property at all.

Not a big issue, obviously.  Just a little confusing.

**Comment by kjmartens** [comment]
Thanks, we'll adjust the documentation to be clearer. :)
