### ISSUE TITLE
AJAX form submission fails with 500 Can't use render() if no form template specified

### ISSUE THREAD

**Issue by icreatestuff** [solspace/craft3-freeform#255]
I have a form which is being rendered in a completely custom template on the frontend using the `{{ form.renderTag }}` tag and manually looping over all the rows and field types etc, instead of using the `{{ craft.freeform.form('contact').render() }}` tag.

In the backend setup for this form I choose to not select any specify Formatting Template (such as 'Flexbox' or 'Tailwind') and I set  'Enable AJAX' to true/on. When I submit the form on the frontend I get an 500 AJAX error stating that:

```
Exception 'Solspace\Freeform\Library\Exceptions\FreeformException' with message 'Can't use render() if no form template specified' 

in /Users/matthewjones/Sites/finding-our-hope/vendor/solspace/craft-freeform/packages/plugin/src/Services/FormsService.php:397
```

It seems that on submit the form is trying to be re-rendered but fails because I've chosen not to use a formatting template.

To test, I chose the 'Flexbox' formatting template and submitted the form again from the frontend. I see my custom form layout being swapped out for an unstyled representation of the form (presumabely because I'm not including any styling for the 'Flexbox'  template).

From this page in the docs https://docs.solspace.com/craft/freeform/v3/overview/formatting-templates.html I gathered that the formatting template is entirely optional.

> Formatting templates are optional, and only necessary if using the render() method, which essentially allows you to attach/relate a formatting template to a form so that you don't need to include formatting inside the template(s) you place the form inside.

**Steps to reproduce**

1. Create a form with minimal fields and choose '-' for the 'Formatting Template' setting
2. Turn on 'Enable Ajax' for the form.
3. Render the form on the frontend in a manual way without using the `craft.freeform.form('myFormHandle').render()` tag
4. Submit the form from the frontend

**Expected behavior**
The form should submit successfully via AJAX.

**Craft & Plugin Info:**

- Craft Version: 3.7.24
- Freeform Version: 3.12.8
- Freeform Edition: Pro
- Fresh Install or Upgrade: Fresh install

**Comment by kjmartens** [comment]
One caveat to the built-in AJAX forms working (especially with multi-page forms) is that it requires the use of a formatting template applied to the form so that it knows which formatting code to pull in for subsequent pages. If you're not using multi-page forms, Freeform will still attempt to reload a fresh copy of the form after success, if it doesn't return to a different page.

If you're comfortable with the idea of having the AJAX form submitted and NOT presenting the form again, you have a couple of options:

- [Forcing a different Success URL on AJAX forms](https://docs.solspace.com/craft/freeform/v3/guides/success-return-on-forms.html#forcing-a-different-success-url-on-ajax-forms)
- [Display alternate Success markup from a Template or Existing Div after AJAX Submit](https://docs.solspace.com/craft/freeform/v3/guides/success-return-on-forms.html#display-alternate-success-markup-from-a-template-or-existing-div-after-ajax-submit)

You would still need to have a formatting template such as Flexbox applied to the form to workaround the error though.

**Comment by icreatestuff** [comment]
HI @kjmartens thanks for your response and setting out some options.

I'm confused, is this a recent change in behaviour (to re-render the form on AJAX submission)? We have other sites running Freeform 3.11.* and earlier versions of 3.12 that I don't think exhibit the same behaviour - I couldn't see anything obvious in the changelog to indicate a something has been altered here.

Ideally what we'd want to happen is the custom form layout to remain after AJAX submission and either have the errors returned and placed in the context of the field(s) they relate to, or if successful for the fields the be emptied (form reset) and the success message to appear. We **don't** want to reload the page, send the user to a different page or replace the form entirely with a custom message or other content.

Do we need to go down the route of setting our custom layout as a new formatting template to get the behaviour we're aiming for?

Thanks

**Comment by kjmartens** [comment]
I tested this out on my end now, and what I noticed was that if I had no formatting template set in the form builder in 3.11, I would still get the same issue as in 3.12. However, if I had a formatting template set (e.g. Grid) upon submit of the manual form (e.g. Demo Templates Bootstrap area), it retained the manual formatting of Bootstrap in 3.11 but not 3.12. I'll see why that might be with 3.12 and if we can do anything about it.

>Do we need to go down the route of setting our custom layout as a new formatting template to get the behaviour we're aiming for?

This might be what you need to do, at least in the meantime. Sorry about this. 😕

**Comment by gustavs-gutmanis** [comment]
We added support for multi-page ajax forms in `3.11` which re-rendered the form's HTML from the ajax response payload. We did not account for people with no formatting templates, this wrong has been righted now :)

**Comment by icreatestuff** [comment]
Thanks for your quick work @kjmartens and @gustavs-gutmanis! Looking forward to seeing that fixed in a future release. In the meantime I've setup a custom formatting template so even if the form is re-rendered it at least looks correct.
