### ISSUE TITLE
composer conflicts when installing Freeform league/flysystem

### ISSUE THREAD

**Issue by CreateSean** [solspace/craft3-freeform#256]
**Describe the bug or issue you're experiencing**

**Steps to reproduce**

1. install Freeform via CLI
2. get composer error

>  Problem 1
>     - solspace/craft-freeform[3.12.0, ..., 3.12.9] **require league/flysystem 1.1.4 -> found league/flysystem[1.1.4] but the package is fixed to 1.1.8** (lock file 
> version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
>     - Root composer.json requires solspace/craft-freeform ^3.12 -> satisfiable by solspace/craft-freeform[3.12.0, ..., 3.12.9].

I suspect that you need to update the requirement to 1.1.8

**Expected behavior**
should install no problem

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 3.7.25
- Freeform Version: latest - trying to install
- Freeform Edition:
- Fresh Install or Upgrade: fresh

**Additional context**

**Comment by kjmartens** [comment]
Thanks for reporting this @CreateSean. We've fixed this in 3.12.9.1 now. 🙂
