### ISSUE TITLE
"Display errors about blocked email under each email field" in settings/spam not working after upgrading

### ISSUE THREAD

**Issue by bartdigitalpulse** [solspace/craft3-freeform#258]
**Describe the bug or issue you're experiencing**

"Display errors about blocked email under each email field" in settings/spam not working after upgrading to freeform 3.12.9.1
After upgrading from 3.11.11.1 to 3.12.9.1 I no longer get the error messages to display on the form. 

**Steps to reproduce**

1. Enable "Display errors about blocked email under each email field" in settings/spam
2. Add blocked Block Email addresses
3. Upgrade to version 3.12.9.1
3. Reverting to version 3.11.11.1 fixes the problem. 

**Expected behavior**

Show error on form when submitting an email address that is not allowed

**Craft & Plugin Info (please complete the following information):**

- Craft Version: Craft Pro 3.7.25.1
- Freeform Version: 3.12.9.1
- Freeform Edition: Pro
- Fresh Install or Upgrade: Upgrade

**Additional context**

**Comment by kjmartens** [comment]
Sorry for the trouble @bartdigitalpulse. I can duplicate this in my testing as well. Just to clarify, this seems to work as expected when "Display Errors" is chosen for the "Spam Protection Behavior" setting as it should, but when using "Simulate Success", it does not show. We'll check into it and get a fix. :)
