### ISSUE TITLE
Deleting an uploaded file will cause all field values of the submission to be cleared

### ISSUE THREAD

**Issue by panlatent** [solspace/craft3-freeform#259]
**Describe the bug or issue you're experiencing**

**Steps to reproduce**

1.
2.

**Expected behavior**

**Craft & Plugin Info (please complete the following information):**

- Craft Version:
- Freeform Version:
- Freeform Edition:
- Fresh Install or Upgrade:

**Additional context**

**Comment by gustavs-gutmanis** [comment]
Thanks @panlatent, the changes have been added
