### ISSUE TITLE
Consider grouping the commands under freeform

### ISSUE THREAD

**Issue by lenvanessen** [solspace/craft3-freeform#26]
Like the other commands are, much cleaner.
<img width="356" alt="schermafbeelding 2018-03-05 om 09 02 44" src="https://user-images.githubusercontent.com/23024452/36963553-0da84a9c-2054-11e8-8c13-07da59a93e7d.png">

**Comment by gustavs-gutmanis** [comment]
Thanks for letting us know. They are no commands for freeform, so these will be removed.

**Comment by lenvanessen** [comment]
Ok, thanks!
