### ISSUE TITLE
No e-mail notifications are being sent

### ISSUE THREAD

**Issue by lenvanessen** [solspace/craft3-freeform#27]
We've setup an e-mail template and correctly configured the form to use it, but no e-mail notifications are being sent for all forms.

We've debugged with mailhog, but they are actually not sent, it's not a delivery issue.
Though the forms are correctly processed and stored in the DB, for some reason the e-mail is not triggers, not to admin nor to the form submittor.

Also, no logs errors in the log present..

Using craft RC-14 and the beta11 of your extension. Any ideas?

**Comment by lenvanessen** [comment]
Any news on this?

**Comment by kjmartens** [comment]
Hi @lenvanessen, sorry for the delay. Would you be able to elaborate on your setup? When you say admin, are you referring to the "Notify" button in Composer, or something like Dynamic Recipients fieldtype? And what do you have for that? Can you also share what your email notification template code looks like? :)

**Comment by lenvanessen** [comment]
Hi @kjmartens,

I'm referring to the 'notify' button in composer. We also tried linking the dynamic recipients fieldttype, no luck either.

Our template:
```
<p>Submitted on: {{ dateCreated|date('Y-m-d H:i:s') }}</p>
<ul>
{% for field in allFields %}
    <li>{{ field.label }}: {{ field.getValueAsString() }}</li>
{% endfor %}
</ul>
```

**Comment by kjmartens** [comment]
Is there by chance a syntax error or are you calling an incorrect field name in the Subject, From Name, From Email fields? Have you tried testing if email can be sent anywhere else from your install of Craft? :)

**Comment by lenvanessen** [comment]
HI @kjmartens ,

Yes, it was in fact an invalid field being called. But there was no error of it logged, nor displayed, so we did not think to check it.

Perhaps the exception generated by calling the wrong field should be logged? Makes it a lot easier to trace back these issues.

**Comment by kjmartens** [comment]
I thought we had this in place for Freeform 1 for Craft 2, but I think it didn't make it to Freeform 2 for Craft 3. I'll make a note about this. :)
