### ISSUE TITLE
Email marketing integration with Constant Contact not working

### ISSUE THREAD

**Issue by arturpaniczek** [solspace/craft3-freeform#272]
**Steps to reproduce**

1. Attempt to create a mailing list integration as per https://docs.solspace.com/craft/freeform/v3/integrations/email-marketing/constant-contact.html
2. Upon saving, authentication stops midway at https://idfed.constantcontact.com/as//authorization.oauth2?pfidpadapterid=ctctOAuth2IdpAdapter&client_id=[CLIENT_ID]&redirect_uri=[REDIRECT_URI]&response_type=code&scope=contact_data& which displays "400 - Unknown or invalid client_id" error. In the integration entry in Freeform it claims to be "Authorized", but when trying to use it in a form builder, it logs the following error:
```{"error_key":"unauthorized","error_message":"Unauthorized"} {"exception":"Client error: `GET https://api.cc.email/v3/contact_lists` resulted in a `401 Unauthorized` response:\n{\"error_key\":\"unauthorized\",\"error_message\":\"Unauthorized\"}\n"} []```

**Expected behavior**
Integration allows connecting to selected Constant Contact list.

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 3.5.17.1
- Freeform Version: 3.12.13
- Freeform Edition: Pro
- Fresh Install or Upgrade: both

**Additional context**
I attempted recreating the connection several times with no success.

**Comment by arturpaniczek** [comment]
@kjmartens sounds great - thank you for following up

**Comment by kjmartens** [comment]
@arturpaniczek Just letting you know we're currently working on an update where the integration will work with the changes that Constant Contact made to the API. We'll likely have an update available this week. 🙂

**Comment by kjmartens** [comment]
This is now resolved in Freeform 3.13.4+. Please follow the update instructions here: 🙂 
https://docs.solspace.com/craft/freeform/v3/integrations/email-marketing/constant-contact.html#_2022-update-instructions

**Comment by arturpaniczek** [comment]
@kjmartens thank you
