### ISSUE TITLE
Uncaught TypeError: this.parentElement is null

### ISSUE THREAD

**Issue by bengreenbank** [solspace/craft3-freeform#277]
**Describe the bug or issue you're experiencing**
It seems that Freeform is conflicting with Mapbox GLJS on our site. Whilst initialising the map component it throws an error within the `/freeform/plugin.js` script.

**Steps to reproduce**

1. Install Mapbox GL JS
2. Attempt to [initialise a map](https://docs.mapbox.com/mapbox-gl-js/api/map/) and [add a marker](https://docs.mapbox.com/mapbox-gl-js/api/markers/#marker) to the map
3. When initialising the marker, the following console error will log:
```
Uncaught TypeError: this.parentElement is null
    remove http://luton.local/freeform/plugin.js?v=ce8a9776decdcb18a9306d73a4281dcb4ad1a556:2
    remove http://luton.local/assets/js/maps.js?id=37ea00d73bed4bc713f3:35
    addTo http://luton.local/assets/js/maps.js?id=37ea00d73bed4bc713f3:35
    initMapbox http://luton.local/assets/js/mapbox-init.js?id=b6f3b73dca62a59c89d8:24
    <anonymous> http://luton.local/assets/js/mapbox-init.js?id=b6f3b73dca62a59c89d8:8
    EventListener.handleEvent* http://luton.local/assets/js/mapbox-init.js?id=b6f3b73dca62a59c89d8:7
    <anonymous> http://luton.local/assets/js/mapbox-init.js?id=b6f3b73dca62a59c89d8:6
    <anonymous> http://luton.local/assets/js/mapbox-init.js?id=b6f3b73dca62a59c89d8:34
```
4. To confirm, removing any Freeforms from the page makes the map work properly again.

**Expected behavior**

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 3.7.29
- Freeform Version: 3.12.13
- Freeform Edition: Pro (Trial, currently in dev mode).
- Fresh Install or Upgrade: Fresh Install

**Additional context**
Please contact me should you want to test this in our remote environment.

**Comment by kjmartens** [comment]
Sorry for the trouble @bengreenbank... we'll make a fix for this and release an update shortly. 🙂

**Comment by kjmartens** [comment]
We've made a fix for this now. Can you try updating to the latest and see if it works for you? You can try updating to:
`dev-master as 3.12.13.1` 🙂

**Comment by bengreenbank** [comment]
Thanks @kjmartens. This works perfectly now!
