### ISSUE TITLE
error on install

### ISSUE THREAD

**Issue by romanov-sky** [solspace/craft3-freeform#28]
When trying to install (from Craft Plugin store and/or with Composer) i get this error. Can you help, what i'm doing wrong?

`Error: An error occurred

Output: Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

Problem 1
- Installation request for solspace/craft3-freeform 2.0.0-beta.11 -> satisfiable by solspace/craft3-freeform[2.0.0-beta.11].
- solspace/craft3-freeform 2.0.0-beta.11 requires hashids/hashids ^1.0 -> satisfiable by hashids/hashids[1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.0.6] but these conflict with your requirements or minimum-stability.

Running update with --no-dev does not mean require-dev is ignored, it just means the packages will not be installed. If dev requirements are blocking the update you have to resolve those problems.`

**Comment by gustavs-gutmanis** [comment]
Could you list your other composer requirements, please?
I will have a look at what might be causing this.
