### ISSUE TITLE
Submissions does not sync with date range

### ISSUE THREAD

**Issue by romainpoirier** [solspace/craft3-freeform#284]
**Steps to reproduce**

1. Filter submission using the date range fields in `/admin/freeform/submissions/{handle}`
2. The graph with total submissions is updated, but the submissions behind are not filtered

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 3.7.33
- Freeform Version: 3.12.13
- Fresh Install or Upgrade: Upgrade

**Comment by kjmartens** [comment]
Hi @romainpoirier,

The date range settings in the chart are currently only designed to allow you to expand/contract the range of data shown in the chart, not the results. What you are seeing is expected behavior. 🙂
