### ISSUE TITLE
Password and confirm password fields not rendering after upgrading v3.12.13 > v3.13.0

### ISSUE THREAD

**Issue by anchovy** [solspace/craft3-freeform#288]
**Describe the bug or issue you're experiencing**
After upgrading from v3.12.13 > v3.13.0 my existing password and confirm password fields have stopped rendering; all other fields rendering the same as usual, tested using the freeform demo templates.

**Steps to reproduce**

1. add a password and confirm password fields to a form
2. view the template; you'll see the fields are not rendering.

The form
![image](https://user-images.githubusercontent.com/599005/156098667-946ff753-43c6-4967-ba0f-e481d0bc234f.png)

The rendered form
![image](https://user-images.githubusercontent.com/599005/156098646-5f309fce-d986-46c8-9131-19163667198f.png)

**Expected behavior**
Password & Confirm password fields render.

**Craft & Plugin Info (please complete the following information):**

- Craft Version: Craft Pro 3.7.31
- Freeform Version: 3.13.0
- Freeform Edition: Pro
- Fresh Install or Upgrade: Upgrade

**Additional context**

**Comment by hatzipanis** [comment]
Possibly related: we're not seeing credit card fields anymore after a recent update (hard to tell which one). Have tried rendering using default templates and they're not appearing there either.

**Comment by kjmartens** [comment]
Very sorry about this @anchovy and @hatzipanis. I'm not sure how this happened but we'll address this issue right away.

**Comment by kjmartens** [comment]
@anchovy @hatzipanis We've now released 3.13.1, which should correct these issues. Again, very sorry for the trouble caused here!

**Comment by anchovy** [comment]
@kjmartens / thanks for the quick fix.
