### ISSUE TITLE
Unrecognized request URL

### ISSUE THREAD

**Issue by hatzipanis** [solspace/craft3-freeform#289]
**Describe the bug or issue you're experiencing**

We are receiving the following error when trying to transact a single one-time payment with Stripe. It looks like this was introduced in a recent update.

```
yii\db\Exception
SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'errorMessage' at row 1
The SQL being executed was: INSERT INTO `freeform_payments_payments` (`integrationId`, `resourceId`, `submissionId`, `subscriptionId`, `amount`, `currency`, `last4`, `status`, `metadata`, `errorCode`, `errorMessage`, `dateCreated`, `dateUpdated`, `uid`) VALUES (2, NULL, 54055, NULL, NULL, NULL, NULL, 'failed', NULL, '0', 'Unrecognized request URL (GET: /v1/payment_intents/). If you are trying to list objects, remove the trailing slash. If you are trying to retrieve an object, make sure you passed a valid (non-empty) identifier in your code. Please see https://stripe.com/docs or we can help at https://support.stripe.com/.', '2022-02-28 23:52:27', '2022-02-28 23:52:27', '03b06abd-65df-4966-ac99-3d559683cb8a')
```

**Steps to reproduce**

1. Create a single one-time payments
2. Transact on the front-end with demo templates

**Expected behavior**

A payment to transact normally with Stripe.

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 3.7.25.1
- Freeform Version: 3.13.1
- Freeform Edition: Pro
- Fresh Install or Upgrade: Upgrade

**Comment by kjmartens** [comment]
Sorry for the trouble @hatzipanis. I am trying to duplicate this in my testing and I can't.

Can you provide me with more information, including:

1. Version of Freeform you used successfully before upgrading to 3.13.1
2. Exactly how the Single Payment is set up inside form builder, including field mapping, etc.
3. Is this in Test mode? And which testing number are you using?
