### ISSUE TITLE
ReCAPTCHA not rendering

### ISSUE THREAD

**Issue by stephenj-plato** [solspace/craft3-freeform#290]
Recently upgraded to version 3.13.2 and suddenly the ReCAPTCHA stopped rendering. Downgraded to version 3.13.1, but the problem persisted. Finally I downgraded to version 3.12.13 and it came back.

**Steps to reproduce**

1. Upgrade freeform to 3.13.2

**Expected behavior**
ReCAPTCHA should be rendering.

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 3.7.35
- Freeform Version: 3.13.2
- Freeform Edition: Lite
- Fresh Install or Upgrade: Upgrade

**Comment by kjmartens** [comment]
Sorry for the trouble @stephenj-plato. We'll work on getting a fix out very soon.

**Comment by kjmartens** [comment]
This is fixed in v3.13.3 now. Sorry again for the trouble. 🙂

**Comment by stephenj-plato** [comment]
> This is fixed in v3.13.3 now. Sorry again for the trouble. 🙂

You're awesome! No problem :)
