### ISSUE TITLE
FreeForm Lite ReCAPTCHA not loading

### ISSUE THREAD

**Issue by davidcraigmyle** [solspace/craft3-freeform#295]
I have just upgraded some sites to Craft 3.7.36 and with it FreeForm Lite 3.13.4.
After this the ReCAPTHA is not showing.
It works fine with the sites I've done with a Pro licence but the Lite versions aren't showing anything.

(I do see that there is a request closed for this but this was before this update)

**Steps to reproduce**

- Upgraded Craft to 3.7.36 and FreeForm Lite to 3.13.4

**Expected behavior**

- ReCAPTCHA to show on forms

**Craft & Plugin Info (please complete the following information):**

Craft Version: 3.7.36
Freeform Version: 3.13.4
Freeform Edition: Lite
Fresh Install or Upgrade: Upgrade

**Comment by kjmartens** [comment]
Sorry for the trouble, @davidcraigmyle.

I can confirm this in my testing as well. We'll get it corrected ASAP.

**Comment by kjmartens** [comment]
@davidcraigmyle This is fixed in 3.13.5 now. Sorry again for the trouble!
