### ISSUE TITLE
Freeform migrations Failed Unknown column 'forms.type' in 'field list'

### ISSUE THREAD

**Issue by reachpriti12** [solspace/craft3-freeform#298]
I am upgrading Freeform v3.8.0 to the latest one and I am getting the Database Exception error. I have attached the screenshot of the error.

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 3.7.36
- Freeform Version: 3.8.0
- Freeform Edition:
- Fresh Install or Upgrade: Upgrade

<img width="912" alt="Screen Shot 2022-03-11 at 8 44 31 AM" src="https://user-images.githubusercontent.com/31907075/157743511-5c29ad8c-0af6-4ca8-b4f5-72897b3ceb45.png">

**Comment by kjmartens** [comment]
I'm very sorry for the trouble @reachpriti12. Out of curiosity, if you try to upgrade to Freeform 3.12.13 first (set "3.12.13" for Freeform version in composer.json, then run `composer update` again), does that work without issue for you?

I'll have a developer check into improving this so it doesn't happen, but thought this might be a quick fix for you.

**Comment by reachpriti12** [comment]
@kjmartens this quick fix worked out yay!.. I was able to upgrade to the latest version. Thanks :)

**Comment by kjmartens** [comment]
Thank you for letting us know! We'll get this corrected soon so others updating from older versions don't run into it either. 🙂
