### ISSUE TITLE
Error after updating Freeform from 3.13.4 to 3.13.5

### ISSUE THREAD

**Issue by dcplebranch** [solspace/craft3-freeform#302]
**Describe the bug or issue you're experiencing**

I get the following error:

ParseError
syntax error, unexpected 'array' (T_ARRAY), expecting function (T_FUNCTION) or const (T_CONST)
1. in /home/vagrant/code/dcpl2/vendor/solspace/craft-freeform/packages/plugin/src/Events/Fields/FetchFieldTypes.php at line 11

**Steps to reproduce**

1. make sure everything is working fine in 3.13.4 including all the forms and the Freeform page in the CP
2. update Freeform from 3.13.4 to 3.13.5
3. go to any page with a form OR go to the Freeform page in the control panel

**Expected behavior**

I don't expect an error, but that's what I got.

**Craft & Plugin Info (please complete the following information):**

- Craft Version: Craft Pro 3.7.36
- Freeform Version: 3.13.5
- Freeform Edition: Pro
- Fresh Install or Upgrade: upgrade

**Additional context**

This is on my local vagrant VM. I tried this using the CP update method, as well as using the composer.json file and "composer update" from the command line. I even tried removing the vendor folder and doing a fresh "composer install" but still got the same error.

<img width="1266" alt="parse_error" src="https://user-images.githubusercontent.com/13337547/157921009-55be74f8-2b7b-4dab-865f-262acb0b3b4f.png">
.

**Comment by kjmartens** [comment]
Very sorry about this @dcplebranch. We've just released v3.13.5.1, which corrects the issue. 🙂

**Comment by dcplebranch** [comment]
Thanks @kjmartens that fixed it!
