### ISSUE TITLE
CORS form submission

### ISSUE THREAD

**Issue by TijnVanHofwegen** [solspace/craft3-freeform#303]
Unable to submit a form cross domain.
It should have been possible with this update:
https://github.com/solspace/craft3-freeform/commit/1335ca64da3da15e2b4bcc25d196eddc34d2c628

Changing line 97 from
`$corsHeaders['Access-Control-Allow-Origin'] = $origins;`
to
`$corsHeaders['Origin'] = $origins;`
fixes the issue for me. Please check https://www.yiiframework.com/doc/api/2.0/yii-filters-cors for reference.

**Steps to reproduce**
1. set allowedGraphqlOrigins in Craft CMS general settings
2. Do a cross domain form submission

**Craft & Plugin Info:**

- Craft Version: 3.7.26
- Freeform Version: 3.13.5.1
- Freeform Edition: Lite
- Fresh Install or Upgrade: Fresh

**Comment by kjmartens** [comment]
Thank you for this @TijnVanHofwegen. We'll release an update shortly. :)

**Comment by kjmartens** [comment]
@TijnVanHofwegen We've made a bit of a smarter fix for this that will work better for some other scenarios. Would you be able to update to the `dev-master` version and see if it continues to work for you? :)
