### ISSUE TITLE
Error saving form with custom datetime field: Could not create a field of type datetime

### ISSUE THREAD

**Issue by skramstad** [solspace/craft3-freeform#31]
Hi.

I get this error message when I add a custom Date field. **Could not create a field of type datetime**
Nothing in the log and the same happened when I try to add a custom number field.

When I remove the field, it successfully saved the form.

Details:
Craft 3 RC 15
Freeform Lite 2.0.0-beta.11

**Comment by kjmartens** [comment]
Hi @skramstad, the field types after Dynamic Recipients field in the list are all supposed to be available to Freeform Pro only. It seems there's an issue with Freeform Lite where it allows you to create field types that are available in Pro only. We'll get this fixed for the next release. In the meantime, if you wish to use the Date & Time field or other Pro fields, you'll need to install Freeform Pro as well. :)

**Comment by skramstad** [comment]
Ah that explains it. Thanks for the info!
