### ISSUE TITLE
Email templates can't be deleted in Freeform Lite 2.0.0-beta.13

### ISSUE THREAD

**Issue by martinhellwagner** [solspace/craft3-freeform#36]
When I want to delete an email notification template in Freeform Lite 2.0.0-beta.13, it's deleted just as expected, but when I click on the "Email Notifications" tab at a later time, the template suddenly shows up again (even though it should be deleted).

It's not a big issue per se, but I just wanted to let you know anyways.

**Comment by kjmartens** [comment]
Thanks, I can duplicate this as well. It seems it's not actually deleting the email notification template.
