### ISSUE TITLE
User permission for "Manage All Submissions" not being respected

### ISSUE THREAD

**Issue by lukehmu** [solspace/craft3-freeform#38]
Hello,

We have a non-admin user who will be able to create forms and should be able to access all submissions. Their user group settings are as follows:
![image](https://user-images.githubusercontent.com/1893145/38307746-a759bbf6-380c-11e8-9638-36c8d24ab3bf.png)

We are assuming that the "Manage All Submissions" permission should enable them to access all submissions, without having to select each form individually. It seems odd that they'd be able to have full access but then we (admins) need to give them permission to view submissions for each form they create.

This results in them being able to export a CSV for the data, but not click on the submission (no link on the title):
![image](https://user-images.githubusercontent.com/1893145/38307881-28b36f44-380d-11e8-901f-2ed9f7afa94f.png)

edit:
Craft 3 RC17.1
Freeform Lite 2.0.0-beta.13

Thanks,
Luke

**Comment by kjmartens** [comment]
Thanks @lukehmu, I can duplicate this as well. We'll get a fix out soon. :)
