### ISSUE TITLE
Error after updating to Craft 3.0.0

### ISSUE THREAD

**Issue by ryanfoote** [solspace/craft3-freeform#39]
The following error gets thrown by Freeform after updating to Craft 3.0.0:

`Undefined class constant 'Client' `

I apologize, I disabled the plugin before grabbing the remainder of the trace so that I could complete the Craft upgrade process.

**Comment by spAnser** [comment]
vendor/solspace/craft3-freeform/src/Freeform.php at line 201
```
        if (\Craft::$app->getEdition() >= \Craft::Client) {
```

**Comment by kjmartens** [comment]
Thanks, we're pushing out an update shortly. It seems like they last minute removed the Client edition from Craft 3 for `3.0.0`. Until the update is available, to get around this, you can update `Client` to `Pro`. :)

**Comment by ryanfoote** [comment]
Thanks for the update! I suppose that license change explains why I had to re-apply a few Craft licenses this morning.

**Comment by kjmartens** [comment]
This has now been fixed in the Beta 14 release, but the fix above will apply to anyone currently affected, unless you run `composer update` to update to latest version of Freeform Lite / Pro. :)

**Comment by ryanfoote** [comment]
Fixed in 664e9a5af347b0ce2ce3cd5a6dbcecd344052af9

Thanks @kjmartens!

**Comment by kjmartens** [comment]
I'm just reopening this one for a little while longer so others that encounter this will see the solution. :)

**Comment by spAnser** [comment]
Craft reimplemented the Client variable as deprecated. So no one else should see this error now.
