### ISSUE TITLE
Error 'Form has to be an int'

### ISSUE THREAD

**Issue by miro94** [solspace/craft3-freeform#4]
After selecting a form and saving the section, an error appears that the form have to be an Integer.
(Sorry, screenshot is in german)
![form](https://user-images.githubusercontent.com/19932813/35381753-94e38a22-01bd-11e8-8a65-08945fccfe57.png)

**Comment by kjmartens** [comment]
This should be resolved now in Freeform 2.0.0-beta.2 :)
Please updates and let me know if the issue persists.
