### ISSUE TITLE
Invalid argument supplied for foreach() in FileUploadField

### ISSUE THREAD

**Issue by charliegrinsted** [solspace/craft3-freeform#43]
I'm having an issue uploading a file. The field is not required, nor does it have a maximum file size or count limit. The error occurs with any of the allowed file types.

Invalid argument supplied for foreach() at line 133
/craft3-freeform/src/Library/Composer/Components/Fields/FileUploadField.php

**Comment by kjmartens** [comment]
Would you be able to elaborate on your setup? I assume you're using the latest version of Freeform 2 and Craft 3? And are you using Local storage or Cloud storage? When you say you don't have a maximum file size or count limit, there must be something set for the File Upload field in the property editor column inside Composer, as it otherwise seems to force `0`.

**Comment by charliegrinsted** [comment]
Thanks for the response!

This is with Freeform 2 and Craft 3.0.1. The Asset Source for the field is a Local volume which works perfectly directly via Assets. The count isn't set but shows a default value of 1.

Looking back, the file upload was working with beta 9 but hasn't since.

**Comment by kjmartens** [comment]
Hmm, we haven't heard of anyone else with this issue yet. Are you able to send us FTP access by chance so we can have a closer look? Or we could possibly provide you some code to help us debug. :)

**Comment by kjmartens** [comment]
Just to follow up, have you tested this in the demo templates, and does it work okay there? Are you building your form somewhat manually for the file upload field? And if so, can you make sure your **name** attribute's value has `[]` at the end of it? We recently uncovered this issue, and will likely come up with a fix that doesn't require you to have `[]` when using as a single upload field. :)

**Comment by charliegrinsted** [comment]
It works with `[]` appended, thanks a lot :)
