### ISSUE TITLE
Possible to send a form without CRAFT_CSRF_TOKEN?

### ISSUE THREAD

**Issue by divyan** [solspace/craft3-freeform#44]
Hi,

I got a problem trying to send data to the form-action without using the CRAFT_CSRF_TOKEN. I want it to work without the token-verification.
I see that Controllers/ApiController.php has protected $allowAnonymous = true; in it, so it should be possible workaround the token-check would it?
Can it be done, and so how is this possible?

**Comment by kjmartens** [comment]
If you're looking to not use CSRF protection, you'll need to disable CSRF protection in your Craft config, as Craft otherwise prevents any POST requests from going through if they don't have a valid CSRF token. :)
