### ISSUE TITLE
Error submitting a form that has been inserted via Ajax

### ISSUE THREAD

**Issue by jackfaulkner** [solspace/craft3-freeform#46]
Hi, I'm having trouble with a form that has been loaded from an entry template on to another page using Ajax.  If I go to the entry, the form works correctly and is able to be submitted normally. However when loaded on to another page, the form fails to submit. If I try to submit it via Ajax (using code from [the example in the docs](https://solspace.com/craft/freeform/docs/ajax-forms/)), the response is `{success: false, finished: false, errors: Array(0)}`.

Is this something to do with the `CRAFT_CSRF_TOKEN` field or another unique identifier inserted by Freeform? I'm guessing something is trying to prevent spam or malicious use by confirming the form is being submitting from the correct page. If so, is there a way to override this? Perhaps I can request the entry containing the form with a URL variable that indicates what page the form will be loaded into, so the token can be adjusted.

Thanks for your help! Happy to provide code examples if needed.

**Comment by kjmartens** [comment]
You'll need to refresh the CSRF token. Something like this is what you would need to do:

```
    <div id="target"></div>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script>
      $(() => {
        $.ajax({
          url: "/ajax",
          success: (response) => {
            $("#target").html(response);
            $('input[name={{ craft.config.csrfTokenName }}]').val('{{ craft.request.csrfToken }}');
          }
        });
      });
    </script>
```

**Comment by jackfaulkner** [comment]
Thanks for your reply @kjmartens, I added that code and confirmed the `CRAFT_CSRF_TOKEN` field is correct in my Ajax-loaded form (it matches another form on the page). I just needed to update the tags in your code to `{{ craft.app.config.general.csrfTokenName }}` and `{{ craft.app.request.csrfToken }}` respectively.

However, this didn't fix my problem! After pulling my hair out for a few hours, I realised my jQuery`.load()` function was stripping out the form's script tags (the Freeform scripts that set the `freeform_form_handle` value and disable the submit button when clicked). I fixed this (switched to `$.get()`) and the script tags now come through when I append the html response to the page. The form is working correctly (with/without CSRF and with/without Ajax handling the submission).

Perhaps you could add some kind of error message about this for idiots like me? :-)
