### ISSUE TITLE
Form submit creates no submission

### ISSUE THREAD

**Issue by rivvakili** [solspace/craft3-freeform#48]
Everything in the CP section works fine: Creating a form ect. All good.
But integrated in a article we have following problem:
If the form is correctly filled and the user clicks submit, a post is made on the same page and the user just sees his filled out form again. Also, no submission are seen in the CP.
Example: http://www.friday-magazine.ch/advertorials/freeform-test?token=GTbzQ-hhCw2SlV7BSIz5N1VT_VgS_RVT

Template integration:
{% if block.freeForm|length > 0 %}
  <div
    class="freeform"
    data-uploadtext="{{ formFileUploadTextLabel.plainText }}"
    data-required="{{ formErrorMessageRequired.plainText }}"
    data-email="{{ formErrorMessageEmail.plainText }}"
    data-phone="{{ formErrorMessagePhone.plainText }}"
    data-zipcode="{{ formErrorMessageZipcode.plainText }}"
    data-birthdate="{{ formErrorMessageBirthdate.plainText }}"
  >
    {{ craft.freeform.form(block.freeForm.handle).render() }}
  </div>
{% endif %}

We disabled spam protection and tried out changing freeform settings in the CP

**Comment by kjmartens** [comment]
When using the Fieldtype, you should only need to use something like:

`{{ block.myFreeformfieldname.render() }}`

Not the full `{{ craft.freeform.form(block.freeForm.handle).render() }}` function :)

**Comment by rivvakili** [comment]
Thanks

But the behaviour is still the same with:
{{ block.freeForm.render() }}

or

{% set form = craft.freeform.form("composerForm") %}
{% if form.submittedSuccessfully %}
    <div>You've successfully submitted this form!</div>{% endif %}
{{ form.render }}



2018-04-17 6:14 GMT+02:00 Kelsey Martens <notifications@github.com>:
