### ISSUE TITLE
Only file email templates are selectable in form builder

### ISSUE THREAD

**Issue by WHITE-developer** [solspace/craft3-freeform#483]
Since this commit (https://github.com/solspace/craft-freeform/commit/558e1078c017a7c17eac065468fa6377a86002ff) the email notification selector is broken again and only the file templates are visible, the database templates aren't showing up
**Craft & Plugin Info (please complete the following information):**

- Craft Version: 4.2.8
- Freeform Version: 4.0.6
- Freeform Edition: PRO

**Comment by kjmartens** [comment]
I'm so sorry for this @WHITE-developer. We'll fix this issue shortly!

**Comment by kjmartens** [comment]
This has been fixed in Freeform 4.0.7 now. 🙂
