### ISSUE TITLE
Incorrect file path for JS calendar plugin used with Date field

### ISSUE THREAD

**Issue by jackfaulkner** [solspace/craft3-freeform#49]
I get a PHP Warning when using the Date field in a form. It appears a file path for the [Flatpickr](http://flatpickr.js.org) plugin is incorrect:

`file_get_contents(example-project/vendor/solspace/craft3-freeform/src/Services/../Resources/js/cp/fields/flatpickr.js): failed to open stream: No such file or directory`

I believe the correct path should be `example-project/vendor/solspace/craft3-freeform/src/Resources/js/cp/fields/flatpickr.js`

This error happens on both local and staging environments, and only when a form is using a Date field with the "Use the Freeform datepicker for this field?" option checked.

Thanks for your help!

**Comment by kjmartens** [comment]
Thanks, this will be fixed in the next release of Freeform :)
