### ISSUE TITLE
Error installing plugin (in Craft-backend)

### ISSUE THREAD

**Issue by sjenset** [solspace/craft3-freeform#5]
When attempting to install the plugin (LITE version - haven't tried PRO yet) I get a MigrationException:

`An error occurred while executing the "Solspace\Freeform\migrations\Install migration: SQLSTATE[42000]: Syntax error or access violation: 1067 Invalid default value for 'dateCreated'`

`The SQL being executed was:`
    CREATE TABLE `freeform_forms` (
    `id` int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `name` varchar(100) NOT NULL,
    `handle` varchar(100) NOT NULL UNIQUE,
    `spamBlockCount` int(11) UNSIGNED NOT NULL DEFAULT 0,
    `submissionTitleFormat` varchar(255) NOT NULL,
    `description` text,
    `layoutJson` mediumtext,
    `returnUrl` varchar(255),
    `defaultStatus` int(11) UNSIGNED,
    `formTemplateId` int(11) UNSIGNED,
    `color` varchar(10),
    `dateCreated` datetime NOT NULL DEFAULT NOW(),
    `dateUpdated` datetime NOT NULL DEFAULT NOW() ON UPDATE CURRENT_TIMESTAMP,
   `uid` char(36) DEFAULT 0
    ) ENGINE=InnoDb DEFAULT CHARSET=utf8"`

The trace is as follows:

`#0 /var/www/moldejazz.test/vendor/craftcms/cms/src/base/Plugin.php(112): craft\db\MigrationManager->migrateUp(Object(Solspace\Freeform\migrations\Install))`
`#1 /var/www/moldejazz.test/vendor/craftcms/cms/src/services/Plugins.php(461): craft\base\Plugin->install()`
`#2 /var/www/moldejazz.test/vendor/craftcms/cms/src/controllers/PluginsController.php(49): craft\services\Plugins->installPlugin('freeform')`
`#3 [internal function]: craft\controllers\PluginsController->actionInstallPlugin()`
`#4 /var/www/moldejazz.test/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)`
`#5 /var/www/moldejazz.test/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)`
`#6 /var/www/moldejazz.test/vendor/craftcms/cms/src/web/Controller.php(80): yii\base\Controller->runAction('install-plugin', Array)`
`#7 /var/www/moldejazz.test/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('install-plugin', Array)`
`#8 /var/www/moldejazz.test/vendor/craftcms/cms/src/web/Application.php(251): yii\base\Module->runAction('plugins/install...', Array)`
`#9 /var/www/moldejazz.test/vendor/craftcms/cms/src/web/Application.php(453): craft\web\Application->runAction('plugins/install...', Array)`
`#10 /var/www/moldejazz.test/vendor/craftcms/cms/src/web/Application.php(211): craft\web\Application->_processActionRequest(Object(craft\web\Request))`
`#11 /var/www/moldejazz.test/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))`
`#12 /var/www/moldejazz.test/web/index.php(21): yii\base\Application->run()`
`#13 {main}``

**Comment by kjmartens** [comment]
Sorry for the trouble... this will be fixed in the next version. :)

**Comment by kjmartens** [comment]
This should be resolved now in Freeform 2.0.0-beta.2 :)
Please updates and let me know if the issue persists.

**Comment by sjenset** [comment]
I'm still getting `An error occurred while executing the "Solspace\Freeform\migrations\Install migration: SQLSTATE[42000]: Syntax error or access violation: 1067 Invalid default value for 'dateCreated' The SQL being executed was: CREATE TABLE `freeform_forms` ( `id` int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY, `name` varchar(100) NOT NULL, `handle` varchar(100) NOT NULL UNIQUE, `spamBlockCount` int(11) UNSIGNED NOT NULL DEFAULT 0, `submissionTitleFormat` varchar(255) NOT NULL, `description` text, `layoutJson` mediumtext, `returnUrl` varchar(255), `defaultStatus` int(11) UNSIGNED, `formTemplateId` int(11) UNSIGNED, `color` varchar(10), `dateCreated` datetime NOT NULL DEFAULT NOW(), `dateUpdated` datetime NOT NULL DEFAULT NOW(), `uid` char(36) DEFAULT 0 ) ENGINE=InnoDb DEFAULT CHARSET=utf8` after (completely removing and re-) installing beta2 :(

**Comment by sjenset** [comment]
Seems to be originating from the craft3-commons dependency btw

**Comment by kjmartens** [comment]
Did you install Freeform through the Plugin Store or Composer? Also, which version of MySQL are you running? :)

**Comment by sjenset** [comment]
Installed it through composer with @beta-stability.

Server version: 5.5.52-MariaDB

**Comment by kjmartens** [comment]
Can you try this again with v2.0.0-beta.3? :)

**Comment by sjenset** [comment]
Using v2.0.0-beta.3 I was able to install both versions successfully :)
