### ISSUE TITLE
Error when using Freeform on server with PHP 7.0

### ISSUE THREAD

**Issue by martinhellwagner** [solspace/craft3-freeform#50]
When using Craft 3.0.2 on a server with PHP 7.0.28, submitting the form fails because apparently Symfony requires PHP 7.1-specific Nullable types ("?" notation). We're using Freeform Lite 2.0.0-beta.16 for the form.

Shouldn't it be possible to use Freeform with PHP 7.0 without Symfony requiring PHP 7.1-specific language features?

**Comment by martinhellwagner** [comment]
The first of (quite possibly many) points where the nullable type is required (and where the logs say that the error occurs) is in _vendor/symfony/Process.php_ in line 139:

`public function __construct($commandline, string $cwd = null, array $env = null, $input = null, ?float $timeout = 60)`

When removing the nullable type in this line, the form errors out in other places that also contain a nullable type.

We're running the same website both on a PHP 7.1 system (where it works flawlessly) and on a PHP 7.0 system (where the errors occur). No other errors occur throughout the website - just when submitting the form.

**Comment by martinhellwagner** [comment]
Any solution for this? We need to push the code into production on Friday, and are still getting the error.

**Comment by kjmartens** [comment]
Is there any chance you installed and setup Craft while on PHP 7.1 and then afterward switched it to PHP 7.0? It's possible that PHP 7.1 related dependences were installed earlier when it was relevant, but would potentially cause some issues if you just switched your environment to PHP 7.0 afterward.

In my testing, I switched my environment to PHP 7.0 (from PHP 7.1) and some parts of Craft like the Updater give similar errors for me, though it's interesting to note I am not seeing issues with Freeform. We also have 750 installs of Freeform and it would seem odd if you were the only one using PHP 7.0. If my first question about your switching environments is not the case, perhaps you're doing something very different with your form? Are you able to send us a screenshot of your form inside Freeform Composer? :)

**Comment by martinhellwagner** [comment]
Yes indeed, we were testing the whole thing on our stage environment with PHP 7.1, and then pushed to the production environment (which is running PHP 7.0).

Is there any way to downgrade *all* PHP 7.1 dependencies when kicking off a project on a PHP 7.0 environment?

**Comment by kjmartens** [comment]
You'll want to do `composer install` on your production environment to get the proper dependencies :)

**Comment by martinhellwagner** [comment]
Inserting the `platform` parameter in the `composer.json` and then running `composer update` did the trick: https://github.com/craftcms/cms/issues/2805
