### ISSUE TITLE
v4 custom attributes loading js manually

### ISSUE THREAD

**Issue by joepagan** [solspace/craft3-freeform#550]
**Describe the bug or issue you're experiencing**

Hey, hope all is good. [Your craft v4 docs suggest](https://docs.solspace.com/craft/freeform/v4/developer/js-plugin.html#loading-freeform-js-manually) I can use:

```twig
 {# loading scripts #}
  {{ craft.freeform.loadFreeformPlugin(
    { "data-custom": "attribute" },
    { "extra": "css attribute" }
  ) }}
```

However, it's typed to a string:

> Solspace\Freeform\Variables\FreeformVariable::loadFreeformPlugin(): Argument #1 ($attributes) must be of type ?string, array given, called in /var/www/html/cms/vendor/twig/twig/src/Extension/CoreExtension.php on line 1607

```php
public function loadFreeformPlugin(string $attributes = null, string $styleAttributes = null): Markup
```

So I instead have to use:

```
{{ craft.freeform.loadFreeformPlugin('async defer') }}
```

**Steps to reproduce**

1. as above

**Expected behavior**
1. use example from docs
2. it worky

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 4.3.3
- Freeform Version: "solspace/craft-freeform": "4.0.8",

**Comment by kjmartens** [comment]
Sorry about this @joepagan.

We had another custom stumble into this issue as well. We updated the docs yesterday to have the correct code/syntax: 🙂 

``` twig
<body>
  {# your template code #}

  {{ craft.freeform.loadFreeformPlugin(
    'data-custom="attribute" extra="something else"',
    'css="stuff"'
  ) }}
</body>
```
