### ISSUE TITLE
Unexpected return value with field's valueAsString method

### ISSUE THREAD

**Issue by joepagan** [solspace/craft3-freeform#558]
**Describe the bug or issue you're experiencing**

Hi, in a `Form::EVENT_AFTER_SUBMIT` event, we recently used `$field->valueAsString()` on a radio, but we get the radio's label, not the value.
`$field->getValue()` works as expected.

**Steps to reproduce**

1. request $field->valueAsString() on a radio field value
2. receive the radio field's label

```php
use Solspace\Freeform\Library\Composer\Components\{ FieldInterface, Form };
use Solspace\Freeform\Events\Forms\SubmitEvent;

...
Event::on(
      Form::class,
      Form::EVENT_AFTER_SUBMIT,
      function (SubmitEvent $event) {
        $form = $event->getForm();
        $formFields = $form->getLayout()->getFields();

        foreach ($formFields as $field) {
          $fieldValue = $field->getValue(); // returns value
          $valueAsString = $field->valueAsString(); // returns label
```

**Expected behavior**

return radio's value

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 4.3.3
- Freeform Version: "solspace/craft-freeform": "4.0.8",
- Freeform Edition:
- Fresh Install or Upgrade:

**Additional context**

**Comment by kjmartens** [comment]
Sorry for the trouble @joepagan. I believe this is somewhat intended functionality, but of course is not the best handling and will review this with a developer. 🙂

**Comment by gustavs-gutmanis** [comment]
Hi @joepagan

The method signature for `::valueAsString` is as follows:
```php
public function getValueAsString(bool $optionsAsValues = true): string
```

You should pass `false` to it to receive labels.
I know this is counter intuitive, but it has been like this for quite a while, and changing the behaviour of it now would likely cause trouble for many other people who expect it to work this way.
We will add a deprecation for it and change the way it works for later major versions.

Thanks for bringing this up!
