### ISSUE TITLE
Delete individual spam entry button doesn't work

### ISSUE THREAD

**Issue by darylknight** [solspace/craft3-freeform#561]
**Describe the bug or issue you're experiencing**

**Steps to reproduce**

https://user-images.githubusercontent.com/1250017/208611771-0636c849-ec22-4b36-852e-1757b781913d.mov

1. Select one spam submission
2. Click delete
3. Nothing happens, goes back to listing page. No logs are generated.

**Expected behavior**
Should be deleted

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 4.3.4
- Freeform Version: 4.0.8
- Freeform Edition: Pro

**Comment by kjmartens** [comment]
Thanks for reporting this @darylknight. I can duplicate the issue as well. We'll get it fixed shortly. 🙂

**Comment by kjmartens** [comment]
Sorry for the wait @darylknight. This should be fixed in 4.0.10 now. 🙂
