### ISSUE TITLE
Migration fails on MigrateFormContentTableNamesToSnakeCase

### ISSUE THREAD

**Issue by T-Ivings** [solspace/craft3-freeform#563]
While trying to upgrade some of our sites to Craft 4, we keep running into an issue with the m220530_052327_MigrateFormContentTableNamesToSnakeCase migration. No migrations run and we're given `Exception: Attempt to read property "enabled" on null`. 

**Steps to reproduce**
1. Upgrade Craft & plugins to the latest versions
2. Attempt to run migrations

**Expected behavior**
Migrations are successful

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 3.7.62 -> 4.3.5
- Freeform Version: 3.13.22.1 -> 4.0.9
- Freeform Edition: Pro
- Fresh Install or Upgrade: Upgrade

**Additional context**
According to the stacktrace, it's mad about line 25 of the migration file, `$tables = $this->db->schema->getTableSchemas();`

**Comment by T-Ivings** [comment]
Turns out it was sentry related, improperly written in the `app.php` file. My mistake, not Freeform at all!

**Comment by kjmartens** [comment]
Thanks for following up! Glad it's sorted. 🙂
