### ISSUE TITLE
2 forms exist on 1 template, submitting 1 form will submit both

### ISSUE THREAD

**Issue by joepagan** [solspace/craft3-freeform#564]
**Describe the bug or issue you're experiencing**

Hi, I am having an issue with all forms across a site where submitting 1 form will submit 2 forms on 1 page.
This is on pretty much every template because there is a newsletter signup component on most pages and a contact form.

It was recently upgraded to `4.0.8` from `3.13.19`, but I _think_ this was intermittent before if I am honest!

I had my suspicions that it was to do with Parsley, though having manually redacted that, I think it must be something to do with the freeform plugin events!
I have also tested this on your demo templates manually loading a 2nd form and does the same!

**Steps to reproduce**

If on desktop, we need to partially fill out a 2nd form on the page:

1. have 2 forms on 1 template
2. fill details on form 1
3. ensure form 2 has required field & would fail if submitted
4. submit form 1
5. both forms are attempted to be submitted, form 2 will fail and prevent form 1 from submitting (the freeform plugin submit events fire for both forms)

Strangely, if form 2 is not touched, we can submit the form.

However, on mobile, I have tested in iphone 14 real device on browserstack, and iphone 12 pro in chrome dev tools responsive mode, we only fill in form 1 and the same undesirable behaviour occurs.

**Expected behavior**

submit form 1 and only form 1 to submit
form 2 to be completely ignored

**Craft & Plugin Info (please complete the following information):**

- Craft Version:  "craftcms/cms": "4.3.3",
- Freeform Version: "solspace/craft-freeform": "4.0.8",
- Freeform Edition: genuinely not sure at this point, how
- Fresh Install or Upgrade: Upgrade

**Additional context**
- using reCAPTCHA v2 invisible
- forms are ajax enabled
- using `{{ craft.freeform.loadFreeformPlugin('async defer') }}`
![image](https://user-images.githubusercontent.com/2337910/209186980-69bb2f41-8095-43fa-b1f8-e049b8952933.png)

- When it fails, it is not inherently obvious what has failed unless you have some scroll action, this is really bad for frontend users
- This can be really bad on mobile used because reCAPTCHA challenge will load around form 2 leaving a frontend user perplexed about why form 1 failed.
- If a frontend user does submit form 1 and form 2 gets the reCAPTCHA challenge, and they complete the challenge the submit event on form 1 appears to have been destroyed.

**Comment by kjmartens** [comment]
Hi @joepagan,

Does following the guide here resolve the issues? 🙂 
https://docs.solspace.com/craft/freeform/v4/guides/multiple-instances-of-same-form.html

**Comment by joepagan** [comment]
Hi @kjmartens the issue I am experiencing is with 2 different forms

**Comment by kjmartens** [comment]
@joepagan It could still be an issue with different forms due to some fields being shared/reused. 🙂

**Comment by joepagan** [comment]
Hi @kjmartens that's a bit surprising that sharing fields across forms could cause such damaging results. 

How are devs are expected to know this without warnings all over your docs? Have I missed something glaringly obvious?

I'll try this as soon as I can.

**Comment by kjmartens** [comment]
@joepagan I haven't heard of anyone else report this issue, but I am hoping you can rule out some simpler things. 🙂  It's entirely possible that it's an issue with Freeform that happens under the specific setup you have though. I will check with a developer and see if they have any ideas.

When I try this out in the demo templates using the **Multiple Forms in the Same Page** (`/freeform-demo/extras/multiple-forms/`) example in the Extras area, it seems to work fine as well.
