### ISSUE TITLE
Genuine submissions failing honeypot

### ISSUE THREAD

**Issue by darylknight** [solspace/craft3-freeform#569]
**Describe the bug or issue you're experiencing**
I found several similar issues on this that were closed, but they're either for Freeform 3, or not how our forms are set up. So, both on our own website, and yesterday on a client site, we've noticed that some (not all) genuine submissions are getting tagged as spam beause "Honeypot check failed". Here's how we're set up:

- Not on cloudflare (so no server caching or file changes)
- Forms are not cached with Craft
- Freeform honeypot is enabled
- Javascript enhancement is enabled
- We're using the default templates (Bootstrap 5 for one site, Tailwind 3 for another)
- Freeform Script Insert Type as files

Any idea how I can start to track down why submissions are periodically tagged as spam?

**Expected behavior**
Genuine form submissions shouldn't get tagged as spam

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 4.3.5
- Freeform Version: 4.0.9
- Freeform Edition: Pro
- Fresh Install or Upgrade: Upgrade

**Comment by kjmartens** [comment]
Hi @darylknight,

Is there any chance some of these forms might be left open for (or take longer than) more than 3hrs? The JS Enhancement feature is still limited by the PHP session and could explain this issue. We have plans to see if we can adjust the JS Enhancement check to rely on the encrypted payload (which does not expire) in the future. In the meantime, you may need to disable the JS Enhancement feature if possible.

**Comment by darylknight** [comment]
I think that's unlikely. It happens several times a week, and the one on
our site at least is a very short form (
https://theengineisred.com/careers/freelance-shopify-developer). I'll
disable the enhanced JS and see if that fixes anything :) Thanks!

**Comment by kjmartens** [comment]
If the page (not specifically interacting with the form) is open for more than 2-3 hours, that itself will cause the issue. E.g., a visitor gets to the page with the form, leaves the page tab open and comes back later in the day and begins filling out the form. I agree it does sound a bit excessive that many would fall into that scenario, but as you mention, try disabling that setting anyway and see if the issue persists. 🙂

**Comment by darylknight** [comment]
Got it, thank you. I'll try disabling the enhanced javascript and report back.

**Comment by darylknight** [comment]
There haven't been any more spam submissions since I disabled the enhanced javascript, so going to tentatively mark this as solved, thanks!
