### ISSUE TITLE
Recaptcha not showing after last update in combination with Cookiebot "necessary cookies only"

### ISSUE THREAD

**Issue by mrwijsman** [solspace/craft3-freeform#570]
Since the last update recaptcha wont show unless you accept all cookies when using Cookiebot, I think the cause of this issue is related to the latest patch 4.0.9 

"Updated to only load reCAPTCHA scripts when form(s) have reCAPTCHA enabled."

Cookiebot scans the website once a month and puts them in categopries (marketing, statistics etc) cookies showing up after the scan (or loaded on the fly) are being blocked.

- Craft Version: 4.3.6
- Freeform Version:4.0.9
- Freeform Edition: lite
- Fresh Install or Upgrade: upgrade

**Comment by kjmartens** [comment]
Sorry for the trouble @mrwijsman. I'll check with a developer and get back to you on this.
