### ISSUE TITLE
"Opt-In Data Storage Checkbox" not working correctly

### ISSUE THREAD

**Issue by carolineboeykens** [solspace/craft3-freeform#577]
**Describe the bug or issue you're experiencing**
When we enable the option for the "Opt-In Data Storage Checkbox" the submission is not saving in the database.

**Steps to reproduce**

1. Create a form
2. Create a checkbox field
3. Enable the "Opt-In Data Storage Checkbox" with the option from the checkbox field

<img width="298" alt="Screenshot 2023-01-12 at 12 34 58" src="https://user-images.githubusercontent.com/42932673/212057057-fb1e8bf5-2157-49cb-933c-c466f073e376.png">

**Expected behavior**
If the checkbox is checked in the form the submission should be stored in the database.

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 4.3.6.1
- Freeform Version: 4.0.9
- Freeform Edition: Lite
- Fresh Install or Upgrade: Upgrade

**Additional context**
When the option "Disabled" is selected the submission is stored in the database.
<img width="294" alt="Screenshot 2023-01-12 at 12 34 53" src="https://user-images.githubusercontent.com/42932673/212057147-c7a3baf7-932a-4637-86c1-1f923d9e4d10.png">

The option "Store Submitted Data" is always selected:
<img width="227" alt="Screenshot 2023-01-12 at 12 38 22" src="https://user-images.githubusercontent.com/42932673/212057251-a201249b-4427-46d5-b6ba-d13ce8858994.png">

**Comment by kjmartens** [comment]
Hi @carolineboeykens.

Sorry for the trouble. I can duplicate this in my testing as well. We'll get a fix for it soon. 🙂

**Comment by kjmartens** [comment]
This should now be resolved in Freeform 4.0.11. 🙂
