### ISSUE TITLE
Resumed applications not validating on multi-page AJAX forms

### ISSUE THREAD

**Issue by rwhisson** [solspace/craft3-freeform#589]
When resuming a save and continue, multi-page AJAX form you are unable to proceed past the first step (Page 1) because the form will not validate. If you inspect the network request it appears as though the form is trying to validate fields for the page where you saved the application.

**Steps to reproduce**

1. Create a multi-page AJAX form.
2. Add compulsory fields on each step.
3. Add save and continue buttons.
4. Partially fill out form and save and continue on page that is not the first page.
5. Resume saved application (Page 1 of the multi page form loads and prefills).
6. Click next.
7. Form errors `Sorry, there was an error submitting the form. Please correct any errors and try again.` Cant click next even though all fields are filled and valid.

**Expected behavior**

Form proceeds to where you left off before saving the application when you click next.

**Craft & Plugin Info (please complete the following information):**

- Craft Version: Craft Pro 4.3.6.1
- Freeform Version: 4.0.13
- Freeform Edition: PRO
- Fresh Install or Upgrade:

**Additional context**

**Comment by kjmartens** [comment]
Hi @rwhisson,

I'm very sorry for the delay. In my testing, I cannot reproduce this issue. Can you confirm... is one of the fields you're leaving blank an email field type? Any chance you can send a link or include a video? 🙂

**Comment by rwhisson** [comment]
Hi @kjmartens,

Can confirm its still an issue on 4.0.15.

![step1](https://user-images.githubusercontent.com/58797014/219275335-5b4edad3-e3c4-427f-a299-220b5fa9171e.png)
![step2](https://user-images.githubusercontent.com/58797014/219275350-1aef49e0-36d5-44a6-a043-9effef81a7a1.png)
![step3](https://user-images.githubusercontent.com/58797014/219275365-654195e5-274b-4dc2-89bb-832412028eb5.png)
** click `save and continue later`
![resume](https://user-images.githubusercontent.com/58797014/219275379-1c12d394-b08d-44bc-83c0-c70fe14fe69e.png)
![request-headers](https://user-images.githubusercontent.com/58797014/219275529-81eb9668-6843-4419-a9e6-f5d0bad59e6e.png)
![json-response](https://user-images.githubusercontent.com/58797014/219275542-9d5c5ee7-8be7-4819-9f95-87977fdbd189.png)

After resuming the application I cant proceed past step0 because its trying to validate against step2. Even entering all the required fields before saving and continuing still presents the error. I have attached the below stack trace showing how its trying to validate against step2.

```#0 /var/www/html/vendor/solspace/craft-freeform/packages/plugin/src/Bundles/Form/Context/Pages/PageContext.php(122): Solspace\Freeform\Library\Composer\Components\Form->setCurrentPage(2)
#1 [internal function]: Solspace\Freeform\Bundles\Form\Context\Pages\PageContext->handleFormPageJump(Object(Solspace\Freeform\Events\Bags\BagModificationEvent))
#2 /var/www/html/vendor/yiisoft/yii2/base/Event.php(312): call_user_func(Array, Object(Solspace\Freeform\Events\Bags\BagModificationEvent))
#3 /var/www/html/vendor/solspace/craft-freeform/packages/plugin/src/Library/Bags/AbstractBag.php(51): yii\base\Event::trigger('Solspace\\Freefo...', 'set', Object(Solspace\Freeform\Events\Bags\BagModificationEvent))
#4 /var/www/html/vendor/solspace/craft-freeform/packages/plugin/src/Library/Bags/AbstractBag.php(75): Solspace\Freeform\Library\Bags\AbstractBag->set('pageIndex', 2)
#5 /var/www/html/vendor/solspace/craft-freeform/packages/plugin/src/Bundles/Form/Context/Session/SessionContext.php(166): Solspace\Freeform\Library\Bags\AbstractBag->merge(Array)
#6 [internal function]: Solspace\Freeform\Bundles\Form\Context\Session\SessionContext->retrieveContext(Object(Solspace\Freeform\Events\Forms\HandleRequestEvent))
#7 /var/www/html/vendor/yiisoft/yii2/base/Event.php(312): call_user_func(Array, Object(Solspace\Freeform\Events\Forms\HandleRequestEvent))
#8 /var/www/html/vendor/solspace/craft-freeform/packages/plugin/src/Library/Composer/Components/Form.php(765): yii\base\Event::trigger('Solspace\\Freefo...', 'before-handle-r...', Object(Solspace\Freeform\Events\Forms\HandleRequestEvent))
#9 /var/www/html/vendor/solspace/craft-freeform/packages/plugin/src/Controllers/SubmitController.php(52): Solspace\Freeform\Library\Composer\Components\Form->handleRequest(Object(craft\web\Request))
#10 [internal function]: Solspace\Freeform\Controllers\SubmitController->actionIndex()
#11 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#12 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#13 /var/www/html/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('', Array)
#14 /var/www/html/vendor/craftcms/cms/src/web/Application.php(301): yii\base\Module->runAction('freeform/submit', Array)
#15 /var/www/html/vendor/craftcms/cms/src/web/Application.php(625): craft\web\Application->runAction('freeform/submit', Array)
#16 /var/www/html/vendor/craftcms/cms/src/web/Application.php(280): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#17 /var/www/html/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest(Object(craft\web\Request))
#18 /var/www/html/web/index.php(29): yii\base\Application->run()

#0 /var/www/html/vendor/solspace/craft-freeform/packages/plugin/src/Library/Composer/Components/Form.php(772): Solspace\Freeform\Library\Composer\Components\Form->validate()
#1 /var/www/html/vendor/solspace/craft-freeform/packages/plugin/src/Controllers/SubmitController.php(52): Solspace\Freeform\Library\Composer\Components\Form->handleRequest(Object(craft\web\Request))
#2 [internal function]: Solspace\Freeform\Controllers\SubmitController->actionIndex()
#3 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#4 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#5 /var/www/html/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('', Array)
#6 /var/www/html/vendor/craftcms/cms/src/web/Application.php(301): yii\base\Module->runAction('freeform/submit', Array)
#7 /var/www/html/vendor/craftcms/cms/src/web/Application.php(625): craft\web\Application->runAction('freeform/submit', Array)
#8 /var/www/html/vendor/craftcms/cms/src/web/Application.php(280): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#9 /var/www/html/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest(Object(craft\web\Request))
#10 /var/www/html/web/index.php(29): yii\base\Application->run()```

**Comment by kjmartens** [comment]
Hi @rwhisson, I'll get a developer involved, but in the meantime, are you able to try [installing the demo templates](https://docs.solspace.com/craft/freeform/v4/setup/demo-templates.html) included with Freeform and go to the Bootstrap area and see if this feature works correctly there? 🙂

**Comment by rwhisson** [comment]
Hi @kjmartens, I believe you can close this as we were using a neo block freeform object to render the form which was causing the issues.

`{{ block.freeformForm.render(formOptions) }}`

changed to

`{{ craft.freeform.form(block.freeformForm.handle).render(formOptions) }}`

Thanks for your help.
