### ISSUE TITLE
Email Notification Template Storage Type of 'File' Continues to Display 'Database' Templates

### ISSUE THREAD

**Issue by bfopma** [solspace/craft3-freeform#598]
**Describe the bug or issue you're experiencing**
After upgrading from latest version of Craft 3 Freeform to Craft 4 Freeform, I've selected the Email Template Storage Type of 'File'. However, when assigning email notification templates in a form, the existing database templates continue to display as an option. 

<img width="255" alt="image" src="https://user-images.githubusercontent.com/6729531/219082485-a3cb2167-ac1a-4af5-8bb2-4ac047c0580f.png">

<img width="216" alt="image" src="https://user-images.githubusercontent.com/6729531/219082251-c85f82de-e568-495f-a7e2-1e40c0a14a74.png">

Freeform provides a migration option to convert existing database templates to file-based ones; however, this process doesn't impact Project Config so it must be re-run in a production environment. This also requires the production environment to have 'allowAdminChanges' set to 'true', as well as file permissions to write to the templates directory on the filesystem.

**Expected behavior**

I would expect that Freeform would ignore existing database email notification templates if 'File' is selected as the Template Storage Type. Alternately, I would expect the database template migration process to update Project Config so that changes can be deployed from a development environment over to production.

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 4.3.9
- Freeform Version: 4.0.14
- Freeform Edition: Pro
- Fresh Install or Upgrade: Upgrade from Craft 3

**Comment by kjmartens** [comment]
Thanks for reporting this @bfopma. We'll check into it soon. 🙂

**Comment by kjmartens** [comment]
Sorry, I forgot to mention that this has been resolved in 4.0.18+ 🙂
