### ISSUE TITLE
Deactivate Include Attachments? does not work. Also saving some input fields

### ISSUE THREAD

**Issue by skramstad** [solspace/craft3-freeform#6]
Hi.

I created an Email Notification. The field Include Attachments? was deactivated on first save. But when I go back to edit the template it's on and now I cant deactivate it.

Another thing is that If I edit the Email body text, it resets after saving. So I guess something is not saved properly.

I see the same issue for Reply-to Email field.

Freeform Lite v2.0.0-beta.2.

Thanks!

**Comment by kjmartens** [comment]
Thanks, this will be fixed in the next release. :)
