### ISSUE TITLE
plugin.js taking very long to load

### ISSUE THREAD

**Issue by TUSAB-web** [solspace/craft3-freeform#624]
**Describe the bug or issue you're experiencing**

**Steps to reproduce**

1. Load the page
2. Wait 6 seconds for plugin.js to load

**Expected behavior**

The file is only 100k, so not sure why this is happening.

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 4.3.5 Pro
- Freeform Version: 4.0.9
- Freeform Edition: Pro
- Fresh Install or Upgrade: Upgrade

**Additional context**

**Comment by kjmartens** [comment]
Sorry for the trouble you're experiencing @TUSAB-web. I haven't heard of an issue like this before, but I'm curious if changing the **Freeform Script Insert Type** (Craft CP -> Freeform -> Settings -> Form Behavior) setting to **As Files** makes any difference? 🙂

**Comment by TUSAB-web** [comment]
I did as you suggested, and also updated the site to the latest version of Craft and Freeform. I am now seeing that forms are not submitting. I am now going through the documentation in Freeform regarding Submitting forms on cached pages, as well as custom success messages. It looks like some things have changed and I need to update my templates. I will hopefully find the problem, and then I can test if loading the plug-in.js will go faster.

**Comment by kjmartens** [comment]
Please let me know if you need any further assistance, @TUSAB-web. I would just need more information to have a better idea of what the issue might be. 🙂

**Comment by TUSAB-web** [comment]
Thanks, it appears to have been a server latency issue. 99% of the site is cached and loads directly from the files, so I didn’t spot the issue before. I will work on solving that separately. As for the forms not working at all, it was a change to the way the CSRF token was imported. In older versions, it was required that {% do form.registerContext %} be in the dynamic loading script. But the new version doesn’t require that. I took that line out and it seems to be working properly now.
