### ISSUE TITLE
Blank form page

### ISSUE THREAD

**Issue by StuartMcD** [solspace/craft3-freeform#625]
So, decided to update local to latest everything. Al lwent well until now: click on forms, see list of all forms, click on a form, the URL and H1 change but no form is loaded.

All front end pages and behaviors look to be fine.

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 4.4.1
- Freeform Version: 4.0.18
- Freeform Edition: pro
- Fresh Install or Upgrade: Upgrade

I did install [Cloner](https://plugins.craftcms.com/cloner?craft4) prior to upgrade - disabled it and problem still persists.
Getting a few console errors relating to JS on form listing page:
Uncaught SyntaxError: unexpected token: keyword 'return'
[vendor.js:2:699928](https://soccer.test/cpresources/6fc97b59/js/app/vendor.js?v=1678517923)
Uncaught SyntaxError: missing ) after argument list
[form-modal.js:1:24580](https://soccer.test/cpresources/6fc97b59/js/app/form-modal.js?v=1678517923)

​
Then empty form view page:
Uncaught SyntaxError: unexpected token: string literal
[builder.js:2:757619](https://soccer.test/cpresources/6fc97b59/js/builder/builder.js?v=1678517923)

​
Will be reverting until futher notice.

**Comment by kjmartens** [comment]
Sorry for this @StuartMcD. Which version of Freeform did you have prior to the update?

**Comment by StuartMcD** [comment]
4.0.16

**Comment by kjmartens** [comment]
Hi @StuartMcD,

We now have hundreds of customers using 4.0.18 and don't have any other reports of this issue. I'm wondering if there was some kind of a glitch or something specific to your setup.

Is this issue still happening for you? Does it happen for any form you attempt to load? Does it happen when you attempt to create a new form? 🙂

**Comment by StuartMcD** [comment]
If I upgrade Freeform before I update Craft, forms layout disappears BUT if I upgrade Craft then Freeform it works. 

Could be my Docker/ddev contributing as `composer update` cmd would work erratically and not fire on changing version numbers in composer file.

**Comment by kjmartens** [comment]
Ok, thanks for the update @StuartMcD. 🙂
