### ISSUE TITLE
Submissions not accessible in CP, no blue link in submission titles

### ISSUE THREAD

**Issue by tsawitzki** [solspace/craft3-freeform#633]
In the CP submissions show up in the list underneath the rendered stats diagram; however they are not blue and clickable as seen in the official documentation screenshots (and as expected behaviour-wise). 
CSV export works as expected, showing all the indiviual entries. However we want to access the entries from the CP, too.

**Steps to reproduce**

1. Submit something to any form
2. Try to access individual submission data

**Expected behavior**
s. above

**Craft & Plugin Info (please complete the following information):**

- Craft Version: Craft CMS 4.3.3
- Freeform Version: 4.0.7
- Freeform Edition: Lite
- Fresh Install or Upgrade: Fresh Install

**Comment by kjmartens** [comment]
Hi @tsawitzki,

Sorry for the trouble you're experiencing. This was an issue that was addressed in 4.0.8. 🙂 
https://docs.solspace.com/craft/freeform/v4/setup/changelog.html#_4-0-8-2022-11-21

You'll just need to upgrade. 🙂
