### ISSUE TITLE
Json Decode error after updating.

### ISSUE THREAD

**Issue by Mark8ken** [solspace/craft3-freeform#635]
**Describe the bug or issue you're experiencing**
Internal server error on the admin dashboard, form editing and submission viewing.
Forms appear to be working via the front end.

**Steps to reproduce**
We were running a number of updates, all successful on our staging env.
I believe Freeform updated successfully.
Ran a Blitz update, and it failed, the restore DB process then failed and the error began to appear.

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 3.8.2
- Freeform Version: 3.13.26
- Freeform Edition: Pro
- Fresh Install or Upgrade: Upgrade

**Additional context**
Blitz is disabled, dashboard works when the app is deactivated.
Have seen this error in the past, previously solved by re-installing, however, we had to rebuild forms.

Log info:
GuzzleHttp\Exception\InvalidArgumentException: json_decode error: Syntax error in /home/client-name/vendor/guzzlehttp/guzzle/src/Utils.php:278 Stack trace:
 #0 /home/client-name/vendor/guzzlehttp/guzzle/src/functions.php(149): GuzzleHttp\Utils::jsonDecode('{"options":[{"l...', true, 512, 0)
 #1 /home/client-name/vendor/solspace/craft-freeform/packages/plugin/src/Services/FieldsService.php(501): GuzzleHttp\json_decode('{"options":[{"l...', true)
 #2 /home/client-name/vendor/solspace/craft-freeform/packages/plugin/src/Services/FieldsService.php(88): Solspace\Freeform\Services\FieldsService->createField(Array)
 #3 /home/client-name/vendor/solspace/craft-freeform/packages/plugin/src/Widgets/Pro/FieldValuesWidget.php(125): Solspace\Freeform\Services\FieldsService->getAllFields()
 #4 /home/client-name/vendor/craftcms/cms/src/controllers/DashboardController.php(76): Solspace\Freeform\Widgets\Pro\FieldValuesWidget->getSettingsHtml()
 #5 /home/client-name/vendor/craftcms/cms/src/web/View.php(1529): craft\controllers\DashboardController->craft\controllers\{closure}()
 #6 /home/client-name/vendor/craftcms/cms/src/controllers/DashboardController.php(77): craft\web\View->namespaceInputs(Object(Closure), '__NAMESPACE__')
 #7 [internal function]: craft\controllers\DashboardController->actionIndex()
 #8 /home/client-name/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
 #9 /home/client-name/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
 #10 /home/client-name/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('index', Array)
 #11 /home/client-name/vendor/craftcms/cms/src/web/Application.php(293): yii\base\Module->runAction('dashboard/index', Array)
 #12 /home/client-name/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('dashboard/index', Array)
 #13 /home/client-name/vendor/craftcms/cms/src/web/Application.php(278): yii\web\Application->handleRequest(Object(craft\web\Request))
 #14 /home/client-name/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest(Object(craft\web\Request))
 #15 /home/client-name/public_html/index.php(21): yii\base\Application->run()
 #16 {main}

**Comment by kjmartens** [comment]
Sorry for the trouble @MarkAitken-eBrands,

Are you able to test out the latest I committed to the repo and see if that resolves this issue? 🙂 

In your site's main `composer.json` file, update your version of `solspace/craft-freeform`  to be `dev-fix/SFT-294 as 3.13.27.1` and try running `composer update` to grab it.

**Comment by Mark8ken** [comment]
That has fixed the issue, thank you! 

However, I get an alert that says my license is only for standard but I have Pro installed. 

I do have a license for pro.

**Comment by kjmartens** [comment]
@MarkAitken-eBrands licensing and validation issues like this are completely out of our control. You may need to contact the Craft support team for this one. But first, can you check and see if it's something simple that can be addressed with one of these solutions? 🙂 
https://docs.solspace.com/craft/freeform/v4/setup/installing-updating.html#changing-editions
