### ISSUE TITLE
Purge commands not working

### ISSUE THREAD

**Issue by joelstrom** [solspace/craft3-freeform#639]
Hello!

We would like to purge all of our submissions from website's forms, but noticed that the console command to do that does not seem to do much.

Running a command like ./craft freeform/purge/submissions --age-in-days=1 gives the following:
Purging submissions which are at least 1 days old...

Purged 0 submissions
Purged 0 assets

This happens even if there are thousands of submissions saved.

A workaround could be to simply do it manually through the backend, but the action itself seems to be so heavy that it might cause the server to become very slow or unresponsive as a result.

Any help would be greatly appreciated!

Freeforms version: 3.13.27
Craft version: 3.8.5

**Comment by kjmartens** [comment]
Hi @joelstrom,

I have tested this on my end and it seems like `./craft freeform/purge/submissions --age-in-days=1` works fine, but there may potentially be an issue with the Spam purge command `./craft freeform/purge/spam --age-in-days=1`

Just to confirm, are you trying to purge regular submissions or spam submissions? And if so, roughly how many do you have on the site? 🙂

**Comment by joelstrom** [comment]
Hello!

Both commands give the same response, as if nothing would happen:

<img width="517" alt="Screenshot 2023-03-27 at 11 02 57" src="https://user-images.githubusercontent.com/15905441/227879298-1dcb186a-50ba-45eb-8ce7-3e5a47c00c1c.png">

On my local install I have 2407 submissions, in other environments where we also get the same issue a bit more:

<img width="337" alt="Screenshot 2023-03-27 at 11 00 55" src="https://user-images.githubusercontent.com/15905441/227878567-d5b964e3-9a5a-4f8c-b64c-fff5e0074b0d.png">

**Comment by kjmartens** [comment]
I just wanted to let you know we're looking into this issue and hope to have a solution next week. 🙂

**Comment by joelstrom** [comment]
thank you for the update!

**Comment by kjmartens** [comment]
This should be fixed in v4.0.22. Thanks for your patience! 🙂
