### ISSUE TITLE
TypeError Solspace\Freeform\Library\Session\Honeypot::createFromUnserializedData(): Argument #1 ($data) must be of type array

### ISSUE THREAD

**Issue by icreatestuff** [solspace/craft3-freeform#641]
**Describe the bug or issue you're experiencing**

Updated from Freeform v4.0.19 to v4.0.20 and now on frontend pages with forms I get the following

```
TypeError

Solspace\Freeform\Library\Session\Honeypot::createFromUnserializedData(): Argument #1 ($data) must be of type array,
Solspace\Freeform\Library\Session\Honeypot given, called in /Users/mymac/Sites/sbs/vendor/solspace/craft-freeform/packages/plugin/src/Services/HoneypotService.php on line 217
```

The highlighted function in `Honeypot.php` is

```php
public static function createFromUnserializedData(array $data): self
{
        $honeypot = new self();
        $honeypot->name = $data['name'];
        $honeypot->hash = $data['hash'];
        $honeypot->timestamp = $data['timestamp'];
 
        return $honeypot;
}
```

No other code changes took place.

Backend Spam Settings as shown.

![Screenshot 2023-03-28 at 21 52 10](https://user-images.githubusercontent.com/1300714/228364063-365fe0df-6b48-44dc-9f8e-ca324cd8f1b4.png)

**Craft & Plugin Info (please complete the following information):**

- Craft Version: Pro 4.4.5
- Freeform Version: 4.0.20
- Freeform Edition: Pro
- Fresh Install or Upgrade: Upgrade

**Comment by kjmartens** [comment]
Sorry for the trouble @icreatestuff.

Can you send a screenshot of the Diagnostics page (inside Freeform settings) for this site? 🙂

**Comment by icreatestuff** [comment]
Sure thing, here you go

![Screenshot 2023-03-28 at 22 19 42](https://user-images.githubusercontent.com/1300714/228369427-10f7844d-aee4-4cd9-9473-5341ad976f83.png)

**Comment by kjmartens** [comment]
@icreatestuff can you try updating to v4.0.21? It should resolve this issue for you now. 🙂

**Comment by icreatestuff** [comment]
Thanks @kjmartens that seems to have done the trick 👍
