### ISSUE TITLE
Honeypot protection is broken past 4.0.19

### ISSUE THREAD

**Issue by bymayo** [solspace/craft3-freeform#648]
Since updating a project from Craft 3 > Craft 4, we used the latest versions of Freeform 4.0.20 and 4.0.21 but our client flagged that forms would just "Refresh" and not submit. When we checked this seemed to be an issue with ALL form submissions being flagged as spam.

We disabled honeypot JS enhancement protection and the forms submit fine, but the client got increased spam. So we tested a few versions and it seems that with JS honeypot enhancement on, this works at 4.0.19, but not any higher.

I can see a few honeypot fixes in the latest 2 versions, so i suspect these arent working correctly.

We're using Blitz so run the solution to get Freeform to work with cached pages (https://docs.solspace.com/craft/freeform/v3/templating/caching.html#static-page-caching-cdn-blitz) and this has been fine for years on Craft 3. So has something changed in this that we need to amend? 

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 4.4.6.1
- Freeform Version: 4.0.19 (But issue is on any version higher than this)
- Freeform Edition: Pro
- Fresh Install or Upgrade: Upgrade

**Comment by kjmartens** [comment]
Sorry for the trouble @bymayo. We did make some changes to the JS Honeypot recently. Just to confirm, does the issue only happen when the form is cached? We'll investigate this shortly. 🙂

**Comment by kjmartens** [comment]
@bymayo, can you try adding this to your script to refreshing tokens, etc?

```
// Update the Payload if encrypted payloads are enabled
form.querySelector('input[name=freeform_payload]').value = response.payload;
```

That might be all that is necessary. We're updating our documentation to mention this. 🙂
