### ISSUE TITLE
 disable hCaptcha depending on the URL Param

### ISSUE THREAD

**Issue by wafamustafa** [solspace/craft3-freeform#651]
I'm trying to disable hCaptcha depending on the URL Param and I cant seem to achieve the end result. I've updated the template code as per documentation to use "disableRecaptcha: true" but it doesn't seem to trigger the change
**Steps to reproduce**

``` twig
{% set formHandle = block.handle %}

{% if craft.request.getParam('giTest') is not null %}
    {% set disableRecaptcha = 'disableRecaptcha: true' %}
{% else %}
    {% set disableRecaptcha = 'disableRecaptcha: false' %}
{% endif %}

{{ craft.freeform.form(formHandle, {
    "id": formHandle,
    "class": "form-horizontal inline "~formHandle,
    disableRecaptcha
}).render() }}
```

**Expected behavior**
When working correctly should not show captcha

**Craft & Plugin Info (please complete the following information):**

- Craft Version: Craft Pro 3.7.56
- Freeform Version: 3.13.20
- Freeform Edition:
- Fresh Install or Upgrade:

**Comment by kjmartens** [comment]
Sorry for the delay @wafamustafa.

I just tested this on my end, and using the `disableRecaptcha: true` parameter correctly disables hCaptcha Invisible. Please note that this parameter does not apply to reCAPTCHA v2 Checkbox or hCaptcha Checkbox. 🙂
