### ISSUE TITLE
`inputClass` values are appended when the same form is output multiple times

### ISSUE THREAD

**Issue by johndwells** [solspace/craft3-freeform#659]
I have 2 instances of the same form being rendered on the page (one of them is rendered in a modal). The design requires that the `class=` attributes on each form's input fields differ.

To customize the input field class, we simply specify [`inputClass`](https://docs.solspace.com/craft/freeform/v4/templates/queries/form/#inputclass) values when rendering the form.

However when rendering the same form twice, the 2nd rendered form input's classes **includes** values from the 1st form's  values.

**Steps to reproduce**

```
{{ craft.freeform.form('getInTouch', {
    inputClass: 'example-class-1'
}).render() }}
{# Outputs:
<input class="freeform-input example-class-1 "
            name="name" type="text" id="form-input-name" placeholder="Name" data-required="">
#}

{{ craft.freeform.form('getInTouch', {
    inputClass: 'example-class-2'
}).render() }}
{# Outputs:
<input class="freeform-input example-class-1  freeform-input example-class-2 " 
            name="name" type="text" id="form-input-name" placeholder="Name" data-required="">
#}
```

As you can see, the 2nd render class value is "freeform-input example-class-1  freeform-input example-class-2 ".

**Expected behavior**

The 2nd form input render should be just:

```
<input class="freeform-input example-class-2 "
            name="name" type="text" id="form-input-name" placeholder="Name" data-required="">
```

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 4.4.7.1
- Freeform Version: 4.0.22
- Freeform Edition: Pro
- Fresh Install or Upgrade: N/A

**Comment by kjmartens** [comment]
Hi @johndwells,

It's a known issue that sometimes a snowballing effect of classes like this can happen under certain conditions. This will be resolved in an upcoming major version of Freeform. However, have you tried adding a unique `id` parameter for each form as well? 🙂 
https://docs.solspace.com/craft/freeform/v4/guides/multiple-instances-of-same-form/

If nothing else, you could at least apply CSS to the form inputs through the form ID if you add this.

**Comment by johndwells** [comment]
Hi @kjmartens thanks for confirming the issue! Yes we can workaround it in a manner you describe.

**Comment by kjmartens** [comment]
Thanks @johndwells 🙂
