### ISSUE TITLE
Submissions wrongly marked as spam

### ISSUE THREAD

**Issue by FrDH** [solspace/craft3-freeform#674]
**Describe the bug or issue you're experiencing**
For apparently no reason, submissions pretty regularly (a couple of times a day) are wrongly marked as spam. This happens for quite a lot of our clients and we can't figure out why. The submissions all are "marked as spam because": Honeypot check failed.

Our form behavior- and spam-settings:
![Scherm­afbeelding 2023-05-05 om 15 49 12](https://user-images.githubusercontent.com/1387163/236476207-3bfd6585-2ac1-471f-8913-84cbf7e7b0c1.png)
![Scherm­afbeelding 2023-05-05 om 15 45 43](https://user-images.githubusercontent.com/1387163/236476228-ab582173-4311-417f-be15-d4ceea4a7807.png)

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 3.8.7
- Freeform Version: 3.13.28
- Freeform Edition: PRO
- Fresh Install or Upgrade:

**Additional context**
This has been happening for quite some time now, for multiple clients in different craft / freeform versions (all craft 3). We've been breaking our heads over this for way too long now and would really like some grip on how to handle this issue.

Thanks in advance.

**Comment by kjmartens** [comment]
Hi @FrDH,

I'm very sorry for the trouble you've been experiencing.

With the information you've given, my best guess is that it has to do with the enabling of the JS enhancement feature and enough time passing on the page for the PHP session to time out. This is an issue we recently addressed in Freeform 4, but I will queue it up to have a developer port that change over to Freeform 3 as well.

In the meantime, is it possible to disable the JS enhancement feature? I anticipate us having this change available on May 8 or 9. 🙂

**Comment by FrDH** [comment]
I'll discuss with the team, but without the JS enhancement, the spambox used to explode :/
I forgot to mention, but we've set the PHP session timeout to 2 hours. The logs show that some of the spam-submissions were submitted after only 2 minutes.
We'll be sure to update may 10th :)
Thanks!

**Comment by kjmartens** [comment]
Ok, good to know. I wonder if those 2-min ones were somehow still affected by this. Let's see what happens after the change in `3.13.29`. If any continue to be incorrectly flagged as spam, we'll work closely with you to ensure we get to the bottom of it. 🙂

**Comment by kjmartens** [comment]
Should be resolved in 3.13.29 now @FrDH 🙂 

If using caching, just be sure to additionally include the `payload` (see examples in docs link below):
https://docs.solspace.com/craft/freeform/v3/templating/caching/

**Comment by FrDH** [comment]
Thanks for the quick responses. I just updated some sites to use 3.13.29, I'll report back if about (lack of) noticeable changes :)

**Comment by FrDH** [comment]
3.13.29 seems to have fixed the issue, a week after updating there were no new submissions wrongly marked as spam.
Thanks again.

**Comment by kjmartens** [comment]
Excellent! Thanks @FrDH 🙂
