### ISSUE TITLE
Can't add Freeform Field Value widget 

### ISSUE THREAD

**Issue by WHITE-developer** [solspace/craft3-freeform#690]
When we try to add the Freeform Field Value widget we get the following error message in the logs:

[web.ERROR] [TypeError] Solspace\Freeform\Elements\Submission::getFieldColumnName(): Argument #1 ($field) must be of type Solspace\Freeform\Library\Composer\Components\FieldInterface, string given, called in /var/www/html/vendor/solspace/craft-freeform/packages/plugin/src/Widgets/Pro/FieldValuesWidget.php on line 158

In the CP we get the message 'Couldn’t save widget', but in the DB the row was still added to the widgets table. This will cause in internal server error the next time you hit the CP dashboard with the same error as in the logs.

It looks like it doesn't matter which options you choose while adding the widget. We made sure that the form does have the field that chosen.

**Craft & Plugin Info**

- Craft Version: 4.4.8
- Freeform Version: 4.0.24.1
- Freeform Edition: Pro

**Comment by kjmartens** [comment]
Sorry for the trouble @WHITE-developer. I can duplicate this issue as well and we'll get a fix for it shortly. 🙂

**Comment by kjmartens** [comment]
This is now fixed in Freeform 4.0.25 🙂

**Comment by nixondesigndev** [comment]
Ah thanks guys, that’s great :)

Best wishes
Helen Connole
