### ISSUE TITLE
Error installing with composer

### ISSUE THREAD

**Issue by rivvakili** [solspace/craft3-freeform#7]
Hi
When I try to access the craft admin after installling the plugin via the composer I get following error:
Craft CMS 3 RC 7 , Freeform beta 3 (and 2), Mysql 5.7.17

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'my7cych01v6ycydg.craft_freeform_unfinalized_files' doesn't exist
The SQL being executed was: SELECT `assetId`
FROM `craft_freeform_unfinalized_files`
WHERE dateCreated < '2018-01-29 16:08:41'

PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'my7cych01v6ycydg.craft_freeform_unfinalized_files' doesn't exist in C:\xampp\htdocs\friday-magazine\vendor\yiisoft\yii2\db\Command.php:1067
Stack trace:
#0 C:\xampp\htdocs\friday-magazine\vendor\yiisoft\yii2\db\Command.php(1067): PDOStatement->execute()
#1 C:\xampp\htdocs\friday-magazine\vendor\yiisoft\yii2\db\Command.php(429): yii\db\Command->queryInternal('fetchAll', 7)
#2 C:\xampp\htdocs\friday-magazine\vendor\yiisoft\yii2\db\Query.php(292): yii\db\Command->queryColumn()
#3 C:\xampp\htdocs\friday-magazine\vendor\craftcms\cms\src\db\Query.php(168): yii\db\Query->column(NULL)
#4 C:\xampp\htdocs\friday-magazine\vendor\solspace\craft3-freeform\src\Services\FilesService.php(152): craft\db\Query->column()
#5 C:\xampp\htdocs\friday-magazine\vendor\solspace\craft3-freeform\src\Freeform.php(263): Solspace\Freeform\Services\FilesService->cleanUpUnfinalizedAssets()
#6 C:\xampp\htdocs\friday-magazine\vendor\yiisoft\yii2\base\BaseObject.php(108): Solspace\Freeform\Freeform->init()
#7 C:\xampp\htdocs\friday-magazine\vendor\yiisoft\yii2\base\Module.php(158): yii\base\BaseObject->__construct(Array)
#8 C:\xampp\htdocs\friday-magazine\vendor\craftcms\cms\src\base\Plugin.php(88): yii\base\Module->__construct('freeform', Object(craft\web\Application), Array)
#9 [internal function]: craft\base\Plugin->__construct('freeform', Object(craft\web\Application), Array)
#10 C:\xampp\htdocs\friday-magazine\vendor\yiisoft\yii2\di\Container.php(381): ReflectionClass->newInstanceArgs(Array)
#11 C:\xampp\htdocs\friday-magazine\vendor\yiisoft\yii2\di\Container.php(156): yii\di\Container->build('Solspace\\Freefo...', Array, Array)
#12 C:\xampp\htdocs\friday-magazine\vendor\yiisoft\yii2\BaseYii.php(349): yii\di\Container->get('Solspace\\Freefo...', Array, Array)
#13 C:\xampp\htdocs\friday-magazine\vendor\craftcms\cms\src\services\Plugins.php(777): yii\BaseYii::createObject(Array, Array)
#14 C:\xampp\htdocs\friday-magazine\vendor\craftcms\cms\src\services\Plugins.php(196): craft\services\Plugins->createPlugin('freeform', Array)
#15 C:\xampp\htdocs\friday-magazine\vendor\craftcms\cms\src\base\ApplicationTrait.php(1167): craft\services\Plugins->loadPlugins()
#16 C:\xampp\htdocs\friday-magazine\vendor\craftcms\cms\src\web\Application.php(95): craft\web\Application->_init()
#17 C:\xampp\htdocs\friday-magazine\vendor\yiisoft\yii2\base\BaseObject.php(108): craft\web\Application->init()
#18 C:\xampp\htdocs\friday-magazine\vendor\yiisoft\yii2\base\Application.php(206): yii\base\BaseObject->__construct(Array)
#19 C:\xampp\htdocs\friday-magazine\vendor\craftcms\cms\src\web\Application.php(83): yii\base\Application->__construct(Array)
#20 [internal function]: craft\web\Application->__construct(Array)
#21 C:\xampp\htdocs\friday-magazine\vendor\yiisoft\yii2\di\Container.php(381): ReflectionClass->newInstanceArgs(Array)
#22 C:\xampp\htdocs\friday-magazine\vendor\yiisoft\yii2\di\Container.php(156): yii\di\Container->build('craft\\web\\Appli...', Array, Array)
#23 C:\xampp\htdocs\friday-magazine\vendor\yiisoft\yii2\BaseYii.php(349): yii\di\Container->get('craft\\web\\Appli...', Array, Array)
#24 C:\xampp\htdocs\friday-magazine\vendor\craftcms\cms\bootstrap\bootstrap.php(243): yii\BaseYii::createObject(Array)
#25 C:\xampp\htdocs\friday-magazine\vendor\craftcms\cms\bootstrap\web.php(42): require('C:\\xampp\\htdocs...')
#26 C:\xampp\htdocs\friday-magazine\web\index.php(41): require('C:\\xampp\\htdocs...')
#27 {main}

Next yii\db\Exception: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'my7cych01v6ycydg.craft_freeform_unfinalized_files' doesn't exist
The SQL being executed was: SELECT `assetId`
FROM `craft_freeform_unfinalized_files`
WHERE dateCreated < '2018-01-29 16:08:41' in C:\xampp\htdocs\friday-magazine\vendor\yiisoft\yii2\db\Schema.php:595
Stack trace:
#0 C:\xampp\htdocs\friday-magazine\vendor\yiisoft\yii2\db\Command.php(1082): yii\db\Schema->convertException(Object(PDOException), 'SELECT `assetId...')
#1 C:\xampp\htdocs\friday-magazine\vendor\yiisoft\yii2\db\Command.php(429): yii\db\Command->queryInternal('fetchAll', 7)
#2 C:\xampp\htdocs\friday-magazine\vendor\yiisoft\yii2\db\Query.php(292): yii\db\Command->queryColumn()
#3 C:\xampp\htdocs\friday-magazine\vendor\craftcms\cms\src\db\Query.php(168): yii\db\Query->column(NULL)
#4 C:\xampp\htdocs\friday-magazine\vendor\solspace\craft3-freeform\src\Services\FilesService.php(152): craft\db\Query->column()
#5 C:\xampp\htdocs\friday-magazine\vendor\solspace\craft3-freeform\src\Freeform.php(263): Solspace\Freeform\Services\FilesService->cleanUpUnfinalizedAssets()
#6 C:\xampp\htdocs\friday-magazine\vendor\yiisoft\yii2\base\BaseObject.php(108): Solspace\Freeform\Freeform->init()
#7 C:\xampp\htdocs\friday-magazine\vendor\yiisoft\yii2\base\Module.php(158): yii\base\BaseObject->__construct(Array)
#8 C:\xampp\htdocs\friday-magazine\vendor\craftcms\cms\src\base\Plugin.php(88): yii\base\Module->__construct('freeform', Object(craft\web\Application), Array)
#9 [internal function]: craft\base\Plugin->__construct('freeform', Object(craft\web\Application), Array)
#10 C:\xampp\htdocs\friday-magazine\vendor\yiisoft\yii2\di\Container.php(381): ReflectionClass->newInstanceArgs(Array)
#11 C:\xampp\htdocs\friday-magazine\vendor\yiisoft\yii2\di\Container.php(156): yii\di\Container->build('Solspace\\Freefo...', Array, Array)
#12 C:\xampp\htdocs\friday-magazine\vendor\yiisoft\yii2\BaseYii.php(349): yii\di\Container->get('Solspace\\Freefo...', Array, Array)
#13 C:\xampp\htdocs\friday-magazine\vendor\craftcms\cms\src\services\Plugins.php(777): yii\BaseYii::createObject(Array, Array)
#14 C:\xampp\htdocs\friday-magazine\vendor\craftcms\cms\src\services\Plugins.php(196): craft\services\Plugins->createPlugin('freeform', Array)
#15 C:\xampp\htdocs\friday-magazine\vendor\craftcms\cms\src\base\ApplicationTrait.php(1167): craft\services\Plugins->loadPlugins()
#16 C:\xampp\htdocs\friday-magazine\vendor\craftcms\cms\src\web\Application.php(95): craft\web\Application->_init()
#17 C:\xampp\htdocs\friday-magazine\vendor\yiisoft\yii2\base\BaseObject.php(108): craft\web\Application->init()
#18 C:\xampp\htdocs\friday-magazine\vendor\yiisoft\yii2\base\Application.php(206): yii\base\BaseObject->__construct(Array)
#19 C:\xampp\htdocs\friday-magazine\vendor\craftcms\cms\src\web\Application.php(83): yii\base\Application->__construct(Array)
#20 [internal function]: craft\web\Application->__construct(Array)
#21 C:\xampp\htdocs\friday-magazine\vendor\yiisoft\yii2\di\Container.php(381): ReflectionClass->newInstanceArgs(Array)
#22 C:\xampp\htdocs\friday-magazine\vendor\yiisoft\yii2\di\Container.php(156): yii\di\Container->build('craft\\web\\Appli...', Array, Array)
#23 C:\xampp\htdocs\friday-magazine\vendor\yiisoft\yii2\BaseYii.php(349): yii\di\Container->get('craft\\web\\Appli...', Array, Array)
#24 C:\xampp\htdocs\friday-magazine\vendor\craftcms\cms\bootstrap\bootstrap.php(243): yii\BaseYii::createObject(Array)
#25 C:\xampp\htdocs\friday-magazine\vendor\craftcms\cms\bootstrap\web.php(42): require('C:\\xampp\\htdocs...')
#26 C:\xampp\htdocs\friday-magazine\web\index.php(41): require('C:\\xampp\\htdocs...')
#27 {main}
Additional Information:
Array
(
    [0] => 42S02
    [1] => 1146
    [2] => Table 'my7cych01v6ycydg.craft_freeform_unfinalized_files' doesn't exist
)

**Comment by gustavs-gutmanis** [comment]
Hi, @rivvakili 
Have you upgraded your `craft` install to version `3` from version `2`?
Are any other `freeform` database tables present in your database?
Does this happen right after you do the `composer require/install/update`, or does it happen after you go to the `craft` `settings > plugins` and then install `freeform`?

I am not able to reproduce this, unfortunately. It would help out a lot if you could answer these.

**Comment by rivvakili** [comment]
no, its a new craft 3 project. yes there tables are present, should I remove them manually and try to reinstall?
It happens right after composer update

**Comment by rivvakili** [comment]
Turns out I was blind on both eyes. Its just the missing prefix "craft_". I can rename the tables. I apologize.

**Comment by rivvakili** [comment]
no wait, that wont work. So the problem is that the plugins assumes the freeform tables to have our "craft_" default prefix but they dont and I guess they should not. Any idea how to fix this? Is that something we can fix on our side?

**Comment by gustavs-gutmanis** [comment]
The install script checks your settings and if it sees that you are using a table prefix, it will add it when creating tables.  
So it installs with prefixes, but none of your other tables use prefixes? Very strange.  
Could you show me the contents of your `config/general.php`? Be sure to edit out any sensitive information when you do.

**Comment by gustavs-gutmanis** [comment]
I just had an idea, I will investigate on it and let you know if I came up with anything.

**Comment by gustavs-gutmanis** [comment]
I installed a fresh craft install, set the DB prefix to something custom, then `composer install`ed freeform and installed it in the craft settings, and it installs everything right. I cannot reproduce your issue at all.  
Was there something you did differently?

**Comment by rivvakili** [comment]
Ah, I see. So its probably because we are using nystudio107's setup as bases for our project. https://github.com/nystudio107/craft which uses a own way of multi-env setup: https://github.com/nystudio107/craft3-multi-environment ?

**Comment by gustavs-gutmanis** [comment]
@rivvakili I don't think that is the problem.
Could you remove all traces of Freeform from your database manually (all of the tables and their foreign keys, as well as `freeform` and `freeform-pro` (if installed) rows from the `plugins` table) and try again with the very latest version?

**Comment by rivvakili** [comment]
Worked: tried with beta 6. I ve got an "Couln't install plugin" message in settings->plugin (install) but the plugin has been installed and works (so far)

Thanks!

**Comment by gustavs-gutmanis** [comment]
Glad to hear that!
