### ISSUE TITLE
Forms not submitting when a Google reCAPTCHA (v2) has been added

### ISSUE THREAD

**Issue by rossthomson89** [solspace/craft3-freeform#715]
Forms not submitting when a Google reCAPTCHA has been added. Using reCAPTCHA V2 on any form lets users fill out the form, do the "I'm not a robot check" but when they click "Submit" an error occurs and marks ALL form fields as "Please verify that you are not a robot."

Disabling the Honeypot or Enhanced Javascript Feature makes no difference. Users can only submit the form if there is NO reCAPTCHA present. 

**Steps to reproduce**

1. Create any type of basic form 
2. Add a reCAPCTHA
3. Fill in form fields
4. Pass the "I'm not a robot check"
5. Click Submit. 
6. Submission fails and every field is marked as "Please verify that you are not a robot."

**Expected behavior**

The form should submit successfully if users pass the "I'm not a robot" check. 

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 4.4.14
- Freeform Version: 4.1.1 
- Freeform Edition: Pro
- Fresh Install or Upgrade: Fresh Install

Now seeing this on a couple of projects I'm working on locally. Both have the latest CMS and plugins installed.

**Comment by kjmartens** [comment]
I'm very sorry about this @rossthomson89. We've just released a fix for it in 4.1.2 now. 🙂
