### ISSUE TITLE
Big performance issue on freeform_lock delete

### ISSUE THREAD

**Issue by WHITE-developer** [solspace/craft3-freeform#738]
**Describe the bug or issue you're experiencing**
We are seeing major SQL Performance issues because of the number of `DELETE FROM 'craft_freeform_lock' WHERE 'dateCreated' < ?` queries that are getting executed on every site request. Are these request really necessary when the date is always a week old?

On a high traffic site these request are pulling down our database. Can't this be replaced or have an option to run it as a console request
In combination with Blitz where we are using sprig or async methods to getting CSRF tokens this is getting triggered multiple times per page view!

**Steps to reproduce**

1. visit the site
2. see the delete query getting triggerd

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 4.4.15
- Freeform Version:4.1.5
- Freeform Edition: PRO

**Comment by kjmartens** [comment]
I'm sorry for the trouble you're experiencing with this @WHITE-developer. We are working on a solution and will likely have it available within the next day or two. 🙂

**Comment by kjmartens** [comment]
This should be resolved now in Freeform 4.1.6+. Let me know if you continue to see any issues, @WHITE-developer  🙂

**Comment by WHITE-developer** [comment]
Thanks @kjmartens for the quick fix, do you think this could also be implemented in the v3 version, there we see also a lot of the same requests on the DB?

**Comment by kjmartens** [comment]
Yes @WHITE-developer, we'll release an update for v3 shortly as well. 🙂

**Comment by kjmartens** [comment]
This is now updated in Freeform 3.13.32 as well. 🙂
