### ISSUE TITLE
'Unable to determine the base path' after updating (3.x)

### ISSUE THREAD

**Issue by mathieuser** [solspace/craft3-freeform#741]
Hi, 
I'm struggling to update an older site (Craft version 3.4). I've updates succesfully to 3.8, before making the jump to 4.X, but the only plugin that doesnt work is Freeform. I can't even get it installed again with a deleted vendor folder, nor does it work when clearing the composer cache... Am I overlooking something? This doesn't seem to be an issue anyone else has had.

**Steps to reproduce**

1. Udate craft 3.4 to 3.8
2. see the error 'Install of solspace/craft-freeform failed. Couldn't install solspace/craft-freeform: Unable to determine the base path' when running composer update 

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 3.8.16
- Freeform Version: /
- Freeform Edition: Lite
- Fresh Install or Upgrade: Upgrade

**Comment by mathieuser** [comment]
Just tried on a clean 4.x install, i'm getting the same error...

**Comment by mathieuser** [comment]
Sorry, this was my bad and a local issue, seemed to be a problem with running composer inside a vagrant ssh box. This is fixed for me!

**Comment by kjmartens** [comment]
Glad you were able to figure this one out. Thanks for letting us know. 🙂
