### ISSUE TITLE
Data not saved when clicking "Previous" on multi-page forms

### ISSUE THREAD

**Issue by eeeeeeeeeve** [solspace/craft3-freeform#742]
**Describe the bug or issue you're experiencing**

The [documentation](https://docs.solspace.com/craft/freeform/v3/overview/multi-page-forms/) suggests that in versions 3.8.0+, data will be saved when clicking Previous on a form page. However, this does not seem to be the case, whether using AJAX or not. 

This appears to be an issue on two of our sites, one on Freeform 3.13.11 and the other on Freeform 4.0.17.

**Craft & Plugin Info:**

- Craft Version: Craft Pro 3.7.44
- Freeform Version: 3.13.11 / 4.0.17
- Freeform Edition: Pro

**Comment by kjmartens** [comment]
Sorry for the trouble @eeeeeeeeeve. I can duplicate this in my testing as well. We'll look into this and see what's up. 🙂

**Comment by kjmartens** [comment]
This is now resolved in Freeform 5.5.1+. 🙂
