### ISSUE TITLE
PaymentRecord relations with Submission

### ISSUE THREAD

**Issue by birdkiwi** [solspace/craft3-freeform#76]
Hi!

Seems like a bug: ActiveRecord **PaymentRecord** has **getSubmission** function with relation to Submission. The first argument passed is **{{%freeform_submissions}}**. According to Yii documentation, the first argument should be the class name.

I'm trying to get payments with related submissions in a custom controller:
```
$payments = PaymentRecord::find()
            ->with('submission')
            ->orderBy('id DESC');
```
and getting this error: 
`Class '{{%freeform_submissions}}' not found`

https://github.com/solspace/craft3-freeform/blob/master/src/Records/Pro/Payments/PaymentRecord.php#L64

**Steps to reproduce**
1. Trying to get Payments with Submissions

**Expected behavior**
Get payments and related submissions

**Craft & Plugin Info (please complete the following information):**
 - Craft Version: 3.5.17
 - Freeform Version: 3.9.10
 - Freeform Edition: PRO
 - Fresh Install or Upgrade: Fresh

**Comment by gustavs-gutmanis** [comment]
Thanks for reporting this @birdkiwi  
It'll be fixed in the next release.
