### ISSUE TITLE
EVENT_AFTER_UPLOAD not returning assetId

### ISSUE THREAD

**Issue by birdkiwi** [solspace/craft3-freeform#78]
I'm trying to get uploaded asset id with **EVENT_AFTER_UPLOAD** event. 
However, an example provided in docs not working. $field->getValue() returning empty value **array(0) { }**.
https://docs.solspace.com/craft/freeform/v3/developer/file-upload-events.html#after-an-upload-has-finished

**Steps to reproduce**
1. Create an empty module
2. Add init method
```
public function init()
{
    Craft::setAlias('@modules', __DIR__);
    parent::init();

    Event::on(
        FilesService::class,
        FilesService::EVENT_AFTER_UPLOAD,
        function (UploadEvent $event) {
            $field = $event->getField();

            // Get the uploaded Asset ID
            $assetId = $field->getValue();

            var_dump($assetId);
            die();
        }
    );
}
```
3. Upload any file in any form.

**Expected behavior**

$assetId is not empty and returning asset ids.

**Craft & Plugin Info (please complete the following information):**
 - Craft Version: 3.5.17.1
 - Freeform Version: 3.9.11
 - Freeform Edition: PRO
 - Fresh Install or Upgrade: fresh

**Additional context**

**Comment by gustavs-gutmanis** [comment]
@birdkiwi thanks for reporting this, it's fixed and will be released in the upcoming release.
