### ISSUE TITLE
Locale not working when using more than one Date & time field in the same form

### ISSUE THREAD

**Issue by pascalminator** [solspace/craft3-freeform#783]
**Describe the bug or issue you're experiencing**

When I create multiple date & time fields in the same form, the first field is localised in french correctly, but when I create additional date & time fields they stay in english. I also tried to force the localisation by adding 'fr' in the config but it doesn't change anything.

**Steps to reproduce**

1. Use Craft localised in a different language than english (french for me)
2. Create a form and add multiple date & time fields
3. Preview your form in front-end and notice the first field being correctly localised and the additionnal ones incorectly displaying in english

**Expected behavior**

All date & time field should be in french

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 4.4.17
- Freeform Version: 4.1.6
- Freeform Edition: Pro (trial because the website is not in prod yet)
- Fresh Install or Upgrade: Fresh install

**Comment by kjmartens** [comment]
Sorry for the trouble @pascalminator.

I can duplicate this in my testing as well. I've noted it and we'll see if we can fix this shortly. 🙂

**Comment by kjmartens** [comment]
Sorry for the long wait on this one @pascalminator. We were able to come up with a solution for this and it's now available in Freeform v4.1.11. 🙂
