### ISSUE TITLE
Error when attempting to edit user, or user group

### ISSUE THREAD

**Issue by Kashkin** [solspace/craft3-freeform#8]
> Error: Undefined class constant 'PERMISSION_FORMS_MANAGE' in SERVERPATH/vendor/solspace/craft3-freeform/src/Freeform.php:230
> Stack trace:
> 0. [internal function]: Solspace\Freeform\Freeform->Solspace\Freeform\{closure}(Object(craft\events\RegisterUserPermissionsEvent))
> 1. SERVERPATH/vendor/yiisoft/yii2/base/Event.php(221): call_user_func(Object(Closure), Object(craft\events\RegisterUserPermissionsEvent))
> 2. SERVERPATH/vendor/yiisoft/yii2/base/Component.php(565): yii\base\Event::trigger('craft\\services\\...', 'registerPermiss...', Object(craft\events\RegisterUserPermissionsEvent))
> 3. SERVERPATH/vendor/craftcms/cms/src/services/UserPermissions.php(213): yii\base\Component->trigger('registerPermiss...', Object(craft\events\RegisterUserPermissionsEvent))
> 4. SERVERPATH/vendor/craftcms/cms/src/services/UserPermissions.php(229): craft\services\UserPermissions->getAllPermissions()
> 5. SERVERPATH/vendor/twig/twig/lib/Twig/Extension/Core.php(1595): craft\services\UserPermissions->getAssignablePermissions(NULL)
> 6. SERVERPATH/vendor/craftcms/cms/src/helpers/Template.php(76): twig_get_attribute(Object(craft\web\twig\Environment), Object(Twig_Source), Object(craft\services\UserPermissions), 'getAssignablePe...', Array, 'method', false, false)
> 7. SERVERPATH/storage/runtime/compiled_templates/ee/ee660c2ec1da6451467b3a63f866e5b34c572f99922a09fa516c418fee52c43a.php(48): craft\helpers\Template::attribute(Object(craft\web\twig\Environment), Object(Twig_Source), Object(craft\services\UserPermissions), 'getAssignablePe...', Array, 'method')
> 8. SERVERPATH/vendor/twig/twig/lib/Twig/Template.php(389): __TwigTemplate_c345e269ca0acbdf7b24c9afea5a20395ad5d1cf1da76819f5fba90f2385bb2c->doDisplay(Array, Array)
> 9. SERVERPATH/vendor/craftcms/cms/src/web/twig/Template.php(51): Twig_Template->displayWithErrorHandling(Array, Array)
> 10. SERVERPATH/vendor/twig/twig/lib/Twig/Template.php(366): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
> 11. SERVERPATH/vendor/craftcms/cms/src/web/twig/Template.php(32): Twig_Template->display(Array, Array)
> 12. SERVERPATH/storage/runtime/compiled_templates/34/348c7b819e6ea66a836efc604e1bea7fcc77473ebc6396db98d6526705e1e975.php(380): craft\web\twig\Template->display(Array)
> 13. SERVERPATH/vendor/twig/twig/lib/Twig/Template.php(188): __TwigTemplate_450d8c6a5992a09e15987ec269b3d759c9f3ccf0dbb775e5435c0dec51f359dc->block_content(Array, Array)
> 14. SERVERPATH/storage/runtime/compiled_templates/52/52d095f7769e22f93570415195f8d799b06daee8b8054f55716751c547d867e6.php(636): Twig_Template->displayBlock('content', Array, Array)
> 15. SERVERPATH/vendor/twig/twig/lib/Twig/Template.php(188): __TwigTemplate_0ff8b6b2d9197e5523a2797e6c1f6845dd3c4defe5a1952ada4f16bf797cfec3->block_main(Array, Array)
> 16. SERVERPATH/storage/runtime/compiled_templates/52/52d095f7769e22f93570415195f8d799b06daee8b8054f55716751c547d867e6.php(533): Twig_Template->displayBlock('main', Array, Array)
> 17. SERVERPATH/vendor/twig/twig/lib/Twig/Template.php(188): __TwigTemplate_0ff8b6b2d9197e5523a2797e6c1f6845dd3c4defe5a1952ada4f16bf797cfec3->block_body(Array, Array)
> 18. SERVERPATH/storage/runtime/compiled_templates/e2/e25fa1820e2c95cdafc542dd213dfb93302d556734df7fa87eb39ce1c66a81cd.php(53): Twig_Template->displayBlock('body', Array, Array)
> 19. SERVERPATH/vendor/twig/twig/lib/Twig/Template.php(389): __TwigTemplate_4d29c2e31e93d8ae352742824113e33c0aa9aa8a95e07330b62a1d3ab9612ab1->doDisplay(Array, Array)
> 20. SERVERPATH/vendor/craftcms/cms/src/web/twig/Template.php(51): Twig_Template->displayWithErrorHandling(Array, Array)
> 21. SERVERPATH/vendor/twig/twig/lib/Twig/Template.php(366): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
> 22. SERVERPATH/vendor/craftcms/cms/src/web/twig/Template.php(32): Twig_Template->display(Array, Array)
> 23. SERVERPATH/storage/runtime/compiled_templates/81/818c62b9550f9232c78a3d76e8d955117d0839ce1174664453eb28e92cd6ed32.php(36): craft\web\twig\Template->display(Array, Array)
> 24. SERVERPATH/vendor/twig/twig/lib/Twig/Template.php(389): __TwigTemplate_46c305540d19a0585fbec8246e9bb8908a46630f49e6029cabd97f51c0e14b96->doDisplay(Array, Array)
> 25. SERVERPATH/vendor/craftcms/cms/src/web/twig/Template.php(51): Twig_Template->displayWithErrorHandling(Array, Array)
> 26. SERVERPATH/vendor/twig/twig/lib/Twig/Template.php(366): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
> 27. SERVERPATH/vendor/craftcms/cms/src/web/twig/Template.php(32): Twig_Template->display(Array, Array)
> 28. SERVERPATH/storage/runtime/compiled_templates/52/52d095f7769e22f93570415195f8d799b06daee8b8054f55716751c547d867e6.php(90): craft\web\twig\Template->display(Array, Array)
> 29. SERVERPATH/vendor/twig/twig/lib/Twig/Template.php(389): __TwigTemplate_0ff8b6b2d9197e5523a2797e6c1f6845dd3c4defe5a1952ada4f16bf797cfec3->doDisplay(Array, Array)
> 30. SERVERPATH/vendor/craftcms/cms/src/web/twig/Template.php(51): Twig_Template->displayWithErrorHandling(Array, Array)
> 31. SERVERPATH/vendor/twig/twig/lib/Twig/Template.php(366): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
> 32. SERVERPATH/vendor/craftcms/cms/src/web/twig/Template.php(32): Twig_Template->display(Array, Array)
> 33. SERVERPATH/storage/runtime/compiled_templates/34/348c7b819e6ea66a836efc604e1bea7fcc77473ebc6396db98d6526705e1e975.php(82): craft\web\twig\Template->display(Array, Array)
> 34. SERVERPATH/vendor/twig/twig/lib/Twig/Template.php(389): __TwigTemplate_450d8c6a5992a09e15987ec269b3d759c9f3ccf0dbb775e5435c0dec51f359dc->doDisplay(Array, Array)
> 35. SERVERPATH/vendor/craftcms/cms/src/web/twig/Template.php(51): Twig_Template->displayWithErrorHandling(Array, Array)
> 36. SERVERPATH/vendor/twig/twig/lib/Twig/Template.php(366): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
> 37. SERVERPATH/vendor/craftcms/cms/src/web/twig/Template.php(32): Twig_Template->display(Array, Array)
> 38. SERVERPATH/vendor/twig/twig/lib/Twig/Template.php(374): craft\web\twig\Template->display(Array)
> 39. SERVERPATH/vendor/twig/twig/lib/Twig/Environment.php(289): Twig_Template->render(Array)
> 40. SERVERPATH/vendor/craftcms/cms/src/web/View.php(308): Twig_Environment->render('users/_edit', Array)
> 41. SERVERPATH/vendor/craftcms/cms/src/web/View.php(356): craft\web\View->renderTemplate('users/_edit', Array)
> 42. SERVERPATH/vendor/craftcms/cms/src/web/Controller.php(121): craft\web\View->renderPageTemplate('users/_edit', Array)
> 43. SERVERPATH/vendor/craftcms/cms/src/controllers/UsersController.php(871): craft\web\Controller->renderTemplate('users/_edit', Array)
> 44. [internal function]: craft\controllers\UsersController->actionEditUser('815', Object(craft\elements\User))
> 45. SERVERPATH/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
> 46. SERVERPATH/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
> 47. SERVERPATH/vendor/craftcms/cms/src/web/Controller.php(80): yii\base\Controller->runAction('edit-user', Array)
> 48. SERVERPATH/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('edit-user', Array)
> 49. SERVERPATH/vendor/craftcms/cms/src/web/Application.php(251): yii\base\Module->runAction('users/edit-user', Array)
> 50. SERVERPATH/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('users/edit-user', Array)
> 51. SERVERPATH/vendor/craftcms/cms/src/web/Application.php(216): yii\web\Application->handleRequest(Object(craft\web\Request))
> 52. SERVERPATH/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
> 53. SERVERPATH/public/index.php(21): yii\base\Application->run()
> 54. {main}

**Comment by skramstad** [comment]
I can confirm this error happens to me too...

**Comment by kjmartens** [comment]
Thank you, we can duplicate this issue as well, and will have a fix available shortly.
