### ISSUE TITLE
Alternate Success Markup docs incorrect for 3.10

### ISSUE THREAD

**Issue by TUSAB-web** [solspace/craft3-freeform#83]
**Describe the bug or issue you're experiencing**
In 3.10, the method for calling alternate success message (AJAX) changed according to the docs. I switched my code to the new method and it doesn’t work. This is using the “existing div” instructions from the docs.

**Steps to reproduce**
1. Create form, turn on AJAX
2. Enter 3.10 code into template using “Existing Div” instructions from this page: https://docs.solspace.com/craft/freeform/v3/guides/ajax-return-loads-success.html#alternate-success-markup-from-a-template-or-existing-div-after-ajax-submit

**Expected behavior**
The suggested 3.9 code still works in 3.10, but the new suggested code for 3.10 from the docs does not work.

**Craft & Plugin Info (please complete the following information):**
 - Craft Version: 3.5.17.1
 - Freeform Version: 3.10.0
 - Freeform Edition: Pro Trial
 - Fresh Install or Upgrade: Upgrade

**Additional context**

**Comment by gustavs-gutmanis** [comment]
@TUSAB-web thanks for reporting this!

The documentation will be fixed shortly. 
Meanwhile the correct way of adding event listeners to the `document` object is as follows:

```js
document.addEventListener('freeform-render-success', function (event) {
  event.preventDefault();
  $('#form-wrapper').html($('#custom-content').html());
});
```
