### ISSUE TITLE
Cacheable forms CSRF token error

### ISSUE THREAD

**Issue by TUSAB-web** [solspace/craft3-freeform#84]
**Describe the bug or issue you're experiencing**
When using the code on this page: https://docs.solspace.com/craft/freeform/v3/templating/caching.html#static-page-caching-cdn-blitz to handle forms on cached pages, the system returns an error "Unable to verify your data submission.” At the bottom of the error message, the CSRF tokens don’t match.

**Steps to reproduce**
1. Create a form in Freeform
2. Create a blank template with the form’s handle as suggested in docs, as well as a file in /dynamic/index.twig following all instructions for “Static Page Caching”
3. Exclude dynamic from Blitz caching
4. The page works for 10-15 minutes, but then no longer does when the cached page gets old.

**Expected behavior**
CSRF token should be swapped in by the script.

**Craft & Plugin Info (please complete the following information):**
 - Craft Version:3.5.17.1
 - Freeform Version: 3.10.0
 - Freeform Edition: Pro Trial
 - Fresh Install or Upgrade: Upgrade

**Additional context**
Have tried this with a setup that was working fine without any caching, but recently added caching. Error occurs on existing templates that were updated with the suggested code, so I then created a blank template I created with only the suggested code in it and have the same problem. I confirmed that files in the “/templates/dynamic” folder are not being cached.

**Comment by gustavs-gutmanis** [comment]
@TUSAB-web Could you please check if the script which handles fetching fresh csrf, honeypot and form hash values works?  
The network tab should show an XHR request. Please see if the form you're posting is actually using the updated values.

It looks like the script which should be in your cached template never asks for new values, or doesn't replace them.

**Comment by TUSAB-web** [comment]
Thanks for that tip. I checked the network tab; it shows an XHR request which returns an error:

```
{
    "error": "Impossible to access an attribute (\"hash\") on a null variable."
}
```

**Comment by gustavs-gutmanis** [comment]
Alright, so that's saying that the network response doesn't return the object it should.  

* so either the twig is set up incorrectly
* or the url is incorrect

Could you please tell me what your folder structure looks like (for the dynamic part in particular) and what's in the dynamic page twig template?

**Comment by TUSAB-web** [comment]
The folder structure is /templates/dynamic. The file inside is index.twig. The contents of that file are below:

```
{% set form = craft.freeform.form(craft.app.request.get('form')) %}
{{ {
    hash: form.hash,
    csrf: {
        name: craft.app.config.general.csrfTokenName,
        value: craft.app.request.csrfToken,
    }
}|json_encode|raw }}
```

**Comment by gustavs-gutmanis** [comment]
Ok, everything is correct there.  
What does your network tab show as the response from `/dynamic` page request?

**Comment by TUSAB-web** [comment]
URL: http://localhost/dynamic?form=composerForm
Status: 500 Internal Server Error
Source: Network
Address: ::1:80
Initiator: 
jquery-3.5.1.min.js:2:82618

**Comment by gustavs-gutmanis** [comment]
Looks like the url isn't accessible.
What if you try `https://localhost/dynamic/index?form=composerForm`? You can open it in the browser too, you'll see if it works.

**Comment by TUSAB-web** [comment]
When I go directly to that URL, I get a Twig runtime error:

"Impossible to access an attribute ("hash") on a null variable.”

The line highlighted is:

hash:form.hash,

**Comment by TUSAB-web** [comment]
Seems like the hash information isn’t being passed successfully from the JS to the dynamic template?

**Comment by gustavs-gutmanis** [comment]
It means that the forms isn't found.  
Do you have a form with the handle `composerForm`?

**Comment by TUSAB-web** [comment]
I changed “composerForm” to the handle of the form and it worked. But I have other forms with different handles, so how will those work?

**Comment by gustavs-gutmanis** [comment]
If you have the script that loads this information inside the same twig where you have your cached form, you can change the handle part to use twig.

Assuming you have this in your template:

```twig
{# Initialize the form #}
{% set form = craft.freeform.form("myFormHandle") %}

{# Cached form comes here #}
{% cache %}
    {{ form.render }}
{% endcache %}
```

And in the same template, later on you have the `$.ajax()` call:
Change the `url` part to use the current form's handle, like this:

```js
url: '/dynamic?form={{ form.handle }}',
```

**Comment by TUSAB-web** [comment]
Gustavs - Thank you very much! I thought “composerForm” was a freeform system default; it didn’t occur to me it was a stand-in for the actual form handle.  It looks like I am back in business.

**Comment by gustavs-gutmanis** [comment]
I'll make the example more clear by specifying the form handle as `my-form-handle` instead, so that this doesn't confuse others.

Thanks
