### ISSUE TITLE
Error when installing via terminal to blank craft site for testing

### ISSUE THREAD

**Issue by NeilWSmith** [solspace/craft3-freeform#843]
I created a blank Craft 4 site for testing and tried to install Freeform from the plugin store and that was just hanging so I tried to install via terminal and got the following error:
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - maennchen/zipstream-php[2.1.0, ..., v2.x-dev] require psr/http-message ^1.0 -> found psr/http-message[1.0, 1.0.1, 1.1] but the package is fixed to 2.0.x-dev (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - maennchen/zipstream-php[3.0.0-beta.1, ..., 3.1.0] require php-64bit ^8.1 -> your php-64bit version (8.0.2; overridden via config.platform, actual: 8.1.13) does not satisfy that requirement.
    - solspace/craft-freeform v4.x-dev requires phpoffice/phpspreadsheet ^1.29 -> satisfiable by phpoffice/phpspreadsheet[1.29.0].
    - phpoffice/phpspreadsheet 1.29.0 requires maennchen/zipstream-php ^2.1 || ^3.0 -> satisfiable by maennchen/zipstream-php[2.1.0, ..., v2.x-dev, 3.0.0-beta.1, ..., 3.1.0].
    - Root composer.json requires solspace/craft-freeform v4.x-dev -> satisfiable by solspace/craft-freeform[v4.x-dev].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

**Steps to reproduce**

1. Create blank Craft site in MAMP PRO (using PHP 8.1.13)
2. Run composer require solspace/craft-freeform in terminal

**Expected behavior**
Above error message results.

Running "composer require solspace/craft-freeform --with-all-dependencies" successfully installs Freeform.

**Craft & Plugin Info (please complete the following information):**

- Craft Version: Craft Solo 4.5.0-beta.2
- Freeform Version: v4.x-dev
- Freeform Edition: LITE/Trial
- Fresh Install or Upgrade: Fresh Install

**Additional context**

**Comment by kjmartens** [comment]
Sorry for the trouble you experienced with this, @NeilWSmith. We'll check into it and see what we can do to resolve it. 🙂

**Comment by kjmartens** [comment]
@NeilWSmith Can you see if an update to 4.1.7 or 4.1.8 resolves the issue for you? 🙂
