### ISSUE TITLE
CSP Inline Styles error with renderTag

### ISSUE THREAD

**Issue by clarknelson** [solspace/craft3-freeform#85]
**Describe the bug or issue you're experiencing**
I am implementing a CSP policy that attempts to prevent inline styles. There is a div that is inserted, I am assuming as part of a security policy, that doesn't comply. 

`<div style="position: absolute !important; width: 0 !important; height: 0 !important; overflow: hidden !important;" aria-hidden="true" tabindex="-1"><label aria-hidden="true" tabindex="-1" for="freeform_form_handle">Leave this field blank</label><input type="text" value="" name="freeform_form_handle" id="freeform_form_handle" aria-hidden="true" tabindex="-1"></div>`

Is it possible to add a `nonce` value to this div? Or maybe add a class which I can can add styles to a style sheet? Is there any way to modify this div? 

**Steps to reproduce**
1. Implement CSP which does not allow `unsafe-inline` https://github.com/born05/craft-csp
2. I used the flexbox template, although I have a custom template set up so I can modify the code
3. This div is inserted as part of the form

**Expected behavior**
Possibly I can modify `{{ form.renderTag() }}` to disable this div, or modify the JS bundle to change how this div is created. 

**Craft & Plugin Info (please complete the following information):**
 - Craft Version: 3.5.17
 - Freeform Version: 3.10.0
 - Freeform Edition: Pro
 - Fresh Install or Upgrade: N/A

**Additional context**

**Comment by clarknelson** [comment]
Along the same lines: 

`<script src="{my-domain}/cpresources/2dae3db1/freeform.js?v=1610487984"></script>`

output by 

`{{ craft.freeform.loadFreeformScripts(slide.form) }}`

would ideally have a nonce value also. Is the `/2dae3db1/` and `?v=1610487984` important? Or can I hard code this script in with the nonce value

**Comment by gustavs-gutmanis** [comment]
Hi @clarknelson,

Currently it's not possible to do this, but I'm working on adding several craft events which will let you adjust whatever you need to adjust in such cases, and I will get back to you here.

As for the second comment - you can do it manually, but it's very unsafe, because if the cache gets cleared, the files would have differently hashed directories and thus your manual entry would point to a script that no longer exists.

**Comment by gustavs-gutmanis** [comment]
Ok, so the next release will contain several new events you can use to modify the script and style tags that are added by freeform, as well as the possibility to alter the honeypot include.
I've also added a classname for the honeypot div which uses the honeypot name you define in settings, so you should be able to manually style it via CSS.

**Comment by gustavs-gutmanis** [comment]
To add a `nonce` attribute to script and style tags added by Freeform, you would create a custom module and have this in there:

```php
use Solspace\Freeform\Events\Forms\RegisterRenderObjectOptionsEvent;
use Solspace\Freeform\Library\DataObjects\FormRenderObject\AbstractFormRenderObject;
use yii\base\Event;

Event::on(
    AbstractFormRenderObject::class,
    AbstractFormRenderObject::EVENT_REGISTER_OPTIONS,
    function (RegisterRenderObjectOptionsEvent $event) {
        $nonce = 'abc'; // Get your nonce here
        $event->addOption('nonce', $nonce);
    }
);
```

**Comment by clarknelson** [comment]
I'm getting this now :( 

![image](https://user-images.githubusercontent.com/4106671/104769435-ee212e80-5734-11eb-9358-529b427d04b5.png)

Thanks for your help, I assume the honeypot options wont be available for a while.

**Comment by gustavs-gutmanis** [comment]
Both the honeypot and the event you're using right now will be available only in the next release. You can install the dev-master version right now to use it, if you want to.

--  
Gustavs Gutmanis

**Comment by clarknelson** [comment]
Thank you so much! It is working wonderfully with the CSP plugin in a module. Do you have any quick instructions on how to modify the honeypot? I imagine that's not in the documentation yet

**Comment by gustavs-gutmanis** [comment]
You're right, the docs haven't been updated just yet, they'll come out with the new version.

Here's an example of how I'd edit the honeypot div. You can override the whole output, and it comes as a string, so you'll have to do the string search and manipulation yourself.

```php
use Solspace\Freeform\Services\HoneypotService;
use Solspace\Freeform\Events\Honeypot\RenderHoneypotEvent;

Event::on(
    HoneypotService::class,
    HoneypotService::EVENT_RENDER_HONEYPOT,
    function (RenderHoneypotEvent $event) {
        $output = $event->getOutput();

        $output = str_replace(
            ' class="',
            ' nonce="my-nonce" class="',
            $output
        );

        $event->setOutput($output);
    }
);
```

**Comment by clarknelson** [comment]
woohoo! thank you so much saving me on a deadline

**Comment by gustavs-gutmanis** [comment]
Glad I could help!
