### ISSUE TITLE
Email Notifications Never send || AWS SES Mailer

### ISSUE THREAD

**Issue by DynamiteGoesBoom** [solspace/craft3-freeform#866]
Database email notifications don't work. I ssh'd into the server and successfully ran `./craft mailer/test` and received the email. But when I submit a freeform form on the frontend no email gets sent to the Admins. I also tried one single recipient but that also did not work.

I've checked the logs and nothing pertinent was discovered along with no errors within freeform

**Steps to reproduce**

1. Setup a new form 
2. use AWS SES as the mailer

**Expected behavior**

for the submissions to get sent

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 4.5.6.1
- Freeform Version: 4.1.9 
- Freeform Edition: Pro
- Fresh Install or Upgrade: n/a

**Comment by kjmartens** [comment]
Sorry for the trouble you're experiencing @DynamiteGoesBoom.

Have you reviewed the list of common issues for Emails Not Sending? 🙂 
https://docs.solspace.com/craft/freeform/v4/common-issues/#emails-not-sending

I also want to confirm... when you say this is affecting Database Notifications with AWS SES as the mailer, is that just your current setup, or does it work when you change it to a different mailer and/or file-based notification template? 🙂

**Comment by DynamiteGoesBoom** [comment]
@kjmartens there was a type-oh in the email notifications 🙈 Sorry to bug you with this and thanks again!

**Comment by kjmartens** [comment]
All good @DynamiteGoesBoom 😅
