### ISSUE TITLE
Freeform 3.10.2 - form rendering error

### ISSUE THREAD

**Issue by i-just** [solspace/craft3-freeform#88]
After updating from Freeform 3.10.1 to 3.10.2 I get the following error when trying to view any Freeform form on the front end (not in admin):

`Argument 3 passed to Solspace\Freeform\Library\DataObjects\FormRenderObject\JavascriptObject::__construct() must be of the type array, integer given, called in /srv/pre/src/motability/drc/vendor/solspace/craft-freeform/packages/plugin/src/Events/Forms/FormRenderEvent.php on line 99`

The same forms work as expected when I downgrade back to 3.10.1.

Craft CMS Pro 3.5.17.1
Freeform Pro 3.10.2

**Comment by gustavs-gutmanis** [comment]
Thanks for reporting this @i-just.
The patch will be out soon
