### ISSUE TITLE
Spam purge functionality not working - no spam is purged

### ISSUE THREAD

**Issue by terryupton** [solspace/craft3-freeform#892]
**Describe the bug or issue you're experiencing**

It seems that the Purge Spam feature is not working as no spam is being purged on the system.
Currently the settings are setup to purge after 7 days. 
However, we are still seeing spams since we tested this last dating back to October 5th (more than 7 days).
<img width="1620" alt="Screenshot 2023-10-20 at 17 02 24" src="https://github.com/solspace/craft-freeform/assets/5698596/fb377045-bade-4f85-aa6d-c5954ff25a28">

<img width="2033" alt="Screenshot 2023-10-20 at 17 07 24" src="https://github.com/solspace/craft-freeform/assets/5698596/cc330c65-475b-4e50-8ba0-b3ebc42906d2">

**Steps to reproduce**

1. Settings set to purge Spam after 7 days.
2. Wait for 7 days and check if spam has been purged.

**Expected behavior**
Spam t be removed that is older than 7 days. 

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 
Craft Pro 4.5.6.1

- Freeform Version:
4.1.9

- Freeform Edition:
Lite

- Fresh Install or Upgrade:
Fresh Install

**Comment by terryupton** [comment]
Hey @kjmartens 
Any thoughts on this? Thanks.

**Comment by kjmartens** [comment]
Sorry for the delay, @terryupton.

I have played around with this for a little while, and I can't seem to duplicate the issue. I have a few questions, though... 🙂 

1. Has this been happening for a while, or did you just notice it happening recently?
2. Is this happening for ALL spam submissions? Or just some of them (e.g. does it seem to effectively remove 90% of them, but there are strays left over)?
3. If you adjust the day number to something else (such as `5 days`), does it make a difference?
4. If you clear the Craft cache, does that make any difference at all?

**Comment by terryupton** [comment]
Hey @kjmartens,

Thanks for coming back to me. Answers as follows:

_1. Has this been happening for a while, or did you just notice it happening recently?_  
**This has happened since the beginning of this site installation, as far as I am aware. I had previously manually removed them as a process in order to get a fixed date to test the purging against.**

_2. Is this happening for ALL spam submissions? Or just some of them (e.g. does it seem to effectively remove 90% of them, but there are strays left over)?_  
**All of them. None are removed.**

_3. If you adjust the day number to something else (such as 5 days), does it make a difference?_  
**I tried this previously swapping from 14 to 7 and it didn't make a difference.**

_4. If you clear the Craft cache, does that make any difference at all?_  
**I have manually just cleared caches and will see if this has any effect. However, I run updates monthly and I clear caches as part of the deployment process, so this has already occurred several times and had no effect to date.**

I am happy to share databases or project config files if it helps.

**Comment by kjmartens** [comment]
Hmm that is strange. Sure, please send us a copy of the database and project config files to support@solspace.com 🙂

**Comment by kjmartens** [comment]
Sorry again for the delay... we are investigating this now.

One thing I noticed is that the `freeform_lock` database table is not updating. The last row created was `2023-07-24 11:11:26`. This is critical for the purge (and some other parts of Freeform) to work correctly.

If you have any ideas why this might be happening, let us know. In the meantime, we'll investigate on our end. 🙂

**Comment by terryupton** [comment]
Hi Kelsey,

Thanks for the update. I have no idea why the freeform_lock database table is not updating.

It was just a fresh Craft 4 install and updates have been run via the 'craft update' commands regularly since the project was started in July 2022.

**Comment by kjmartens** [comment]
Thanks @terryupton.

We are continuing to investigate and should have a solution soon. 🙂

**Comment by kjmartens** [comment]
@terryupton, can you try out Freeform 4.1.12? We made an update to this that should make it work more reliably and resolve this issue for you. 🙂

**Comment by terryupton** [comment]
@kjmartens I upgraded but I am still seeing the same issues and it is not purging the spam submissions.

To give you some specific details.
On 21st November 2023 I upgraded and then I went into the back-end and removed all spam submissions to I have a new start date to test from.
The purging is set to 7 days.
I have waited until today 30th to login and test and I would expect anything prior to 23rd to have been purged and removed.
However, I am still seeing entries from 21st, 22nd, 23rd etc  

Happy to share my database again or try further solutions.
Hoping we can resolve this.

Thanks
Terry

**Comment by kjmartens** [comment]
Sorry @terryupton,

Would you be able to send us a copy of the database then? 🙂

**Comment by kjmartens** [comment]
Hi @terryupton,

Wondering if you can try one more thing for me. Have you tried running the `php craft freeform/purge/spam --age-in-days=30` console command? Does that work? This will help us narrow down what the issue might be. 🙂 

https://docs.solspace.com/craft/freeform/v4/developer/console-commands/

**Comment by terryupton** [comment]
Hi @kjmartens 

Happy New Year!

I have run the following command.
`php craft freeform/purge/spam --age-in-days=14`

And this is the result.
<img width="631" alt="Screenshot 2024-01-02 at 14 19 32" src="https://github.com/solspace/craft-freeform/assets/5698596/135b61c6-1701-42fd-bef5-c346fb9709b5">

However, there are still spam messages as follows:
<img width="620" alt="Screenshot 2024-01-02 at 14 19 47" src="https://github.com/solspace/craft-freeform/assets/5698596/5c7b3990-bf8b-45d5-89b3-04785b8895ea">

**Comment by terryupton** [comment]
Any update on this please @kjmartens ?

**Comment by terryupton** [comment]
Any update on this please @kjmartens ?
I am still seeing issues and spam is not being purged.

**Comment by kjmartens** [comment]
Sorry for the delay @terryupton.

I am assigning @gustavs-gutmanis to work with you on this one to investigate why it is not working. He'll reach out to you shortly.

**Comment by gustavs-gutmanis** [comment]
Hi @terryupton,

I'm currently working on a refactor for the way submissions and spam submissions are being purged.

If possible, could you tell me approximately how many spam submissions do you have?
It seems strange that the script runs like it should but removes nothing. We can't replicate this on our end, hopefully the changes will work for you.

I'll let you know when I have a branch ready for you to test.

**Comment by terryupton** [comment]
Hi @gustavs-gutmanis the number has naturally increased since I first raised this.
One one form it is around 41 submissions on the other form is around 807 submissions.

**Comment by gustavs-gutmanis** [comment]
That is even weirder, those are very small numbers.
Thanks for the info

**Comment by gustavs-gutmanis** [comment]
@terryupton 

Could you please install this branch `fix-purge` on your machine and see if it now works properly?

You could try it via the CLI with the command you tried before.
`php craft freeform/purge/spam --age-in-days=14`

To install this particular branch, change your `composer.json` dependency to use `dev-fix-purge`

```json
{
  "require": {
    "solspace/craft-freeform": "dev-fix-purge",
    ...
  ...
}
```

**Comment by furioursus** [comment]
FWIW, i am having the same issue. i changed my composer requirements to use this branch, reinstalled the composer packages, ran `craft up` and still get the following output:

```
➜  oaklandca.gov-live git:(feature/freeform-spam) ✗ ddev php craft freeform/purge/spam -d 1
Purging spam submissions which are at least 1 days old...

Purged 0 submissions
Purged 0 assets
```

There are currently 180k+ spam entries that have backed up in our database and they are not younger than 1 day old.

**Comment by kjmartens** [comment]
@furioursus or @terryupton,

Sorry for the continued issues. Can you provide your latest database for our review? I will have a developer look directly at your database and release a solution that is actually purging your database. 🙂

**Comment by furioursus** [comment]
> @furioursus or @terryupton,
> 
> Sorry for the continued issues. Can you provide your latest database for our review? I will have a developer look directly at your database and release a solution that is actually purging your database. 🙂

Great. I’ve sent you a dropbox link with the database. Please [email me](mailto:yo@github.furioursus.dev) if you have any further questions!

**Comment by kjmartens** [comment]
Thank you @furioursus 🙂

**Comment by terryupton** [comment]
Also sent a Dropbox link in an email @kjmartens

**Comment by kjmartens** [comment]
Thank you @terryupton 🙂

**Comment by gustavs-gutmanis** [comment]
Hi @terryupton 

Could you please try one thing for me?
Enable Freeform PRO as a trial for just a second, and run the purge command.

The purge is a PRO only feature, and I noticed that you're on Lite. That would be the issue behind all of this...

**Comment by gustavs-gutmanis** [comment]
@terryupton @furioursus 

I have removed the `PRO` check for spam purge, please try the same branch again.

**Comment by kjmartens** [comment]
@terryupton @furioursus,

We've now released Freeform 4.1.15, which includes support for Spam purging in the `Lite` edition of Freeform. If you continue to experience issues, please let us know. 🙂

**Comment by terryupton** [comment]
@kjmartens - I have installed the update and I immediately had this error in the craft queue:

```
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'craft_freeform_submissions.dateCreated' in 'where clause' The SQL being executed was: SELECT COUNT(*) FROM (SELECT `elements`.`id` AS `elementsId`, `elements_sites`.`id` AS `elementsSitesId`, `content`.`id` AS `contentId` FROM `craft_elements` `elements` INNER JOIN `craft_freeform_submissions` `freeform_submissions` ON `freeform_submissions`.`id` = `elements`.`id` INNER JOIN `craft_freeform_statuses` `sub_freeform_statuses` ON sub_freeform_statuses.`id` = freeform_submissions.`statusId` LEFT JOIN `craft_freeform_submissions_enquiry_form_1` `fc1` ON `fc1`.`id` = `freeform_submissions`.`id` LEFT JOIN `craft_freeform_submissions_instant_quote_2` `fc2` ON `fc2`.`id` = `freeform_submissions`.`id` INNER JOIN `craft_elements_sites` `elements_sites` ON `elements_sites`.`elementId` = `elements`.`id` INNER JOIN `craft_content` `content` ON `content`.`elementId` = `elements`.`id` WHERE (freeform_submissions.`isSpam`=TRUE) AND (`craft_freeform_submissions`.`dateCreated` < '2024-02-23 16:09:40') AND (`elements`.`archived`=FALSE) AND (`elements`.`dateDeleted` IS NULL) AND (`elements`.`draftId` IS NULL) AND (`elements`.`revisionId` IS NULL)) `subquery` INNER JOIN `craft_elements` `elements` ON `elements`.`id` = `subquery`.`elementsId` INNER JOIN `craft_elements_sites` `elements_sites` ON `elements_sites`.`id` = `subquery`.`elementsSitesId` INNER JOIN `craft_freeform_submissions` `freeform_submissions` ON `freeform_submissions`.`id` = `subquery`.`elementsId` INNER JOIN `craft_freeform_forms` `freeform_forms` ON freeform_forms.`id` = freeform_submissions.`formId` INNER JOIN `craft_freeform_statuses` `freeform_statuses` ON freeform_statuses.`id` = freeform_submissions.`statusId` LEFT JOIN `craft_freeform_submissions_enquiry_form_1` `fc1` ON `fc1`.`id` = `freeform_submissions`.`id` LEFT JOIN `craft_freeform_submissions_instant_quote_2` `fc2` ON `fc2`.`id` = `freeform_submissions`.`id` INNER JOIN `craft_content` `content` ON `content`.`id` = `subquery`.`contentId`
```

<img width="1398" alt="Screenshot 2024-03-01 at 16 10 21" src="https://github.com/solspace/craft-freeform/assets/5698596/4a0f02ab-aa6d-4109-b80d-db180dbb5dce">

**Comment by furioursus** [comment]
> @terryupton @furioursus,
> 
> We've now released Freeform 4.1.15, which includes support for Spam purging in the `Lite` edition of Freeform. If you continue to experience issues, please let us know. 🙂

Will this be coming to the Lite version of 5.0? Client has already begun preparing for the transition to Craft 5 and so we need to make sure that upgrade path is available when we take it to production.

**Comment by kjmartens** [comment]
Hmm, sorry about this @terryupton. A weird issue, but we're checking into it.

@furioursus Yes, we have queued up adding this for Lite edition in Freeform 5 (should be ready sometime next week). 🙂

**Comment by kjmartens** [comment]
@terryupton Can you try 4.1.15.1 now? It contains a fix for more reliably handling database prefixes. 🙂

**Comment by terryupton** [comment]
Perfect @kjmartens! This update has worked and removed the error and I can confirm the spam purging has successfully run automatically.  Thanks for your help and persistence with this.

**Comment by kjmartens** [comment]
Glad it's finally resolved! Thanks for the update. Enjoy your weekend! 😊
