### ISSUE TITLE
Error when uninstalling Freeform Lite 

### ISSUE THREAD

**Issue by BrianneHostutler** [solspace/craft3-freeform#9]
I upgraded Freeform Lite today (which was previously working) and noticed the issue mentioned here: (https://github.com/solspace/craft3-freeform/issues/8). 

When I went to uninstall Freeform from Settings > Plugins so that I could work with the users, I got the following error:

Database Exception – yii\db\Exception
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'craft3.freeform_unfinalized_files' doesn't exist
The SQL being executed was: SELECT `assetId`
FROM `freeform_unfinalized_files`
WHERE dateCreated < '2018-01-30 05:55:45'
Error Info: Array
(
    [0] => 42S02
    [1] => 1146
    [2] => Table 'craft3.freeform_unfinalized_files' doesn't exist
)
↵
Caused by: PDOException
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'craft3.freeform_unfinalized_files' doesn't exist

**Comment by gustavs-gutmanis** [comment]
@BrianneHostutler do you have `Freeform Pro` installed as well? If so - did you uninstall it before uninstalling `Freeform Lite`?

**Comment by kjmartens** [comment]
@BrianneHostutler would you be able to try this again now with Beta 5? :)

**Comment by BrianneHostutler** [comment]
Just tried it out and it uninstalled without an issue! Thanks!

**Comment by kjmartens** [comment]
Awesome, thanks! :)
