### ISSUE TITLE
Drag and Drop field not working with trailing slash

### ISSUE THREAD

**Issue by fvwanja** [solspace/craft3-freeform#915]
On our server we activated a trailing slash in all URLs in the frontend.

## How we created the error
From our .htaccess file (this script may not be perfect though... 🫠):

```
    # Force trailing slash
    RewriteCond %{REQUEST_FILENAME} !-f

    # Exclude certain directories
    RewriteCond %{REQUEST_URI} !^/admin [NC]
    RewriteCond %{REQUEST_URI} !^/freeform [NC]

    # Exclude some file extensions manually that are not detected by !-f automatically
    RewriteCond %{REQUEST_URI} !\.(xml|txt|php|jpg|svg)$
    RewriteRule ^(.*[^/])$ /$1/ [L,R=301]
```

## Temporary solution
We had to add a line `RewriteCond %{REQUEST_URI} !^/freeform [NC]` to make the drag and drop field work again. This is something we had to do for all Craft CMS requests as well (`/admin`).

Otherwise we get an Error 400 (see screenshot).

![Screenshot 2023-11-09 at 10 54 17](https://github.com/solspace/craft-freeform/assets/90781427/1510c480-aee9-4845-947f-a9ff2de4eb65)

## More information on the error
```
XHRGET
https://example.dev/freeform/files/upload/
[HTTP/2 400  269ms]

name	"Bad Request"
message	"Post request required"
code	0
error	"Post request required"
status	400
```

## Steps to reproduce

1. Setup a forced trailing slash for all urls
2. Create a native upload field
3. Create a drag-and-drop upload field
4. Select the same asset source for both fields
5. Submit the form

Only the native upload field will create an attachement in the email that is sent and save the files in the selected asset source.

## Expected behavior

Both fields should save the attachements in the selected asset source.

## Craft & Plugin Info (please complete the following information):

- Craft Version: 4.5.10
- Freeform Version: 4.1.11
- Freeform Edition: Pro
- Fresh Install or Upgrade: Fresh

## Additional context

Problem also occurs
- with HTTP and HTTPS
- with and without HTTP-Authentication

Running on Chrome (https://www.whatsmybrowser.org/b/4GRF2) but also in Firefox so this is not browser-related.

If I can provide any other information that you need, just let me know how and what you need.

Maybe this is something, that is intended to be like this, however a more detailed error message in the browsers console could help others identify the issue a bit quicker.

Thank you very much! 👍

**Comment by kjmartens** [comment]
Hi @fvwanja,

This is somewhat expected behavior (just like you had to do for the admin directory) - we have a similar thing noted here:
https://docs.solspace.com/craft/freeform/v4/common-issues/#_500-error-no-form-id-specified-or-the-request-response-is-empty

**Comment by fvwanja** [comment]
Hi @kjmartens ,

thank you for your reply! Once you know, you know... 👍
