### ISSUE TITLE
Issue receiving submission data from Email Notifications

### ISSUE THREAD

**Issue by br-designer** [solspace/craft3-freeform#918]
**Describe the bug or issue you're experiencing**
Using the submission object for email notifications is not returning data. Specifically, submission.fieldMetadata returns null. Email notifications were working at some point. We upgrade CraftCMS and all plugins on a monthly basis, so we're unsure when the issue occurred. Submission data shows up in the Freeforms submission area, so the data exists.

**Steps to reproduce**

1. Submit a form on the website (Twig form using Form query).
2. The client receives an email notification without fields label and value.

Here is the Email Notification Template where submission.fieldMetadata returns null:
```
{% if submission is not null %}
  <h4>{{ submission.id }}: {{ submission.title }}</h4>
  <ul>
  {% for field in submission.fieldMetadata %}
    <li>{{ field.label }}: {{ attribute(submission, field.handle) }}</li>
  {% endfor %}
  </ul>
{% endif %}
```

**Expected behavior**
The client would receive an email notification with the label and value of the field.

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 4.5.6.1
- Freeform Version: 4.1.10
- Freeform Edition: Pro
- Fresh Install or Upgrade: Upgrade

**Additional context**
Previous versions for context:
October
Craft CMS 4.5.4
Freeform Pro 4.1.7

September
Craft CMS 4.4.13
Freeform Pro 4.0.25

**Comment by gustavs-gutmanis** [comment]
Hi @br-designer 

Sorry to hear it broke for you, but accessing `fieldMetadata` isn't meant for general usage. Could you please try iterating over the `submission` element directly?

```twig
  {% for field in submission %}
    <li>{{ field.label }}: {{ attribute(submission, field.handle) }}</li>
  {% endfor %}
```

I would recommend, however, iterating over form fields, and accessing their values.

```
  {% for field in form.layout.fields %}
    <li>{{ field.label }}: {{ field.value }}</li>
  {% endfor %}
```

Please note, that `field.value` might be an array value in case of checkbox groups, multi-select fields, etc.  
If you're ok with rendering the selected array values as a comma delimited string, then you could use `field.valueAsString` instead of `field.value`.

**Comment by br-designer** [comment]
Hi @gustavs-gutmanis, 

Thanks for the quick response! Iterating over the `submission` element directly worked (as well as your suggested approach). The Freeform [docs](https://docs.solspace.com/craft/freeform/v4/overview/email-notifications/#using-submission-object) could use clarification on this.

**Comment by kjmartens** [comment]
>The Freeform [docs](https://docs.solspace.com/craft/freeform/v4/overview/email-notifications/#using-submission-object) could use clarification on this.

Sorry about that. We'll update the documentation shortly. 🙂
