### ISSUE TITLE
Forms not displayed in the correct default language

### ISSUE THREAD

**Issue by Larsundso** [solspace/craft3-freeform#920]
**Describe the bug or issue you're experiencing**
The form is set up in language A
If no translation is provided it displays language A
If translation to English is provided it displays English even when the default language is set to language A

It also seems like Form page titles aren't translated at all.

**Steps to reproduce**

1. Create a Form in a non-english language
2. create en/freeform.php language file with english version of form
3. set default language to initial form language
4. observe form being displayed in english

**Expected behavior**
form should be displayed in the non-english version

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 4.5.9
- Freeform Version: 4.1.11
- Freeform Edition: Pro
- Fresh Install or Upgrade: Fresh

**Additional context**
Related to #264

**Comment by kjmartens** [comment]
Sorry for the trouble and the delay, @Larsundso.

I am able to duplicate this behavior as well. I'll have a developer take a look and see what we can do. 🙂

**Comment by fvwanja** [comment]
I can reproduce this as well. When submitting an invalid form I get an error message: `"Sorry, there was an error submitting the form. Please try again."` but I cannot translate that. I created a file _translations/de/freeform.php_ but to no effect:

```php
<?php

return [
  'Sorry, there was an error submitting the form. Please try again.' => 'Leider ist beim Absenden des Formulars ein Fehler aufgetreten. Bitte versuchen Sie es erneut.',
  'Form has been submitted successfully!' => 'Das Formular wurde erfolgreich abgeschickt!'
];
```

The same for `"Form has been submitted successfully!"` after a successfull form submission. Mayber there is some whitespace or line breaks in there? When I copy and paste the message from the rendered frontend of my page and paste it here, it looks like this:

```
Form has been submitted successfully!

```

- Craft Version: 4.5.14
- Freeform Version: 4.1.13
- Freeform Edition: Pro

Thank you for your time and effort 👍

**Comment by kjmartens** [comment]
We believe this is an issue on Craft's side of things. We created an issue and we'll see what they say: 🙂 
https://github.com/craftcms/cms/issues/15267
