### ISSUE TITLE
Deleting submissions does not delete them from the database

### ISSUE THREAD

**Issue by darylknight** [solspace/craft3-freeform#926]
**Describe the bug or issue you're experiencing**
When you select all submissions and say "Delete all..." and confirm, it removes them all from the Craft control panel, but they are not removed from the database. I've just realised this because my db export was huge. I deleted all the submissions and re-exported, and the database size did not change. My form is showing 0 submissions inside Craft, but the freeform_submissions database table still contains 46000 rows.

**Steps to reproduce**

1. Delete all the Freeform submissions inside Craft
2. All the submissions are still in the database

**Expected behavior**
All information should be deleted from the database

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 4.5.11.1
- Freeform Version: 4.1.13
- Freeform Edition: Pro

**Comment by joelstrom** [comment]
We're having this same issue right now, but with Craft 3.9.6 & Freeforms 3.13.32

**Comment by kjmartens** [comment]
Sorry for the delay @darylknight and @joelstrom.

Is this not expected behavior with Soft Deleting submission elements in Craft? When I use the `Delete` or `Delete All` feature, it correctly soft deletes the submissions and they are now only visible inside the `Trashed` filter. Attempting to export submission data does not include these submissions.

If I then view the soft-deleted submissions and click on `Delete Permanently`, it seems to permanently delete them correctly. 🙂

**Comment by darylknight** [comment]
Thanks for the reply Kelsey. 

Sorry I was unaware that submissions were not actually deleted when you delete them but moved to Trashed. Solspace plugins often don't use native Craft functionality so I wasn't aware that it used a trash bin for deleted submissions. 

No this doesn't seem to work. I have a form called Age Gate. I deleted all the submissions:

![image](https://github.com/solspace/craft-freeform/assets/1250017/2f0470a1-42cf-46d2-8d9b-9281d0902c26)

If I go to the Trashed section of the control panel, there are 13,000 submissions in there:

![image](https://github.com/solspace/craft-freeform/assets/1250017/8c46d35b-9543-4721-ab9f-132436eea3dc)

In the database, there are 49,000 submissions:

![image](https://github.com/solspace/craft-freeform/assets/1250017/cd9e02ad-08e5-4472-8059-8f1f0036f010)

The list of submissions has a "Delete all "function. But the Trashed view only has "Delete these selected 100"; I can't "Delete all" through the control panel . If I run `./craft gc/run`, it says ` deleting trashed rows in the `{{%freeform_submissions}}` table ... done` and they are gone from Craft > Freeform > Trashed submissions:
![image](https://github.com/solspace/craft-freeform/assets/1250017/b6a02cc1-46ba-46bb-80ee-47ff7ec29eba)

but they aren't deleted from the database:

![image](https://github.com/solspace/craft-freeform/assets/1250017/84341451-8841-4105-b71a-a5d80a13f46a)

**Comment by kjmartens** [comment]
This is weird, @darylknight. I just tried monitoring this very closely in the database on my end, and I notice that every single remnant is removed from `elements`, `elements_sites`, `content`, `freeform_submissions`, and `freeform_submissions_my_form_name`.

If you have a look at your database tables, are you seeing any breakdown among the ones I just listed? For example, is the Freeform element being removed from `elements`, `elements_sites`, `content`, but NOT from `freeform_submissions` and `freeform_submissions_my_form_name`, or something like that? 🙂 

/cc @joelstrom

**Comment by darylknight** [comment]
Thanks for double checking Kelsey. I'll dive into this again when I'm back at work in January.

**Comment by darylknight** [comment]
Yep, still happening (Freeform 4.1.11). Weirdly, running garbage collection did actually hang on on `deleting trashed rows in the {{%freeform_submissions}} table ... done` for a while as if it were working, but when I refresh the database connection view of the tables, all the rows are still in there.

Database before:

![Screenshot 2024-01-04 163539](https://github.com/solspace/craft-freeform/assets/1250017/5d98ad25-b845-47bc-8e9b-54790a55bb6b)

Form dashboard before:
![Screenshot 2024-01-04 163548](https://github.com/solspace/craft-freeform/assets/1250017/5696c900-40b5-44f5-b927-493efe6cb22f)

Submissions deleted from the Age Gate form in the control panel, then run garbage collection:
![Screenshot 2024-01-04 164630](https://github.com/solspace/craft-freeform/assets/1250017/baec9abb-89f1-47ef-8eb1-0a3a7367e007)

Dashboard afterwards:

![Screenshot 2024-01-04 163748](https://github.com/solspace/craft-freeform/assets/1250017/55868969-5c14-4ae0-ba37-570697d3fd3d)

Database tables afterwards:
![Screenshot 2024-01-04 164549](https://github.com/solspace/craft-freeform/assets/1250017/f64d6f3a-defe-4d0c-97e8-86c09ae264dc)

**Comment by darylknight** [comment]
Any updates to this?

**Comment by kjmartens** [comment]
Sorry for the long delay @darylknight...

Is this issue still happening for you? It's definitely an odd issue. Is there any chance you can try updating to Freeform 5 and see if that makes any difference? 🙂

**Comment by darylknight** [comment]
No worries - I think we can close this for now. If it pops up again or I can reproduce it again I'll let you know!
