### ISSUE TITLE
ActiveCampaign

### ISSUE THREAD

**Issue by wedot** [solspace/craft3-freeform#93]
Can not connect FreeForm to the ActiveCampaign contact list. I'd like to use Free Form to add Subscribers to the ActiveCampaign contact list. It would be very nice to add this option to the Plugin.

**Comment by wedot** [comment]
Right, this is that I try to do. I will test it with the CRM integration. I think it will create a Deal in the CRM. 

I don't know if it is possible to just add a Contact without to subscribt it to a list. Maybe I need to make a list for all new contacts.

**Comment by kjmartens** [comment]
@wedot The latter approach might be your way around it. Include a mailing list (whether you use it or not) and subscribe them to that in order to have the Mailing List version of ActiveCampaign work (until we can revise it). :)
