### ISSUE TITLE
Mailer service error - "end of statement block" expected

### ISSUE THREAD

**Issue by Coysh** [solspace/craft3-freeform#947]
**Describe the bug or issue you're experiencing**
On one specific database notification, I'm getting the following error:
`Mailer service.ERROR: Unexpected token "name" of value "if" ("end of statement block" expected) in "__string_template__f2d553f539dc45ec157c3ffae508601b" at line 5. {"template":"membershipApplicationNotify","file":"/home/xxx/xx.xxx.xxx/vendor/twig/twig/src/TokenStream.php"} []`

This has been working fine for a few years, and there has been no obvious change apart from an upgrade to Craft 4.

Code of the notification template:
```
<h3>New application received</h3>
<p>Submitted on: {{ dateCreated|date('Y-m-d H:i:s') }}</p>
{% for field in allFields %}
    {% if field.handle == "orgName" %}
        <h3>Organisation details</h3>
    {% elseif field.handle == "primaryTitle" %}
        <h3>Primary contact details</h3>
    {% elseif field.handle == "historyDocument" %}
        <h3>Further information</h3>
    {% elseif field.handle == "referee1Title" %}
        <h3>Referees</h3>
        <h4>Referee 1</h4>
    {% elseif field.handle == "referee2Title" %}
        <h4>Referee 2</h4>
    {% endif %}
    <strong>{{ field.label }}:</strong> {{ field.getValueAsString() }}<br />
{% endfor %}
```

**Steps to reproduce**

1. Send notification of submission
2.

**Expected behavior**
Notification emailed

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 4.5.13
- Freeform Version: 4.1.13
- Freeform Edition: Pro
- Fresh Install or Upgrade:

**Additional context**

**Comment by kjmartens** [comment]
Hi @Coysh,

Would you be able to send a screenshot of what the entire notification template looks like in the CP (or attach the template file here if using File-based templates)? 🙂

**Comment by Coysh** [comment]
Hi @kjmartens,

Attached screenshots below
![CleanShot 2024-01-03 at 09 48 37@2x](https://github.com/solspace/craft-freeform/assets/5764356/46128f12-8007-43d0-a5f0-880d8f037b29)
<img width="1380" alt="CleanShot 2024-01-03 at 09 49 17@2x" src="https://github.com/solspace/craft-freeform/assets/5764356/8f7f5fb3-0dbf-4c5a-9a5e-7ea478f1e77d">

**Comment by kjmartens** [comment]
Hmm this is odd that it's causing any issues. I'm not seeing any particular problems with the template code. Just to confirm, you are saving submission data for this form? ("Store Submission Data" setting inside form builder is enabled)

Can you try something for me? Create a brand new notification template and leave it with the default Email Body, etc. Then assign that new template to your form and test again. See if it works or causes the same or different error. 🙂 

If it doesn't error, try a simpler conditional like this in that new notification template:

```twig
<h3>New application received</h3>
<p>Submitted on: {{ dateCreated|date('Y-m-d H:i:s') }}</p>
{% for field in allFields %}
    {% if field.handle == "orgName" %}
        <h3>Organisation details</h3>
    {% endif %}
    <strong>{{ field.label }}:</strong> {{ field.getValueAsString() }}<br />
{% endfor %}
```

And then, if that works without issue, expand on it one at a time and try again:

```twig
<h3>New application received</h3>
<p>Submitted on: {{ dateCreated|date('Y-m-d H:i:s') }}</p>
{% for field in allFields %}
    {% if field.handle == "orgName" %}
        <h3>Organisation details</h3>
    {% elseif field.handle == "primaryTitle" %}
        <h3>Primary contact details</h3>
    {% endif %}
    <strong>{{ field.label }}:</strong> {{ field.getValueAsString() }}<br />
{% endfor %}
```

**Comment by Coysh** [comment]
Hi Kelset, That seemed to work. Thanks for the assistance.
