### ISSUE TITLE
Can't export from dashboard ("Template not found: freeform/export-profiles")

### ISSUE THREAD

**Issue by smalomo** [solspace/craft3-freeform#948]
**Describe the bug or issue you're experiencing**
Clicking the export button from the Dashboard (https://f.happycog.com/i/myPPug/o5uxqnAyNx) leads to a `404` page "Template not found: freeform/export-profiles"

**Steps to reproduce**

1. Click on Freeform Dashboard
2. Click "Export" button

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 3.9.10
- Freeform Version: 3.13.33
- Freeform Edition: Pro
- Fresh Install or Upgrade: 

**Additional context**
1. I am able to view the Export Profiles screen and export each form individually from there
2. There are 36 forms but only 9 profiles created
3. I'm able to create and save a new export profile

**Comment by kjmartens** [comment]
Sorry about this @smalomo. I have fixed the URL path for it and it'll be available in the next `v3` release. Just to be clear, the "Export" button there is only a link to the _Export Profiles_ page. It does not do any exporting, etc.

**Comment by smalomo** [comment]
Thanks so much @kjmartens!
