### ISSUE TITLE
Error "count(): Parameter must be an array or an object that implements Countable" while submitting a form without uploading a file

### ISSUE THREAD

**Issue by jurgenkrol** [solspace/craft3-freeform#98]
If you use an upload field in a form but leave it empty when submitting, the following PHP error will be logged:

count(): Parameter must be an array or an object that implements Countable {"field":"[object] (Solspace\\Freeform\\Fields\\FileUploadField: \"DBk0Xw4YJ\")"} []

This issue occurs with PHP version 7.2 or higher.

**Steps to reproduce**
1. Create upload field in the form settings
2. Submit form without uploading a file

**Craft & Plugin Info:**
 - Craft Version: 3.5.19.1
 - Freeform Version: 3.10.4

**Comment by gustavs-gutmanis** [comment]
Hi @jurgenkrol

Could you give me more of a stack trace, or some more info on what your file field properties look like?  
I cannot reproduce the issue you're describing.

**Comment by jurgenkrol** [comment]
Hi Gustavs,

The error appears in the error log of Freeform, at Settings -> Reliability-> Error Log. There's no further stack trace there.

In our case, we have 2 upload fields with the same settings. The configuration settings of the fields are:

Asset source: (our standard craft asset source)
Upload location folder: (empty)
File Count: 1
Maximum File Size: 64000
Allowed File Kinds:
- Illustrator
- Image
- PDF
- Photoshop
- PowerPoint
- Text
- Word

The fields are not required.

When submitting the form with a file upload for both fields, the form submits correctly and the files are saved in the upload folder mentioned in the settings. When one of the fields (or both) are left empty, the form will not submit properly and the error occurs in the Freeform log.

In the template the statement form.hasErrors returns true, but form.errors and uploadField.renderErrors() return nothing.

The PHP version used is 7.3. In our development environment we use PHP 7.1 and the problem doesn't occur there.

**Comment by gustavs-gutmanis** [comment]
I cannot reproduce this on any of the PHP versions starting from `7.0`

I have located the one place which might be causing this issue, even though it shouldn't, because there are failsafes in place, but could you try out if this fixes the issue?

Set your `composer.json` freeform to this
```json
"solspace/craft-freeform": "dev-file-upload-fix as 3.10.4"
```

and run `composer update` so that the fixed version gets applied and let me know if the problem is gone.

**Comment by jurgenkrol** [comment]
Unfortunately, the error still occurs with this fix.

I saw you made a change in src/Fields/FileUploadField.php where the count PHP function is used. When submitting the form the uploadFile function in /src/Services/FileService.php is also executed and also contains this count function. But the fix you made in FileUploadField.php is not present in FileService.php.

Could this be the reason why it doesn't work yet?

**Comment by gustavs-gutmanis** [comment]
yeah, you are right @jurgenkrol, try it now, I added the service fix to that same branch now

**Comment by jurgenkrol** [comment]
Thanks Gustavs, your last fix solved the issue!

**Comment by gustavs-gutmanis** [comment]
Alright, good to know, it'll be out in the next release.
Please switch to `dev-master` for now, until we do a new release with the patch inside.
