### ISSUE TITLE
Applying m250101_200000_F-4to5_MigrateData fails

### ISSUE THREAD

**Issue by phillipsandoveracademy** [solspace/craft3-freeform#989]
**Describe the bug or issue you're experiencing**
Upgrading from Freeform 4.1.3 to Freeform 5.x.x fails each time after several attempts on a fresh database. Reading the Freefrom 4 upgrade guide, I am not aware of anything I need to do prior to upgrade, unless I missed guidance. Is there a way to identify what data is causing this issue?

**Steps to reproduce**

1. Update Freeform 4.1.3 via cli
2. Perform Craft Update—either composer install/update or php craft update freeform

**Expected behavior**
Migration migrates all 29 migrations.

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 4.7.0
- Freeform Version: 4.1.3 --> 5.x.x
- Freeform Edition: Pro
- Fresh Install or Upgrade: Both

**Additional context**

<img width="2026" alt="Screenshot 2024-01-26 at 11 30 16 AM" src="https://github.com/solspace/craft-freeform/assets/11964584/040c3f1f-6f9e-4f59-809c-20ae0ef8510f">
Clean install error.

<img width="1982" alt="Screenshot 2024-01-26 at 8 49 21 AM" src="https://github.com/solspace/craft-freeform/assets/11964584/9860a504-a396-4b66-98a3-4bead15194e0">
Upgrade error.

**Comment by kjmartens** [comment]
Sorry for the trouble @phillipsandoveracademy. We'll have an updated version with a fix for this available today. 🙂

**Comment by kjmartens** [comment]
This should now be fixed in Freeform 5.0.4+. 🙂
