### ISSUE TITLE
V5 User notification

### ISSUE THREAD

**Issue by StuartMcD** [solspace/craft3-freeform#990]
**Describe the bug or issue you're experiencing**
Notification templates exist and FF lists them in the templates page but not when editing a form.
**Steps to reproduce**

1.Open up form
2. Notifications tab
3. Step thru option and all template paths are blank

![image](https://github.com/solspace/craft-freeform/assets/5855813/1584cdfd-6d17-45ec-80fc-045754cabde4)
![image](https://github.com/solspace/craft-freeform/assets/5855813/2d0a0620-d633-41b9-83ca-286a747e0c23)
![image](https://github.com/solspace/craft-freeform/assets/5855813/e92318d9-8623-49cc-b087-0b43af60bd88)

**Expected behavior**
I can SEE and choose a template :)

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 4.7.0
- Freeform Version: 5.0.3
- Freeform Edition: Pro
- Fresh Install or Upgrade: Upgrade

**Additional context**
Tried installing FF 5.0.0, then 5.0.1 etc same behaviour.
Possible relation to next issue -> Forms - Notifications

**Comment by StuartMcD** [comment]
Just discovered, that when I populate the User Select notification fields with email addresses and save, it saves the content but as soon as you navigate outside the freeform area within the CMS and return - all fields are empty :(

Console logs: `Cannot assign null to property Solspace\Freeform\Library\DataObjects\NotificationTemplate::$includeAttachments of type bool`

**Comment by kjmartens** [comment]
This should now be fixed in Freeform 5.0.4+. 🙂
