### ISSUE TITLE
V5 Notifications page

### ISSUE THREAD

**Issue by StuartMcD** [solspace/craft3-freeform#991]
When clicking the primary link "notifications" greeted with this error

`Cannot assign null to property Solspace\Freeform\Library\DataObjects\NotificationTemplate::$includeAttachments of type bool`

![image](https://github.com/solspace/craft-freeform/assets/5855813/d72f0ce3-3be5-4b21-b9e0-dc8a1638c6dc)

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 4.7.0
- Freeform Version: 5.0.3
- Freeform Edition: Pro
- Fresh Install or Upgrade: Upgrade

**Additional context**
![image](https://github.com/solspace/craft-freeform/assets/5855813/9910c675-bf05-439c-b097-2b81b14b5662)

**Comment by kjmartens** [comment]
Sorry for the trouble @StuartMcD . We'll have an updated version with a fix for this available today. 🙂

**Comment by kjmartens** [comment]
This should now be fixed in Freeform 5.0.4+. 🙂
