### ISSUE TITLE
V5.0.4 - Field Render Attributes don't work & can't have an inline submit button

### ISSUE THREAD

**Issue by DowleyDeveloped** [solspace/craft3-freeform#995]
Hi!

I have a form which uses custom classes, but when adding them (as per [this](https://docs.solspace.com/craft/freeform/v5/templates/objects/field/#override-classes-values)) the attributes don't actually display. 

Due to this, I cannot upgrade as all forms on the site break (in terms of look).

Previously i also had the submit button inline with the other fields, but it looks like this is no longer a option within V5? Can I ask why? This was something that is commonly used for forms across multiple sites (signups for example).

**Steps to reproduce**

1. Add a field render tag and add any attribute.
2. See they don't get loaded

**Expected behavior**
Field should have the classes/attributes

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 4.7.1
- Freeform Version: 5.0.4
- Freeform Edition: Pro
- Fresh Install or Upgrade: Upgrade

**Comment by kjmartens** [comment]
Hi @DowleyDeveloped,

There are a few spots in the documentation that likely still need to be updated, included what you have linked to.

The new approach is to use something like this:
https://docs.solspace.com/craft/freeform/v5/templates/formatting/#on-submit-buttons

``` twig
{{ form.render({
    buttons: {
        attributes: {
            container: { ... },
            column: { ... },
            buttonWrapper: { ... },
            submit: { class: "form-field-button blue" },
            back: { class: "form-field-button gray" },
            save: { class: "form-field-button blue" },
        },
        submit: { label: "Send" },
        back: { label: "Previous" },
        save: { label: "Save" },
    },
}) }}
```

Would this approach not work for you? If so, would you be able to let me know what you need exactly? 🙂 We're considering/planning on adding an option to prevent Freeform from inserting Submit buttons automatically so customers can hardcode them if they absolutely must.

EDIT: Just rereading and seeing you're wanting attributes on all fields... so here is a more complete example:

``` twig
{{ form.render({
    attributes: {
        novalidate: true,
        row: {
            class: "row",
        },
    },
    buttons: {
        attributes: {
            container: { ... },
            column: { ... },
            buttonWrapper: { ... },
            submit: { class: "form-field-button blue" },
            back: { class: "form-field-button gray" },
            save: { class: "form-field-button blue" },
        },
        submit: { label: "Send" },
        back: { label: "Previous" },
        save: { label: "Save" },
    },
    fields: {
        "@global": {
            attributes: {
                input: {
                    class: "input-class",
                },
                container: {
                    "data-container": true,
                },
                label: {
                    class: "label-class",
                },
            },
        },
        "@dropdown": {
            attributes: {
                input: {
                    class: "select fullwidth",
                },
                container: {
                    "data-select-container": true,
                },
            },
        },
        "@checkboxes": {
            instructions: "Select all that apply.",
        },
        "@text": { ... },
        "@checkboxes, @multiple-select": {
            instructions: "Select all that apply.",
        },
        "#myField": {
            attributes: {
                container: {
                    "data-my-input-container": true,
                },
                input: {
                    id: "my-field",
                    class: "big-text",
                },
            },
        },
        ":options": { ... },
        ":required": { ... },
        ":errors": { ... },
        ":required, @dropdown, @text, #myHandle1": { ... }
    },
}) }}
```

**Comment by DowleyDeveloped** [comment]
@kjmartens Thanks for this! What if we wanted to add something based on a field object instead of the overall? 

For example a `field.isRequired` conditional.

Obviously we wouldn't be able to do this this on the form render, and would have to come from the field itself.

**Comment by DowleyDeveloped** [comment]
@kjmartens Also that example throws up errors on the buttons:

**Property Solspace\Freeform\Form\Layout\Page\Buttons\PageButtons::$submit does not exist**
The classes I'm trying to add to submit buttons don't seem to be working (even through attributes)

**Comment by kjmartens** [comment]
@DowleyDeveloped,

I wonder if you copied my example before I edited it. I accidentally had the wrong code up for like 20mins. Sorry about that. Can you refresh this page and try again?

**Comment by phrichards** [comment]
@kjmartens Sorry to hijack this with something that is not 100% related to the question but since you said "We're considering/planning on adding an option to prevent Freeform from inserting Submit buttons automatically so customers can hardcode them if they absolutely must" I'd like to provide an example of what I'm looking for in that area/understand if it's possible with the new way buttons are managed.

On one of our forms we're using a custom layout template that wraps the "Submit" text on a button with a `<span>`, which we're then targeting with some CSS to provide colour and animation. We've also added an icon inside the button. Is any of that possible with template overrides or inside the form editor? From what I can tell it seems like we can only affect wrappers around the `<button>` element and not insert anything in the element itself. If that's the case we'd definitely like an option to prevent the button from being added automatically.

**Comment by kjmartens** [comment]
@phrichards thank you very much for your feedback. We appreciate the details and use case that was overlooked.

We will most definitely be offering a solution to this issue soon. Either an option to disable the automatic insertion of submit buttons and the ability to hard code your own, or the ability to customize the output better. 🙂

**Comment by DowleyDeveloped** [comment]
@kjmartens Ah missed the update. Thanks!

**Comment by kjmartens** [comment]
This is now addressed in Freeform 5.0.6+ 🙂 
https://docs.solspace.com/craft/freeform/v5/templates/formatting/#submit-button-customization

**Comment by DowleyDeveloped** [comment]
That's awesome, thanks @kjmartens!

Just wondering, as per my previous comment, is there no way of doing an inline submit button through the Dashboard?

(Like a signup form for example)

**Comment by kjmartens** [comment]
@DowleyDeveloped by "dashboard", do you mean the form builder?

It's currently not possible to add a submit button to the layout in the form builder. However, with the latest changes, you have full control at the template level and can do either this:

``` twig
{{ form.renderTag({
    returnUrl: "contact/success",
    disable: ["submitButtons"]
}) }}

    {# Your fields #}

    {% set page = form.pages.current %}

    {{ page.buttons.renderSubmit({ 'data-optional': 'attributes here' }) }}
    {% if form.pages.current.buttons.back %}
        {{ page.buttons.renderBack }}
    {% endif %}
    {% if form.pages.current.buttons.save %}
        {{ page.buttons.renderSave }}
    {% endif %}

{{ form.renderClosingTag }}
```

OR

``` twig
{{ form.renderTag({
    returnUrl: "contact/success",
    disable: ["submitButtons"]
}) }}

    {# Your fields #}

    {% set page = form.pages.current %}

    <button {{ page.buttons.submitRenderProps({ 'data-optional': 'attributes here' }) }}>
        Submit
    </button>
    {% if form.pages.current.buttons.back %}
        <button {{ page.buttons.backRenderProps }}>
            Back
        </button>
    {% endif %}
    {% if form.pages.current.buttons.save %}
        <button {{ page.buttons.saveRenderProps }}>
            Save
        </button>
    {% endif %}

{{ form.renderClosingTag }}
```

**Comment by DowleyDeveloped** [comment]
Hi @kjmartens 

Ok good to know thanks!

Would be a nice to have for future release though!
